import mongoose, { Schema, Document, Model } from 'mongoose'

export interface PracticeTask {
  taskId: string
  type: 'drill' | 'full_session' | 'review' | 'homework'
  title: string
  description: string
  targetCompetency: string
  difficulty: 'easy' | 'medium' | 'hard'
  estimatedMinutes: number
  completed: boolean
  completedAt?: Date
}

export interface Milestone {
  name: string
  description: string
  targetScore: number
  currentScore: number
  achieved: boolean
  achievedAt?: Date
}

export interface IPathwayPlan extends Document {
  _id: mongoose.Types.ObjectId
  userId: mongoose.Types.ObjectId

  // Current state assessment
  readinessLevel: 'not_ready' | 'developing' | 'approaching' | 'ready' | 'strong'
  readinessScore: number                // 0-100

  // Focus areas
  topBlockingWeaknesses: Array<{
    competency: string
    currentScore: number
    targetScore: number
    reason: string
  }>
  strengthsToPreserve: string[]

  // Next steps
  nextSessionRecommendation: {
    domain: string
    interviewType: string
    focusCompetencies: string[]
    difficulty: 'easy' | 'medium' | 'medium_high' | 'hard'
    reason: string
  }

  // Practice tasks
  practiceTasks: PracticeTask[]

  // Progression
  milestones: Milestone[]
  difficultyProgression: Array<{
    level: string
    achievedAt?: Date
    requiredScore: number
  }>

  // Session that generated this plan
  generatedFromSessionId?: mongoose.Types.ObjectId
  generatedAt: Date

  // Overall goal context
  userGoal: string
  targetRole: string
  targetTimeline?: string

  // 30-day adaptive plan fields
  planType?: 'standard' | 'monthly' | 'universal'
  startDate?: Date
  endDate?: Date
  planDurationDays?: number
  monthLabel?: string                      // e.g., "2026-04"
  tier?: 'free' | 'pro' | 'enterprise'
  autoGenerated?: boolean

  // Universal phased plan (session-count pacing)
  domain?: string
  depth?: string
  sessionsCompleted?: number
  phaseThresholds?: Record<string, number>
  lessons?: Array<{
    lessonId: string
    competency: string
    completed: boolean
    completedAt?: Date
  }>

  // Adaptive phase tracking
  currentPhase?: 'assessment' | 'foundation' | 'building' | 'intensity' | 'mastery' | 'review'
  phaseHistory?: Array<{
    phase: string
    enteredAt: Date
    exitedAt?: Date
    avgScore: number
  }>

  // Daily schedule (supports up to 31 days)
  dailySchedule?: Array<{
    day: number
    date: string
    theme: string
    phase: string
    tasks: PracticeTask[]
    completed: boolean
  }>

  createdAt: Date
  updatedAt: Date
}

const PracticeTaskSchema = new Schema({
  taskId: { type: String, required: true },
  type: { type: String, enum: ['drill', 'full_session', 'review', 'homework'], required: true },
  title: { type: String, required: true },
  description: { type: String, default: '' },
  targetCompetency: { type: String, required: true },
  difficulty: { type: String, enum: ['easy', 'medium', 'hard'], default: 'medium' },
  estimatedMinutes: { type: Number, default: 10 },
  completed: { type: Boolean, default: false },
  completedAt: { type: Date },
}, { _id: false })

const MilestoneSchema = new Schema({
  name: { type: String, required: true },
  description: { type: String, default: '' },
  targetScore: { type: Number, required: true },
  currentScore: { type: Number, default: 0 },
  achieved: { type: Boolean, default: false },
  achievedAt: { type: Date },
}, { _id: false })

const PathwayPlanSchema = new Schema<IPathwayPlan>(
  {
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },

    readinessLevel: {
      type: String,
      enum: ['not_ready', 'developing', 'approaching', 'ready', 'strong'],
      default: 'developing',
    },
    readinessScore: { type: Number, default: 0, min: 0, max: 100 },

    topBlockingWeaknesses: [{
      competency: { type: String, required: true },
      currentScore: { type: Number, required: true },
      targetScore: { type: Number, required: true },
      reason: { type: String, default: '' },
    }],
    strengthsToPreserve: [{ type: String }],

    nextSessionRecommendation: {
      domain: { type: String, default: '' },
      interviewType: { type: String, default: '' },
      focusCompetencies: [{ type: String }],
      difficulty: { type: String, enum: ['easy', 'medium', 'medium_high', 'hard'], default: 'medium' },
      reason: { type: String, default: '' },
    },

    practiceTasks: [PracticeTaskSchema],
    milestones: [MilestoneSchema],
    difficultyProgression: [{
      level: { type: String },
      achievedAt: { type: Date },
      requiredScore: { type: Number },
    }],

    generatedFromSessionId: { type: Schema.Types.ObjectId, ref: 'InterviewSession' },
    generatedAt: { type: Date, default: Date.now },

    userGoal: { type: String, default: '' },
    targetRole: { type: String, default: '' },
    targetTimeline: { type: String },

    // 30-day adaptive plan
    planType: { type: String, enum: ['standard', 'monthly', 'universal'], default: 'standard' },
    startDate: { type: Date },
    endDate: { type: Date },
    planDurationDays: { type: Number, default: 30 },
    monthLabel: { type: String },
    tier: { type: String, enum: ['free', 'pro', 'enterprise'] },
    autoGenerated: { type: Boolean, default: false },

    // Universal phased plan (session-count pacing)
    domain: { type: String },
    depth: { type: String },
    sessionsCompleted: { type: Number, default: 0, min: 0 },
    phaseThresholds: { type: Schema.Types.Mixed },
    lessons: [{
      lessonId: { type: String, required: true },
      competency: { type: String, required: true },
      completed: { type: Boolean, default: false },
      completedAt: { type: Date },
    }],

    currentPhase: {
      type: String,
      enum: ['assessment', 'foundation', 'building', 'intensity', 'mastery', 'review'],
    },
    phaseHistory: [{
      phase: { type: String, required: true },
      enteredAt: { type: Date, required: true },
      exitedAt: { type: Date },
      avgScore: { type: Number, default: 0 },
    }],

    dailySchedule: [{
      day: { type: Number, required: true },
      date: { type: String, required: true },
      theme: { type: String, default: '' },
      phase: { type: String, default: '' },
      tasks: [PracticeTaskSchema],
      completed: { type: Boolean, default: false },
    }],
  },
  { timestamps: true }
)

PathwayPlanSchema.index({ userId: 1, generatedAt: -1 })

export const PathwayPlan: Model<IPathwayPlan> =
  mongoose.models.PathwayPlan ||
  mongoose.model<IPathwayPlan>('PathwayPlan', PathwayPlanSchema)
