import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['problem-comprehension', 'Problem comprehension', 'problem-solving', 'warm-up', 'must', 0,
    'Present a small scenario (e.g. to-do API). Assess whether candidate asks clarifying questions.',
    'Surface — note what questions they ask and what they miss.', 'Interviewer-led format.'],
  ['api-endpoint-design', 'Basic API endpoint design', 'technical-depth', 'exploration', 'must', 2,
    'Ask candidate to design REST routes, verbs, request/response for the scenario.',
    'Probe HTTP status codes and why specific methods were chosen.', 'Small well-scoped problems.'],
  ['schema-design', 'Simple database schema', 'technical-depth', 'exploration', 'must', 2,
    'Ask for tables, relationships, basic normalization for the scenario.',
    'Probe "What if we add a new field?" to test schema evolution thinking.'],
  ['feature-walkthrough', 'Implementation walkthrough', 'problem-solving', 'exploration', 'must', 2,
    'Walk through (or code) one specific feature end-to-end.',
    'Probe edge cases and error handling as they implement.', 'Communication and thought process matter most.'],
  ['error-handling', 'Error handling and edge cases', 'problem-solving', 'exploration', 'if-time', 1,
    'Ask about error scenarios — what if input is invalid, two users update same record?',
    'Probe basic concurrency awareness.'],
  ['testing-approach', 'Testing approach', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask what tests they would write. Look for unit test awareness.',
    'Surface — awareness level is sufficient.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['validation-summary', 'Validate against requirements', 'problem-solving', 'closing', 'must', 0,
    'Ask candidate to confirm their design meets original requirements. Note gaps.',
    'Surface — quick validation check.'],
]

const mid: CompactSlot[] = [
  ['incident-triage', 'Production incident triage', 'operational', 'warm-up', 'must', 0,
    'Present a realistic production issue (500 errors, latency spike). Assess debugging methodology.',
    'Surface — calibrate systematic vs. ad-hoc approach.', 'Production-grade concerns expected.'],
  ['api-service-decomposition', 'API design and service decomposition', 'technical-depth', 'exploration', 'must', 2,
    'Ask candidate to design APIs for a multi-component system. Look for service boundary reasoning.',
    'Probe sync vs async choices and backward compatibility.'],
  ['database-perf-tradeoffs', 'Database design with performance tradeoffs', 'technical-depth', 'exploration', 'must', 2,
    'Discuss indexing, denormalization, read/write patterns for the scenario.',
    'Probe "95th percentile latency is 2x median — what could cause that?"'],
  ['caching-strategy', 'Caching strategy', 'technical-depth', 'exploration', 'must', 2,
    'Ask about cache layers, invalidation, consistency for the scenario.',
    'Probe invalidation strategy depth — not just name-dropping Redis.'],
  ['async-processing', 'Async processing and queues', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about queue-based architectures. When to go async vs sync.',
    'Probe "What happens when the queue is full? Dead letter strategy?"'],
  ['feature-rollout', 'Feature rollout strategy', 'operational', 'exploration', 'if-time', 2,
    'Ask about feature flags, phased deployment, rollback plans.',
    'Probe how they handle rollback when data has already been written.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['stakeholder-comm', 'Stakeholder communication', 'communication', 'closing', 'must', 0,
    'Ask how they would communicate progress, risks, and timelines to stakeholders.',
    'Surface — assess communication clarity.'],
]

const senior: CompactSlot[] = [
  ['strategic-framing', 'Strategic problem framing', 'leadership', 'warm-up', 'must', 0,
    'Present an ambiguous org-level scenario (monolith slowing 8 teams). Assess how candidate frames it.',
    'Surface — note whether they ask about business goals and team structure.', 'Candidate-led format.'],
  ['architectural-assessment', 'Architectural assessment of existing systems', 'technical-depth', 'exploration', 'must', 2,
    'Ask candidate to assess current architecture: tech debt, risk, portfolio analysis.',
    'Probe business-value vs technical-quality matrix reasoning.'],
  ['migration-strategy', 'Migration strategy design', 'technical-depth', 'exploration', 'must', 2,
    'Ask about strangler fig, parallel runs, feature-flag cutover for the scenario.',
    'Probe "What is your rollback plan if new architecture performs worse?"'],
  ['cross-team-coordination', 'Cross-team coordination and RFC process', 'leadership', 'exploration', 'must', 2,
    'Ask how they would drive alignment across teams via RFC/ADR process.',
    'Probe how to handle team leads who resist the approach.'],
  ['capacity-cost', 'Capacity planning and cost modeling', 'operational', 'exploration', 'if-time', 2,
    'Ask about infrastructure cost growth and strategy to reduce while maintaining reliability.',
    'Probe specific cost-performance tradeoffs and measurement.'],
  ['org-change-mgmt', 'Organizational change management', 'leadership', 'exploration', 'if-time', 2,
    'Ask about resistance, buy-in, training for the proposed changes.',
    'Probe knowledge transfer strategy and bus-factor mitigation.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['risk-rollback', 'Risk mitigation and rollback planning', 'operational', 'closing', 'must', 0,
    'Ask about success metrics, kill criteria, and failsafe planning.',
    'Surface — how they know the migration is succeeding.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('backend', 'case-study', '0-2', entry, [
    'Microservices or event-driven systems',
    'Production incident debugging',
    'Database sharding or replication',
    'Kubernetes or infrastructure tooling',
    'Candidate leading unprompted',
  ]),
  template('backend', 'case-study', '3-6', mid, [
    'Org-wide architectural strategy',
    'Multi-year technical roadmaps',
    'Distributed consensus algorithms',
    'Multi-region deployment',
    'Team-building scenarios',
  ]),
  template('backend', 'case-study', '7+', senior, [
    'Writing production code',
    'Junior-style CRUD API problems',
    'Reciting specific tool configurations',
    'Solving problems without discussing team dynamics',
    'Well-constrained narrow problems',
  ]),
]
