import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['tech-background', 'Technical background chat', 'technical-depth', 'warm-up', 'must', 0,
    'Ask about languages they know and a project they built. Calibrate level, no tricks.',
    'Surface — move on after 2 min.', 'Academic/bootcamp projects are acceptable.'],
  ['data-structures', 'Data structures fundamentals', 'technical-depth', 'exploration', 'must', 2,
    'Assess understanding of arrays, hash tables, linked lists, trees. Ask to compare tradeoffs.',
    'Probe time/space complexity and when to pick one over another.', 'Breadth over depth.'],
  ['coding-problem', 'Coding problem (easy-medium)', 'problem-solving', 'exploration', 'must', 2,
    'Give 1 array/string/hash-map problem at LeetCode easy-medium. Assess approach before code.',
    'Probe edge cases, optimization, and complexity analysis.', 'Not trick questions.'],
  ['rest-api-basics', 'REST API basics', 'technical-depth', 'exploration', 'must', 2,
    'Ask about HTTP methods, status codes, resource design. Look for practical understanding.',
    'Ask them to design a simple CRUD endpoint and discuss status codes.'],
  ['sql-databases', 'SQL and relational databases', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask about basic queries, JOINs, indexing concepts. Look for working knowledge.',
    'Ask them to write a JOIN then explain what an index does.'],
  ['web-concepts', 'Basic web concepts', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask what happens when you type a URL. Look for client-server understanding.',
    'Probe DNS, HTTP request cycle, server response.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tech', 'Technology interests', 'motivation', 'closing', 'must', 0,
    'Ask about technology preferences and learning interests. Assess enthusiasm.',
    'Surface — wrap up warmly.'],
]

const mid: CompactSlot[] = [
  ['system-design-intro', 'System design fundamentals', 'technical-depth', 'warm-up', 'must', 0,
    'Present a bounded system design problem (URL shortener, rate limiter). Assess requirements gathering.',
    'Surface — let them drive the high-level approach.', 'Key difference from entry level.'],
  ['database-optimization', 'Database design and optimization', 'technical-depth', 'exploration', 'must', 2,
    'Probe schema design, indexing strategies, SQL vs NoSQL tradeoffs, query optimization.',
    'Ask about execution plan reasoning and index selection.', 'Trade-off reasoning is critical.'],
  ['api-design', 'API design', 'technical-depth', 'exploration', 'must', 2,
    'Assess REST best practices, versioning, pagination, error handling, auth patterns.',
    'Probe why specific choices over alternatives.'],
  ['caching-strategies', 'Caching strategies', 'technical-depth', 'exploration', 'must', 2,
    'Ask about cache layers, invalidation patterns, Redis use cases. Look for tradeoff reasoning.',
    'Probe cache-aside vs write-through and invalidation edge cases.'],
  ['concurrency-basics', 'Concurrency and multithreading', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about thread safety, race conditions, async/await, connection pooling.',
    'Probe practical experience, not textbook definitions.'],
  ['microservices', 'Microservices fundamentals', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about service boundaries, inter-service communication, database-per-service.',
    'Probe when NOT to use microservices.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['operational-concerns', 'Operational concerns', 'operational', 'closing', 'must', 0,
    'Ask about monitoring, logging, deployment strategies. Assess awareness.',
    'Surface — conceptual awareness is sufficient.'],
]

const senior: CompactSlot[] = [
  ['arch-presentation', 'Architecture presentation', 'technical-depth', 'warm-up', 'must', 0,
    'Ask candidate to present a system they designed. Look for scope and tradeoff awareness.',
    'Surface — use this to calibrate depth for follow-ups.', 'Candidate drives the conversation.'],
  ['large-scale-design', 'Large-scale system design', 'technical-depth', 'exploration', 'must', 2,
    'Present an open-ended problem (collaborative editing, real-time analytics). Multi-service scope.',
    'Probe failure modes, cascading failures, and what happens when components go down.',
    '3-5 year forward-looking reasoning expected.'],
  ['distributed-systems', 'Distributed systems deep-dive', 'technical-depth', 'exploration', 'must', 2,
    'Probe CAP theorem in real scenarios, consistency models, consensus algorithms.',
    'Challenge with "What if X fails?" and probe recovery strategies.'],
  ['architecture-evaluation', 'Architecture evaluation and tech strategy', 'technical-depth', 'exploration', 'must', 2,
    'Discuss build vs buy, legacy modernization, migration planning. Look for strategic reasoning.',
    'Probe total cost of ownership and multi-stakeholder consensus building.'],
  ['reliability-engineering', 'Reliability engineering', 'operational', 'exploration', 'if-time', 2,
    'Ask about failover strategies, circuit breakers, SLO/SLI definition, chaos engineering.',
    'Probe real experience with production reliability, not textbook patterns.'],
  ['cross-cutting-scale', 'Cross-cutting concerns at scale', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about observability, security architecture, API gateway design, rate limiting.',
    'Probe real instrumentation examples and organizational adoption.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['tech-mentorship', 'Technical mentorship and standards', 'leadership', 'closing', 'must', 0,
    'Ask how they established coding standards, ADRs, or technical onboarding.',
    'Surface — one example of systemic improvement.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('backend', 'technical', '0-2', entry, [
    'Full system design (distributed systems)',
    'Advanced concurrency (locks, deadlocks)',
    'Database internals (B-trees, execution plans)',
    'Microservices architecture',
    'LeetCode hard problems',
  ]),
  template('backend', 'technical', '3-6', mid, [
    'Organizational-level architecture decisions',
    'Cross-cutting concerns affecting 5+ teams',
    'Multi-region multi-datacenter reasoning',
    'Problems solvable with simple CRUD',
  ]),
  template('backend', 'technical', '7+', senior, [
    'LeetCode-style algorithmic puzzles as primary signal',
    'Basic system design solvable in 15 minutes',
    'Textbook definition questions',
    'Technology trivia',
    'Problems with a single right answer',
  ]),
]
