import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['coding-warmup', 'Problem introduction and clarification', 'problem-solving', 'warm-up', 'must', 0,
    'Present an easy array/string problem. Assess whether candidate asks about constraints and edge cases.',
    'Surface — note clarifying questions asked.', 'Hints are expected and acceptable.'],
  ['brute-force', 'Approach discussion — brute force then optimize', 'problem-solving', 'exploration', 'must', 2,
    'Ask candidate to describe brute force approach, then optimize. Assess Big-O awareness.',
    'Probe time/space complexity and why optimization matters.', 'Working brute-force is often sufficient.'],
  ['coding-impl', 'Coding implementation', 'technical-depth', 'exploration', 'must', 2,
    'Candidate implements solution. Provide hints if stuck. Assess correct language usage.',
    'Probe variable naming, basic structure, syntax confidence.'],
  ['testing-trace', 'Testing and trace-through', 'problem-solving', 'exploration', 'must', 1,
    'Ask candidate to trace through 1-2 examples. Assess ability to catch bugs.',
    'Probe edge cases: empty input, single element, duplicates.'],
  ['follow-up-optimize', 'Optimization follow-up', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask "Can you do better?" or "What if input is very large?" Assess optimization thinking.',
    'Probe scaling awareness and space-time tradeoffs.'],
  ['practical-backend', 'Practical backend problem', 'technical-depth', 'exploration', 'if-time', 1,
    'If time, ask a practical problem: simple REST endpoint, data transformation, DB query.',
    'Probe basic CRUD and data modeling awareness.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['coding-closing', 'Approach reflection', 'problem-solving', 'closing', 'must', 0,
    'Ask what they would do differently with more time. Assess self-awareness.',
    'Surface — wrap up.'],
]

const mid: CompactSlot[] = [
  ['problem-scoping', 'Problem scoping and clarification', 'problem-solving', 'warm-up', 'must', 0,
    'Present a medium problem (sliding window, graph, DP). Expect proactive edge case identification.',
    'Surface — more ambiguous than junior, less hand-holding.', 'Engineering judgment is key signal.'],
  ['multi-approach', 'Multiple approaches with tradeoffs', 'problem-solving', 'exploration', 'must', 2,
    'Expect 2-3 approaches with Big-O analysis for each. Assess trade-off reasoning.',
    'Probe why they chose one approach over others.'],
  ['clean-implementation', 'Clean implementation', 'technical-depth', 'exploration', 'must', 2,
    'Assess code quality: readability, modularity, error handling, proper naming.',
    'Probe design decisions in the code structure.', 'Code quality matters as much as correctness.'],
  ['self-testing', 'Self-driven testing', 'problem-solving', 'exploration', 'must', 2,
    'Expect candidate to test corner cases unprompted: empty, overflow, duplicates.',
    'Probe testing strategy and self-correction ability.'],
  ['system-oriented', 'System-oriented coding', 'technical-depth', 'exploration', 'if-time', 2,
    'LRU cache, rate limiter, task scheduler — backend-flavored coding problems.',
    'Probe production concerns: logging, metrics, error responses.'],
  ['concurrency-patterns', 'Concurrency patterns', 'technical-depth', 'exploration', 'if-time', 2,
    'Basic thread safety, producer-consumer. Assess practical concurrency awareness.',
    'Probe race conditions and how to prevent them.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['scaling-followup', 'Scaling and production follow-up', 'technical-depth', 'closing', 'must', 0,
    'Ask how solution scales, production-readiness, monitoring considerations.',
    'Surface — assess awareness of real-world deployment.'],
]

const senior: CompactSlot[] = [
  ['requirements-gathering', 'Requirements gathering from vague prompt', 'problem-solving', 'warm-up', 'must', 0,
    'Present deliberately vague problem. Assess whether candidate drives scope definition.',
    'Surface — note quality of questions asked.', 'Candidate must drive the conversation.'],
  ['architecture-in-code', 'Architecture and approach design', 'technical-depth', 'exploration', 'must', 2,
    'Expect class hierarchy/interface design before implementation. 2-3 approaches with detailed tradeoffs.',
    'Probe scalability, failure modes, maintainability of each approach.',
    'Design within code — architect before implementing.'],
  ['production-quality', 'Production-quality implementation', 'technical-depth', 'exploration', 'must', 2,
    'Assess error handling, input validation, clean abstractions, separation of concerns.',
    'Probe "why this abstraction?" and extensibility.', 'Trade-off articulation is mandatory.'],
  ['comprehensive-testing', 'Comprehensive testing strategy', 'problem-solving', 'exploration', 'must', 2,
    'Expect non-obvious edge cases, failure scenarios, performance testing discussion.',
    'Probe production testing: load, chaos, observability.'],
  ['system-component', 'System-oriented component', 'technical-depth', 'exploration', 'if-time', 2,
    'Implement distributed-style component: consistent hashing, event sourcing sketch.',
    'Probe concurrency and back-pressure handling.'],
  ['data-processing', 'Data processing pipeline', 'technical-depth', 'exploration', 'if-time', 2,
    'Stream processing or batch pipeline logic. Assess partitioning and scaling strategy.',
    'Probe failure recovery and exactly-once semantics.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['extension-monitoring', 'Extension and production monitoring', 'operational', 'closing', 'must', 0,
    'How to scale, handle requirement changes, monitor in production.',
    'Surface — assess forward-looking production thinking.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('backend', 'coding', '0-2', entry, [
    'LeetCode hard problems',
    'System design questions',
    'Distributed systems concepts',
    'Advanced concurrency patterns',
    'Production-scale optimization',
  ]),
  template('backend', 'coding', '3-6', mid, [
    'Primarily easy problems with hand-holding',
    'Ignoring code quality and structure',
    'Skipping testing discussion',
    'Pure algorithmic puzzles without backend context',
  ]),
  template('backend', 'coding', '7+', senior, [
    'LeetCode-style puzzles as primary evaluation',
    'Simple problems without architectural thinking',
    'Ignoring production concerns',
    'Single correct answer problems',
    'Heavy algorithmic focus over design judgment',
  ]),
]
