import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Backend × Behavioral × 0-2 ────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-introduction', 'Resume walkthrough', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves. Calibrate scope expectations for junior level.',
    'Surface only — move on after 2 minutes.', 'Stories from academics, internships, hackathons are expected.'],
  ['motivation-curiosity', 'Motivation and curiosity', 'motivation', 'warm-up', 'must', 0,
    'Ask why backend engineering. Look for genuine curiosity about systems and how things work.',
    'Surface treatment — one follow-up at most.', 'Assess coachability and learning orientation.'],
  ['learning-new-tech', 'Learning a new technology', 'problem-solving', 'exploration', 'must', 2,
    'Ask about quickly learning a new language or framework. Look for resource strategy and persistence.',
    'Probe what resources they used, blockers encountered, and how fast they got productive.',
    'Accept bootcamp, course, or self-study context.'],
  ['team-collaboration', 'Team collaboration on a project', 'collaboration', 'exploration', 'must', 2,
    'Ask about working well within a team. Look for specific role, not just "we did X."',
    'Isolate their contribution: "You said we — what specifically did YOU do?"',
    'Academic projects and hackathons acceptable.'],
  ['debugging-problem', 'Debugging a difficult problem', 'problem-solving', 'exploration', 'must', 2,
    'Ask about struggling with a coding problem and resolving it. Look for systematic approach.',
    'Probe the actual technical approach, not just the outcome.',
    'Limited blast-radius debugging stories expected.'],
  ['handling-feedback', 'Handling feedback and criticism', 'self-awareness', 'exploration', 'if-time', 1,
    'Ask about receiving critical feedback and how it helped them improve.',
    'Probe what changed in their behavior afterward.'],
  ['adaptability-pressure', 'Adaptability under pressure', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a project that didn\'t go as planned. Look for adaptation, not just endurance.',
    'Probe what they did differently, not just that they worked harder.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-growth', 'Growth mindset', 'motivation', 'closing', 'must', 0,
    'Ask where they want to grow and what excites them. Assess enthusiasm and self-awareness.',
    'Surface — wrap up the interview warmly.'],
]

// ─── Backend × Behavioral × 3-6 ────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['project-ownership', 'Project ownership narrative', 'ownership', 'warm-up', 'must', 0,
    'Ask candidate to walk through a significant project they owned end-to-end. Calibrate scope.',
    'Surface — use this to pick follow-up topics.', 'Must demonstrate personal ownership of outcomes.'],
  ['technical-decision-making', 'Technical decision-making', 'technical-depth', 'exploration', 'must', 2,
    'Ask about a major technical decision and how they evaluated trade-offs.',
    'Probe why that approach over alternatives, what constraints shaped it.',
    'Expect references to real production systems.'],
  ['conflict-resolution', 'Conflict resolution with peers', 'collaboration', 'exploration', 'must', 2,
    'Ask about a conflict with a coworker and how they resolved it. Look for both perspectives.',
    'Probe both sides of the conflict and the resolution process.'],
  ['handling-ambiguity', 'Handling ambiguity', 'problem-solving', 'exploration', 'must', 2,
    'Ask about navigating unclear requirements. Look for initiative in defining scope.',
    'Probe what they did when they didn\'t have enough information.'],
  ['cross-functional-collaboration', 'Cross-functional collaboration', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about working with PMs, designers, or other teams. Look for friction points and resolution.',
    'Probe specific friction points and how they bridged communication gaps.'],
  ['incident-response', 'Production incident response', 'operational', 'exploration', 'if-time', 2,
    'Ask about a production incident. Look for composure, timeline, root cause, and postmortem.',
    'Probe timeline, root cause analysis, and what changed to prevent recurrence.'],
  ['prioritization-tradeoffs', 'Prioritization under pressure', 'problem-solving', 'exploration', 'must', 2,
    'Ask about having too many things to do and how they prioritized. Look for frameworks.',
    'Probe the framework used (urgency/impact), not just "I worked hard."'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['growth-mentoring', 'Growth and mentoring', 'leadership', 'closing', 'must', 0,
    'Ask about onboarding or mentoring a junior engineer. Assess investment in others.',
    'One example suffices — surface treatment.'],
]

// ─── Backend × Behavioral × 7+ ─────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['career-impact', 'Career narrative and impact trajectory', 'leadership', 'warm-up', 'must', 0,
    'Ask about the biggest impact in their career. This is a curated story, not a resume walkthrough.',
    'Surface — calibrate scope and leadership dimensions.', 'Must show multifaceted leadership.'],
  ['architecture-change', 'Driving architecture changes across teams', 'technical-depth', 'exploration', 'must', 2,
    'Ask about driving a significant technical change affecting multiple teams.',
    'Probe political landscape, opposition, how consensus was built, compromises.',
    'Scope must extend beyond immediate team.'],
  ['influence-without-authority', 'Leading without authority', 'leadership', 'exploration', 'must', 2,
    'Ask about influencing a decision without formal authority. Look for persuasion and case-making.',
    'Probe who opposed, what data was used, how they built consensus.'],
  ['stakeholder-conflict', 'Navigating organizational ambiguity', 'leadership', 'exploration', 'must', 2,
    'Ask about making progress with conflicting stakeholder requirements.',
    'Probe both sides of the conflict and the resolution framework used.'],
  ['mentorship-and-growth', 'Building and mentoring teams', 'leadership', 'exploration', 'must', 2,
    'Ask how they\'ve invested in growing engineers. Look for systems, not one-off mentoring.',
    'Probe specific programs: pairing, knowledge-sharing, career conversations.',
    'Must show multiplicative impact — making the whole team better.'],
  ['strategic-tech-decision', 'Strategic technical decision with business impact', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about a technical decision with significant business implications.',
    'Probe the business reasoning, not just technical merits.'],
  ['engineering-culture', 'Setting engineering standards and culture', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they\'ve established or changed engineering practices.',
    'Probe what practices outlasted them and how they drove adoption.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['failure-org-consequences', 'Failure with organizational consequences', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant failure and what they did differently. Look for organizational learning.',
    'Probe systemic changes, not just personal growth.', 'Failure questions carry more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('backend', 'behavioral', '0-2', entry, [
    'Organizational strategy or direction-setting',
    'Cross-team influence with senior stakeholders',
    'Production incident management or on-call',
    'Multi-month project ownership',
    'Building engineering culture',
  ]),
  template('backend', 'behavioral', '3-6', mid, [
    'Organizational-level strategy',
    'Building teams from scratch or hiring decisions',
    'Influencing company-level roadmap',
    'Setting org-wide engineering standards',
    'Pure academic or theoretical questions',
  ]),
  template('backend', 'behavioral', '7+', senior, [
    'Basic teamwork questions',
    'Individual coding or debugging stories',
    'Questions answerable with limited scope',
    'Learning a new technology as primary topic',
    'Questions an IC3/IC4 could answer equally well',
  ]),
]
