import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['requirements-gathering', 'Requirements gathering', 'problem-solving', 'warm-up', 'must', 0,
    'Present a well-defined problem (URL shortener). Guide candidate through functional requirements.',
    'Surface — note whether candidate asks questions before jumping in.', 'Interviewer-driven format.'],
  ['component-identification', 'High-level component identification', 'technical-depth', 'exploration', 'must', 2,
    'Ask candidate to identify basic components: client, server, database. Assess connected thinking.',
    'Probe how components connect and communicate.', 'Focus on clarity and structured thinking.'],
  ['api-design-basic', 'API design', 'technical-depth', 'exploration', 'must', 2,
    'Ask for REST endpoints, HTTP methods, basic request/response for the scenario.',
    'Probe status codes and resource naming conventions.'],
  ['data-model', 'Data model design', 'technical-depth', 'exploration', 'must', 2,
    'Ask for tables, relationships, primary/foreign keys.',
    'Probe "What if you need to store X additionally?"', 'Basic and well-constrained scope.'],
  ['read-write-flow', 'Read/write flow walkthrough', 'technical-depth', 'exploration', 'if-time', 1,
    'Walk through what happens on a read vs write. Assess end-to-end understanding.',
    'Probe where bottlenecks might appear.'],
  ['simple-caching', 'Simple caching introduction', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask what a cache is and where they would put one. Awareness-level assessment.',
    'Knowing a cache exists and why is sufficient.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['scaling-awareness', 'Basic scaling awareness', 'technical-depth', 'closing', 'must', 0,
    'Ask "What if 10x more users?" Assess awareness that scaling concepts exist.',
    'Surface — load balancing awareness is sufficient.'],
]

const mid: CompactSlot[] = [
  ['req-estimation', 'Requirements and back-of-envelope estimation', 'problem-solving', 'warm-up', 'must', 0,
    'Present problem (chat system, news feed). Expect proactive questions about scale, latency, read/write ratio.',
    'Surface — assess estimation skills (QPS, storage, bandwidth).', 'Collaborative format.'],
  ['high-level-arch', 'High-level architecture', 'technical-depth', 'exploration', 'must', 2,
    'Complete architecture: API gateway, services, database, cache, CDN, queues. Should move quickly.',
    'Probe technology choices and justification (Redis, Kafka, etc.).'],
  ['data-model-indexing', 'Data model with indexing strategy', 'technical-depth', 'exploration', 'must', 2,
    'Deep data model with indexing, read/write patterns, and partitioning strategy.',
    'Probe index selection reasoning and write amplification tradeoffs.'],
  ['caching-deep', 'Caching strategy', 'technical-depth', 'exploration', 'must', 2,
    'Cache layers, invalidation, TTL, cache-aside vs write-through. Must go beyond name-dropping.',
    'Probe "What if cached data is stale?" and invalidation edge cases.'],
  ['scalability', 'Scalability deep-dive', 'technical-depth', 'exploration', 'if-time', 2,
    'Horizontal scaling, sharding, replication. "What if 100x traffic?"',
    'Probe specific sharding strategies and rebalancing.'],
  ['async-queues', 'Message queues and async processing', 'technical-depth', 'exploration', 'if-time', 2,
    'When to go async, delivery guarantees, dead letter queues.',
    'Probe "What happens when consumer is down?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['failure-modes', 'Failure modes and monitoring', 'operational', 'closing', 'must', 0,
    'Ask "What happens when X fails?" Assess resilience thinking.',
    'Surface — monitoring and alerting awareness.'],
]

const senior: CompactSlot[] = [
  ['scope-definition', 'Scope definition from vague problem', 'problem-solving', 'warm-up', 'must', 0,
    'Present deliberately broad problem (Design YouTube). Candidate must drive scope and requirements.',
    'Surface — assess quality of trade-off decisions made during scoping.', 'Fully candidate-led.'],
  ['comprehensive-arch', 'Comprehensive architecture', 'technical-depth', 'exploration', 'must', 2,
    'Multiple services, data stores, communication patterns. Should speed through to leave time for deep dives.',
    'Probe why specific patterns chosen over alternatives.'],
  ['component-deep-dive', 'Critical component deep-dive', 'technical-depth', 'exploration', 'must', 2,
    'Deep dive into 2-3 critical components with implementation-level detail.',
    'Probe "What if this component fails?" and cascading failure scenarios.',
    'Where senior interviews are won or lost.'],
  ['consistency-distributed', 'Consistency models and distributed tradeoffs', 'technical-depth', 'exploration', 'must', 2,
    'CAP/PACELC applied to real design decisions. Must choose tradeoffs, not just identify them.',
    'Probe "Why consistency over availability here?" with business justification.'],
  ['multi-region', 'Multi-region deployment', 'technical-depth', 'exploration', 'if-time', 2,
    'Global data replication, latency-based routing, conflict resolution across regions.',
    'Probe disaster recovery and region failover strategy.'],
  ['cost-optimization', 'Cost optimization and efficiency', 'operational', 'exploration', 'if-time', 2,
    'Infrastructure costs, compute vs storage tradeoffs, reserved vs spot capacity.',
    'Probe cost estimation methodology and optimization priorities.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['system-evolution', 'System evolution and tech debt', 'technical-depth', 'closing', 'must', 0,
    'How does design change over 3 years? How does tech debt accumulate? Assess forward-looking reasoning.',
    'Surface — assess long-term thinking.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('backend', 'system-design', '0-2', entry, [
    'Distributed systems or CAP theorem',
    'Sharding or data replication',
    'Specific technology name-dropping requirements',
    'Multi-region deployment',
    'Complex scaling beyond basic caching',
  ]),
  template('backend', 'system-design', '3-6', mid, [
    'Organizational-level architecture',
    'Multi-region global systems',
    'Consensus algorithms (Paxos, Raft)',
    'Problems staying at surface level only',
  ]),
  template('backend', 'system-design', '7+', senior, [
    'Basic well-constrained problems (too simple)',
    'Interviewer driving the conversation',
    'Surface-level designs without deep dives',
    'Single correct answer problems',
    'Technology trivia over strategic reasoning',
  ]),
]
