import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Business × Case Study × 0-2 ─────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['case-clarifying-questions', 'Clarifying questions before structuring', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a case prompt. Wait and observe — does candidate ask 2-3 clarifying questions before structuring?',
    'Surface — jumping to analysis without clarifying is the #1 entry-level mistake.',
    'Custom frameworks over memorized templates — building from scratch beats robotically applying profitability tree.'],
  ['case-framework-structure', 'Case framework structuring', 'strategic-thinking', 'warm-up', 'must', 0,
    'Give candidate 60-90 seconds of silence to structure. Look for MECE framework tailored to the case.',
    'Surface — assess whether they present 3-4 branches with clear logic before diving into analysis.',
    'Taking structured silence is expected and rewarded — not a sign of hesitation.'],
  ['case-hypothesis-analysis', 'Hypothesis testing and branch analysis', 'financial-acumen', 'exploration', 'must', 2,
    'Ask candidate to work through the framework branch by branch. Provide data in response to good questions.',
    'Probe: "You said revenue is the issue. How would you narrow down whether it\'s price or volume?"',
    'Math must be done out loud — silent calculation is the fastest way to fail a case.'],
  ['case-quantification', 'Quantitative exercise within the case', 'financial-acumen', 'exploration', 'must', 2,
    'Insert a quantitative exercise: break-even, market sizing, or revenue impact calculation.',
    'Probe: "That number seems off. Can you walk me through the calculation again?"',
    'The #1 math mistake is losing zeros — always sanity-check large-number multiplications.'],
  ['case-insight-interpretation', 'Interpreting data and generating insight', 'strategic-thinking', 'exploration', 'must', 2,
    'Provide a chart or data exhibit. Ask what the data means strategically, not just numerically.',
    'Probe: "Good analysis. If you could only investigate one more thing before recommending, what would it be?"',
    'Analysis without "so what" — stating numbers without strategic meaning — is a red flag.'],
  ['case-new-information', 'Incorporating new information mid-case', 'strategic-thinking', 'exploration', 'if-time', 1,
    'Introduce new data or a constraint mid-case. Tests ability to adapt framework and update hypothesis.',
    'Probe: "The CEO is in 5 minutes. Give me your recommendation in 30 seconds."'],
  ['case-risk-identification', 'Identifying key risks to the recommendation', 'strategic-thinking', 'exploration', 'if-time', 2,
    'Ask what the biggest risk to their recommendation is and how they would mitigate it.',
    'Probe: "What\'s the worst-case scenario if your assumption about volume is wrong?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['case-final-recommendation', 'Decisive final recommendation', 'communication', 'closing', 'must', 0,
    'Ask for a final recommendation. Look for: clear direction, 2-3 reasons, acknowledged risks, mitigation.',
    'Surface — "it depends" is not a recommendation. Synthesis must be decisive.'],
]

// ─── Business × Case Study × 3-6 ─────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['mid-case-scoping', 'Case scoping and context-setting', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a complex multi-layered case. Assess quality of scoping questions — strategic awareness revealed here.',
    'Surface — better scoping demonstrates domain experience. Note what they ask for and what they ignore.',
    'Cases integrate multiple frameworks — market sizing plus competitive analysis plus financial modeling.'],
  ['ma-or-market-entry', 'M&A or market entry deep analysis', 'strategic-thinking', 'exploration', 'must', 2,
    'Present an M&A or market entry case requiring comprehensive evaluation including financial analysis.',
    'Probe: "The PE firm expects 3x return in 5 years. Does the deal work at this valuation?"',
    'Goes deeper than entry-level — regulatory landscape, reimbursement, required investment, 5-year projection.'],
  ['competitive-response', 'Competitive response strategy', 'strategic-thinking', 'exploration', 'must', 2,
    'Present a disruptive entrant scenario. Ask candidate to design a competitive response.',
    'Probe: "When do you compete directly vs. acquire vs. partner vs. concede the segment?"',
    'Game-theoretic thinking expected — anticipating competitor moves, defensive vs. offensive posture.'],
  ['operational-improvement', 'Operational improvement and margin analysis', 'financial-acumen', 'exploration', 'must', 2,
    'Present a company with margins 500bp below industry average. Ask for diagnosis and improvement program.',
    'Probe: "How does your recommendation change if optimizing for revenue instead of market share?"',
    'Must quantify each recommendation — "we should improve efficiency" without numbers fails.'],
  ['multi-exhibit-integration', 'Integrating insights across multiple data exhibits', 'financial-acumen', 'exploration', 'if-time', 2,
    'Provide 2-3 data exhibits simultaneously. Ask candidate to integrate findings into a coherent diagnosis.',
    'Probe: "A/B test shows +5% conversion but -2% retention. What do you do?"',
    'Mid-level cases test integration across analytical threads, not single-framework application.'],
  ['implementation-go-to-market', 'Implementation and go-to-market planning', 'stakeholder-management', 'exploration', 'if-time', 2,
    'Ask how they would execute their recommendation. Tests organizational change and milestone thinking.',
    'Probe: "Walk me through the first 90 days after the board approves your recommendation."'],
  ['portfolio-optimization', 'Portfolio prioritization and capital allocation', 'strategic-thinking', 'exploration', 'must', 2,
    'Present a multi-business-unit portfolio. Ask which to invest in, hold, or divest and why.',
    'Probe: "How does this fit with the company\'s broader portfolio strategy?"',
    'Industry context matters — generic frameworks without sector-specific adaptation fail.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['mid-case-synthesis', 'Synthesized recommendation with quantified impact', 'communication', 'closing', 'must', 0,
    'Ask for final recommendation with quantified impact, risk assessment, and implementation timeline.',
    'Surface — "we should probably" instead of "this would generate $XM" is inadequate at this level.'],
]

// ─── Business × Case Study × 7+ ─────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['senior-context-scoping', 'Strategic context scoping as peer conversation', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a real (anonymized) complex engagement scenario. Observe — does candidate jump to strategic insight?',
    'Surface — the best senior candidates go to the strategic insight in 2 min, then structure around it.',
    'The case IS the conversation — rigid 4-step framework exercise signals not ready for partner track.'],
  ['corporate-transformation', 'CEO-level corporate transformation strategy', 'strategic-thinking', 'exploration', 'must', 2,
    'Present a full corporate transformation challenge. Ask for a 3-year repositioning strategy.',
    'Probe: "The board wants this in 6 months, not 12. What do you cut? What do you protect?"',
    'Must address portfolio reconfiguration, org redesign, investment sequencing, and board communication.'],
  ['portfolio-rationalization', 'Portfolio rationalization and capital reallocation', 'financial-acumen', 'exploration', 'must', 2,
    'Ask which of 6 business divisions to invest in, divest, or restructure and why.',
    'Probe: "This strategy requires $200M over 3 years. The company has $300M and 4 competing priorities."',
    'Three Horizons framework expected — balance short-term performance with long-term positioning.'],
  ['disruption-response', 'Market disruption response under time pressure', 'strategic-thinking', 'exploration', 'must', 2,
    'Present a venture-funded disruptor with 18-month runway before material impact. Design the response.',
    'Probe: "You\'re 6 months into execution and results are 40% below projections. What do you do?"',
    'Organizational and implementation dimensions mandatory — 70% execution design, 30% analytics.'],
  ['org-restructuring', 'Post-merger or post-pivot organizational restructuring', 'leadership', 'exploration', 'if-time', 2,
    'Ask for an org restructuring design after a merger or strategic pivot. Tests org design expertise.',
    'Probe: "The CEO of the acquired company demands to stay. She\'s brilliant but culturally misaligned."'],
  ['pe-value-creation', 'Private equity value creation plan', 'financial-acumen', 'exploration', 'if-time', 2,
    'Ask for a PE-style 100-day value creation plan with measurable EBITDA targets.',
    'Probe: "If you\'re wrong about this recommendation, what\'s the cost? What\'s your hedge?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['board-strategic-pitch', 'Board pitch on a strategic pivot', 'communication', 'closing', 'must', 0,
    'Ask them to pitch a complex tradeoff recommendation to a board in under 5 minutes.',
    'Probe: "A board member asks what\'s the probability this works. How do you answer?"',
    'C-suite communication explicitly tested — concise, data-backed, explicit risk/reward and resource requests.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('business', 'case-study', '0-2', entry, [
    'Memorized frameworks applied without adaptation (robotically using the profitability tree)',
    'Doing math silently — interviewer cannot follow the reasoning',
    'Forgetting to ask clarifying questions before structuring',
    'Wishy-washy recommendation — "we could do A or B, it depends" without committing',
    'Over-engineering the structure and leaving too little time for insight and synthesis',
  ]),
  template('business', 'case-study', '3-6', mid, [
    'Generic frameworks without adaptation to case context',
    'Ignoring business model and monetization implications',
    'No competitive awareness — analyzing in a vacuum',
    'Skipping implementation and go-to-market strategy',
    'Analysis without quantification — "we should probably" instead of "this would generate $XM"',
  ]),
  template('business', 'case-study', '7+', senior, [
    'Treating the case like a junior exercise with a structured 4-step framework walk-through',
    'Strategy without implementation — the slide deck is not the deliverable',
    'Ignoring organizational resistance, cultural integration, and change management',
    'Generic frameworks (Porter\'s Five Forces as main analytical tool for a restructuring)',
    'Solving the presenting symptom instead of the structural cause',
  ]),
]
