import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Business × Behavioral × 0-2 ────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['resume-walkthrough', 'Resume walkthrough and motivation', 'communication', 'warm-up', 'must', 0,
    'Ask candidate to walk through their background and why consulting or strategy. Assess communication clarity.',
    'Surface — use to calibrate scope expectations. Why consulting, why this firm, why now.',
    'Potential over proven track record — assess analytical horsepower and learning speed.'],
  ['analytical-thinking', 'Breaking down a complex problem', 'strategic-thinking', 'warm-up', 'must', 0,
    'Ask about breaking down a complex problem to find a solution. Tests structured thinking instinct.',
    'Surface — one follow-up at most.', 'Structured thinking is the single highest-signal trait at this level.'],
  ['handling-ambiguity', 'Handling ambiguity and incomplete information', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask about navigating unclear or incomplete information. Tests comfort decomposing fuzzy problems.',
    'Probe: "At the point where you didn\'t have enough info, what did you actually do?"',
    'STAR method expected — candidates who don\'t use it stand out negatively.'],
  ['teamwork-collaboration', 'Cross-functional collaboration', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about working with people from different backgrounds to achieve a goal.',
    'Isolate their contribution: "You said we — what specifically did YOU do versus the team?"',
    'School, internship, hackathon, and volunteer stories are expected and acceptable.'],
  ['leadership-without-title', 'Taking initiative without a formal title', 'leadership', 'exploration', 'must', 2,
    'Ask about taking initiative or leading without a formal title. McKinsey PEI "Leadership" dimension.',
    'Probe what they did to mobilize others and what the outcome was.',
    'Shows proactive drive — internship, school club, or volunteer context is fine.'],
  ['explaining-complex-ideas', 'Explaining a complex idea simply', 'communication', 'exploration', 'if-time', 1,
    'Ask about explaining a complex idea to a non-technical audience. Tests translation over jargon.',
    'Probe what they changed in their communication based on audience feedback.'],
  ['handling-setback', 'Resilience and overcoming a setback', 'stakeholder-management', 'exploration', 'if-time', 2,
    'Ask about a significant setback and how they responded. McKinsey PEI "Drive" dimension.',
    'Probe what they did differently after the failure and what they learned about themselves.',
    'Tests grit, ownership, and learning from failure rather than blame.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['motivation-fit', 'Motivation and firm fit', 'communication', 'closing', 'must', 0,
    'Ask why consulting and why this firm specifically. Evaluate authenticity and quality of research.',
    'Surface — wrap up warmly. Quality of their closing questions also evaluated.'],
]

// ─── Business × Behavioral × 3-6 ────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['career-story', 'Career arc and narrative', 'communication', 'warm-up', 'must', 0,
    'Ask for extended career walkthrough — key transitions, why consulting, what they want next.',
    'Surface — more scrutiny than entry-level. Career intentionality matters at this level.',
    'Stories must feature real responsibility and consequences — "I worked hard" is not a story.'],
  ['client-relationship-management', 'Managing a difficult client relationship', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about managing a difficult client relationship. The signature mid-level consulting question.',
    'Probe: "How did the client react when you delivered that message? What did you do next?"',
    'Client-facing credibility is the differentiator — delivering hard truths while maintaining trust.'],
  ['stakeholder-alignment', 'Aligning competing stakeholders on one recommendation', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about aligning multiple stakeholders with competing interests. Tests structured influence.',
    'Probe: "Who specifically was resistant? What was their underlying concern?"',
    'Must map stakeholder incentives and describe deliberate coalition-building strategy.'],
  ['leading-under-ambiguity', 'Leading a team or workstream through ambiguity', 'leadership', 'exploration', 'must', 2,
    'Ask about leading a workstream through a vague, high-stakes project. Tests translation of ambiguity to action.',
    'Probe: "Walk me through the exact conversation where you pushed back on the partner or VP."',
    'Engagement manager expectations — ran workstreams, managed junior members, interfaced with client sponsors.'],
  ['delivering-under-pressure', 'Delivering a recommendation under a tight deadline', 'strategic-thinking', 'exploration', 'if-time', 2,
    'Ask about delivering a critical recommendation with imperfect information. Tests 80% vs. perfection judgment.',
    'Probe what alternatives they considered and why they chose this approach over others.'],
  ['developing-others', 'Coaching or developing a junior team member', 'leadership', 'exploration', 'if-time', 1,
    'Ask about coaching or developing a junior team member. Tests investment in team capability.',
    'Probe: "How did you handle the underperformer? What specifically changed?"'],
  ['driving-lasting-change', 'Work that led to lasting change', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask about work that led to lasting change at a client or organization. Tests implementation thinking.',
    'Probe: "How did you measure success? What happened 6 months later?"',
    'Quantified impact expected — cycle time, cost savings, revenue impact with specific numbers.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['navigating-org-politics', 'Navigating organizational complexity', 'stakeholder-management', 'closing', 'must', 0,
    'Ask about influencing a decision in a politically complex environment. Tests courage and constructiveness.',
    'Surface — one clear example of managing competing pressures. Probe for outcome and relationship preservation.'],
]

// ─── Business × Behavioral × 7+ ─────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['extended-career-narrative', 'Extended career narrative and leadership trajectory', 'leadership', 'warm-up', 'must', 0,
    'Ask about career arc with emphasis on leadership trajectory, business impact, and strategic choices.',
    'Surface — partner-level assessment: "Would I trust this person with a $10M+ client relationship?"',
    'Questions shift from solving problems to building systems and organizations.'],
  ['building-from-scratch', 'Building a practice, team, or capability from scratch', 'leadership', 'exploration', 'must', 2,
    'Ask about building something from scratch — practice, team, capability, or market offering.',
    'Probe: "How large was the team? What was the budget? What measurable impact did it produce?"',
    'Commercial track record is non-negotiable — must demonstrate revenue generation or P&L ownership.'],
  ['executive-board-communication', 'Communicating strategic decisions to C-suite or board', 'communication', 'exploration', 'must', 2,
    'Ask how they communicate strategic decisions to a board or C-suite audience. Tests tailored communication.',
    'Probe: "How did you frame this for the board? What questions did they push back on?"',
    'Not just presenting — shaping decisions. Must frame tradeoffs concisely with explicit resource requests.'],
  ['organizational-transformation', 'Leading organizational transformation', 'leadership', 'exploration', 'must', 2,
    'Ask about leading an organization through major change — restructuring, transformation, or strategic pivot.',
    'Probe: "How did you make this stick? What happened after you left the room?"',
    'Must address culture, communication, and sustained execution — not just project management.'],
  ['pl-ownership', 'P&L ownership and revenue accountability', 'financial-acumen', 'exploration', 'if-time', 2,
    'Ask about accountability for a revenue target or P&L. Tests commercial acumen.',
    'Probe: "Walk me through how you won that client. What was your approach to the relationship?"'],
  ['developing-next-gen-leaders', 'Developing the next generation of leaders', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they identified, developed, and promoted talent. Tests pipeline thinking, not just managing reports.',
    'Probe: "Who did you develop who is now in a leadership role? What was your approach?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['failure-at-scale', 'Significant failure with organizational consequences', 'leadership', 'closing', 'must', 0,
    'Ask about a significant professional failure and how they handled the aftermath at org level.',
    'Probe: "What did the organization change? What did YOU personally change?"',
    'At this level, failures have organizational consequences — tests accountability and institutional learning.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('business', 'behavioral', '0-2', entry, [
    'Managing P&L, revenue targets, or organizational budgets',
    'Building or leading a consulting practice or business unit',
    'Board-level communication or C-suite stakeholder management',
    'Multi-year strategic planning or portfolio optimization',
    'Expecting quantified business impact in millions — accept qualitative or small-scale metrics',
  ]),
  template('business', 'behavioral', '3-6', mid, [
    'School projects or classroom examples (must be professional context)',
    'Basic teamwork without leadership or influence component',
    'Purely technical execution without strategic judgment',
    'Partnership development or board-level relationship management',
    'Practice-building, revenue generation, or firm leadership',
  ]),
  template('business', 'behavioral', '7+', senior, [
    'Individual contributor tasks without organizational scope',
    'Basic teamwork or collaboration without leadership dimension',
    'Project execution without strategic context or business impact',
    'Learning from feedback (entry-level topic)',
    'Client management at workstream level (mid-level topic)',
  ]),
]
