import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Business × Technical × 0-2 ─────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['market-sizing', 'Market sizing and estimation', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a market sizing prompt. Tests structured decomposition and comfort with assumptions and math.',
    'Surface — walk through their approach before they calculate. Approach matters more than the number.',
    'Process over precision — well-reasoned estimate within 2x of reality is a pass.'],
  ['data-interpretation', 'Chart or data interpretation', 'financial-acumen', 'warm-up', 'must', 0,
    'Provide a chart or table. Ask what story the data tells and what they would investigate next.',
    'Surface — probe whether they generate hypotheses unprompted or just read numbers.',
    'Strongest candidates extract insight and hypothesis, not just describe the data.'],
  ['mental-math-quantitative', 'Quantitative reasoning and mental math', 'financial-acumen', 'exploration', 'must', 2,
    'Present a quick math or logic problem (percentage change, break-even, revenue impact). Talk through it.',
    'Probe: "Can you double-check that multiplication? Walk me through it step by step."',
    'The #1 math mistake is losing zeros — always sanity-check result against common sense.'],
  ['excel-proficiency', 'Excel or spreadsheet tool proficiency', 'financial-acumen', 'exploration', 'must', 2,
    'Ask about building a pivot table or VLOOKUP to analyze sales data. Tests practical intermediate competency.',
    'Probe: "What if the dataset had 100K rows — how would your approach change?"',
    'Intermediate Excel is the baseline — pivot tables, VLOOKUP, conditional formatting, basic charts.'],
  ['basic-financial-literacy', 'Basic financial literacy and P&L logic', 'financial-acumen', 'exploration', 'must', 2,
    'Ask what could explain revenue growing 12% while profit declined 5%. Tests margin dynamics.',
    'Probe: "Which cost line would you look at first? What data would confirm your hypothesis?"',
    'Conceptual understanding, not full financial modeling — revenue vs. cost structure, margin basics.'],
  ['business-framework-application', 'Business framework application', 'strategic-thinking', 'exploration', 'if-time', 1,
    'Ask how they would structure an analysis of market entry or similar strategic question.',
    'Probe: "That framework assumes X — what if X is not true in this context?"'],
  ['sql-fundamentals', 'SQL query writing', 'financial-acumen', 'exploration', 'if-time', 2,
    'Ask them to write a query to find top customers by revenue in a quarter. Tests basic SQL competency.',
    'Probe: "How would you add a year-over-year comparison to this query?"',
    'SQL increasingly standard — JOINs, GROUP BY, and basic aggregation expected even at entry level.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['data-communication', 'Presenting analysis to a non-technical stakeholder', 'communication', 'closing', 'must', 0,
    'Ask how they would present their findings to a client who does not know Excel or SQL.',
    'Surface — tests ability to translate quantitative findings into clear actionable narrative.'],
]

// ─── Business × Technical × 3-6 ─────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['problem-framing', 'Business problem clarification and scoping', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a complex business scenario. Assess whether they ask clarifying questions about objectives and data.',
    'Surface — better scoping questions equal a better analytical exercise. Note question quality.',
    'Analysis must drive strategy, not just describe data — "revenue is declining" is observation, not insight.'],
  ['financial-modeling', 'Financial modeling and scenario analysis', 'financial-acumen', 'exploration', 'must', 2,
    'Ask them to walk through building a 3-year projection and key assumptions. Tests model-building depth.',
    'Probe: "Which assumption has the most impact on the outcome? How sensitive is the result to it?"',
    'Must articulate assumption sensitivity — "A 200bp change in discount rate moves valuation by $15M."'],
  ['competitive-analysis', 'Competitive analysis and strategic positioning', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask for competitive landscape analysis of an industry. Tests Porter\'s Five Forces application with real data.',
    'Probe: "How does your recommendation change if the competitive landscape shifts in 12 months?"',
    'Must reference real competitors and market share data — generic SWOT without data fails.'],
  ['market-entry-quantification', 'Market entry opportunity sizing', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask whether a company should enter a new market. Look for TAM sizing integrated with financial analysis.',
    'Probe: "What discount rate would you use? What ROI threshold makes this worth the investment?"',
    'Quantitative intuition matters — "this market is roughly $2B growing at 5%" with rough reasoning.'],
  ['advanced-data-analysis', 'Operational data insight generation', 'financial-acumen', 'exploration', 'if-time', 2,
    'Provide operational data and ask for the 3 most impactful findings and recommended actions.',
    'Probe: "Your analysis shows two conflicting signals. How do you resolve the tension?"',
    'Expected to go beyond descriptive analytics to diagnostic and prescriptive insight.'],
  ['pricing-strategy', 'Pricing strategy and revenue optimization', 'financial-acumen', 'exploration', 'if-time', 2,
    'Ask them to design a pricing analysis for a company losing deals on price. Tests value-based pricing.',
    'Probe: "How would you measure customer willingness-to-pay without surveys?"'],
  ['recommendation-synthesis', 'Strategic recommendation synthesis', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask for their final recommendation from the analytical exercise. Tests synthesis across multiple threads.',
    'Probe: "Walk me through the first 30 days of implementing your recommendation."',
    'Communication of analysis to non-technical stakeholders tested — explain DCF to a CEO.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['implementation-risks', 'Implementation plan and key risks', 'stakeholder-management', 'closing', 'must', 0,
    'Ask what could go wrong with their recommendation and how they would mitigate it.',
    'Surface — "good recommendation, now how do you execute it?" separates mid from entry level.'],
]

// ─── Business × Technical × 7+ ──────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['complex-scenario-framing', 'Strategic scenario scoping and hypothesis formation', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a multi-business-unit strategic crossroads. Assess incisive scoping questions and upfront hypotheses.',
    'Surface — financial reasoning embedded in strategic questions, not asked in isolation.',
    'Experience-formed opinions expected — "I don\'t know but I\'d research it" is no longer sufficient.'],
  ['investment-due-diligence', 'Investment thesis and strategic due diligence', 'financial-acumen', 'exploration', 'must', 2,
    'Ask them to walk through a due diligence framework for a large acquisition. Tests comprehensive assessment.',
    'Probe: "What\'s the single number for deal health you give the board? What do you refuse to collapse into one metric?"',
    'Three types of due diligence: Financial (QoE, NWC), Commercial (market position), Operational (integration risk).'],
  ['portfolio-capital-allocation', 'Portfolio strategy and capital allocation', 'strategic-thinking', 'exploration', 'must', 2,
    'Present a multi-business-unit portfolio and ask which to invest in, hold, or divest.',
    'Probe: "Two business units have conflicting strategic priorities that can\'t both be funded. How do you resolve?"',
    'Tests Three Horizons thinking, growth-share matrix logic, and portfolio-level tradeoff decisions.'],
  ['ma-integration-plan', 'M&A integration and value capture', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask for a 100-day integration plan after an acquisition. Tests practical M&A and EBITDA realization.',
    'Probe: "Integration is 9 months behind plan. Revenue synergies aren\'t materializing. What do you do?"',
    'PE-style format — actionable 100-day plan with measurable EBITDA growth targets.'],
  ['strategic-planning-design', 'Designing the strategic planning process', 'strategic-thinking', 'exploration', 'if-time', 2,
    'Ask how they would design the annual strategic planning process for a large company.',
    'Probe: "The chief strategy officer left 3 months ago. The planning process has stalled. Walk me through your first 30 days."'],
  ['org-design-for-execution', 'Organizational design for strategic execution', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they would restructure an org to execute a customer-centric strategy shift.',
    'Probe: "This strategy requires firing 2,000 people. How do you present that to the board? To employees?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['board-pitch-synthesis', 'Board pitch on a strategic recommendation', 'communication', 'closing', 'must', 0,
    'Ask them to pitch their recommendation to a simulated board in under 3 minutes. Tests executive narrative.',
    'Probe: "This investment won\'t show impact for 18 months. How do you justify it to a quarterly-focused board?"',
    'Must frame complex tradeoffs concisely with quantified impact, key risks, and resource requirements.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('business', 'technical', '0-2', entry, [
    'DCF valuation, WACC calculation, or complex financial modeling',
    'Advanced statistical methods (regression, hypothesis testing)',
    'M&A analysis, due diligence, or deal structuring',
    'Multi-scenario financial models with sensitivity analysis',
    'P&L management or investment thesis development',
  ]),
  template('business', 'technical', '3-6', mid, [
    'Reciting frameworks without adapting to context (generic Porter\'s without specific data)',
    'Building models without articulating key assumptions and sensitivities',
    'Analysis without recommendation — data description without strategic conclusion',
    'Over-precision without acknowledging uncertainty ranges',
    'Single-metric myopia ignoring tradeoffs',
  ]),
  template('business', 'technical', '7+', senior, [
    'Same analytical depth as mid-level — executing analysis instead of designing frameworks',
    'Strategy without implementation plan — the slide deck is not the answer',
    'Ignoring organizational resistance and change management',
    'Financial analysis without strategic context (analyst-level DCF without CEO-level "so what")',
    'Recommendations that do not scale beyond a single business unit',
  ]),
]
