import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Civil × Behavioral × 0-2 ───────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro-project', 'Intro and a project you worked on', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves and describe a project or site they have worked on. Look for genuine interest in how things get built.',
    'Surface only — use to pick follow-up topics.', 'Internships, site visits, and academic projects are all expected at this level.'],
  ['motivation-civil', 'Why civil engineering and site work', 'motivation', 'warm-up', 'must', 0,
    'Ask what drew them to civil engineering and what they enjoy about being on a site. Look for a builder\'s curiosity.',
    'One follow-up at most — keep it warm.', 'Assess attitude to field work and coachability, not depth.'],
  ['spotted-drawing-mismatch', 'Spotting a drawing-vs-site mismatch', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask about a time on site they noticed something that did not match the drawing. Look for diligence and the instinct to flag it.',
    'Probe who they escalated to and what happened — not just that they noticed.',
    'Checking shuttering, reinforcement, or levels is the expected scope here.'],
  ['raised-safety-concern', 'Raising a safety concern as a junior', 'ownership', 'exploration', 'must', 2,
    'Ask about a safety issue they raised despite being junior. Look for the courage to speak up.',
    'Probe how it was received and whether anything changed afterward.',
    'Even small near-misses count — focus on the instinct to act.'],
  ['learned-from-senior', 'Learning from a senior engineer on site', 'problem-solving', 'exploration', 'must', 2,
    'Ask about something they learned from watching a senior engineer handle a site problem. Look for absorption and reflection.',
    'Probe the actual lesson and how they have applied it since.',
    'Observing and assisting is the expected scope; look for curiosity.'],
  ['working-with-contractor', 'Working with a contractor or foreman', 'collaboration', 'exploration', 'if-time', 1,
    'Ask about working alongside a contractor, foreman, or labour gang. Look for respect and clear communication.',
    'Probe how they communicated an instruction or constraint without friction.'],
  ['site-pressure-junior', 'Handling a stressful moment on site', 'adaptability', 'exploration', 'if-time', 2,
    'Ask about a time something went wrong on site and they felt the pressure. Look for composure and asking for help.',
    'Probe their escalation instinct — knowing when to call a senior is a strength here.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-what-excites', 'What kind of projects excite you most', 'motivation', 'closing', 'must', 0,
    'Ask what kind of structures or civil projects they most want to work on next. Assess enthusiasm and self-awareness.',
    'Surface — wrap up warmly and note growth signals.'],
]

// ─── Civil × Behavioral × 3-6 ───────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['quality-schedule-evolution', 'How your view of quality vs schedule evolved', 'motivation', 'warm-up', 'must', 0,
    'Ask how their thinking on balancing quality and program changed with experience. Calibrate field judgment.',
    'Surface — use to identify which deep-dives to pursue.', 'Must reflect on real projects with real schedule pressure.'],
  ['owned-critical-activity', 'Owning a critical site activity', 'ownership', 'exploration', 'must', 2,
    'Ask about a critical activity they owned — a major pour, deep excavation, or heavy lift. Look for planning and control.',
    'Probe the method statement, the contingency they held, and what they would do differently.',
    'Should own the activity end-to-end, not just observe — expect planning and coordination.'],
  ['quality-under-pressure', 'Holding the line on quality or safety under schedule pressure', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask about a time the program pushed them toward cutting a corner. Look for refusal to compromise and how they made the case.',
    'Probe how they framed the argument to the contractor or client and what it cost.',
    'Standing firm with a clear, evidenced argument differentiates at this level.'],
  ['drawing-site-conflict', 'Resolving a design-vs-construction conflict', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a clash between the design and what was buildable on site. Look for a structured resolution, not a workaround.',
    'Probe who they involved — designer, consultant, RFI process — and how the decision was recorded.',
    'Expect ownership of the resolution path, not just flagging the clash.'],
  ['contractor-coordination', 'Coordinating multiple contractors or trades', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about coordinating subcontractors or trades whose work interfaced. Look for sequencing and interface management.',
    'Probe how they prevented or resolved a clash between trades on the program.'],
  ['variation-or-rework', 'Handling a variation or significant rework', 'ownership', 'exploration', 'if-time', 2,
    'Ask about managing a variation or a rework that hit cost and time. Look for ownership of the commercial and technical impact.',
    'Probe how they documented it and protected the project position.'],
  ['client-or-consultant-friction', 'Friction with a client or consultant', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about friction with a client or consultant over scope, quality, or pace. Look for influence and professionalism.',
    'Probe how they aligned on the shared goal rather than digging in.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retrospective-site-decision', 'A site decision you\'d make differently', 'self-awareness', 'closing', 'must', 0,
    'Ask what they would change knowing what they know now. Assess honesty and growth.',
    'Surface — one example suffices; wrap up warmly.'],
]

// ─── Civil × Behavioral × 7+ ────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['delivery-leadership', 'Project delivery as a leadership discipline', 'leadership', 'warm-up', 'must', 0,
    'Ask how they connect site delivery to commercial, safety, and client outcomes. Look for multi-dimensional leadership thinking.',
    'Surface — calibrate scope and identify which leadership dimensions to probe.',
    'Must show impact across cost, time, quality, safety, and people dimensions.'],
  ['built-safety-culture', 'Building a safety culture on a site', 'leadership', 'exploration', 'must', 2,
    'Ask about establishing or transforming the safety culture on a site they ran. Look for changing behaviour, not just posting signs.',
    'Probe the resistance they faced from the workforce or contractors and how the culture stuck.',
    'Scope must span the whole site and its subcontractors — not one toolbox talk.'],
  ['major-claim-negotiation', 'Negotiating a major variation or claim', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about negotiating a significant variation or claim with a client. Look for protecting both the relationship and the position.',
    'Probe how they framed the commercial argument and what evidence carried it.',
    'High-value, multi-party negotiation with real commercial stakes expected.'],
  ['ran-project-pl', 'Running a project P&L and program', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask about owning a project\'s cost, program, and resources end-to-end. Look for genuine commercial control, not just reporting.',
    'Probe what they did when the project drifted on cost or time and how they recovered it.',
    'Full accountability for the outcome — not section-level scope — is what counts.'],
  ['stop-work-call', 'Crisis judgment — halting work on site', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a high-stakes call to stop or rework a major activity. Look for decision-making under pressure and incomplete information.',
    'Probe what drove the decision, the cost of it, and how they communicated it to the client.',
    'Multi-party, high-consequence decisions with real safety or commercial impact expected.'],
  ['mentoring-engineers', 'Developing junior engineers', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they have developed junior site engineers into independent owners. Look for deliberate investment in people.',
    'Probe a specific engineer they grew and how they did it.'],
  ['delivery-business-impact', 'Connecting delivery to commercial outcomes', 'leadership', 'exploration', 'if-time', 2,
    'Ask about a delivery decision with direct cost, reputation, or repeat-business impact. Look for business framing.',
    'Probe how they connected the engineering call to a specific commercial outcome.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['project-bet-failure', 'A project bet that didn\'t pan out', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant decision or project that underdelivered. Look for organizational learning, not excuses.',
    'Probe systemic changes they drove afterward, not just personal lessons.', 'Failure questions carry more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('civil', 'behavioral', '0-2', entry, [
    'Running a project P&L or negotiating major claims',
    'Building site-wide safety culture across subcontractors',
    'Deep code-clause or structural-analysis trivia (warm-up is not technical)',
    'Cross-project portfolio strategy or commercial leadership',
    'Generic conflict questions without a site or project context',
  ]),
  template('civil', 'behavioral', '3-6', mid, [
    'Entry-level "first site visit" framing',
    'Project-portfolio strategy or P&L ownership (senior territory)',
    'Generic teamwork stories without a construction or site context',
    'Accepting "the contractor messed up" without probing their own action',
    'Pure code or design trivia instead of delivery decision-making',
  ]),
  template('civil', 'behavioral', '7+', senior, [
    'Individual drawing checks or single safety observations',
    'Single-activity ownership without project-level scope',
    'Generic leadership questions that could apply to any role',
    'Questions a mid-level site engineer could answer equally well',
    'Accepting "we improved safety" without probing the culture change and enforcement',
  ]),
]
