import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Civil × Technical × 0-2 ────────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['technical-background', 'Engineering background and interests', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask the candidate to describe their civil engineering background and which areas — structures, geotech, construction — interest them most.',
    'Surface only — calibrate scope; no deep probing yet.', 'Foundational mechanics and reasoning matter more than breadth here.'],
  ['load-path-intro', 'Tracing a basic load path', 'technical-depth', 'warm-up', 'must', 0,
    'Ask them to describe how load travels from a slab down to the ground in a simple building. Look for a clear load path.',
    'Surface — note whether they think in terms of load paths at all.'],
  ['beam-analysis', 'Simply supported beam analysis', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to find reactions and where max bending moment and shear occur for a simply supported beam. Look for correct mechanics.',
    'Probe how the BMD and SFD change between a point load and a UDL — not just the numbers.',
    'Hand-calculation reasoning expected; accept clear sketches over precise figures.'],
  ['rcc-fundamentals', 'RCC beam reinforcement basics', 'technical-depth', 'exploration', 'must', 2,
    'Ask why we provide main bars and stirrups in an RCC beam and what each resists. Look for understanding of bending vs shear.',
    'Probe how stirrup spacing relates to shear demand, not just that stirrups exist.',
    'Conceptual clarity over code-clause recall at this level.'],
  ['soil-basics', 'Soil and bearing capacity basics', 'technical-depth', 'exploration', 'must', 2,
    'Ask what bearing capacity means and why it matters for a foundation. Look for a grasp of soil failure vs settlement.',
    'Probe the difference between bearing-capacity failure and excessive settlement.'],
  ['setting-out', 'Surveying and setting-out on site', 'operational', 'exploration', 'if-time', 1,
    'Ask how a structure is set out on site from a drawing — control points, levels, checks. Look for practical awareness.',
    'Surface probe — assess whether they connect the drawing to the ground.'],
  ['concrete-quality', 'Concrete quality and basic QC', 'operational', 'exploration', 'if-time', 2,
    'Ask what they would check before and during a concrete pour. Look for awareness of mix, slump, cover, and curing.',
    'Probe one item in depth — e.g. why cover matters or what a slump test tells you.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-curiosity', 'Technical curiosity and growth direction', 'self-awareness', 'closing', 'must', 0,
    'Ask which area of civil engineering they most want to deepen and how they are pursuing it.',
    'Surface — wrap up warmly; assess genuine enthusiasm.'],
]

// ─── Civil × Technical × 3-6 ────────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['design-walkthrough', 'Walk through a member you designed', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask candidate to walk through a beam, column, or footing they designed end-to-end. Calibrate design judgment.',
    'Surface — listen for governing cases and assumptions, not just the final size.', 'Must show independent design ownership.'],
  ['design-decision', 'A key design or scheme decision', 'problem-solving', 'warm-up', 'must', 0,
    'Ask about a significant design decision they drove. Calibrate ability to weigh structural and constructability trade-offs.',
    'Surface — pick the most interesting decision for deeper follow-up.'],
  ['footing-design', 'Isolated footing design and checks', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they size and check an isolated footing for a column load on known soil. Look for the governing checks.',
    'Probe which check governs — bearing, punching shear, one-way shear, settlement — and when they would switch foundation type.',
    'Explicit discussion of governing failure mode is the key differentiator at this level.'],
  ['slab-detailing', 'Slab design, deflection and crack control', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they design and detail a one-way slab and check serviceability, not just strength. Look for deflection and crack control.',
    'Probe what they would change if deflection governed rather than moment.'],
  ['column-design', 'Column design under axial and moment', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they design an RCC column for combined axial load and moment. Look for interaction and slenderness awareness.',
    'Probe how slenderness and minimum eccentricity affect their design.'],
  ['soil-report', 'Reading a geotechnical report', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask how they use a soil investigation report to choose a foundation. Look for interpreting SBC, water table, and soil profile.',
    'Probe how the water table or a soft layer would change their foundation choice.'],
  ['constructability', 'Designing for constructability', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a time they changed a design so it could actually be built. Look for the link between detailing and the field.',
    'Probe a specific congestion, formwork, or sequencing issue they resolved through design.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-mentoring', 'Sharing technical knowledge', 'leadership', 'closing', 'must', 0,
    'Ask how they help junior engineers grow their design or site judgment and what approach they use.',
    'Surface — one example suffices; assess investment in others.'],
]

// ─── Civil × Technical × 7+ ─────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['scheme-strategy', 'Structural scheme and project strategy', 'leadership', 'warm-up', 'must', 0,
    'Ask how they chose a structural scheme for a significant project and tied it to cost, program, and risk. Calibrate strategic scope.',
    'Surface — listen for commercial and constructability vocabulary alongside the engineering.', 'Scheme-level direction distinguishes senior from mid-level.'],
  ['design-vision', 'Design philosophy and standards', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask about design standards or a design philosophy they have set for a team or project. Calibrate breadth of judgment.',
    'Surface — note how they balance robustness, economy, and buildability.'],
  ['system-selection', 'Structural system selection on difficult ground', 'problem-solving', 'exploration', 'must', 2,
    'Ask how they select a structural system for a mid-rise on compressible ground, weighing superstructure and foundation together.',
    'Probe how settlement, soil-structure interaction, and differential movement drive the call.',
    'Must reason about the structure and the ground as one coupled problem.'],
  ['geotechnical-judgment', 'Retaining and deep-excavation judgment', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they would approach a retaining structure or deep excavation next to an existing building. Look for design plus temporary works.',
    'Probe lateral earth pressure assumptions, monitoring, and how they would control ground movement.',
    'Risk identification and temporary-works thinking are essential at this level.'],
  ['value-engineering', 'Value engineering a structure', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask about value-engineering a structure without compromising safety. Look for genuine optimisation, not just cost-cutting.',
    'Probe what they changed, what they refused to change, and how they proved it was safe.'],
  ['complex-detailing', 'Solving a complex detailing or analysis problem', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a difficult detailing, connection, or analysis problem they solved. Look for rigour and first-principles reasoning.',
    'Probe the assumptions they made and how they verified the result.'],
  ['temporary-works', 'Temporary works and construction sequence', 'operational', 'exploration', 'if-time', 2,
    'Ask how they planned temporary works and the construction sequence for a complex pour or erection. Look for buildability foresight.',
    'Probe a specific failure mode in the temporary condition they had to design against.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-legacy', 'Technical legacy and engineering impact', 'leadership', 'closing', 'must', 0,
    'Ask what engineering or technical legacy they are most proud of and what they hope to build here.',
    'Surface — connect their arc to the role.', 'Inability to articulate an engineering philosophy is a red flag at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('civil', 'technical', '0-2', entry, [
    'Choosing structural systems for whole buildings or bridges',
    'Soil-structure interaction or settlement analysis',
    'Value engineering or scheme-level optimisation',
    'Temporary works and complex erection sequencing',
    'Deep code-clause recall as a memory test',
  ]),
  template('civil', 'technical', '3-6', mid, [
    'Whole-scheme selection on difficult ground (senior territory)',
    'Project value-engineering strategy',
    'Setting design standards for a team or organisation',
    'Pure code-clause memorisation without mechanics',
    'Defaulting to "the software gives the answer" without reasoning the result',
  ]),
  template('civil', 'technical', '7+', senior, [
    'Basic beam reactions or stirrup-purpose questions',
    'Single-member design without scheme or ground context',
    'Design decisions with only element-level scope',
    'Questions a mid-level design engineer could answer equally well',
    'Clever calculations with no constructability or commercial context',
  ]),
]
