import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Data Analyst × Behavioral × 0-2 ──────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-introduction', 'Background and analytics journey', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to walk through their background. Calibrate for coursework, bootcamp, internship, or first analyst role.',
    'Surface only — 2 minutes max.', 'Academic, bootcamp, and internship projects all acceptable context.'],
  ['motivation-analytics', 'Why data analytics', 'motivation', 'warm-up', 'must', 0,
    'Ask what draws them to analytics specifically. Look for curiosity about the why behind numbers, not just "I like Excel."',
    'Surface — one follow-up at most.', 'Probe genuine curiosity and a decision-driving orientation.'],
  ['first-analysis-walkthrough', 'First analysis someone actually used', 'problem-solving', 'exploration', 'must', 2,
    'Ask about an analysis or report they built: the question, their approach, and what the stakeholder did with it.',
    'Probe whether they understand the decision their analysis informed. "What changed because of your numbers?"',
    'Accept coursework, internship, or personal projects — no production reporting experience required.'],
  ['explaining-a-number', 'Explaining a finding to a non-technical person', 'data-communication', 'exploration', 'must', 2,
    'Ask about explaining a metric or chart to someone non-technical. Look for audience-awareness and plain language.',
    'Probe how they chose the chart and whether the listener could act on it. "How did you avoid jargon?"',
    'Communication is the core analyst differentiator — a correct number that nobody understands is wasted work.'],
  ['messy-data-challenge', 'Messy data or spreadsheet challenge', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a messy dataset or broken spreadsheet they had to wrangle. Look for a systematic, hands-on approach.',
    'Probe how they detected the problem: "What made that data messy and how did you notice?"'],
  ['clarifying-a-request', 'Asking clarifying questions before running a query', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a time the request was unclear and they had to clarify scope before pulling data.',
    'Probe the specific questions they asked and what would have gone wrong without them.'],
  ['cross-functional-collaboration', 'Working with a non-analyst stakeholder', 'collaboration', 'exploration', 'if-time', 1,
    'Ask about a project with a PM, marketer, or business owner. Look for their specific contribution, not "we did X."',
    'Isolate their role: "You said we — what specifically did YOU do?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-curiosity', 'Learning goals and curiosity', 'motivation', 'closing', 'must', 0,
    'Ask what they want to learn next and what excites them about analytics. Assess enthusiasm.',
    'Surface — wrap up warmly.'],
]

// ─── Data Analyst × Behavioral × 3-6 ──────────────────────────────────────
const mid: CompactSlot[] = [
  ['ownership-narrative', 'End-to-end ownership of an analysis or report', 'problem-solving', 'warm-up', 'must', 0,
    'Ask about an analysis they owned fully: scoping the question, pulling data, analyzing, recommending, and following through.',
    'Surface — use to calibrate scope and pick follow-up topics.', 'Must demonstrate end-to-end ownership, not just running a query someone handed them.'],
  ['stakeholder-pushback', 'Pushing back on a misleading or vanity metric', 'data-communication', 'exploration', 'must', 2,
    'Ask about a time they pushed back on a metric leadership wanted to use that was misleading or a vanity number.',
    'Probe what they objected to, the alternative they proposed, and what changed. "Who gave ground and why?"',
    'Shift from "did you run it" to "did you protect the decision quality."'],
  ['conflicting-definitions', 'Reconciling conflicting metric definitions across teams', 'data-communication', 'exploration', 'must', 2,
    'Ask about two teams disagreeing on a metric definition (active user, revenue, conversion). Look for brokering alignment.',
    'Probe both definitions, the one they landed on, and how they got buy-in. "How did you make it stick?"',
    'Must show they can resolve definitional conflict, not just report two different numbers.'],
  ['dashboard-adoption', 'Building a dashboard stakeholders actually rely on', 'data-communication', 'exploration', 'must', 2,
    'Ask about a dashboard or recurring report they built that stakeholders adopted. Look for user-centered design.',
    'Probe how they learned what stakeholders needed and how they know it gets used. "What did you cut from it and why?"'],
  ['prioritization-under-load', 'Prioritizing competing ad-hoc requests', 'problem-solving', 'exploration', 'must', 2,
    'Ask how they handled a flood of requests when everyone wanted theirs first. Look for a defensible prioritization framework.',
    'Probe what they said no (or "not yet") to and how they communicated the trade-off to the deprioritized stakeholder.'],
  ['reporting-error-owned', 'A reporting error they caught or owned', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a time a report had a wrong number. Look for self-awareness, how they caught it, and the fix.',
    'Probe the prevention step: "What did you change so it could not happen again?"'],
  ['mentoring-junior', 'Mentoring a junior analyst', 'leadership', 'exploration', 'if-time', 1,
    'Ask about helping a junior analyst grow. Look for investment in others.',
    'One example suffices — surface treatment. Probe what changed in the junior\'s work.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-business-sense', 'Business awareness and impact orientation', 'data-communication', 'closing', 'must', 0,
    'Ask what excites them about this business space and how they stay connected to the decisions their work informs.',
    'Surface — wrap up. Look for intrinsic motivation beyond producing charts.'],
]

// ─── Data Analyst × Behavioral × 7+ ───────────────────────────────────────
const senior: CompactSlot[] = [
  ['analytics-strategy-narrative', 'Career trajectory and analytics strategy impact', 'leadership', 'warm-up', 'must', 0,
    'Ask how they have shaped how an org reasons about its data — metrics, reporting standards, or analytics roadmap.',
    'Surface — calibrate scope, org size, and strategic dimensions.',
    'Must show systems thinking: single report → team standards → org-wide source of truth.'],
  ['source-of-truth', 'Establishing a single source of truth and metric definitions', 'leadership', 'exploration', 'must', 2,
    'Ask about creating canonical metric definitions or a single source of truth across teams. Look for org-level impact.',
    'Probe how they drove adoption and stopped teams from going rogue. "What did you intentionally NOT standardize, and why?"',
    'Must demonstrate governance and influence, not just a tidy data model.'],
  ['executive-influence', 'Influencing an executive decision with analysis', 'data-communication', 'exploration', 'must', 2,
    'Ask about an analysis that changed an executive or VP\'s mind on a meaningful decision. Look for influence.',
    'Probe how they built the case, anticipated objections, and what the decision ultimately was.',
    'Stories must link to a real business decision — revenue, retention, cost, or strategy.'],
  ['analytics-culture', 'Driving a data-driven culture in non-analyst teams', 'leadership', 'exploration', 'must', 2,
    'Ask about getting non-data teams to adopt data-driven decisions and self-serve reporting. Look for culture-building.',
    'Probe how they measured whether it stuck. "What changed that outlasted you?"'],
  ['building-analytics-team', 'Building or scaling an analytics function', 'leadership', 'exploration', 'must', 2,
    'Ask about hiring and developing analysts. Look for what they optimize for and how they create leverage.',
    'Probe specific programs: hiring bar, onboarding, review of analyses, knowledge sharing.',
    'Must show multiplicative impact — raising the whole team, not just individual mentoring.'],
  ['strategic-bet-failure', 'An analytics initiative that did not pay off', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a major analytics initiative (a platform migration, a self-serve push) that failed. Look for organizational learning.',
    'Probe systemic changes made afterward. Absence of any failure story signals risk aversion or revisionism.'],
  ['data-governance-decision', 'Navigating a data trust or governance conflict', 'leadership', 'exploration', 'if-time', 2,
    'Ask about a conflict over data ownership, definitions, or trust between teams. Look for influence without authority.',
    'Probe who opposed, what evidence they marshaled, and the compromise reached.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-strategic-vision', 'Vision for analytics at this company', 'leadership', 'closing', 'must', 0,
    'Ask where they see analytics going here and what they would do in their first 90 days.',
    'Surface — wrap up. Look for strategic vision, not just tactical enthusiasm.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('data-analyst', 'behavioral', '0-2', entry, [
    'Organizational analytics strategy or direction-setting',
    'Establishing org-wide metric definitions or source of truth',
    'Multi-year program leadership or roadmap ownership',
    'Influencing executive or C-level decisions',
    'Building or scaling an analytics team from scratch',
  ]),
  template('data-analyst', 'behavioral', '3-6', mid, [
    'Org-level analytics strategy or roadmap setting',
    'Hiring decisions or team structure design',
    'Company-level direction setting',
    'Pure SQL syntax or statistical method questions',
    'Academic or hypothetical scenarios with no real example',
  ]),
  template('data-analyst', 'behavioral', '7+', senior, [
    'Individual report-pulling stories without strategic context',
    'IC-level query or dashboard stories as the primary topic',
    'Questions a junior analyst could answer equally well',
    'Generic teamwork or communication questions',
    'Pure tool or technical implementation questions without an org dimension',
  ]),
]
