import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Data Science × Coding × 0-2 ───────────────────────────────────────────
const entry: CompactSlot[] = [
  ['clarify-problem-coding', 'Clarifying problem inputs, outputs, and edge cases', 'problem-solving', 'warm-up', 'must', 0,
    'Present a SQL or pandas problem. Ask candidate to clarify expected output format and edge cases.',
    'Surface — note if they ask about NULLs, duplicate rows, and date formats upfront.', 'Correctness over optimization; brute force that works is acceptable at entry level.'],
  ['sql-aggregation-window', 'SQL aggregation with window functions', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask a medium SQL problem requiring GROUP BY plus ROW_NUMBER, RANK, or DENSE_RANK.',
    'Surface — verify they know RANK vs DENSE_RANK vs ROW_NUMBER distinction.', 'SQL is the eliminatory gate — fail SQL and the ML round is unreachable.'],
  ['sql-join-date-filter', 'SQL multi-table join with date filtering', 'ml-engineering', 'exploration', 'must', 2,
    'Ask an SQL problem requiring a JOIN across two tables with a date window filter or subquery.',
    'Probe NULL handling and whether they explain logic step-by-step as they write.',
    'Endless subqueries when a CTE or window function is cleaner is a common anti-pattern.'],
  ['pandas-manipulation', 'Pandas DataFrame filtering, groupby, and merge', 'ml-engineering', 'exploration', 'must', 2,
    'Ask a pandas task: filter + groupby + aggregation, or merge + fill missing values.',
    'Probe NULL/NaN handling approach and explanation of each transformation step.',
    'Pandas questions mirror SQL — same logic, different syntax; step-by-step narration required.'],
  ['statistical-computation', 'Computing a statistic from raw data in Python', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask them to compute correlation, percentile, or rolling average from a list without using .corr() or .quantile().',
    'Probe the mathematical formula they recall and how they handle edge cases (empty list, single value).',
    'Basic statistical coding demonstrates real understanding vs just calling library methods.'],
  ['edge-case-validation', 'Testing and validating with example inputs', 'problem-solving', 'exploration', 'if-time', 1,
    'After they produce a solution, ask them to walk through it with a concrete example including an edge case.',
    'Probe whether they check for empty inputs, NULLs, and duplicate keys before declaring done.'],
  ['code-clarity-explanation', 'Narrating and explaining code choices', 'data-communication', 'exploration', 'if-time', 1,
    'Ask them to explain one nontrivial line or clause of their solution in plain terms.',
    'Probe: "Why did you choose a LEFT JOIN here instead of INNER JOIN?" (intent over syntax).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-coding-reflection', 'Reflecting on solution quality and alternatives', 'problem-solving', 'closing', 'must', 0,
    'Ask if there is another approach they considered and what the trade-offs would be.',
    'Surface — rewards honest self-assessment; penalizes candidates who think first solution is always optimal.'],
]

// ─── Data Science × Coding × 3-6 ───────────────────────────────────────────
const mid: CompactSlot[] = [
  ['approach-analysis', 'Defining approach and comparing alternatives', 'problem-solving', 'warm-up', 'must', 0,
    'Present an ambiguous coding problem. Ask them to name two approaches and analyze trade-offs before writing.',
    'Surface — penalize jumping straight to code; reward framing of complexity and trade-offs.', 'Problems at this level are intentionally ambiguous; candidates must define scope themselves.'],
  ['ml-from-scratch', 'Implementing an ML algorithm from scratch in NumPy', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask them to implement logistic regression (sigmoid, binary cross-entropy, gradient descent) without scikit-learn.',
    'Probe convergence handling, correct gradient direction, and numerical stability of sigmoid.',
    'ML from scratch is the differentiator — proves understanding of the math, not just the API.'],
  ['complex-sql-cte', 'Complex SQL with chained CTEs and window functions', 'ml-engineering', 'exploration', 'must', 2,
    'Ask a hard SQL problem: cohort retention table (Day-1/7/30 by signup month) or top-N per category with growth.',
    'Probe query correctness first, then optimization: "How would you speed this up on a 1B-row table?"',
    'CTE + window function combos appear in ~40% of hard FAANG DS SQL questions.'],
  ['statistical-simulation', 'Statistical simulation in Python (Monte Carlo, bootstrap)', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask them to estimate A/B test power with Monte Carlo or compute a bootstrap confidence interval.',
    'Probe: "What if N=100 instead of 1000? How does your power estimate change?" (statistical intuition).',
    'Statistical simulation is much more common at mid level, especially at Google and quant firms.'],
  ['feature-engineering-code', 'Feature engineering from raw event logs in code', 'ml-engineering', 'exploration', 'must', 2,
    'Provide a raw event log schema and ask them to create churn prediction features (recency, frequency, monetary).',
    'Probe vectorized pandas vs apply vs iterrows: "Why not use iterrows here?" (performance awareness).',
    'Feature engineering in code tests design skill — not just "what features" but "write the code."'],
  ['follow-up-optimization', 'Optimizing or extending the initial solution', 'problem-solving', 'exploration', 'if-time', 2,
    'After initial solution, ask: "What if data is 100x larger?" or "Add L2 regularization to your implementation."',
    'Probe runtime/space complexity and whether they reason about bottlenecks before refactoring.'],
  ['production-implication', 'Production and scalability implications of the code', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask what would break or need to change if this code were deployed to a production pipeline.',
    'Probe error handling, logging, and retraining triggers as indicators of production awareness.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-code-quality', 'Code quality, modularity, and limitations', 'problem-solving', 'closing', 'must', 0,
    'Ask what they would refactor first and what the biggest limitation of their current implementation is.',
    'Surface — rewards intellectual honesty and engineering discipline over defensive attachment to first draft.'],
]

// ─── Data Science × Coding × 7+ ────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['problem-reframing', 'Reframing the problem and identifying hidden constraints', 'problem-solving', 'warm-up', 'must', 0,
    'Present a production ML scenario. Ask them to challenge assumptions and identify hidden constraints.',
    'Surface — note if they define scope proactively and identify the hardest sub-problem before coding.', 'Shift from "can you implement?" to "can you reason about production systems at scale?"'],
  ['debug-ml-code', 'Debugging a broken ML training loop or pipeline', 'ml-engineering', 'exploration', 'must', 2,
    'Provide a broken PyTorch or NumPy training loop (wrong LR schedule, missing grad zero, shape mismatch).',
    'Probe systematic diagnostic approach: "How do you isolate whether it\'s the data, the loss, or the optimizer?"',
    'Debug over build: given broken model code, find/fix the bug — more common than greenfield at senior level.'],
  ['ml-system-as-code', 'Designing an ML pipeline system in pseudocode or code', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to design and code an A/B test analysis framework or feature store serving pipeline.',
    'Probe latency budgets: "Feature fetch target is <10ms, model compute <30ms — how do you hit that?" (production numbers).',
    'Must know latency budgets: feature 1-5ms, model 10-30ms, network 10-20ms, serial 5-10ms.'],
  ['hard-dsa-with-ml', 'Hard DSA problem with ML or data context', 'problem-solving', 'exploration', 'must', 2,
    'Present a medium-hard LeetCode problem with a data angle (streaming median, top-k with updates).',
    'Probe runtime complexity and ask a follow-up that escalates the constraint. Google uses this mechanic.',
    'Google\'s follow-up escalation mechanic cannot be memorized — tests thinking, not pattern recall.'],
  ['advanced-sql-architecture', 'Query optimization and data architecture reasoning', 'ml-engineering', 'exploration', 'must', 2,
    'Ask a complex analytical SQL query and follow up with query plan optimization and indexing strategy.',
    'Probe: "How would you rewrite this to avoid a full table scan on 10B rows?" (data architecture depth).'],
  ['system-extension-escalation', 'Extending the solution at scale or under new constraints', 'ml-engineering', 'exploration', 'if-time', 2,
    'After initial solution, ask: "Scale to 1B rows", "Add concept drift handling", or "Handle cold start."',
    'Probe business impact connection: "How does this technical decision affect model quality for users?" (business alignment).'],
  ['statistical-methods-at-scale', 'Statistical methods at scale: sequential testing, bandits', 'experimentation', 'exploration', 'if-time', 2,
    'Ask them to implement or reason about a multi-armed bandit or sequential A/B testing framework in code.',
    'Probe the explore-exploit trade-off and how they would tune parameters for a specific business context.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-business-alignment', 'Connecting code decisions to business and team outcomes', 'data-communication', 'closing', 'must', 0,
    'Ask how their design choices would affect the team\'s ability to iterate quickly and the user-facing product.',
    'Surface — look for engineering leadership thinking: maintainability, iteration velocity, and business outcomes.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('data-science', 'coding', '0-2', entry, [
    'ML algorithm implementation from scratch',
    'System design or pipeline architecture questions',
    'Statistical simulation or Monte Carlo methods',
    'Complex CTEs with chained window functions',
    'Production deployment or monitoring discussions',
  ]),
  template('data-science', 'coding', '3-6', mid, [
    'Production ML debugging of complex architectures',
    'Transformer or attention mechanism implementation',
    'Latency-budget optimization for serving pipelines',
    'Distributed training or GPU memory management',
    'Statistical methods at scale (sequential testing, bandits)',
  ]),
  template('data-science', 'coding', '7+', senior, [
    'Basic SQL syntax or single-table aggregations',
    'Simple pandas filtering or groupby questions',
    'Conceptual statistics without code',
    'Entry-level algorithm questions with no data context',
    'Problems that can be solved with standard library calls alone',
  ]),
]
