import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Data Analyst × Coding × 0-2 ──────────────────────────────────────────
const entry: CompactSlot[] = [
  ['clarify-problem-coding', 'Clarifying inputs, outputs, and edge cases', 'problem-solving', 'warm-up', 'must', 0,
    'Present a pandas or SQL wrangling problem. Ask them to clarify the expected output shape and edge cases.',
    'Surface — note if they ask about NaNs, duplicate rows, and column types upfront.', 'Correctness over optimization; brute force that works is acceptable at entry level.'],
  ['groupby-aggregation', 'Groupby and aggregation in pandas', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask a groupby + agg task (revenue per category, orders per customer) on a small DataFrame.',
    'Surface — verify they pick the right aggregation and reset the index sensibly.', 'Groupby/agg is the bread-and-butter analyst operation — fluency here is the floor.'],
  ['filter-and-merge', 'Filtering and merging two DataFrames', 'ml-engineering', 'exploration', 'must', 2,
    'Ask a task needing a filter plus a merge (join orders to a customers frame, keep matching rows).',
    'Probe inner vs left merge and what happens to unmatched rows and NaNs.',
    'Choosing the wrong merge type (and silently dropping rows) is the most common entry-level bug.'],
  ['missing-values', 'Handling missing values', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to handle NaNs in a column: fill, drop, or flag, and justify the choice for the use case.',
    'Probe: "How does a NaN change a mean vs a sum?" and when dropping rows is wrong.',
    'Reward thinking about WHY a value is missing, not just calling fillna(0).'],
  ['dedup-cleaning', 'Deduplication and basic cleaning', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to remove duplicate rows and fix an obvious data issue (type, casing, stray whitespace).',
    'Probe: "How do you decide which duplicate to keep?" (subset, sort, keep first/last).'],
  ['simple-statistic', 'Computing a simple statistic from a column', 'statistical-thinking', 'exploration', 'if-time', 1,
    'Ask them to compute a per-group average or a percentile from a column.',
    'Probe edge cases: empty groups, single values, and how NaNs affect the result.'],
  ['narrate-code', 'Narrating and explaining each step', 'data-communication', 'exploration', 'if-time', 1,
    'Ask them to explain one nontrivial line of their solution in plain terms.',
    'Probe: "Why a left merge here instead of inner?" (intent over syntax).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-coding-reflection', 'Reflecting on the solution and alternatives', 'problem-solving', 'closing', 'must', 0,
    'Ask if there is another approach they considered and what the trade-offs would be.',
    'Surface — rewards honest self-assessment over assuming the first solution is optimal.'],
]

// ─── Data Analyst × Coding × 3-6 ──────────────────────────────────────────
const mid: CompactSlot[] = [
  ['approach-analysis', 'Defining the approach and reshaping plan', 'problem-solving', 'warm-up', 'must', 0,
    'Present a mildly ambiguous wrangling problem. Ask them to outline the steps and the final shape before coding.',
    'Surface — penalize jumping straight to code; reward planning the joins, grain, and reshape.', 'Problems are intentionally a bit ambiguous; candidates must define the output grain themselves.'],
  ['pivot-reshape', 'Pivot, melt, and reshaping data', 'ml-engineering', 'exploration', 'must', 2,
    'Ask a pivot/unstack or melt task (long-to-wide monthly metrics, or wide-to-long for charting).',
    'Probe: "What happens to the index after pivot, and how do you handle duplicate keys?" (aggfunc).',
    'Reshaping fluency separates a competent analyst from someone who only knows groupby.'],
  ['cohort-retention', 'Building a retention cohort from an event log', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to build a weekly or monthly signup-cohort retention table from a user-event log.',
    'Probe the denominator: "What counts as retained, and how do you handle users with no later events?"',
    'Cohort construction is a staple analyst task — denominator definition is where candidates slip.'],
  ['time-series-resample', 'Time-series resampling and rolling windows', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to resample daily transactions to weekly totals and add a 4-week rolling average.',
    'Probe: "How do you handle weeks with missing days?" and set/sort the datetime index correctly.',
    'Time-series rollups appear constantly; reward correct resampling over manual date math.'],
  ['funnel-analysis', 'Building a conversion funnel from a clickstream', 'ml-engineering', 'exploration', 'must', 2,
    'Provide a clickstream schema and ask for a multi-step funnel with drop-off per step.',
    'Probe vectorized vs loop: "Why not iterrows here?" and how they order events and handle repeats.',
    'Funnel logic tests both data reasoning and vectorized pandas — not just "what step," but "write it."'],
  ['optimize-vectorize', 'Optimizing or vectorizing a slow solution', 'problem-solving', 'exploration', 'if-time', 2,
    'After an initial solution, ask: "This runs on 50M rows — how do you speed it up?"',
    'Probe vectorization, avoiding apply, and reducing the data before the expensive step.'],
  ['multi-source-join', 'Joining multiple sources cleanly', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask them to combine three frames (orders, users, refunds) into one analytical table.',
    'Probe join fan-out: "How do you make sure one order does not become three rows?" (grain control).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-code-quality', 'Code quality, correctness checks, and limitations', 'problem-solving', 'closing', 'must', 0,
    'Ask how they would validate the output is correct and what the biggest limitation of their solution is.',
    'Surface — rewards verification habits and intellectual honesty over attachment to a first draft.'],
]

// ─── Data Analyst × Coding × 7+ ───────────────────────────────────────────
const senior: CompactSlot[] = [
  ['problem-reframing', 'Reframing the problem and the data grain', 'problem-solving', 'warm-up', 'must', 0,
    'Present a multi-source analytical task. Ask them to define the output grain and identify the hardest sub-problem.',
    'Surface — note if they pin down grain, keys, and dedup strategy proactively before coding.', 'Shift from "can you write pandas?" to "can you assemble a trustworthy dataset from messy sources?"'],
  ['assemble-analytical-dataset', 'Assembling a clean dataset from messy sources', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to join orders, users, and refunds, dedup to one row per order, and compute net revenue.',
    'Probe: "How do you avoid join fan-out and double counting?" and the order of dedup vs aggregation.',
    'Join fan-out and double counting are the classic senior-level traps — watch the grain at every step.'],
  ['cohort-mom-metrics', 'Cohort and month-over-month metrics efficiently', 'ml-engineering', 'exploration', 'must', 2,
    'Ask for net revenue per signup cohort by month, including month-over-month change, computed efficiently.',
    'Probe: "How do you compute MoM without a Python loop?" (groupby + shift / window logic) and correctness on gaps.'],
  ['funnel-at-scale', 'Funnel or sessionization on a large event log', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to build a funnel or sessionize a large clickstream and report drop-off, with performance in mind.',
    'Probe: "This is 500M events — what runs out first, and how do you stage the computation?" (memory/scale).',
    'Must reason about memory and staging, not just produce correct logic on a toy frame.'],
  ['debug-wrangling', 'Debugging a wrangling result that is silently wrong', 'ml-engineering', 'exploration', 'must', 2,
    'Provide code whose output is subtly wrong (a duplicated key inflating totals, a bad merge, a timezone bug).',
    'Probe systematic diagnosis: "How do you isolate whether it is the join, the dedup, or the dates?" (debug over build).'],
  ['sql-equivalent', 'Translating the wrangling into efficient SQL', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask them to express the same cohort or funnel logic as an efficient SQL query with CTEs and window functions.',
    'Probe: "How do you avoid a full scan on a 10B-row table?" (CTEs, partitioning, pre-aggregation).'],
  ['parametrize-reuse', 'Making the analysis reusable and parametrized', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how they would turn the one-off script into a reusable, parametrized function others can run.',
    'Probe inputs, validation, and how they prevent silent breakage when the source schema changes.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-business-alignment', 'Connecting code decisions to trust and team velocity', 'data-communication', 'closing', 'must', 0,
    'Ask how their choices affect data trust and the team\'s ability to reuse and iterate on the analysis.',
    'Surface — look for engineering-leaning analyst thinking: correctness, reuse, and maintainable pipelines.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('data-analyst', 'coding', '0-2', entry, [
    'Cohort, funnel, or sessionization construction',
    'Time-series resampling or rolling-window logic',
    'Multi-source joins with grain or fan-out control',
    'Vectorization or large-scale performance optimization',
    'ML algorithm implementation or statistical simulation',
  ]),
  template('data-analyst', 'coding', '3-6', mid, [
    'Multi-source dataset assembly with dedup and grain control at scale',
    'Memory or performance tuning on hundreds of millions of rows',
    'Translating analyses into optimized SQL with window functions',
    'ML-from-scratch or numerical algorithm implementation',
    'Debugging subtly wrong production wrangling pipelines',
  ]),
  template('data-analyst', 'coding', '7+', senior, [
    'Basic groupby or single-frame filtering questions',
    'A simple two-frame merge with no grain concerns',
    'Dropping duplicates or filling NaNs on a toy frame',
    'Computing a single statistic from one column',
    'Problems solvable with one standard pandas call and no edge cases',
  ]),
]
