import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Data Analyst × System Design × 0-2 ───────────────────────────────────
const entry: CompactSlot[] = [
  ['pipeline-concept', 'Basic reporting pipeline: source to chart', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask them to describe how a daily dashboard gets built from a production database to a chart.',
    'Surface — check awareness that reporting is source → transformed table → visualization; no infra depth expected.', 'Entry-level expectation: the pipeline concept, not warehouse internals.'],
  ['data-sources', 'Where the report data comes from', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask what data sources feed a sales dashboard and how they would get the data into one place.',
    'Surface — note whether they think about more than one source and joining them.', 'Reward awareness that real reports stitch multiple sources, not one clean table.'],
  ['scheduling-freshness', 'Keeping a report fresh and on time', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they ensure the dashboard is up to date each morning and what runs on a schedule.',
    'Probe: "The job fails at 6am — how does anyone find out?" (freshness awareness, basic alerting).',
    'Charting straight off live production tables instead of a scheduled, modeled layer is a common anti-pattern.'],
  ['sanity-checks', 'Sanity-checking the numbers before they ship', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they would verify the report is correct before stakeholders see it.',
    'Probe: "What checks tell you the number is wrong?" (row counts, totals vs a known source, null spikes).'],
  ['simple-transformation-layer', 'Why a transformed table beats raw data', 'ml-engineering', 'exploration', 'must', 2,
    'Ask why they would build a cleaned/aggregated table instead of querying raw tables for every chart.',
    'Probe: "What goes wrong if every dashboard queries the raw orders table directly?" (consistency, load, repetition).'],
  ['stakeholder-consumption', 'How the stakeholder actually consumes the report', 'data-communication', 'exploration', 'if-time', 1,
    'Ask who reads the dashboard, how often, and what decision it supports.',
    'Probe: "What is the one thing this report has to get right?" (fit to the consumer).'],
  ['handling-a-new-source', 'Adding a new data source to the report', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask what steps are needed to add a new source (e.g., a CSV export or a new app table) to an existing report.',
    'Probe whether they think about schema differences and keeping definitions consistent.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-pipeline-gaps', 'Gaps and what they would learn next', 'ml-engineering', 'closing', 'must', 0,
    'Ask which part of the pipeline they feel least confident about and how they would learn it.',
    'Surface — rewards self-awareness about the gap from analyst to analytics engineering.'],
]

// ─── Data Analyst × System Design × 3-6 ───────────────────────────────────
const mid: CompactSlot[] = [
  ['business-question-framing', 'Framing the reporting need before designing', 'problem-solving', 'warm-up', 'must', 0,
    'Present a goal (self-serve analytics for marketing + sales + product). Ask what questions the system must answer.',
    'Surface — evaluate whether they pin down the decisions and consumers before drawing architecture.', 'Reward starting from the decision the pipeline supports, not the tooling.'],
  ['modeling-layers', 'Modeling layers: staging to marts', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask how they would structure the warehouse: raw, staging, and consumable marts or a dimensional model.',
    'Surface — probe: "Why a staging layer at all?" and where business logic should live.',
    'Staging-to-marts modeling is the core mid-level analytics-engineering competency.'],
  ['ingestion-and-scheduling', 'Ingestion, scheduling, and incremental refresh', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how data lands in the warehouse and how transforms are scheduled. Probe incremental vs full refresh.',
    'Probe: "This table is a billion rows — do you rebuild it nightly?" and "How do you backfill a fix?"',
    'Always-full-refresh on large tables signals a missing grasp of incremental modeling.'],
  ['metrics-consistency', 'A shared metrics layer so teams agree on numbers', 'data-communication', 'exploration', 'must', 2,
    'Ask how they ensure marketing, sales, and product all compute the same metric the same way.',
    'Probe: "Two teams report different active-user counts — how does your design prevent that?" (single source of truth).',
    'Letting each team define metrics independently guarantees divergent numbers and lost trust.'],
  ['attribution-late-data', 'Joining sources and handling late-arriving data', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to design an attribution report joining spend, clicks, and conversions across systems.',
    'Probe: "A conversion is attributed days later — how do you reprocess without double counting?" (late data, idempotency).'],
  ['data-quality-tests', 'Data-quality tests and monitoring', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask what automated tests guard the pipeline (uniqueness, not-null, row-count, freshness, referential).',
    'Probe: "A test fails at 3am — what happens?" (alerting, blocking downstream, ownership).'],
  ['serving-layer', 'BI serving layer and performance for dashboards', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how dashboards query the data fast: pre-aggregation, extracts, caching, or a BI semantic layer.',
    'Probe: "The dashboard takes 40s to load — how do you fix it?" (pre-aggregation vs live query trade-off).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-failure-modes', 'Failure modes and safe changes', 'ml-engineering', 'closing', 'must', 0,
    'Ask how they roll out a definition change safely and what breaks first when the pipeline is under stress.',
    'Surface — evaluate change hygiene and awareness of downstream impact on stakeholders.'],
]

// ─── Data Analyst × System Design × 7+ ────────────────────────────────────
const senior: CompactSlot[] = [
  ['platform-and-business-framing', 'Framing the analytics platform in business terms', 'leadership', 'warm-up', 'must', 0,
    'Present a large-scale analytics need. Ask them to frame goals, consumers, and constraints before architecture.',
    'Surface — note whether they map stakeholders, define success at org level, and reference real patterns.', 'Must show industry awareness: reference how real companies structure analytics platforms.'],
  ['semantic-metrics-layer', 'Designing a semantic / metrics layer for the org', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to design a metrics layer so every team reports identical numbers for core KPIs.',
    'Probe: "Where do definitions live and how do you stop teams from forking them?" (governance + enforcement).',
    'Senior differentiator: durable metric consistency by design, not by convention.'],
  ['lineage-and-quality', 'Lineage, data-quality monitoring, and trust at scale', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they guarantee trust: lineage, freshness SLAs, anomaly detection, and incident response.',
    'Probe: "A number is wrong and 40 dashboards use it — how do you find blast radius and notify owners?" (lineage).',
    'Must reason about blast radius and trust, not just add more dbt tests.'],
  ['freshness-cost-tradeoffs', 'Freshness, cost, and compute trade-offs at scale', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they balance freshness against warehouse cost across many pipelines and consumers.',
    'Probe: "What do you sacrifice first — freshness, granularity, or history?" and "How do you control runaway compute spend?"',
    'Must proactively surface cost-performance trade-offs without being asked — the senior tell.'],
  ['self-serve-governance', 'Self-serve analytics with guardrails', 'leadership', 'exploration', 'must', 2,
    'Ask how they enable analysts and PMs to self-serve without producing inconsistent or wrong numbers.',
    'Probe: "How do you balance self-serve speed against governance?" (certified datasets, ownership, access).'],
  ['real-time-vs-batch', 'When real-time reporting is worth the complexity', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they decide between batch and near-real-time reporting and what changes architecturally.',
    'Probe: "The exec wants live numbers — when is that worth it and when is it a trap?" (proportional complexity).'],
  ['organizational-dimension', 'Platform vs team trade-offs and enabling analysts', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they balance a central analytics platform against team-specific reporting needs.',
    'Probe: "How do you onboard a new team — certified marts vs self-serve?" and "ROI of building the platform vs buying BI tools?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-strategic-tradeoffs', 'Strategic trade-offs and scope cuts under constraints', 'leadership', 'closing', 'must', 0,
    'Ask: "Cut the rollout to 3 months instead of 6 — what do you drop and why?" Assess strategic prioritization.',
    'Surface — look for crisp trade-off reasoning tied to business value and trust, not just technical preference.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('data-analyst', 'system-design', '0-2', entry, [
    'Semantic / metrics layer or org-wide metric governance',
    'Incremental modeling, backfills, or late-arriving data',
    'Data lineage, blast-radius analysis, or freshness SLAs',
    'Warehouse cost optimization at scale',
    'Real-time streaming or ML serving infrastructure',
  ]),
  template('data-analyst', 'system-design', '3-6', mid, [
    'Org-wide semantic layer or analytics platform governance',
    'Lineage-driven incident response or blast-radius analysis',
    'Warehouse cost-vs-freshness trade-offs at scale',
    'Real-time streaming analytics architecture',
    'ML model serving or feature store design',
  ]),
  template('data-analyst', 'system-design', '7+', senior, [
    'Basic source-to-chart reporting pipeline concepts',
    'Simple scheduling or "keep the report fresh" questions',
    'Beginner staging-vs-marts modeling with no scale',
    'Single-dashboard design without platform framing',
    'Questions that do not require cross-team or governance thinking',
  ]),
]
