import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Data Analyst × Technical × 0-2 ───────────────────────────────────────
const entry: CompactSlot[] = [
  ['sql-basics', 'SQL joins and aggregation foundations', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask a single concept: a multi-table JOIN with a GROUP BY and a filter (top customers, orders per region).',
    'Surface — verify they can join cleanly and aggregate; check INNER vs LEFT JOIN intuition.', 'SQL is the eliminatory gate for analysts — this is where most entry candidates are screened.'],
  ['descriptive-stats', 'Descriptive statistics: mean, median, percentiles', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask mean vs median, when each misleads, and what a percentile tells you. Calibrate intuition, not formulas.',
    'Surface — probe: "Average salary is $90k but median is $60k — what does that tell you?"', 'Conceptual literacy over formula recall; knowing when the mean lies matters more than the equation.'],
  ['sql-window-intro', 'A first window function: ranking and running totals', 'ml-engineering', 'exploration', 'must', 2,
    'Ask a problem needing ROW_NUMBER or RANK (latest order per customer, top-N per group).',
    'Probe RANK vs DENSE_RANK vs ROW_NUMBER and how ties are handled.',
    'A window function is the line between a beginner and a usable analyst.'],
  ['metric-definition', 'Defining and decomposing a simple metric', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask them to define a metric precisely (active user, conversion) and decompose what could move it.',
    'Probe edge cases: "Does a user who logs in twice count once or twice? What about bots?"',
    'Loose metric definitions are a top entry-level weakness — push for explicit, defensible definitions.'],
  ['null-and-data-quality', 'NULL handling and basic data quality checks', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how NULLs affect a COUNT, AVG, or JOIN, and how they would sanity-check a result before sending it.',
    'Probe: "Your COUNT looks too low — how do you figure out why?" (NULLs, join fan-out, filters).'],
  ['chart-reading', 'Reading and choosing the right chart', 'data-communication', 'exploration', 'if-time', 1,
    'Ask when to use a bar vs line vs scatter, and to interpret a simple trend correctly.',
    'Probe: "What would mislead a reader in this chart?" (truncated axis, aggregation hiding detail).'],
  ['spreadsheet-to-sql', 'Translating a spreadsheet task into SQL', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they would reproduce a VLOOKUP or pivot-table task in SQL.',
    'Probe whether they map a pivot to GROUP BY and a lookup to a JOIN.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tool-knowledge', 'Tools, BI stack, and learning path', 'ml-engineering', 'closing', 'must', 0,
    'Ask which tools (SQL, Excel, Tableau, Looker) they are most confident in and what they are learning.',
    'Surface — assess self-awareness about gaps and growth trajectory.'],
]

// ─── Data Analyst × Technical × 3-6 ───────────────────────────────────────
const mid: CompactSlot[] = [
  ['sql-window-depth', 'Window functions and CTEs in depth', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask a problem needing chained CTEs plus window functions (running total, month-over-month growth, sessionization).',
    'Surface — gauge fluency; probe execution order and why a window function beats a self-join here.', 'Window-function + CTE fluency is the core mid-level analyst SQL gate.'],
  ['retention-cohorts', 'Cohort retention and funnel SQL', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to compute cohort retention (Day-1/7/30 by signup month) or a multi-step funnel conversion.',
    'Probe the denominator choice and how they handle users with no later activity. "What counts as retained?"',
    'Retention and funnel SQL appear constantly — denominator definition is where most candidates slip.'],
  ['experiment-reading', 'Reading an A/B test and deciding ship', 'experimentation', 'exploration', 'must', 2,
    'Present an A/B result (lift, p-value, sample size, runtime). Ask whether to ship and why.',
    'Probe: "2% lift, p=0.07, one week of data — ship?" Look for sample-size, guardrail, and novelty-effect reasoning.',
    'Analysts read experiments more than they design them — judgment on borderline results is the test.'],
  ['metric-decomposition', 'Decomposing a metric movement', 'statistical-thinking', 'exploration', 'must', 2,
    'Present a metric drop (DAU down 8%). Ask them to decompose it (new vs returning, platform, geo, segment).',
    'Probe: "Uniform across regions — now what?" (most root causes concentrate in one segment).',
    'Confusing correlation with causation in a metric investigation is the #1 disqualifier.'],
  ['dashboard-design', 'Designing a dashboard for a real stakeholder', 'data-communication', 'exploration', 'must', 2,
    'Ask them to design a dashboard for a specific stakeholder (Head of Sales). Require chosen metrics and layout.',
    'Probe: "What do you intentionally leave OFF, and why?" (signal over clutter) and the refresh cadence.',
    'A good dashboard answers a decision; reward ruthless editing over a wall of charts.'],
  ['data-quality-debug', 'Debugging a suspicious number', 'ml-engineering', 'exploration', 'if-time', 2,
    'Present a number that looks wrong (revenue doubled overnight). Ask how they isolate pipeline vs real change.',
    'Probe: "How do you tell a data bug from a real business change?" (systematic elimination).'],
  ['stat-significance-literacy', 'Statistical significance and confidence intervals', 'statistical-thinking', 'exploration', 'if-time', 2,
    'Ask them to explain a confidence interval and a p-value to a stakeholder in plain language.',
    'Probe: "Stakeholder says the result \'isn\'t significant so it does nothing\' — is that right?" (interpretation nuance).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-technical-growth', 'Technical depth and active growth areas', 'ml-engineering', 'closing', 'must', 0,
    'Ask which analytical or technical area they are investing in and a recent thing they shipped.',
    'Surface — assess intentional skill development and production mindset.'],
]

// ─── Data Analyst × Technical × 7+ ────────────────────────────────────────
const senior: CompactSlot[] = [
  ['sql-performance', 'SQL performance and query optimization', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask how they would speed up a slow analytical query on a billion-row table (partitioning, indexes, pre-aggregation).',
    'Surface — gauge whether they reason about scans, shuffles, and materialization, not just rewrite syntax.', 'At senior level SQL correctness is assumed; performance and modeling judgment are the gate.'],
  ['metric-framework', 'Designing a north-star and guardrail metric system', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask them to design a metric framework for a product: north-star, input metrics, and guardrails.',
    'Probe: "How do you keep the north-star from being gamed?" and "PM wants engagement, VP wants revenue — reconcile."',
    'Must design a coherent, hard-to-game metric system, not just list KPIs.'],
  ['observational-confounders', 'Confounders, Simpson\'s paradox, and mix shift', 'statistical-thinking', 'exploration', 'must', 2,
    'Present an aggregate that contradicts every segment (flat overall, up in each region). Ask them to diagnose it.',
    'Probe: "How do you separate a real effect from a mix shift?" (Simpson\'s paradox and segment weighting).',
    'Senior analysts must reason about confounders in observational data, not just read clean experiments.'],
  ['experimentation-rigor', 'Experimentation rigor: power, peeking, and guardrails', 'experimentation', 'exploration', 'must', 2,
    'Ask how they set up trustworthy experiment reading: power, runtime, peeking, multiple comparisons, guardrails.',
    'Probe: "Team keeps checking the test daily and stops when it hits significance — what\'s wrong?" (peeking/inflation).'],
  ['data-modeling-standards', 'Data modeling and definitional standards at scale', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they design canonical tables and metric definitions so the whole org reports the same numbers.',
    'Probe: "Two teams report different revenue from the same warehouse — how do you fix the system?" (single source of truth).'],
  ['anomaly-and-monitoring', 'Anomaly detection and report monitoring', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they would automatically catch a broken pipeline or a metric anomaly before stakeholders see it.',
    'Probe thresholds vs seasonality-aware checks and how they avoid alert fatigue.'],
  ['analytical-leadership', 'Setting analytical standards across a team', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they raise SQL and analysis quality across analysts: review, templates, definitions, self-serve.',
    'Probe: "Two analysts disagree on a metric definition — how do you resolve it durably?" (standards leadership).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-technical-vision', 'Technical vision and analytics tooling bets', 'ml-engineering', 'closing', 'must', 0,
    'Ask how they stay current and what analytics tooling or modeling bets they think matter most now.',
    'Surface — look for genuine opinions on trade-offs, not buzzwords.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('data-analyst', 'technical', '0-2', entry, [
    'Window-function-heavy retention or sessionization queries',
    'A/B test power analysis or experiment design from scratch',
    'Query performance tuning on billion-row tables',
    'Metric framework or north-star design',
    'ML model selection or statistical modeling',
  ]),
  template('data-analyst', 'technical', '3-6', mid, [
    'SQL query optimization on billion-row tables',
    'Org-wide metric framework or data governance design',
    'Causal inference for observational studies',
    'ML model internals or feature engineering',
    'Data warehouse architecture or pipeline orchestration',
  ]),
  template('data-analyst', 'technical', '7+', senior, [
    'Basic single-table SQL or simple JOIN syntax',
    'Mean vs median or basic percentile definitions',
    'A first window function with no performance angle',
    'Reading a single clean A/B result with an obvious answer',
    'Chart-type selection or beginner BI questions',
  ]),
]
