import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Data Science × System Design × 0-2 ───────────────────────────────────
const entry: CompactSlot[] = [
  ['pipeline-concept', 'Basic ML pipeline concept: data in to predictions out', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask them to describe a simple ML pipeline from data collection to serving predictions.',
    'Surface — check awareness that ML is more than model.fit(); no infrastructure depth expected.', 'Entry-level expectation: awareness of the pipeline concept, not infrastructure depth.'],
  ['data-labeling-collection', 'Where does training data come from?', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask how they would collect and label data for a simple problem (spam, sentiment, churn).',
    'Surface — note whether they mention labeling as a hard/first step, not an afterthought.', 'Not mentioning data collection and labeling as the first/hardest step is a common anti-pattern.'],
  ['simple-model-selection', 'Choosing a first model for a simple ML problem', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask which model they would try first for a spam classifier or sentiment analysis problem and why.',
    'Probe: "Why not a neural network for this problem?" (proportional complexity reasoning).',
    'Treating entry system design like a backend system design (microservices, Kubernetes) is a disqualifier.'],
  ['evaluation-and-deployment', 'How to know if the model is good enough to deploy', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they would evaluate the model offline and what threshold of quality would justify deployment.',
    'Probe: "What metrics would you track to know if the model is working in production?" (monitoring awareness).'],
  ['production-drift-awareness', 'What happens when new data looks different from training data', 'ml-engineering', 'exploration', 'must', 2,
    'Ask what they would do if the model starts making bad predictions after deployment.',
    'Probe: "How do you know if the model is making bad predictions?" (monitoring without drift vocabulary).'],
  ['notebook-to-production', 'Taking a Jupyter notebook model to production', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask what steps are needed to go from a working Jupyter notebook to a deployed model.',
    'Probe: "What parts of the notebook code would NOT work in production?" (engineering awareness).'],
  ['recommendation-concept', 'Simple recommendation or ranking system concept', 'ml-engineering', 'exploration', 'if-time', 1,
    'Ask how they would build a simple recommendation system from user click data.',
    'Probe: "How do you handle a new user with no history?" (cold-start intuition).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-pipeline-gaps', 'Gaps and what they would learn next', 'ml-engineering', 'closing', 'must', 0,
    'Ask what part of the pipeline they feel least confident about and how they would learn it.',
    'Surface — rewards self-awareness about the engineering-to-production gap.'],
]

// ─── Data Science × System Design × 3-6 ───────────────────────────────────
const mid: CompactSlot[] = [
  ['problem-formulation', 'Translating business goal into ML objective', 'problem-solving', 'warm-up', 'must', 0,
    'Present a business goal (increase engagement, reduce fraud). Ask how they translate it into an ML objective.',
    'Surface — evaluate metric selection, proxy vs business metric distinction, and success definition.', 'Standard round at L4-L5 Google and E4-E5 Meta; product sense + statistical rigor must combine.'],
  ['metrics-offline-online', 'Defining offline and online metrics — and why they diverge', 'experimentation', 'warm-up', 'must', 0,
    'Ask for offline metrics (AUC, NDCG, precision@k) AND online metrics (CTR, engagement, revenue) for their system.',
    'Surface — probe: "Why might offline and online metrics disagree?" (production realism).',
    'Must distinguish training optimization from business metrics and explain disagreement scenarios.'],
  ['data-pipeline-features', 'Data pipeline design: ingestion, feature engineering, feature store', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they would design the data collection, feature engineering, and feature storage for their system.',
    'Probe: "Where do training labels come from?" and "Feature store goes down — how does system degrade?"',
    'Labeling strategy is commonly overlooked; missing it signals Kaggle mindset over production mindset.'],
  ['model-architecture-tradeoffs', 'Model architecture and training trade-offs', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask about model architecture selection for the scenario: candidate generation, ranking, re-ranking layers.',
    'Probe: "Why this over transformers?" and "Explain bias-variance using your proposed model."',
    'Two-tower models, multi-task learning, ANN search are expected vocabulary at this level.'],
  ['serving-and-latency', 'Serving infrastructure: batch vs real-time, latency budget', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how predictions are served, with latency/throughput requirements and batch vs real-time decision.',
    'Probe: "Latency budget? Where are the bottlenecks?" and "Walk through a single prediction request."'],
  ['monitoring-and-drift', 'Monitoring, drift detection, and feedback loops', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they would detect data drift, alert on it, and trigger retraining in their system.',
    'Probe: "How detect data drift? What do you do when drift is detected?" (feedback loop design).'],
  ['cold-start-and-scaling', 'Cold-start handling and scaling to 10x traffic', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they handle cold start for new users or items, and what breaks first at 10x scale.',
    'Probe: "What would you sacrifice first — latency, freshness, or coverage?" (scaling trade-offs).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-ab-deployment', 'A/B testing and safe deployment strategy', 'experimentation', 'closing', 'must', 0,
    'Ask how they would roll out the model safely: canary, shadow mode, A/B test, and rollback criteria.',
    'Surface — evaluate deployment hygiene and awareness of production risk.'],
]

// ─── Data Science × System Design × 7+ ────────────────────────────────────
const senior: CompactSlot[] = [
  ['product-and-business-framing', 'Framing the problem in product and business terms first', 'leadership', 'warm-up', 'must', 0,
    'Present a large-scale ML problem. Ask them to frame it in business terms before defining ML objectives.',
    'Surface — note whether they map stakeholders, define success at org level, and ask about constraints.', 'Must show industry awareness: reference how real companies solve similar problems.'],
  ['multi-model-architecture', 'Multi-model architecture: retrieval, ranking, re-ranking, diversity', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how multiple ML models interact in their design (retrieval + ranking + re-ranking + diversity layer).',
    'Probe comparative analysis: "Why this architecture over alternative X? Walk through the trade-offs."',
    'Staff+ must show novel architectural solutions, not just recombine known canonical patterns.'],
  ['feature-platform-design', 'Feature platform design: offline compute, online serving, drift', 'ml-engineering', 'exploration', 'must', 2,
    'Ask for a detailed feature platform design: offline vs online compute paths, <10ms serve latency, drift handling.',
    'Probe: "Proposed X. Principal engineer argues Y. How do you evaluate which to build?"',
    'Advanced topics: exploration/exploitation, RL for personalization, semi-supervised for label scarcity.'],
  ['scale-and-reliability', 'Serving at scale: real-time <50ms, compression, caching', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they achieve <50ms end-to-end latency for a real-time inference system at 100K req/sec.',
    'Probe: "Most likely thing to go wrong in production?" (proactive failure mode identification).',
    'Must proactively identify risks and failure modes without being asked — this is the senior differentiator.'],
  ['monitoring-and-remediation', 'Monitoring, observability, and automated remediation', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they would detect silent model degradation, alert, and trigger automated remediation.',
    'Probe: "Running 6 months, metrics slowly degrading. Walk through your diagnosis." (systematic approach).',
    'Must discuss concept drift, feedback loop delays, and retraining triggers — not just dashboards.'],
  ['training-infrastructure', 'Distributed training and experiment tracking at scale', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they design training infrastructure for distributed training, experiment tracking, and model registry.',
    'Probe: "Tension between experimentation velocity and model quality — how do you manage that?" (org trade-off).'],
  ['organizational-dimension', 'Platform vs product trade-offs and enabling other teams', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they balance building a shared ML platform vs supporting product-specific model development.',
    'Probe: "How onboard a new team — self-serve vs white-glove?" and "ROI of building the platform vs buying?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-strategic-tradeoffs', 'Strategic trade-offs and scope cuts under constraints', 'leadership', 'closing', 'must', 0,
    'Ask: "Cut scope to 3 months instead of 6 — what do you drop and why?" Assess strategic prioritization.',
    'Surface — look for crisp trade-off reasoning tied to business value and team capability, not just technical preference.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('data-science', 'system-design', '0-2', entry, [
    'Complex multi-model architectures (retrieval + ranking + re-ranking)',
    'Feature store design or streaming vs batch trade-offs',
    'Distributed training or model compression techniques',
    'Experiment tracking at scale or model registry design',
    'Backend infrastructure (Kafka, Kubernetes, microservices)',
  ]),
  template('data-science', 'system-design', '3-6', mid, [
    'Organizational platform strategy or build-vs-buy decisions',
    'Staff-level novel architectural trade-offs without clear answers',
    'Causal inference for non-RCT settings',
    'Multi-modal ML systems (vision + language fusion)',
    'Autonomous vehicle or robotics perception systems',
  ]),
  template('data-science', 'system-design', '7+', senior, [
    'Single-model Jupyter notebook architecture questions',
    'Basic train/test split or cross-validation setup',
    'Simple evaluation metric definition without system context',
    'Standard algorithm selection questions without production framing',
    'Questions that do not require cross-team or platform thinking',
  ]),
]
