import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Data Analyst × Case Study × 0-2 ──────────────────────────────────────
const entry: CompactSlot[] = [
  ['clarify-question', 'Clarifying the business question and metric', 'problem-solving', 'warm-up', 'must', 0,
    'Present a vague prompt (e.g., "signups dropped 15%"). Ask them to clarify the metric, time frame, and scope.',
    'Surface — note whether they state assumptions upfront or jump straight to an answer.', 'Clarity and structure matter far more than sophistication at this level.'],
  ['hypothesis-listing', 'Listing plausible hypotheses', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask what could explain the movement. Look for a structured set of hypotheses (seasonality, tracking, real change).',
    'Surface — reward breadth and structure over a single guess.', 'Penalize anchoring on one cause; reward MECE-style hypothesis listing.'],
  ['segmentation-instinct', 'Segmenting to localize the cause', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask which segmentations they would check first (platform, geo, new vs returning, channel) and why.',
    'Probe: "You segmented by platform and it\'s all on iOS — what does that suggest?" (localizing the cause).',
    'Most real causes concentrate in one segment; the instinct to slice is the core skill here.'],
  ['data-quality-check', 'Ruling out a data or tracking problem', 'problem-solving', 'exploration', 'must', 2,
    'Ask how they would confirm the number is real before raising an alarm.',
    'Probe: "How do you tell a tracking bug from a genuine drop?" (sanity checks, recent deploys, pipeline).',
    'Forgetting to check data quality first is the most common entry-level miss.'],
  ['so-what-recommendation', 'Stating a finding and a recommendation', 'data-communication', 'exploration', 'must', 2,
    'Ask them to turn their analysis into a tentative finding and one recommended action.',
    'Probe: "So what should the business do?" (the so-what test).',
    'A correct diagnosis with no recommendation is the top rejection reason.'],
  ['report-design-basics', 'Designing a simple recurring report', 'data-communication', 'exploration', 'if-time', 1,
    'Ask how they would lay out a weekly report for a stakeholder: which metrics, which chart, what to omit.',
    'Probe: "What would you leave off so the reader is not overwhelmed?" (signal over clutter).'],
  ['next-steps', 'What they would explore with more time', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask what they would dig into next given another day or more data. Look for analytical curiosity.',
    'Probe whether next steps connect to a decision or are just technical exploration.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-takeaway', 'The single most important takeaway', 'data-communication', 'closing', 'must', 0,
    'Ask for the one actionable insight and what the business should do first. Assess crisp communication.',
    'Surface — a clean executive summary signals strong communication instincts.'],
]

// ─── Data Analyst × Case Study × 3-6 ──────────────────────────────────────
const mid: CompactSlot[] = [
  ['clarify-scope-live', 'Clarifying scope in a live interactive case', 'problem-solving', 'warm-up', 'must', 0,
    'Present a deliberately vague prompt ("conversion fell 12% last week"). Ask them to clarify before analyzing.',
    'Surface — evaluate whether they pin down the metric, segments, and time frame before diving in.', 'Live interactive case; the interviewer supplies data points on request.'],
  ['structured-decomposition', 'Decomposing the metric systematically', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask them to decompose the metric (conversion = sessions x add-to-cart x checkout) and structure their approach.',
    'Surface — penalize jumping to solutions; reward systematic hypothesis elimination.', 'Must combine product sense with analytical rigor, not just slice randomly.'],
  ['root-cause-segmentation', 'Root cause analysis via prioritized segmentation', 'statistical-thinking', 'exploration', 'must', 2,
    'Have them investigate the drop via prioritized segmentation. Reveal that one segment moved when probed.',
    'Probe: "Uniform across geo — now what?" (~70% of root causes concentrate in one segment).',
    'Confusing correlation with causation in root cause analysis is the #1 disqualifier.'],
  ['attribution-decision', 'An analytical decision with confounders', 'experimentation', 'exploration', 'must', 2,
    'Ask them to recommend which acquisition channel to scale. Surface attribution and confounder issues.',
    'Probe: "This channel has the highest conversion — but is that the channel or the audience?" (selection bias).',
    'Reward awareness that channel comparisons are confounded by audience and intent.'],
  ['recommendation-with-guardrails', 'A crisp recommendation with caveats and guardrails', 'data-communication', 'exploration', 'must', 2,
    'Ask for a final recommendation including risks, caveats, and a guardrail metric to watch.',
    'Probe: "What guardrail would you monitor?" and "What if the effect is not significant?"',
    '40% of rejections cite lack of business sense — the recommendation must name concrete impact.'],
  ['defend-under-pushback', 'Defending the analysis when challenged', 'problem-solving', 'exploration', 'must', 2,
    'Challenge one of their conclusions and assess how they respond. Pushback IS the test.',
    'Probe: "What if it is just noise?" Look for flexibility and evidence, not defensiveness.'],
  ['dashboard-for-stakeholder', 'Designing a decision-oriented dashboard', 'data-communication', 'exploration', 'if-time', 2,
    'Ask them to design a dashboard for a named stakeholder that answers a specific decision.',
    'Probe: "What is the one decision this dashboard supports?" and what they deliberately exclude.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-business-decision', 'Translating analysis into a business decision', 'data-communication', 'closing', 'must', 0,
    'Ask what the business should actually do, in one sentence, and why now rather than later.',
    'Surface — crisp, defensible, decision-quality communication tied to business value.'],
]

// ─── Data Analyst × Case Study × 7+ ───────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-framing', 'Framing the metric in business and strategy terms', 'leadership', 'warm-up', 'must', 0,
    'Present a strategic scenario ("revenue flat QoQ; you own analytics — what is your read and plan?").',
    'Surface — look for stakeholder mapping, success definition at the business level, and systems thinking.', 'Shift from "diagnose this number" to "design how the business measures and decides."'],
  ['measurement-strategy', 'Designing a measurement and metric framework', 'leadership', 'exploration', 'must', 2,
    'Ask them to design the executive metric set and the dashboard the leadership team reviews weekly.',
    'Probe: "Which are leading vs lagging?" and "How do you keep the north-star from being gamed?"',
    'Must design a coherent measurement system, not just pick KPIs.'],
  ['mix-shift-reasoning', 'Reasoning about mix shift and confounders', 'statistical-thinking', 'exploration', 'must', 2,
    'Present a flat aggregate that grew in every segment. Ask them to explain and recommend.',
    'Probe: "How do you separate a real effect from a mix shift?" (Simpson\'s paradox and segment weighting).',
    'Senior analysts must untangle confounded aggregates, not just report them.'],
  ['quantified-impact', 'Quantifying business impact and trade-offs', 'data-communication', 'exploration', 'must', 2,
    'Ask them to size the impact of a recommendation in business terms and frame the trade-off for an executive.',
    'Probe: "What is the revenue or cost at stake, and what is your confidence?" (executive framing).',
    'Articulate impact in executive terms: revenue, retention, efficiency, risk.'],
  ['governance-and-trust', 'Establishing data trust and definitional standards', 'leadership', 'exploration', 'must', 2,
    'Ask how they would fix an org where teams report different numbers for the same metric.',
    'Probe: "How do you get adoption without becoming a bureaucratic bottleneck?" (governance vs velocity).'],
  ['prioritizing-analytics-work', 'Prioritizing analytics work under constraints', 'leadership', 'exploration', 'if-time', 2,
    'Present competing demands: three teams want analytics support but you can resource two. Ask how they prioritize.',
    'Probe: "How do you measure the ROI of an analysis or a dashboard?" (value-based prioritization).'],
  ['killing-a-report', 'Deciding to deprecate a report or metric', 'leadership', 'exploration', 'if-time', 2,
    'Ask about retiring a widely viewed but misleading report or metric. Look for clear decision criteria.',
    'Probe: "People rely on it but it is wrong — how do you sunset it?" (change management and courage).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-organizational-impact', 'Communicating analytics impact to executives', 'leadership', 'closing', 'must', 0,
    'Ask how they communicate the value of analytics to non-technical executives and the board.',
    'Surface — look for executive fluency and translating numbers into business language.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('data-analyst', 'case-study', '0-2', entry, [
    'Org-wide measurement or metric framework design',
    'Mix shift, Simpson\'s paradox, or confounder reasoning',
    'Quantified business impact sizing for executives',
    'Data governance or single-source-of-truth strategy',
    'Multi-stakeholder prioritization or resource allocation',
  ]),
  template('data-analyst', 'case-study', '3-6', mid, [
    'Org-level analytics strategy or function design',
    'Executive metric framework or governance at scale',
    'Multi-year roadmap or headcount decisions',
    'Deprecating org-wide reports or change management',
    'Pure SQL or modeling without a business decision',
  ]),
  template('data-analyst', 'case-study', '7+', senior, [
    'Basic single-metric diagnosis with an obvious cause',
    'Designing a simple recurring report from scratch',
    'Beginner segmentation without strategic framing',
    'Pure data-pull execution without an org dimension',
    'Questions answerable without cross-functional leadership context',
  ]),
]
