import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Data Science × Behavioral × 0-2 ──────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-introduction', 'Background and data journey', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to walk through their background. Calibrate for academic/bootcamp/personal project context.',
    'Surface only — 2 minutes max.', 'Academic projects, bootcamp, Kaggle all acceptable context.'],
  ['motivation-ds', 'Why data science', 'motivation', 'warm-up', 'must', 0,
    'Ask what draws them to data science specifically. Look for genuine curiosity beyond "I like math."',
    'Surface — one follow-up at most.', 'Probe intellectual curiosity and learning orientation.'],
  ['first-data-project', 'First data project walkthrough', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a data project they worked on: role, approach, and outcome. Look for business connection.',
    'Probe whether they understand business impact, not just technique. "What changed because of your analysis?"',
    'Accept academic/bootcamp/personal projects — no production experience required.'],
  ['communicating-findings', 'Communicating findings to non-technical stakeholders', 'data-communication', 'exploration', 'must', 2,
    'Ask about explaining complex findings to a non-technical audience. Look for audience-awareness.',
    'Probe how they chose the visualization and what the stakeholder did with the insight.',
    'Communication is the #1 differentiator — even the best analysis falls flat if stakeholders cannot act on it.'],
  ['messy-data-challenge', 'Data quality or messy data challenge', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a challenging data quality issue. Look for hands-on experience and systematic approach.',
    'Probe the hardest part of cleaning: "What made that dataset messy and how did you detect it?"'],
  ['learning-new-tool', 'Learning a new tool or technique under pressure', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how they taught themselves a new tool under time pressure. Look for resource strategy.',
    'Probe specific resources used, blockers encountered, and how quickly they became productive.'],
  ['cross-functional-team', 'Working on a cross-functional team', 'collaboration', 'exploration', 'if-time', 1,
    'Ask about a project with a cross-functional team. Look for their specific contribution, not "we did X."',
    'Isolate their role: "You said we — what specifically did YOU contribute?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-curiosity', 'Learning goals and intellectual curiosity', 'motivation', 'closing', 'must', 0,
    'Ask what they want to learn next and what excites them about the field. Assess enthusiasm.',
    'Surface — wrap up warmly.'],
]

// ─── Data Science × Behavioral × 3-6 ──────────────────────────────────────
const mid: CompactSlot[] = [
  ['project-impact-narrative', 'End-to-end project ownership and impact', 'problem-solving', 'warm-up', 'must', 0,
    'Ask about a project they owned fully: framing → data → analysis → recommendation → follow-through.',
    'Surface — use to calibrate scope and pick follow-up topics.', 'Must demonstrate end-to-end ownership, not just modeling.'],
  ['stakeholder-influence', 'Influencing a stakeholder who disagreed with the data', 'data-communication', 'exploration', 'must', 2,
    'Ask about convincing a non-technical stakeholder to adopt a data-driven recommendation.',
    'Probe what they pushed back on, what data was used to address objections, and what changed.',
    'Shift from "did you do the work" to "did you drive impact and influence decisions."'],
  ['ab-testing-ownership', 'A/B test ownership and decision-making', 'experimentation', 'exploration', 'must', 2,
    'Ask about running an A/B test that impacted a product or business decision.',
    'Probe sample size rationale, how they handled inconclusive results, and the go/no-go call.',
    'Must demonstrate A/B fluency: designing, interpreting nuanced results, and making judgment calls.'],
  ['conflicting-metrics', 'Conflicting metrics or KPI disagreements between teams', 'data-communication', 'exploration', 'must', 2,
    'Ask about a time metric definitions conflicted across teams. Look for ability to broker alignment.',
    'Probe both sides of the conflict and how agreement was reached. "Who gave ground and why?"'],
  ['model-business-tradeoff', 'Model deployment with business trade-offs', 'ml-engineering', 'exploration', 'must', 2,
    'Ask about choosing between accuracy and speed, interpretability, or fairness. Look for product sense.',
    'Probe the decision framework: "How did you frame the trade-off for the business stakeholder?"'],
  ['data-project-failure', 'A data project that did not go as planned', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a project that failed or missed expectations. Look for self-awareness and learning.',
    'Probe what they would do differently — absence of any failure signals lack of self-awareness.'],
  ['mentoring-teammate', 'Mentoring a junior data colleague', 'leadership', 'exploration', 'if-time', 1,
    'Ask about helping a junior colleague grow their data skills. Look for investment in others.',
    'One example suffices — surface treatment. Probe what changed in the junior\'s work.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-product-sense', 'Product and business awareness', 'data-communication', 'closing', 'must', 0,
    'Ask what excites them about the product space and how they stay connected to business outcomes.',
    'Surface — wrap up. Look for intrinsic motivation beyond technical craft.'],
]

// ─── Data Science × Behavioral × 7+ ───────────────────────────────────────
const senior: CompactSlot[] = [
  ['data-strategy-narrative', 'Career trajectory and data strategy impact', 'leadership', 'warm-up', 'must', 0,
    'Ask how they have defined or influenced a DS roadmap aligned to business objectives.',
    'Surface — calibrate scope, org size, and strategic leadership dimensions.',
    'Must show systems thinking: single analysis → team roadmap → org strategy → company goals.'],
  ['influencing-product-direction', 'Influencing product direction through data', 'data-communication', 'exploration', 'must', 2,
    'Ask about data insights that fundamentally changed a product\'s direction. Look for org-level impact.',
    'Probe how they got buy-in from skeptical PMs or VPs. "What did you intentionally NOT do, and why?"',
    'Stories must link to product metrics, retention, growth, or efficiency — why a problem mattered.'],
  ['building-data-culture', 'Driving organizational data culture', 'leadership', 'exploration', 'must', 2,
    'Ask about getting non-data teams to adopt data-driven decision-making. Look for culture-building.',
    'Probe how they measured whether the culture shift was working. "What changed that outlasted you?"',
    'Must articulate how they built culture, not just shipped projects.'],
  ['executive-disagreement', 'Navigating executive disagreements with data', 'leadership', 'exploration', 'must', 2,
    'Ask about pushing back on a VP or C-level decision with data. Look for influence without authority.',
    'Probe who opposed, what data evidence was marshaled, and what compromises were made.',
    'Must demonstrate influence without authority — colleagues organically adopting approaches.'],
  ['building-scaling-team', 'Building or scaling a DS team', 'leadership', 'exploration', 'must', 2,
    'Ask about hiring and developing data scientists. Look for what they optimize for and multiplicative impact.',
    'Probe specific programs: hiring bar, onboarding, career conversations, knowledge-sharing systems.',
    'Must show multiplicative impact — making the whole team better, not just individual mentoring.'],
  ['strategic-data-bet-failure', 'Strategic data bet that did not pay off', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a major data initiative that failed. Look for organizational learning, not just personal growth.',
    'Probe systemic changes made afterward. Absence of failure stories signals dishonesty or risk aversion.'],
  ['technical-vision-decision', 'Technical vision: build vs buy vs partner', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask about a build vs buy vs partner decision for ML infrastructure. Look for strategic framing.',
    'Probe the decision process and what trade-offs were prioritized for long-term platform health.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-strategic-vision', 'Vision for DS at this company', 'leadership', 'closing', 'must', 0,
    'Ask where they see DS going here and what they would do differently in their first 90 days.',
    'Surface — wrap up. Look for strategic vision, not just tactical enthusiasm.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('data-science', 'behavioral', '0-2', entry, [
    'Organizational strategy or direction-setting',
    'Production incident ownership or on-call responsibilities',
    'Multi-year program leadership or roadmap ownership',
    'Influencing executive stakeholders or C-level decisions',
    'Building or scaling a team from scratch',
  ]),
  template('data-science', 'behavioral', '3-6', mid, [
    'Organizational-level DS strategy or roadmap setting',
    'Hiring decisions or team structure design',
    'Company-level product direction setting',
    'Pure statistical or algorithmic technical questions',
    'Academic or hypothetical scenarios with no real example',
  ]),
  template('data-science', 'behavioral', '7+', senior, [
    'Individual execution stories without strategic context',
    'IC-level modeling or EDA stories as primary topic',
    'Questions an L4/E4 data scientist could answer equally well',
    'Generic teamwork or communication questions',
    'Pure technical implementation questions without organizational dimension',
  ]),
]
