import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Data Science × Case Study × 0-2 ──────────────────────────────────────
const entry: CompactSlot[] = [
  ['clarify-problem', 'Clarifying the business question and scope', 'problem-solving', 'warm-up', 'must', 0,
    'Present a vague prompt (e.g., churn dataset). Ask them to clarify terms, time frame, and target variable.',
    'Surface — note whether they state assumptions upfront or bury them later.', 'Heavy take-home emphasis; model sophistication matters far less than clarity and business connection.'],
  ['eda-approach', 'Exploratory data analysis approach', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask how they would approach EDA: distributions, missing values, correlations. Look for structure.',
    'Surface — 80% time should go to EDA at entry level, not modeling.', 'Inverted ratio: 80% EDA, 20% modeling — reverse of what most beginners do.'],
  ['model-selection', 'Choosing a model and justifying the choice', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask which model they would try first for a classification problem and why. Look for analytical reasoning.',
    'Probe: "Why this model over alternatives?" — penalize "I always use random forest" responses.',
    'Must state assumptions explicitly; logistic regression before neural networks at this level.'],
  ['business-connection', 'Connecting findings to business recommendations', 'data-communication', 'exploration', 'must', 2,
    'Ask how they would translate model output or EDA findings into actionable recommendations.',
    'Probe: "Business impact if we act on your recommendation?" (so-what test).',
    'Perfect analysis with no business "so what" is the top rejection reason.'],
  ['assumptions-and-limitations', 'Stating assumptions and data limitations', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask what assumptions they would make about the data and analysis. Look for upfront transparency.',
    'Probe: "What would you do differently with more time or better data?" (self-awareness).'],
  ['explain-to-pm', 'Explaining a finding to a product manager', 'data-communication', 'exploration', 'if-time', 1,
    'Ask them to explain one key finding in plain language, as if to a non-technical PM.',
    'Probe: "How would you explain that without using the word \'regression\'?" (layman test).'],
  ['iteration-and-next-steps', 'What would you do next with more resources', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask what they would explore next given another week or more data. Look for analytical curiosity.',
    'Probe whether next steps connect to business value or just technical exploration.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-takeaway', 'Single most important takeaway from the analysis', 'data-communication', 'closing', 'must', 0,
    'Ask what the one actionable insight is and what the business should do first. Assess crisp communication.',
    'Surface — a clean executive summary signals strong communication instincts.'],
]

// ─── Data Science × Case Study × 3-6 ──────────────────────────────────────
const mid: CompactSlot[] = [
  ['clarify-scope-live', 'Clarifying scope in a live interactive case', 'problem-solving', 'warm-up', 'must', 0,
    'Present a deliberately vague prompt (e.g., "DAU dropped 10% last week"). Ask them to clarify before analyzing.',
    'Surface — evaluate whether they define terms, metrics, user segments, and time frames before diving in.', 'Live interactive case, not take-home; interviewer provides data points on request.'],
  ['structure-framework', 'Structuring a metric investigation or experiment', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask how they would structure their approach. Look for decomposition (DAU = new + returning + resurrected - churned).',
    'Surface — penalize jumping to solutions; reward systematic elimination of hypotheses.', 'Must think like a PM + Data Scientist hybrid: product sense, metrics, and statistical rigor combined.'],
  ['root-cause-analysis', 'Root cause analysis with segmentation', 'statistical-thinking', 'exploration', 'must', 2,
    'Present a metric drop and ask them to investigate via segmentation (platform, geo, user type).',
    'Probe: "Segmented by geography — uniform across regions. Now what?" (~70% of root causes are concentrated in one segment).',
    'Confusing correlation with causation in root cause analysis is the #1 disqualifier.'],
  ['experiment-design-live', 'Designing an A/B test for a new feature', 'experimentation', 'exploration', 'must', 2,
    'Ask them to design an A/B test for a scenario. Require sample size, duration, randomization, and guardrails.',
    'Probe: "Stakeholder wants to launch on a 1-week test. What do you recommend?" (rigor vs speed).'],
  ['recommendation-with-guardrails', 'Crisp recommendation with guardrails and trade-offs', 'data-communication', 'exploration', 'must', 2,
    'Ask for a final recommendation on a modeling or metric case, including risks and guardrails.',
    'Probe: "Guardrail metrics alongside your primary?" and "What if the result is not significant?"',
    '40% of rejections cite lack of business sense — recommendation must name concrete business impact.'],
  ['defend-under-pushback', 'Defending analysis when the interviewer pushes back', 'problem-solving', 'exploration', 'must', 2,
    'Challenge one of their analytical conclusions and assess how they respond. Pushback IS the test.',
    'Probe: "What if metric change is not statistically significant?" Look for flexibility, not defensiveness.'],
  ['selection-bias-handling', 'Handling selection bias or confounders in experiment', 'experimentation', 'exploration', 'if-time', 2,
    'Ask how they would handle selection bias, network effects, or novelty effect in their experiment design.',
    'Probe: "How handle selection bias in this experiment?" and "Cost of false positive vs false negative?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-business-decision', 'Translating analysis into a business decision', 'data-communication', 'closing', 'must', 0,
    'Ask what the business should actually do, in one sentence, and why now rather than later.',
    'Surface — decision-quality communication: crisp, defensible, tied to business value.'],
]

// ─── Data Science × Case Study × 7+ ───────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-problem-framing', 'Reframing the business challenge as a data opportunity', 'leadership', 'warm-up', 'must', 0,
    'Present a strategic scenario (e.g., "No centralized DS function; you\'re Head of DS. 90-day plan?").',
    'Surface — look for stakeholder mapping, success definition at org level, and systems thinking.', 'Less "solve this problem" → more "design the data function"; must discuss org and people dimensions.'],
  ['ds-strategy-proposal', 'Proposing a phased data strategy with ROI', 'leadership', 'exploration', 'must', 2,
    'Ask for a phased crawl-walk-run strategy for a data use case. Require ROI estimate and resource justification.',
    'Probe: "Measure ROI of the DS team itself?" and "Two ML projects: high impact/high risk vs moderate/low risk — how decide?"',
    'Articulate impact in executive terms: revenue, efficiency, risk reduction.'],
  ['build-vs-buy', 'ML platform evaluation: build vs buy vs off-shelf', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they would evaluate whether to build an internal ML platform vs use AWS SageMaker or Vertex AI.',
    'Probe: "What would you intentionally not build, and why?" (strategic prioritization).',
    'Build-vs-buy is extremely common — must show when off-the-shelf (AutoML, vendor APIs) beats custom models.'],
  ['experimentation-culture', 'Designing an org-wide experimentation program', 'experimentation', 'exploration', 'must', 2,
    'Ask how they would establish an experimentation culture for a team that has never done A/B testing.',
    'Probe: "Model governance without bureaucracy slowing the team?" (governance vs velocity).',
    'Must discuss feedback loops, cold start, scaling, and change management — not just tooling.'],
  ['model-governance-lifecycle', 'Model governance and lifecycle management at scale', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they manage model lifecycle: approval, monitoring, deprecation, and compliance at org scale.',
    'Probe: "Model accurate but produces biased outcomes — what do you do?" (governance depth).'],
  ['killing-a-project', 'Making the call to kill a project that is not working', 'leadership', 'exploration', 'if-time', 2,
    'Ask about stopping a data initiative that was not delivering. Look for clear decision criteria.',
    'Probe: "Walk through killing a project that wasn\'t working." (strategic courage).'],
  ['multi-stakeholder-tradeoffs', 'Multi-stakeholder trade-offs with constrained resources', 'leadership', 'exploration', 'if-time', 2,
    'Present a budget constraint: three teams want DS support but budget exists for two. Ask how they prioritize.',
    'Probe: "VP Engineering says can\'t support model serving — what do you do?" (influencing without authority).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-organizational-impact', 'Measuring and communicating DS impact to executives', 'leadership', 'closing', 'must', 0,
    'Ask how they communicate DS team value to non-technical executives and board-level stakeholders.',
    'Surface — look for executive fluency and ability to translate ML outcomes into business language.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('data-science', 'case-study', '0-2', entry, [
    'Complex multi-stakeholder trade-off scenarios',
    'Live interactive cases without a dataset prompt',
    'Organizational strategy or team resource allocation',
    'Advanced experimentation design with network effects',
    'Build-vs-buy infrastructure decisions',
  ]),
  template('data-science', 'case-study', '3-6', mid, [
    'Organizational-level strategy or data function design',
    'Multi-year roadmap planning or headcount decisions',
    'ML platform architecture or build-vs-buy evaluation',
    'Model governance or compliance frameworks at scale',
    'Pure algorithmic coding without business context',
  ]),
  template('data-science', 'case-study', '7+', senior, [
    'Individual EDA or single-model analysis stories',
    'Basic metric definition or KPI setting questions',
    'Standard A/B test design without strategic framing',
    'Pure technical implementation without org dimension',
    'Questions answerable without cross-functional leadership context',
  ]),
]
