import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Data Science × Technical × 0-2 ───────────────────────────────────────
const entry: CompactSlot[] = [
  ['stats-foundations', 'Probability and statistics foundations', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask a probability or descriptive statistics concept (Bayes\' theorem, mean vs median, CLT). Calibrate depth.',
    'Surface — gauge intuition, not formula recall.', 'Conceptual understanding over implementation; explain p-value in plain English.'],
  ['hypothesis-testing', 'Hypothesis testing and significance', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask about null/alternative hypotheses, p-values, Type I/II errors, and confidence intervals.',
    'Surface — move on after checking intuition, not formula correctness.', 'SQL is eliminatory; statistics is the conceptual gate.'],
  ['sql-aggregation', 'SQL joins, aggregations, and window functions', 'ml-engineering', 'exploration', 'must', 2,
    'Ask a medium SQL problem: GROUP BY with conditions, ROW_NUMBER/RANK, date filtering, or subquery.',
    'Probe RANK vs DENSE_RANK vs ROW_NUMBER distinction and NULL handling.',
    'SQL is the gating skill — many entry candidates are screened out here.'],
  ['python-pandas', 'Python and Pandas data manipulation', 'ml-engineering', 'exploration', 'must', 2,
    'Ask a pandas task: filtering, groupby+agg, merge, or handling missing values.',
    'Probe NULL/NaN handling and whether they explain logic step-by-step.',
    'Pandas questions often mirror SQL — same logic, different syntax.'],
  ['linear-regression', 'Linear regression assumptions and interpretation', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask about linear regression assumptions (linearity, normality, homoscedasticity) and coefficient interpretation.',
    'Probe: "What if the normality assumption is violated?" (foundational depth).',
    'Must understand why n-1 in sample variance, not just the formula.'],
  ['ml-fundamentals', 'Bias-variance, overfitting, and model evaluation basics', 'statistical-thinking', 'exploration', 'if-time', 2,
    'Ask about bias-variance tradeoff, overfitting vs underfitting, and train/test split rationale.',
    'Probe with scenario: "99% accuracy on fraud dataset — is that good?" (class imbalance).'],
  ['data-visualization', 'Data visualization and chart selection', 'data-communication', 'exploration', 'if-time', 1,
    'Ask when to use bar vs line vs scatter chart and how they choose visualizations for a given audience.',
    'Probe: "How did you decide which chart type for that audience?" (communication intent).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tool-knowledge', 'Tools, learning path, and next steps', 'ml-engineering', 'closing', 'must', 0,
    'Ask what DS tools they are most confident in and what they are actively learning.',
    'Surface — assess self-awareness about skill gaps and growth trajectory.'],
]

// ─── Data Science × Technical × 3-6 ───────────────────────────────────────
const mid: CompactSlot[] = [
  ['ml-algorithm-depth', 'ML algorithm internals and selection trade-offs', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask about Random Forest vs XGBoost vs LightGBM: internals, when to use, and key hyperparameters.',
    'Surface — gauge algorithm fluency and analytical thinking, not just name-dropping.', 'Must go beyond naming algorithms to explain internals, trade-offs, and when NOT to use each.'],
  ['experiment-design', 'A/B test design and power analysis', 'experimentation', 'exploration', 'must', 2,
    'Ask how they would design an A/B test: hypothesis, sample size, runtime, randomization unit, and guardrails.',
    'Probe: "A/B test shows 2% lift, p=0.08. What do you do?" (statistical judgment).',
    'Experimental design is huge at FAANG — power analysis, novelty effects, multiple testing correction.'],
  ['model-evaluation', 'Model evaluation beyond accuracy — PR-AUC, calibration', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask about precision/recall trade-offs, when to use ROC-AUC vs PR-AUC, and model calibration.',
    'Probe: "Explain bias-variance tradeoff using your proposed model." (fundamentals grounding).'],
  ['feature-engineering', 'Feature engineering as a design skill', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they would engineer features for a scenario (fraud detection, churn, recommendation).',
    'Probe: "Design features that adapt over time for fraud that drifts." (feature creativity).',
    'Feature engineering tested as a design skill at this level, not just technique recall.'],
  ['product-metrics', 'Product metrics definition and north star', 'data-communication', 'exploration', 'must', 2,
    'Ask about defining north star, guardrail, and proxy metrics for a product scenario.',
    'Probe: "PM wants engagement, VP wants revenue. How do you define the north star?" (product sense).',
    'Good metrics must be Simple, Clear, and Actionable.'],
  ['production-ml', 'Production ML: drift, monitoring, and retraining', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they detect and respond to model performance degradation in production.',
    'Probe: "How detect model degrading in production?" (monitoring/drift awareness).'],
  ['sql-at-scale', 'Advanced SQL: CTEs, window functions, performance', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask a hard SQL problem requiring CTEs chained with window functions (cohort retention, sessionization).',
    'Probe query performance rationale and whether they can explain execution order.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-technical-growth', 'Technical depth and areas of active growth', 'ml-engineering', 'closing', 'must', 0,
    'Ask which technical area they are investing in and what they have shipped to production recently.',
    'Surface — assess production mindset and intentional skill development.'],
]

// ─── Data Science × Technical × 7+ ────────────────────────────────────────
const senior: CompactSlot[] = [
  ['ml-system-design-overview', 'End-to-end ML system architecture', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask them to walk through architecting a DS solution end-to-end: data → features → training → serving → monitoring.',
    'Surface — identify which components they reach for and depth of production thinking.', 'ML system design is the marquee round at E5+; architecture fluency is the gate.'],
  ['causal-inference', 'Causal inference when RCTs are infeasible', 'experimentation', 'exploration', 'must', 2,
    'Ask how they estimate a causal effect when an A/B test is not possible (diff-in-diff, IVs, PSM, RD).',
    'Probe: "Can\'t A/B test this change. How would you estimate the causal effect?" (causal reasoning).',
    'Causal inference is gating at senior level — candidates prepping only supervised learning are underprepared.'],
  ['advanced-experimentation', 'Advanced experimentation: network effects, bandits, sequential testing', 'experimentation', 'exploration', 'must', 2,
    'Ask about interference/network effects in experiments or multi-armed bandit vs A/B testing.',
    'Probe: "How diagnose a failed experiment with potential interference?" (bias reasoning).'],
  ['ml-fairness-reliability', 'ML fairness, bias detection, and explainability', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask how they detect and mitigate bias in a model, and when explainability (SHAP, LIME) matters.',
    'Probe: "Detect if a feature is proxying for a protected attribute?" (fairness depth).',
    'Research fluency expected — discuss limitations and critique real methodologies.'],
  ['data-platform-decisions', 'Data platform trade-offs: build vs buy, real-time vs batch', 'ml-engineering', 'exploration', 'must', 2,
    'Ask about a major data infrastructure decision: feature store, data warehouse, streaming vs batch.',
    'Probe: "Model latency 200ms, SLA is 50ms. What do you do?" (production trade-offs).'],
  ['research-to-production', 'Research prototype to production pipeline', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they take a research paper or prototype and deploy it to production at scale.',
    'Probe: "Take this paper\'s approach and deploy it to 100M users." (research-to-prod gap).'],
  ['technical-leadership', 'Technical leadership: experiment review, modeling standards', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they establish modeling best practices and experiment review across teams.',
    'Probe: "Team disagrees on evaluation metric. How do you resolve?" (technical leadership).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-technical-vision', 'Technical vision and industry awareness', 'ml-engineering', 'closing', 'must', 0,
    'Ask how they stay current with the field and what technical bets they think matter most right now.',
    'Surface — look for genuine industry awareness and opinions on trade-offs.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('data-science', 'technical', '0-2', entry, [
    'ML algorithm internals or hyperparameter tuning',
    'Model deployment, serving, or production monitoring',
    'Experiment design or A/B testing methodology',
    'Deep learning architectures or embeddings',
    'Feature store design or data pipeline architecture',
  ]),
  template('data-science', 'technical', '3-6', mid, [
    'Causal inference or observational study methods',
    'Advanced ML system design at platform scale',
    'Deep learning from scratch or research paper critique',
    'ML fairness frameworks or regulatory compliance',
    'Distributed training or model compression techniques',
  ]),
  template('data-science', 'technical', '7+', senior, [
    'Basic SQL or Python pandas syntax questions',
    'Conceptual statistics without application to real systems',
    'Simple model accuracy or train/test split questions',
    'Algorithm name-dropping without system context',
    'Entry-level linear regression or logistic regression basics',
  ]),
]
