import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Design × Behavioral × 0-2 ─────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['portfolio-walkthrough', 'Portfolio walkthrough', 'design-process', 'warm-up', 'must', 0,
    'Ask candidate to walk through a favorite project and why they chose it. Calibrate scope for junior.',
    'Surface only — use this to select follow-up topics.', 'Bootcamp, school, and self-initiated projects are expected and fine.'],
  ['design-motivation', 'Motivation for design', 'design-process', 'warm-up', 'must', 0,
    'Ask why they got into UX/design. Look for genuine user-centered curiosity, not just tool interest.',
    'Surface treatment — one follow-up at most.', 'Assess coachability and learning orientation.'],
  ['handling-design-feedback', 'Handling critical design feedback', 'design-process', 'exploration', 'must', 2,
    'Ask about receiving critical feedback on a design. Tests ego resilience and growth mindset.',
    'Probe what specifically changed in their design or approach after the feedback.',
    'Willingness to learn matters more than expertise at this level.'],
  ['developer-collaboration', 'Collaborating with developers on handoff', 'collaboration', 'exploration', 'must', 2,
    'Ask about working with engineers on a design handoff. Look for communication and constraint awareness.',
    'Isolate their role: "You said we — what specifically did YOU do to bridge the gap?"',
    'Academic or internship project context is acceptable.'],
  ['user-empathy-discovery', 'User research discovery moment', 'user-research', 'exploration', 'must', 2,
    'Ask about discovering something surprising from user research. Tests user-centered instinct.',
    'Probe how that finding changed the design direction. Isolate: "How did you know this was the right call?"',
    'User-centricity separates the pack — strongest candidates center stories on user needs, not tools.'],
  ['designing-under-constraints', 'Designing under significant constraints', 'design-process', 'exploration', 'if-time', 1,
    'Ask about designing with tight time, budget, or tech limitations. Look for resourcefulness.',
    'Probe what they deprioritized and how they justified the tradeoff.'],
  ['design-failure-learning', 'A design that did not work as expected', 'design-process', 'exploration', 'if-time', 2,
    'Ask about a design that failed or missed the mark. Look for self-awareness and willingness to iterate.',
    'Probe what they identified as the root cause versus what they would do differently.',
    'Process over polish — thinking clarity beats a beautiful mockup with no reasoning.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-growth-curiosity', 'Growth and design curiosity', 'design-process', 'closing', 'must', 0,
    'Ask what excites them about design and where they want to grow. Assess enthusiasm and self-awareness.',
    'Surface — wrap up the interview warmly.'],
]

// ─── Design × Behavioral × 3-6 ─────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['design-ownership-narrative', 'Project ownership narrative', 'design-process', 'warm-up', 'must', 0,
    'Ask about a project they drove design direction on end-to-end. Calibrate scope and ownership.',
    'Surface — use this to identify follow-up topics.', 'Must demonstrate personal ownership of design outcomes, not just execution.'],
  ['stakeholder-conflict-persuasion', 'Stakeholder conflict and persuasion', 'collaboration', 'exploration', 'must', 2,
    'Ask about a time a PM or exec disagreed with their design. Look for data-backed advocacy.',
    'Probe the exact argument they made and what evidence shifted the conversation.',
    'Influence without authority is the core signal — must speak PM and engineering language.'],
  ['user-advocacy-under-pressure', 'User advocacy under pressure', 'user-research', 'exploration', 'must', 2,
    'Ask about championing a user need when the team wanted to cut it for speed.',
    'Probe what evidence they used and what compromise they reached.',
    'Expect measurable outcomes — qualitative-only answers are weak at this level.'],
  ['navigating-design-ambiguity', 'Navigating ambiguity in design', 'design-process', 'exploration', 'must', 2,
    'Ask about a project where the problem was not well-defined. Look for independent problem scoping.',
    'Probe how they defined success criteria when none were given and how they validated the framing.',
    'Expected to own the problem, not just the pixels.'],
  ['measuring-design-impact', 'Measuring design impact', 'design-process', 'exploration', 'if-time', 2,
    'Ask how they\'ve measured the success of design work. Look for task success, NPS, error rate, conversion.',
    'Probe the specific metric that moved and how they isolated design\'s contribution.',
    'Stories must have measurable outcomes — not just "it was well-received."'],
  ['mentorship-team-contribution', 'Mentorship and team contribution', 'leadership', 'exploration', 'if-time', 1,
    'Ask how they\'ve helped less experienced designers grow. Look for investment in team quality.',
    'Probe a specific critique session or feedback moment that changed a peer\'s approach.'],
  ['cross-functional-influence', 'Cross-functional influence', 'collaboration', 'exploration', 'must', 2,
    'Ask about building alignment between design, product, and engineering when priorities conflict.',
    'Probe who specifically resisted, their underlying concern, and how it was resolved.',
    'Stakeholder fluency required — vague "I communicated well" fails.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['design-decision-reversal', 'Design decision they would reverse', 'design-process', 'closing', 'must', 0,
    'Ask about a design decision they made that they\'d reverse today. Look for honest self-assessment.',
    'Surface — one clear example suffices.'],
]

// ─── Design × Behavioral × 7+ ──────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['design-culture-building', 'Design culture and org building', 'leadership', 'warm-up', 'must', 0,
    'Ask how they\'ve established or reshaped design culture at a company. Must be concrete, not aspirational.',
    'Surface — use to calibrate org-level scope and leadership dimensions.', 'How they talk about their team reveals leadership character — "I" vs. "my team achieved X."'],
  ['executive-influence-strategy', 'Executive influence and strategic alignment', 'leadership', 'exploration', 'must', 2,
    'Ask about influencing a C-suite exec or VP on a design-driven initiative. Tests business fluency.',
    'Probe the data that changed their mind and what the exec\'s specific objection was.',
    'Business fluency non-negotiable — must connect design to revenue, retention, or competitive positioning.'],
  ['design-system-strategy', 'Design system governance across product teams', 'design-systems', 'exploration', 'must', 2,
    'Ask about design system adoption and governance across multiple product teams.',
    'Probe how they balanced consistency with team autonomy and what adoption metrics they tracked.',
    'Design ops maturity expected — hub-and-spoke governance, RFC processes, adoption rate tracking.'],
  ['building-growing-design-team', 'Building and growing a design team', 'leadership', 'exploration', 'must', 2,
    'Ask about building a design team — hiring, structuring, and developing designers.',
    'Probe their hiring philosophy and how they created career growth paths.',
    'Org design is part of the job — embedded vs. centralized, designer-to-PM ratios.'],
  ['design-metrics-business-impact', 'Design metrics and business impact', 'design-process', 'exploration', 'if-time', 2,
    'Ask how they measure design\'s contribution to business outcomes. Look for HEART, SUS, NPS frameworks.',
    'Probe how they connect design metrics to metrics the board already tracks.',
    'Must translate NPS into revenue and SUS into productivity to get executive buy-in.'],
  ['design-quality-at-scale', 'Ensuring design quality at scale', 'design-systems', 'exploration', 'if-time', 2,
    'Ask how they ensure design quality scales as the team and product grow.',
    'Probe the critique rituals and quality gates they introduced and how they measured effectiveness.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['significant-failure-org', 'Significant failure with organizational consequences', 'leadership', 'closing', 'must', 0,
    'Ask about a significant failure and what changed at the org level. Failure questions carry more weight here.',
    'Probe systemic changes introduced, not just personal growth.', 'Expect cross-company examples and systems-level accountability.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('design', 'behavioral', '0-2', entry, [
    'Design system governance or org-wide design strategy',
    'Managing stakeholder conflicts with VPs or C-suite',
    'Leading or mentoring other designers',
    'Design metrics at portfolio level (NPS, SUS, task success rates)',
    'Hiring, team structure, or design operations',
  ]),
  template('design', 'behavioral', '3-6', mid, [
    'Building a design org from scratch or defining org-wide design vision',
    'C-suite executive persuasion or board-level design strategy',
    'Hiring and managing a team of designers',
    'Design operations or tooling decisions at org scale',
    'Multi-product design system governance',
  ]),
  template('design', 'behavioral', '7+', senior, [
    'Tool-specific questions (Figma features, prototyping mechanics)',
    'Individual contributor design execution (wireframing a specific flow)',
    'Basic design principles or UCD process steps',
    'Portfolio walkthrough of individual project details',
    'Design challenge or whiteboard exercise',
  ]),
]
