import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Design × Technical × 0-2 ──────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['design-fundamentals', 'UX vs UI and design fundamentals', 'design-process', 'warm-up', 'must', 0,
    'Ask candidate to explain UX vs UI and how they work together. Assess design vocabulary and clarity.',
    'Surface — use answer to calibrate depth for the rest of the session.', 'Evaluated on thinking clarity, not mastery — a thoughtful junior beats a sloppy mid-level.'],
  ['portfolio-deep-dive', 'Portfolio project deep dive', 'design-process', 'warm-up', 'must', 0,
    'Ask them to walk through a recent project with design decisions. Portfolio IS the technical exam at entry level.',
    'Surface — this is the launching pad for technical follow-ups.', 'Case studies must document full process (research, wireframes, iterations), not just polished mockups.'],
  ['design-rationale', 'Design decision rationale', 'design-process', 'exploration', 'must', 2,
    'Ask why they made a specific layout or interaction choice. Look for reasoning, not aesthetics.',
    'Probe alternatives: "What other approaches did you consider? Why did you reject them?"',
    'Fundamentals over frameworks — hierarchy, contrast, alignment, proximity, consistency.'],
  ['figma-tool-proficiency', 'Figma organization and component usage', 'design-systems', 'exploration', 'must', 2,
    'Ask how they organize Figma files and how they use components vs. variants. Tests practical competency.',
    'Probe: "How do you handle a component that needs to look different across contexts?"',
    'Figma competence expected — auto layout, variants, basic prototyping signal professionalism.'],
  ['accessibility-basics', 'Accessibility considerations in design', 'visual-design', 'exploration', 'must', 2,
    'Ask what accessibility considerations they apply to their designs. Awareness, not expert compliance.',
    'Probe: "What happens to this design for a color-blind user? For a screen reader user?"',
    'Know contrast ratios, touch targets, keyboard nav — not expected to audit WCAG 2.2 AAA.'],
  ['research-methods-basics', 'User research method selection', 'user-research', 'exploration', 'if-time', 1,
    'Ask what research methods they would use to validate a design. Tests method-to-question matching.',
    'Probe: "Why that method for that problem? What would you learn that another method wouldn\'t show?"'],
  ['design-critique-exercise', 'App or feature critique', 'design-process', 'exploration', 'if-time', 2,
    'Present an app or screen and ask what works and what they would improve. Tests critical eye.',
    'Probe: "How would you fix the navigation issue you described? Sketch it out."',
    'Look for heuristic-grounded critique, not aesthetic opinions.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['iteration-evidence', 'Showing earlier design iterations', 'design-process', 'closing', 'must', 0,
    'Ask them to show or describe an earlier version of a project and what changed. Tests iteration mindset.',
    'Surface — one clear before/after story suffices.'],
]

// ─── Design × Technical × 3-6 ──────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['case-study-presentation', 'Case study presentation', 'design-process', 'warm-up', 'must', 0,
    'Ask candidate to present their strongest project end-to-end. The case study IS the technical interview at mid-level.',
    'Surface — set expectation that you will interrupt with probing questions throughout.', 'Case study narrative — problem framing, research rigor, design rationale, measured impact — determines the outcome.'],
  ['design-systems-contribution', 'Design systems contribution and component architecture', 'design-systems', 'exploration', 'must', 2,
    'Ask about contributing to or building a design system. Look for atomic design, token systems, documentation.',
    'Probe: "How do you handle a component request that doesn\'t fit the existing system?"',
    'Expected to be a contributor, not just a consumer — write docs, refactor components, understand theming.'],
  ['advanced-research-methods', 'Advanced user research methodology', 'user-research', 'exploration', 'must', 2,
    'Ask about a usability study: recruitment, screening, task design, analysis. Tests methodology depth.',
    'Probe: "How many participants? How did you recruit? How did findings translate to specific decisions?"',
    'Process depth, not just process awareness — must discuss what worked, failed, and why approach was adapted.'],
  ['accessibility-in-practice', 'Accessibility throughout the design process', 'visual-design', 'exploration', 'must', 2,
    'Ask how they incorporate accessibility from wireframe stage, not as a retrofit. Tests WCAG 2.1 AA knowledge.',
    'Probe: "Walk me through how a screen reader user completes this task in your design."',
    'Accessibility is a design skill — semantic hierarchy, focus order, color independence from wireframe stage.'],
  ['app-critique-teardown', 'App critique and redesign proposal', 'design-process', 'exploration', 'if-time', 2,
    'Present a real app and ask for UX evaluation and redesign of the weakest flow. Often a FAANG product.',
    'Probe: "You critiqued the onboarding — sketch a better version and explain your choices."',
    'Strong candidates evaluate holistically: IA, interaction patterns, accessibility, visual hierarchy.'],
  ['information-architecture', 'Information architecture and navigation design', 'design-process', 'exploration', 'if-time', 2,
    'Ask how they would organize navigation for a feature-rich product. Tests IA patterns and mental models.',
    'Probe: "How did you validate the hierarchy matches users\' mental models?"'],
  ['design-dev-handoff', 'Design-to-development handoff practices', 'collaboration', 'exploration', 'must', 2,
    'Ask how they hand off designs to engineering. Tests specification quality and interaction documentation.',
    'Probe: "How do you specify responsive behavior and state variations for a complex component?"',
    'Quantified impact expected — "error rate dropped from 12% to 3% after redesign" is the bar.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['impact-measurement', 'Measuring quantified design impact', 'design-process', 'closing', 'must', 0,
    'Ask for a concrete example of design impact with a metric. Tests analytical maturity.',
    'Surface — one precise example suffices. Push for numbers if they speak only in qualitative terms.'],
]

// ─── Design × Technical × 7+ ───────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['design-strategy-vision', 'Design strategy and vision for a product line', 'design-systems', 'warm-up', 'must', 0,
    'Ask how they develop and communicate a design strategy connecting to business objectives. Tests strategic range.',
    'Surface — calibrate whether they speak OKR language or default to craft language.', 'Strategy over execution — systems thinking and org design matter more than individual design craft.'],
  ['design-ops-at-scale', 'Design operations and process at scale', 'design-systems', 'exploration', 'must', 2,
    'Ask how they\'ve established design processes across multiple teams. Look for design ops maturity.',
    'Probe their targets: "What\'s your review-cycle duration target? How do you measure it?"',
    'Design ops is a core competency — cycle time targets, component adoption rates, pixel-parity defect rates.'],
  ['design-system-governance', 'Design system governance and architecture at org scale', 'design-systems', 'exploration', 'must', 2,
    'Ask about governing a shared design system across 8+ product teams. Tests change management at scale.',
    'Probe: "A product team wants to fork the design system for a new market. How do you handle that request?"',
    'Hub-and-spoke governance expected — RFC process, adoption metrics, deprecation policies.'],
  ['design-impact-quantitative', 'Quantitative frameworks for measuring design impact', 'design-process', 'exploration', 'must', 2,
    'Ask how they prove design\'s value to the business. Look for HEART, SUS, NPS tied to business metrics.',
    'Probe: "The CEO asks what\'s the ROI of the design team. Walk me through your answer with specific numbers."',
    'Metrics fluency mandatory — business tier (revenue), experience tier (SUS), operational tier (cycle time).'],
  ['research-strategy', 'Research practice and insights infrastructure', 'user-research', 'exploration', 'if-time', 2,
    'Ask how they build a research practice that informs product decisions at scale.',
    'Probe: "How do you decide between foundational research vs. tactical usability testing?"',
    'Research ops expected — research repository, insight taxonomies, democratization vs. specialization.'],
  ['accessibility-strategy', 'Accessibility as strategic program', 'visual-design', 'exploration', 'if-time', 2,
    'Ask how they move an org from accessibility as compliance to accessibility as competitive advantage.',
    'Probe: "How do you get engineering to prioritize accessibility fixes when they have a feature backlog?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['design-innovation-perspective', 'Perspective on design tools and emerging paradigms', 'design-process', 'closing', 'must', 0,
    'Ask how they evaluate and adopt new design tools, AI-assisted design, or emerging interaction paradigms.',
    'Surface — look for neither dismissive nor hype-driven stance. Pragmatic adoption thinking expected.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('design', 'technical', '0-2', entry, [
    'Design system architecture, token systems, or multi-platform governance',
    'Advanced research methodology (diary studies, contextual inquiry, statistical analysis)',
    'Design operations, tooling decisions, or process optimization at scale',
    'Advanced prototyping (code-based prototypes, Framer, complex animations)',
    'Expecting production-quality visual design in portfolio',
  ]),
  template('design', 'technical', '3-6', mid, [
    'Basic design vocabulary (what is UX, what is a wireframe, what is a persona)',
    'Tool-level questions (how to use Figma auto layout — assume proficiency)',
    'Org-level design strategy or design ops architecture',
    'Design team hiring, performance management, or career leveling',
    'Multi-product design system governance at org scale',
  ]),
  template('design', 'technical', '7+', senior, [
    'Individual design execution tasks (wireframe this flow, prototype that interaction)',
    'Tool-level questions (Figma features, prototyping mechanics)',
    'Basic design principles, UCD process steps, or design vocabulary',
    'App critique exercises (appropriate for mid-level, not director-level)',
    'Design challenge or whiteboard exercise',
  ]),
]
