import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Design × Case Study × 0-2 ─────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['case-intro-clarify', 'Clarifying questions and problem scoping', 'design-process', 'warm-up', 'must', 0,
    'Present a narrow design prompt. Assess whether candidate asks clarifying questions before sketching.',
    'Surface — jumping straight to screens without asking is a red flag at any level.', 'Process over polish — narrating thinking aloud is as important as what they draw.'],
  ['user-problem-definition', 'Defining the user and problem', 'user-research', 'warm-up', 'must', 0,
    'Ask them to define the primary user, their goal, and key pain points before sketching.',
    'Surface — this sets the grounding for everything that follows.', 'Asking questions is the first test — candidates who skip this fail the exercise.'],
  ['ideation-alternatives', 'Exploring 2-3 design approaches', 'design-process', 'exploration', 'must', 2,
    'Ask candidate to sketch 2-3 rough approaches and explain tradeoffs before committing to one.',
    'Probe: "You went with option A — what was option B? Why did you reject it?"',
    'Exploring alternatives differentiates — divergent thinking is the key signal.'],
  ['wireframe-key-screens', 'Wireframing key screens and states', 'visual-design', 'exploration', 'must', 2,
    'Ask them to sketch 3-5 key screens and annotate with interaction notes. Look for edge cases.',
    'Probe: "What happens if the user has no items? What does the error state look like?"',
    'Scope is intentionally narrow — look for depth of thinking within a small scope.'],
  ['user-decision-grounding', 'Grounding every decision in user needs', 'user-research', 'exploration', 'must', 2,
    'Ask why each design choice was made. Look for user-centered reasoning, not "it\'s best practice."',
    'Probe: "Who is this designed for specifically? How does that user context change your choice?"',
    'User empathy must be explicit — every decision should reference the user.'],
  ['constraint-adaptation', 'Adapting design to a new constraint', 'design-process', 'exploration', 'if-time', 1,
    'Introduce a mid-exercise curveball (e.g., poor network, visual impairment). Tests adaptability.',
    'Probe: "The user just told you they hate modals. How does your design change?"'],
  ['solution-defense', 'Presenting and defending the solution', 'collaboration', 'exploration', 'if-time', 2,
    'Ask them to walk through the solution and handle pushback. Tests conviction without stubbornness.',
    'Probe: "Engineering says this will take 3 months. What ships in 2 weeks?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['prioritization-tradeoffs', 'Prioritization given limited engineering time', 'design-process', 'closing', 'must', 0,
    'Ask which part of the design ships first given 2 weeks of engineering time. Tests prioritization.',
    'Surface — one clear decision with rationale suffices.'],
]

// ─── Design × Case Study × 3-6 ─────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['scope-negotiation', 'Scope negotiation and problem reframing', 'design-process', 'warm-up', 'must', 0,
    'Present a broad design prompt. Assess whether they negotiate scope and reframe the problem.',
    'Surface — the best candidates reframe the prompt, not just execute it.', 'End-to-end ownership expected — research thinking, IA, interaction design, and measurement.'],
  ['research-strategy-plan', 'Research strategy and problem framing', 'user-research', 'exploration', 'must', 2,
    'Ask what research they would do before designing. Tests depth beyond "I\'d do user interviews."',
    'Probe: "What questions would you ask? How many users? Why that number? What data already exists?"',
    'Problem framing is the differentiator — strong answers spend time on problem space before solutions.'],
  ['information-architecture', 'Information architecture and navigation model', 'design-process', 'exploration', 'must', 2,
    'Ask them to design the IA for a feature-rich product. Tests card sorting logic and mental model alignment.',
    'Probe: "How did you validate the hierarchy matches how users think about this?"',
    'Quantitative reasoning required — "this could affect ~30% of DAUs" with rough reasoning.'],
  ['design-solution-tradeoffs', 'Design solution with annotated tradeoffs', 'visual-design', 'exploration', 'must', 2,
    'Ask for key screens with annotations showing interaction states and tradeoffs. Look for multi-stakeholder awareness.',
    'Probe: "You chose X over Y — walk me through that tradeoff. What did you sacrifice?"',
    'Tradeoff articulation separates strong from adequate — "I chose X accepting the cost of W."'],
  ['usability-metrics-plan', 'Usability testing and success metrics', 'user-research', 'exploration', 'if-time', 2,
    'Ask how they would test the design and what metrics they would track. Tests analytical thinking.',
    'Probe: "You said you\'d measure engagement — define that precisely. What goes up? What\'s the guardrail?"'],
  ['stakeholder-curveball', 'Handling a stakeholder curveball', 'collaboration', 'exploration', 'if-time', 2,
    'Introduce a mid-exercise stakeholder constraint (e.g., VP wants a promo banner on this screen).',
    'Probe: "How do you respond? What do you push back on and what do you accommodate?"'],
  ['competitive-context', 'Competitive awareness and differentiation', 'design-process', 'exploration', 'must', 2,
    'Ask how their solution compares to a competitor that just launched something similar.',
    'Probe: "What\'s your differentiation? How does the competitive context change your design priority?"',
    'Multi-stakeholder awareness — engineering feasibility, business model, content strategy, accessibility.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['implementation-phasing', 'Implementation phasing and first shipment', 'collaboration', 'closing', 'must', 0,
    'Ask what ships in the first release and what comes later. Tests prioritization under time pressure.',
    'Surface — clear milestones and rationale. Time management is a meta-skill being tested.'],
]

// ─── Design × Case Study × 7+ ──────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-context-scoping', 'Strategic context and stakeholder analysis', 'design-process', 'warm-up', 'must', 0,
    'Present a complex org-level design challenge. Assess incisive scoping questions — quality of questions matters.',
    'Surface — quality of questions demonstrates strategic sophistication. Rigid framework signals IC, not leadership.', 'Strategic framing is the entire evaluation — tests design as a business function, not product design craft.'],
  ['diagnostic-research-strategy', 'Diagnostic framing and research strategy', 'user-research', 'exploration', 'must', 2,
    'Ask what they need to learn first and how. Look for stakeholder interviews, design audit, research plan.',
    'Probe: "What specific questions would you ask? What data do you already expect to find?"',
    'Business fluency under pressure — answers framed in business terms: ROI, margin, Q2 board results.'],
  ['strategic-design-framework', 'Strategic design roadmap and OKR definition', 'design-systems', 'exploration', 'must', 2,
    'Ask them to design a phased roadmap (30/60/90 day) with design-specific OKRs tied to business goals.',
    'Probe: "The board wants this in 6 months, not 12. What do you cut?"',
    '90-day plan articulation expected — Listen, Align, Activate with concrete milestones.'],
  ['governance-execution', 'Governance model and execution plan', 'design-systems', 'exploration', 'must', 2,
    'Ask how they would implement the strategy — critique cadence, review gates, design system contribution model.',
    'Probe: "Product wants to ship weekly. Design reviews take 3 days. How do you resolve this?"',
    'Change management is core — phased rollout, buy-in strategies, realistic timelines.'],
  ['design-team-scaling', 'Scaling a design team and maintaining quality', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they\'d scale a design team from 5 to 25 while maintaining quality. Tests hiring and culture design.',
    'Probe: "Your team doubled in size. How did design quality change? What did you do about it?"'],
  ['board-executive-pitch', 'Board or executive pitch on design strategy', 'collaboration', 'exploration', 'if-time', 2,
    'Ask them to pitch their strategy to a simulated executive audience in under 3 minutes.',
    'Probe: "The CFO asks why we\'re spending $2M on a design system rebuild. What\'s your pitch?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['failure-recovery-plan', 'Strategy not hitting OKRs — recovery plan', 'design-process', 'closing', 'must', 0,
    'Ask what they do if 6 months in the design strategy is not hitting OKRs. Tests resilience and adaptability.',
    'Surface — look for diagnostic thinking and stakeholder communication, not just doubling down.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('design', 'case-study', '0-2', entry, [
    'Jumping to UI without asking who the user is',
    'Designing one solution without exploring alternatives',
    'Focusing on visual polish over interaction logic',
    'Ignoring edge cases (error states, empty states, loading states)',
    'Treating the exercise as a solo performance without engaging the interviewer',
  ]),
  template('design', 'case-study', '3-6', mid, [
    'Skipping research and problem framing and jumping to screens',
    'Designing only the happy path without error, empty, or edge states',
    'No success metrics or measurement strategy',
    'Using frameworks (Design Thinking, Double Diamond) as buzzwords without applying them',
    'Spending all time on IA without showing any concrete UI',
  ]),
  template('design', 'case-study', '7+', senior, [
    'Treating the exercise as an IC design task (wireframing specific features)',
    'Proposing strategy without connecting to business metrics',
    'Generic design thinking platitudes without concrete actions',
    'Proposing changes without a change management strategy',
    'Not demonstrating executive communication skills',
  ]),
]
