import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── DevOps × Technical × 0-2 ───────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['infra-calibration', 'Infrastructure you\'ve worked with', 'technical-depth', 'warm-up', 'must', 0,
    'Ask what infrastructure and tools they\'ve used. Calibrate hands-on exposure vs coursework.',
    'Surface — use to pick which fundamentals to probe.', 'Homelab, bootcamp, and internship stacks are all valid.'],
  ['cicd-basics', 'Designing a basic CI/CD pipeline', 'automation', 'exploration', 'must', 2,
    'Ask how they\'d design a CI/CD pipeline for a small team. Look for build → test → deploy stages and where tests run.',
    'Probe how a bad deploy gets caught before production and how a rollback works.',
    'Conceptual understanding is fine; don\'t require a specific tool.'],
  ['containers-vs-vms', 'Containers vs VMs', 'technical-depth', 'exploration', 'must', 2,
    'Ask the difference between containers and VMs and when to choose each. Look for isolation/overhead reasoning.',
    'Probe what a container actually shares with the host and a production consideration (image size, security).'],
  ['iac-fundamentals', 'Infrastructure-as-code basics', 'automation', 'exploration', 'must', 2,
    'Ask how they\'d manage infra as code rather than clicking in a console. Look for repeatability and version control.',
    'Probe what goes wrong with manual provisioning and what "drift" means.'],
  ['monitoring-basics', 'Monitoring a service', 'operational', 'exploration', 'if-time', 2,
    'Ask what they\'d monitor for a new service and how they\'d know it\'s healthy. Look for the metrics/logs/alerts split.',
    'Probe the difference between "is it up" and "is it working for users".'],
  ['one-cloud-depth', 'Depth in one cloud provider', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask about the cloud provider they know best and a service they\'ve used in anger. Look for transferable concepts.',
    'Probe whether they understand the concept or just the console clicks.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['learning-infra-tools', 'How you learn new infra tooling', 'problem-solving', 'closing', 'must', 0,
    'Ask how they get up to speed on a new tool. Assess learning strategy and resourcefulness.',
    'Surface — wrap up and note growth orientation.'],
]

// ─── DevOps × Technical × 3-6 ───────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['prod-infra-calibration', 'Production infrastructure you own', 'technical-depth', 'warm-up', 'must', 0,
    'Ask what production infrastructure they currently own. Calibrate scope and on-call reality.',
    'Surface — use to choose deep-dives.', 'Must be real production systems with users.'],
  ['observability-stack', 'Observability stack for microservices', 'operational', 'exploration', 'must', 2,
    'Ask how they\'d design observability for ~50 microservices. Look for metrics/logs/traces and an alerting philosophy.',
    'Probe how they avoid alert fatigue and what they page on vs ticket on.',
    'Expect opinions formed by real on-call experience.'],
  ['slo-design', 'Designing SLOs for an API', 'operational', 'exploration', 'must', 2,
    'Ask how they\'d set SLOs for a customer-facing API. Look for SLI selection and error-budget reasoning.',
    'Probe the difference between SLO/SLI/SLA and what they do when the budget is spent.',
    'Should connect SLOs to real user experience, not vanity uptime.'],
  ['k8s-operations', 'Kubernetes / orchestration operations', 'technical-depth', 'exploration', 'must', 2,
    'Ask about operating container orchestration in production. Look for real failure experience, not tutorials.',
    'Probe a time something broke (OOM, bad rollout, networking) and how they diagnosed it.'],
  ['multi-env-cicd', 'Multi-environment CI/CD', 'automation', 'exploration', 'if-time', 2,
    'Ask how they manage promotion across dev/staging/prod safely. Look for gating, can/blue-green, and rollback.',
    'Probe how a bad change is contained before it reaches all users.'],
  ['cost-optimization', 'Cloud cost optimization', 'operational', 'exploration', 'if-time', 2,
    'Ask about a time they reduced cloud spend. Look for measurement and tradeoff against reliability.',
    'Probe how they found the waste and what they were careful not to break.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['tradeoff-revisit', 'An infrastructure tradeoff you\'d revisit', 'technical-depth', 'closing', 'must', 0,
    'Ask about a design choice they\'d reconsider now. Assess judgment and hindsight.',
    'Surface — wrap up.'],
]

// ─── DevOps × Technical × 7+ ────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['platform-philosophy', 'Platform-engineering philosophy', 'technical-depth', 'warm-up', 'must', 0,
    'Ask how they think about platform vs project work and developer self-service. Calibrate strategic scope.',
    'Surface — identify which architecture dimensions to probe.', 'Must show org-level, not single-system, thinking.'],
  ['idp-design', 'Internal developer platform design', 'technical-breadth', 'exploration', 'must', 2,
    'Ask how they\'d design an internal developer platform for a 200-person org. Look for golden paths and self-service.',
    'Probe how they\'d drive adoption and avoid building a platform nobody uses.',
    'Scope spans many teams — paved roads, not one pipeline.'],
  ['finops', 'FinOps and cost engineering at scale', 'operational', 'exploration', 'must', 2,
    'Ask their approach to org-wide cloud cost governance. Look for accountability models, not one-off savings.',
    'Probe how they make cost visible to teams and align incentives.'],
  ['multi-region-arch', 'Multi-region infrastructure architecture', 'technical-breadth', 'exploration', 'must', 2,
    'Ask how they\'d design multi-region infrastructure for low latency and resilience. Look for data and failover reasoning.',
    'Probe data consistency across regions and the failure modes of active-active.'],
  ['chaos-engineering', 'Chaos-engineering / resilience program', 'operational', 'exploration', 'if-time', 2,
    'Ask about deliberately testing failure (game days, fault injection). Look for a program, not a one-off experiment.',
    'Probe what they learned and how it changed the architecture.'],
  ['sre-org-design', 'SRE organizational design', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they\'d structure reliability ownership across an engineering org. Look for embedded vs central tradeoffs.',
    'Probe how they keep dev teams accountable for what they ship.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['architecture-bet-failure', 'An infrastructure bet that failed', 'self-awareness', 'closing', 'must', 0,
    'Ask about an architecture decision that didn\'t pan out. Look for organizational learning.',
    'Surface — assess intellectual honesty.', 'Failure carries more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('devops', 'technical', '0-2', entry, [
    'Designing internal developer platforms or multi-region architecture',
    'FinOps and org-wide cost governance',
    'Deep chaos-engineering or SRE org design',
    'Application-level coding or product design',
    'Quizzing obscure cloud-service trivia',
  ]),
  template('devops', 'technical', '3-6', mid, [
    'Entry-level "what is a container" fundamentals',
    'Org-wide platform strategy (senior territory)',
    'Accepting "we have monitoring" without probing alerting philosophy',
    'Application feature design unrelated to infrastructure',
  ]),
  template('devops', 'technical', '7+', senior, [
    'Single-tool how-to questions',
    'Fundamentals an SRE2 could answer equally well',
    'Console-clicking detail without architectural framing',
    'Solutions with no cost or organizational dimension',
  ]),
]
