import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── DevOps × Behavioral × 0-2 ──────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro-automation', 'Intro and an automation you\'re proud of', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves and describe a piece of automation or infra they built. Look for genuine pride in removing toil.',
    'Surface only — use to pick follow-up topics.', 'Homelab, scripts, side projects, and internships are all expected.'],
  ['motivation-devops', 'Why infrastructure/DevOps over dev', 'motivation', 'warm-up', 'must', 0,
    'Ask what drew them to infrastructure and reliability work. Look for curiosity about how systems run in production.',
    'One follow-up at most — keep it warm.', 'Assess operational mindset and coachability, not depth.'],
  ['first-on-call', 'First on-call experience', 'adaptability', 'exploration', 'must', 2,
    'Ask about their first on-call rotation and what surprised them. Look for composure and learning, not heroics.',
    'Probe what they did when paged and what they learned — not just that it was stressful.',
    'Observing or shadowing on-call is acceptable context at this level.'],
  ['automated-a-process', 'Automating a manual process', 'ownership', 'exploration', 'must', 2,
    'Ask about a manual task they automated and its impact. Look for initiative and measurable toil reduction.',
    'Probe how the team adopted it and whether they measured the time saved.',
    'Small scripts that saved real time count — focus on initiative over scale.'],
  ['learned-from-incident', 'Learning from an incident they observed', 'problem-solving', 'exploration', 'must', 2,
    'Ask about an incident they watched senior engineers handle and what they took from it. Look for systemic thinking.',
    'Probe the root cause and what changed afterward — not blame.',
    'Observing and assisting is the expected scope; look for curiosity.'],
  ['working-with-developers', 'Working with developers on a deployment or ops issue', 'collaboration', 'exploration', 'if-time', 1,
    'Ask about helping a dev team ship or debug in production. Look for service-mindset and communication.',
    'Probe how they explained the operational constraint without being a gatekeeper.'],
  ['production-pressure-junior', 'Handling a stressful production moment', 'adaptability', 'exploration', 'if-time', 2,
    'Ask about a time production was degraded and they felt the pressure. Look for how they stayed calm and asked for help.',
    'Probe escalation instinct — knowing when to pull in others is a strength, not a weakness.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-infra-excitement', 'What infra problems excite you most', 'motivation', 'closing', 'must', 0,
    'Ask what kind of reliability or automation problems they want to tackle next. Assess enthusiasm and self-awareness.',
    'Surface — wrap up warmly and note growth signals.'],
]

// ─── DevOps × Behavioral × 3-6 ──────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['reliability-velocity-evolution', 'How your view of reliability vs velocity evolved', 'motivation', 'warm-up', 'must', 0,
    'Ask how their thinking on shipping fast vs staying reliable changed with experience. Calibrate operational judgment.',
    'Surface — use to identify which deep-dives to pursue.', 'Must reflect on real production systems with real users.'],
  ['led-incident-response', 'Leading a major incident response', 'leadership', 'exploration', 'must', 2,
    'Ask about an incident they were incident commander or lead responder on. Look for structured response under pressure.',
    'Probe the timeline, how they coordinated responders, and what the post-mortem changed.',
    'Should own the response, not just participate — expect coordination and comms.'],
  ['advocated-reliability', 'Advocating for reliability investment under feature pressure', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about pushing for reliability work when the team wanted to ship features. Look for a business-framed argument.',
    'Probe how they quantified risk and what won buy-in — error budgets, SLO breaches, incident cost.',
    'Measurable framing (error budget, MTTR, incident cost) differentiates at this level.'],
  ['postmortem-leadership', 'Driving a blameless post-mortem', 'leadership', 'exploration', 'must', 2,
    'Ask about running a post-mortem after a significant failure. Look for blameless framing and concrete action items.',
    'Probe how they kept it systemic vs personal and whether the action items actually shipped.',
    'Expect ownership of the process, not just attendance.'],
  ['oncall-burnout', 'Navigating on-call burnout', 'leadership', 'exploration', 'if-time', 2,
    'Ask about a time on-call load hurt them or the team. Look for sustainable practices, not just toughing it out.',
    'Probe what concretely changed — rotation design, alert tuning, runbook investment.'],
  ['ops-cross-team-friction', 'Cross-team friction over operational practices', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about friction with a dev team over deploys, reliability, or ownership. Look for influence without authority.',
    'Probe how they aligned on shared goals rather than enforcing process.'],
  ['toil-reduction-roi', 'A toil-reduction initiative with measurable ROI', 'ownership', 'exploration', 'if-time', 2,
    'Ask about an automation initiative they drove and its return. Look for prioritization and measurement.',
    'Probe how they chose what to automate and how they proved it was worth it.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retrospective-ops-decision', 'An operational decision you\'d make differently', 'self-awareness', 'closing', 'must', 0,
    'Ask what they\'d change knowing what they know now. Assess intellectual honesty and growth.',
    'Surface — one example suffices; wrap up warmly.'],
]

// ─── DevOps × Behavioral × 7+ ───────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['devops-strategic-discipline', 'DevOps/SRE as a strategic discipline', 'leadership', 'warm-up', 'must', 0,
    'Ask how they connect reliability and platform work to business outcomes. Look for multi-dimensional leadership thinking.',
    'Surface — calibrate scope and identify which leadership dimensions to probe.',
    'Must show impact across technical, people, process, and business dimensions.'],
  ['blameless-culture-org', 'Establishing blameless post-mortem culture org-wide', 'leadership', 'exploration', 'must', 2,
    'Ask about driving blameless culture across an organization. Look for changing how teams respond to failure, not a single retro.',
    'Probe the resistance they faced and how the culture change outlasted them.',
    'Scope must span multiple teams — not one team\'s ritual.'],
  ['built-sre-platform-team', 'Building or scaling an SRE / platform team', 'leadership', 'exploration', 'must', 2,
    'Ask about standing up or scaling an SRE or platform-engineering function. Look for org design and self-service strategy.',
    'Probe how they defined the team\'s charter, hired, and measured its impact on other teams.',
    'Multiplier impact — making every team more reliable — is the right scope.'],
  ['error-budget-policy', 'Defining error-budget / reliability policy', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask about setting SLO/error-budget policy and getting leadership to honor it. Look for the hard part: enforcement.',
    'Probe what happened when a team blew its budget and how the policy held under pressure.',
    'Policy that actually gates releases — not aspirational SLOs — is what counts.'],
  ['outage-crisis-leadership', 'Crisis leadership during a major outage', 'leadership', 'exploration', 'must', 2,
    'Ask about a severe outage they led through with incomplete information. Look for decision-making under ambiguity.',
    'Probe: "Give a one-sentence summary of each decision point" — tests executive communication under fire.',
    'Multi-team, high-stakes outages with real business impact expected.'],
  ['ops-transformation', 'Driving org-wide operational transformation', 'leadership', 'exploration', 'if-time', 2,
    'Ask about transforming how an org operates — DORA metrics, platform adoption, reliability standards. Look for change management.',
    'Probe what practices outlasted them and how they drove adoption across teams.'],
  ['reliability-business-impact', 'Connecting reliability investment to business metrics', 'leadership', 'exploration', 'if-time', 2,
    'Ask about a reliability investment with direct revenue, churn, or trust impact. Look for business framing.',
    'Probe: "Can you connect that reliability work to a specific business metric?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['reliability-bet-failure', 'A platform or reliability bet that didn\'t pan out', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant initiative that failed or underdelivered. Look for organizational learning.',
    'Probe systemic changes, not just personal lessons.', 'Failure questions carry more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('devops', 'behavioral', '0-2', entry, [
    'Leading SRE teams or defining error-budget policy',
    'Org-wide operational or cultural transformation',
    'Deep cloud-architecture trivia (warm-up is not technical)',
    'Cross-org influence or platform strategy',
    'Generic conflict questions without an operational context',
  ]),
  template('devops', 'behavioral', '3-6', mid, [
    'Entry-level "first on-call" framing',
    'Org-wide platform strategy or SRE org design (senior territory)',
    'Generic teamwork stories without an operational context',
    'Accepting vague "we improved reliability" without metrics',
    'Pure tool trivia instead of decision-making',
  ]),
  template('devops', 'behavioral', '7+', senior, [
    'Individual incident fixes or single automation scripts',
    'Single-tool choices without organizational context',
    'Generic leadership questions that could apply to any role',
    'Questions a mid-level SRE could answer equally well',
    'Accepting "we adopted SRE" without probing the culture change and enforcement',
  ]),
]
