import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Electronics × Behavioral × 0-2 ─────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro-build', 'Intro and something you built or broke', 'motivation', 'warm-up', 'must', 0,
    'Ask the candidate to introduce themselves and describe a circuit, board, or device they built or took apart. Look for genuine hands-on curiosity.',
    'Surface only — use to pick follow-up topics.', 'Hobby projects, labs, and internships are all expected at this level.'],
  ['motivation-electronics', 'Why electronics over pure software', 'motivation', 'warm-up', 'must', 0,
    'Ask what drew them to hardware and signals rather than pure software. Look for a pull toward physical systems.',
    'One follow-up at most — keep it warm.', 'Assess curiosity and coachability, not depth.'],
  ['hardest-bench-bug', 'Hardest bug chased on a bench or breadboard', 'problem-solving', 'exploration', 'must', 2,
    'Ask about the toughest bug they chased with a meter, scope, or logic analyzer. Look for a hypothesis-driven method, not part-swapping.',
    'Probe which instrument confirmed the cause and how they narrowed it down — not just that it was hard.',
    'Lab and project context is fine; look for measure-don\'t-guess instinct.'],
  ['datasheet-surprise', 'A part that behaved differently than the datasheet implied', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a time a component or datasheet surprised them. Look for how they reconciled theory with the bench.',
    'Probe how they figured out what was really going on and whether they trusted the data or the measurement.',
    'Reading datasheets carefully is a learned skill — reward the learning.'],
  ['firmware-hardware-handoff', 'Working across the firmware/hardware boundary', 'collaboration', 'exploration', 'must', 2,
    'Ask about a project where they worked with both the firmware and the hardware side. Look for service-mindset at the boundary.',
    'Probe how they communicated a constraint or a bug across the boundary without throwing it over the wall.'],
  ['learned-watching-senior', 'Learning debugging from a senior engineer', 'problem-solving', 'exploration', 'if-time', 1,
    'Ask about a bug they watched a senior engineer root-cause and what they took from it. Look for systemic thinking.',
    'Probe the actual diagnostic technique they absorbed, not just that it impressed them.'],
  ['deadline-pressure-junior', 'Handling a stressful deadline or demo', 'adaptability', 'exploration', 'if-time', 2,
    'Ask about a time a board or demo had to work and the pressure was on. Look for composure and asking for help.',
    'Probe escalation instinct — knowing when to pull in a senior is a strength at this level.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-build-excitement', 'What hardware problems excite you most', 'motivation', 'closing', 'must', 0,
    'Ask what kind of circuits, signals, or systems they want to work on next. Assess enthusiasm and self-awareness.',
    'Surface — wrap up warmly and note growth signals.'],
]

// ─── Electronics × Behavioral × 3-6 ─────────────────────────────────────────
const mid: CompactSlot[] = [
  ['debugging-philosophy-evolved', 'How your debugging approach matured', 'motivation', 'warm-up', 'must', 0,
    'Ask how their approach to hardware debugging changed with experience. Calibrate discipline and judgment.',
    'Surface — use to identify which deep-dives to pursue.', 'Must reflect on real boards or firmware shipped to real use.'],
  ['owned-board-to-production', 'Owning a board or subsystem to production', 'ownership', 'exploration', 'must', 2,
    'Ask about a board, subsystem, or firmware module they owned from bring-up into production. Look for end-to-end ownership.',
    'Probe what went wrong, the respin or rework decision, and what they would do differently.',
    'Should own the artifact, not just contribute — expect bring-up and field context.'],
  ['rootcaused-intermittent', 'Root-causing an intermittent failure', 'problem-solving', 'exploration', 'must', 2,
    'Ask about an intermittent hardware or firmware failure they root-caused. Look for a reproducible method.',
    'Probe how they made an intermittent bug reproducible — temperature, timing, supply, marginality — not part-swapping.',
    'Reproducing the intermittent failure reliably is the key differentiator here.'],
  ['pushed-back-with-data', 'Pushing back on a spec or layout decision with data', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about a time they pushed back on a layout, spec, or component choice using measurement or analysis. Look for evidence-based influence.',
    'Probe what data won the argument — SI plots, thermal numbers, EMC margins, yield.',
    'Measurable framing differentiates at this level over "I had a bad feeling".'],
  ['emc-compliance-surprise', 'An EMC, thermal, or compliance surprise', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a late-stage surprise — failing EMC, thermal, or a compliance test. Look for systematic recovery under pressure.',
    'Probe how they diagnosed it and whether the fix was a respin, a filter, a shield, or a firmware mitigation.'],
  ['cross-discipline-friction', 'Friction across EE/firmware/mechanical', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about friction with the firmware, mechanical, or manufacturing side over a design call. Look for influence without authority.',
    'Probe how they aligned on a shared goal rather than defending their own subsystem.'],
  ['schedule-vs-quality', 'A schedule-vs-quality tradeoff on hardware', 'ownership', 'exploration', 'if-time', 2,
    'Ask about a time they had to trade thoroughness for schedule on a board or release. Look for judgment, not corner-cutting.',
    'Probe what risk they accepted, how they bounded it, and whether it came back to bite them.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retrospective-design-decision', 'A design decision you\'d make differently', 'self-awareness', 'closing', 'must', 0,
    'Ask what they\'d change knowing what they know now. Assess intellectual honesty and growth.',
    'Surface — one example suffices; wrap up warmly.'],
]

// ─── Electronics × Behavioral × 7+ ──────────────────────────────────────────
const senior: CompactSlot[] = [
  ['hardware-leadership-philosophy', 'Hardware engineering as a leadership discipline', 'leadership', 'warm-up', 'must', 0,
    'Ask how they connect board/silicon work to product and business outcomes. Look for multi-dimensional leadership thinking.',
    'Surface — calibrate scope and identify which leadership dimensions to probe.',
    'Must show impact across technical, people, process, and product dimensions.'],
  ['respin-vs-rework-call', 'Making a respin-vs-rework call under pressure', 'technical-depth', 'exploration', 'must', 2,
    'Ask about a respin-versus-rework-versus-slip decision they owned under schedule pressure. Look for risk framing.',
    'Probe how they quantified the risk and communicated it to stakeholders and program management.',
    'Real cost and schedule stakes expected — not a hypothetical.'],
  ['raised-debug-standard', 'Raising the debugging / design-review standard', 'leadership', 'exploration', 'must', 2,
    'Ask about driving a higher debugging or design-review standard across a team. Look for changing how people work, not a single review.',
    'Probe the resistance they faced and which practices outlasted them.',
    'Scope must span a team or product line — not one engineer\'s habit.'],
  ['field-failure-ownership', 'Owning a field failure or recall', 'ownership', 'exploration', 'must', 2,
    'Ask about a failure that reached customers or the field. Look for end-to-end ownership through root cause and corrective action.',
    'Probe the 8D / root-cause process and what systemic change prevented recurrence — not just the patch.',
    'High-stakes, customer-facing failures with real business impact expected.'],
  ['mentored-debugging', 'Mentoring engineers on instrumentation and debugging', 'leadership', 'exploration', 'must', 2,
    'Ask how they have grown junior engineers\' debugging and bench skills. Look for deliberate mentoring, not osmosis.',
    'Probe a specific engineer they leveled up and how they taught measure-don\'t-guess.'],
  ['dfm-reliability-strategy', 'Driving design-for-manufacturability and reliability', 'strategic-thinking', 'exploration', 'if-time', 2,
    'Ask about building DFM, reliability, or test strategy into a product line up front. Look for systemic change management.',
    'Probe what practices outlasted them and how yield or field-return rate improved.'],
  ['reliability-business-impact', 'Connecting hardware quality to business metrics', 'leadership', 'exploration', 'if-time', 2,
    'Ask about a hardware-quality or reliability investment with direct cost, warranty, or trust impact. Look for business framing.',
    'Probe: "Can you connect that to a specific business metric — warranty cost, field-return rate, yield?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['design-bet-failure', 'A design or architecture bet that didn\'t pan out', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant hardware or architecture bet that failed or underdelivered. Look for organizational learning.',
    'Probe systemic changes, not just personal lessons.', 'Failure questions carry more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('electronics', 'behavioral', '0-2', entry, [
    'Owning a product line or making respin-vs-rework calls',
    'Setting team-wide design-review or DFM standards',
    'Deep circuit-analysis or transfer-function derivation (warm-up is not technical)',
    'Cross-discipline organizational influence',
    'Generic conflict questions without a hardware context',
  ]),
  template('electronics', 'behavioral', '3-6', mid, [
    'Entry-level "first time on a bench" framing',
    'Org-wide reliability strategy or design-review culture (senior territory)',
    'Generic teamwork stories without a hardware or firmware context',
    'Accepting vague "we fixed the board" without root cause or measurement',
    'Pure component trivia instead of decision-making',
  ]),
  template('electronics', 'behavioral', '7+', senior, [
    'Individual bench-debug stories without systemic or team scope',
    'Single-part or single-board choices without product-line context',
    'Generic leadership questions that could apply to any role',
    'Questions a mid-level engineer could answer equally well',
    'Accepting "we improved quality" without probing the standard and enforcement',
  ]),
]
