import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Electrical × Technical × 0-2 ───────────────────────────────────────────
const entry: CompactSlot[] = [
  ['ee-background', 'Electrical background and interests', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask the candidate to describe their electrical background and which areas excite them (analog, power, control, embedded).',
    'Surface only — calibrate scope; no deep probing yet.', 'Foundational reasoning and learning ability matter more than depth.'],
  ['analysis-approach', 'Approaching an unfamiliar circuit', 'problem-solving', 'warm-up', 'must', 0,
    'Ask how they start analyzing a circuit they have not seen before. Look for methodical setup (label nodes, pick a law).',
    'Surface — note whether they state assumptions before computing.'],
  ['circuit-analysis-basics', 'Core circuit analysis (KVL/KCL/Ohm)', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to analyze a simple two-loop or node circuit and explain which law they reach for and why.',
    'Probe how they\'d sanity-check the result — units, limiting cases, order of magnitude.',
    'Conceptual clarity and correct method over speed; accept reasoning aloud.'],
  ['ac-power-fundamentals', 'AC power: RMS and power factor', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to explain RMS, real vs reactive power, and power factor in plain terms. Look for physical intuition.',
    'Probe why a facility would correct power factor and what it costs them not to.',
    'Conceptual understanding expected; light numerical reasoning is a bonus.'],
  ['components-behavior', 'Real component behavior (R/L/C, diode, transistor)', 'technical-depth', 'exploration', 'must', 2,
    'Ask how a capacitor or inductor behaves in a transient, or how a diode/transistor acts as a switch. Look for physical reasoning.',
    'Probe the gap between the ideal model and a real part — ESR, leakage, saturation.'],
  ['measurement-method', 'Using bench instruments to debug', 'problem-solving', 'exploration', 'if-time', 1,
    'Ask how they\'d use a scope, meter, or supply to find a problem on a board. Look for a deliberate measurement plan.',
    'Surface probe — assess whether they measure before swapping parts.'],
  ['explain-to-nontechnical', 'Explaining an electrical concept simply', 'communication', 'exploration', 'if-time', 2,
    'Ask them to explain an electrical concept (grounding, impedance, AC vs DC) to a non-technical person.',
    'Probe the analogy they use and whether it stays physically honest.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-ee-curiosity', 'Electrical curiosity and growth direction', 'self-awareness', 'closing', 'must', 0,
    'Ask which electrical topic they are most curious about right now and how they are pursuing it.',
    'Surface — wrap up warmly; assess genuine enthusiasm.'],
]

// ─── Electrical × Technical × 3-6 ───────────────────────────────────────────
const mid: CompactSlot[] = [
  ['system-walkthrough', 'Walk through an electrical system you built', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask candidate to walk through a board or system they designed. Calibrate scope and architectural awareness.',
    'Surface — listen for how subsystems interact, not every component value.', 'Must show end-to-end ownership from schematic to working hardware.'],
  ['key-design-decision', 'A key electrical design decision', 'problem-solving', 'warm-up', 'must', 0,
    'Ask about a significant design decision they drove (topology, protection, layout). Calibrate trade-off reasoning.',
    'Surface — pick the most interesting decision for deeper follow-up.'],
  ['power-system-sizing', 'Sizing conductors and protection', 'technical-depth', 'exploration', 'must', 2,
    'Give a load current and cable run; ask them to size the conductor and select overcurrent protection.',
    'Probe voltage drop, thermal/derating factors, and which standards apply (NEC/IEC).',
    'Explicit derating and protection coordination is the key differentiator here.'],
  ['control-loop-stability', 'Reading a Bode plot and compensating', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they read stability from an open-loop Bode plot and how they\'d compensate for a target phase margin.',
    'Probe the compensator choice and the trade-off it introduces (bandwidth vs margin).',
    'Look for physical intuition behind gain/phase margin, not just memorized rules.'],
  ['converter-topology', 'Choosing a power converter topology', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they\'d pick between buck/boost/flyback (or similar) for a given spec. Look for spec-driven reasoning.',
    'Probe efficiency, isolation, EMI, and thermal considerations behind the choice.'],
  ['thermal-emi-awareness', 'Thermal and EMI considerations', 'technical-breadth', 'exploration', 'if-time', 2,
    'Ask how they accounted for heat and EMI in a real design. Look for awareness beyond the schematic.',
    'Probe a specific thermal or noise problem they hit and how they solved it.'],
  ['board-debug-systematic', 'Debugging a misbehaving board systematically', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about isolating a hard hardware fault. Look for systematic narrowing rather than random part swaps.',
    'Probe what they measured, what the true root cause was, and how they confirmed it.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-knowledge-sharing', 'Sharing electrical knowledge and growth', 'leadership', 'closing', 'must', 0,
    'Ask how they help less experienced engineers learn hardware design and debug.',
    'Surface — one example suffices; assess investment in others.'],
]

// ─── Electrical × Technical × 7+ ────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['ee-strategy', 'Electrical architecture and product alignment', 'leadership', 'warm-up', 'must', 0,
    'Ask how they aligned a major electrical architecture decision with cost, reliability, and product goals. Calibrate strategic scope.',
    'Surface — listen for product vocabulary alongside technical rationale.', 'Direction-setting distinguishes senior from mid-level.'],
  ['architecture-vision', 'Power/control architecture vision', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask about a power or control architecture they authored for a product or platform. Calibrate planning horizon.',
    'Surface — note how they balanced performance, cost, and manufacturability.'],
  ['power-system-architecture', 'Architecting power distribution and protection', 'technical-breadth', 'exploration', 'must', 2,
    'Ask how they\'d architect distribution and protection for a mixed AC/DC system, including grounding and fault coordination.',
    'Probe fault scenarios, selectivity, and reliability margins.',
    'Must reason about fault coordination and grounding, not just nominal operation.'],
  ['power-electronics-scale', 'Power electronics at scale (second-order effects)', 'technical-depth', 'exploration', 'must', 2,
    'Ask about an isolated converter or motor drive at meaningful power and the second-order issues that bite at scale.',
    'Probe efficiency, EMI, thermal, and parasitic-driven failure modes.',
    'Anticipating parasitics, saturation, and thermal runaway is the right depth.'],
  ['reliability-derating', 'Designing for reliability and derating', 'technical-breadth', 'exploration', 'must', 2,
    'Ask how they embed reliability into a design — derating, worst-case analysis, tolerance stack-up, field margins.',
    'Probe a specific failure mode they designed out and how they verified the margin.'],
  ['topology-tradeoff-org', 'Driving a contentious topology or standards trade-off', 'leadership', 'exploration', 'if-time', 2,
    'Ask about a contested architecture or standards decision across teams. Look for data-driven consensus.',
    'Probe who opposed it, what data settled it, and how dissent was incorporated.'],
  ['machines-grid-reasoning', 'Electrical machines or grid-interaction reasoning', 'technical-breadth', 'exploration', 'if-time', 2,
    'Ask about a problem involving motors, generators, or grid interaction (harmonics, inrush, power quality).',
    'Probe how they reasoned from machine fundamentals to a system-level fix.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-legacy', 'Electrical legacy and leadership impact', 'leadership', 'closing', 'must', 0,
    'Ask what electrical or organizational legacy they are most proud of and what they hope to build here.',
    'Surface — connect their arc to the role.', 'Inability to articulate an electrical vision is a red flag at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('electrical', 'technical', '0-2', entry, [
    'Power-system fault coordination or grid-interaction analysis',
    'Cross-team electrical architecture decisions',
    'Advanced power-electronics or control-theory derivations',
    'Product-level reliability or standards strategy',
    'Deep specialization in any one sub-area (power, analog, or control)',
  ]),
  template('electrical', 'technical', '3-6', mid, [
    'Product-line electrical architecture strategy',
    'Executive-level cost or reliability communication',
    'Team hiring or org-design decisions',
    'Pure closed-book formula derivations with no design context',
    'Defaulting to "it depends" without committing to a trade-off',
  ]),
  template('electrical', 'technical', '7+', senior, [
    'Basic KVL/KCL or single-component analysis questions',
    'Individual board debugging without systemic context',
    'Design decisions with only board-level scope',
    'Questions a mid-level EE could answer equally well',
    'Clever circuit tricks without product or reliability context',
  ]),
]
