import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Electronics × Technical × 0-2 ──────────────────────────────────────────
const entry: CompactSlot[] = [
  ['technical-background-ece', 'Technical background and interests', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask the candidate to describe their background and which area — analog, digital, comms, embedded — excites them most.',
    'Surface only — calibrate scope; no deep probing yet.', 'First-principles reasoning matters more than breadth at this level.'],
  ['favorite-circuit', 'A circuit or project they understand deeply', 'problem-solving', 'warm-up', 'must', 0,
    'Ask them to walk through a circuit or project they understand well. Look for the ability to reason about what each part does.',
    'Surface — pick the most promising area for deeper follow-up.'],
  ['opamp-fundamentals', 'Op-amp / analog fundamentals', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to explain a basic op-amp configuration (inverting/non-inverting). Look for what sets the gain and what limits the ideal model.',
    'Probe what happens at the rails, with finite gain-bandwidth, or under load — not just the ideal formula.',
    'Conceptual clarity over encyclopedic coverage; reward physical intuition.'],
  ['sampling-aliasing', 'Sampling and aliasing', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to explain sampling and aliasing and how to prevent it. Look for Nyquist intuition, not just the theorem statement.',
    'Probe how they would choose an anti-alias filter and sample rate for a real signal.',
    'Reward the ability to connect the math to a real sensor or audio example.'],
  ['digital-logic-timing', 'Basic digital logic and timing', 'technical-depth', 'exploration', 'must', 2,
    'Ask a basic digital-logic or timing question (e.g., what setup/hold means, or designing simple combinational/sequential logic).',
    'Probe whether they understand why timing matters, not just how to draw a gate.',
    'Limited-scope coursework or project context is expected and fine.'],
  ['microcontroller-experience', 'A microcontroller they have actually programmed', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask about a microcontroller project they built. Look for hands-on understanding of GPIO, ADC, or a bus like I2C/SPI/UART.',
    'Surface probe — assess whether they understand the peripheral or just copied example code.'],
  ['debugging-on-hardware', 'Debugging a circuit on the bench', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a time a circuit did not work and how they debugged it. Look for systematic, measurement-driven method.',
    'Probe the actual diagnostic steps and which instrument they reached for, not just the fix.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-curiosity-ece', 'Technical curiosity and growth direction', 'self-awareness', 'closing', 'must', 0,
    'Ask which area of electronics or communications they most want to go deeper on and how they are pursuing it.',
    'Surface — wrap up warmly; assess genuine enthusiasm.'],
]

// ─── Electronics × Technical × 3-6 ──────────────────────────────────────────
const mid: CompactSlot[] = [
  ['system-walkthrough-ece', 'Walk through a system you designed', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask the candidate to walk through a board, link, or embedded system they designed. Calibrate scope and design judgment.',
    'Surface — listen for how blocks interact, not every component value.', 'Must show end-to-end ownership and system-level thinking.'],
  ['key-design-decision-ece', 'A key analog or design decision', 'problem-solving', 'warm-up', 'must', 0,
    'Ask about a significant design decision they drove (topology, modulation, partitioning). Calibrate tradeoff reasoning.',
    'Surface — pick the most interesting decision for deeper follow-up.'],
  ['filter-feedback-design', 'Filter and feedback-stability design', 'technical-depth', 'exploration', 'must', 2,
    'Probe a filter or feedback design decision — order, topology, phase margin. Look for real tradeoff reasoning.',
    'Probe passive vs active, stopband vs phase, and how they ensured stability or avoided ringing.',
    'Explicit tradeoff discussion is the key differentiator at this level.'],
  ['digital-timing-cdc', 'Digital timing and clock-domain crossing', 'technical-depth', 'exploration', 'must', 2,
    'Ask about setup/hold, metastability, and crossing clock domains. Look for synchronizer design, not luck.',
    'Probe how they handled a real CDC bug or designed a synchronizer / FIFO across domains.'],
  ['modulation-link-budget', 'A modulation scheme and link reasoning', 'technical-depth', 'exploration', 'must', 2,
    'Ask about a modulation scheme they worked with end-to-end and how they reason about SNR, BER, or link budget.',
    'Probe why that scheme, how noise/ISI affected it, and what they did about it.',
    'Reward fluency moving between the spec, the math, and the measured result.'],
  ['embedded-peripherals', 'Embedded peripherals and real-time constraints', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about interrupts, DMA, or bus protocols (I2C/SPI/UART) in a shipped system. Look for real-time and concurrency awareness.',
    'Probe a timing or contention bug they hit and how interrupt priority, DMA, or buffering resolved it.'],
  ['mixed-signal-debug', 'Debugging a mixed-signal or noise issue', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a noise, ground, or mixed-signal problem they root-caused. Look for systematic, instrument-driven diagnosis.',
    'Probe how they isolated it — grounding, decoupling, layout, shielding — and confirmed the fix on the scope.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-mentoring-ece', 'Technical mentoring and growth', 'leadership', 'closing', 'must', 0,
    'Ask how they help less experienced engineers build circuit and debugging intuition.',
    'Surface — one example suffices; assess investment in others.'],
]

// ─── Electronics × Technical × 7+ ───────────────────────────────────────────
const senior: CompactSlot[] = [
  ['architecture-strategy-ece', 'System architecture and product alignment', 'leadership', 'warm-up', 'must', 0,
    'Ask how they have aligned a hardware or radio architecture with product and cost goals. Calibrate strategic scope.',
    'Surface — listen for product and cost vocabulary alongside the technical rationale.', 'Direction-setting distinguishes senior from mid-level.'],
  ['link-radio-architecture', 'Architecting a communication link or radio chain', 'technical-depth', 'warm-up', 'must', 0,
    'Ask about a receive/transmit chain or link they architected, antenna to bits. Calibrate system-level fluency.',
    'Surface — note how they reason about link budget, sensitivity, and the partition between analog and DSP.'],
  ['signal-power-integrity', 'Signal integrity and power integrity', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they approach SI/PI on a high-speed board. Look for termination, return-path, and decoupling strategy.',
    'Probe a real SI/PI problem they solved and how they used simulation and TDR/scope measurement to confirm it.',
    'Must show a repeatable methodology, not a one-off fix.'],
  ['analog-digital-dsp-tradeoff', 'Choosing analog vs digital vs DSP', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a problem they could solve in analog, digital, or DSP, and how they chose. Look for principled partitioning.',
    'Probe the cost, power, accuracy, and risk tradeoffs that drove the decision and what they would change.'],
  ['dft-dfm-strategy', 'Design-for-test and design-for-manufacturability', 'technical-breadth', 'exploration', 'must', 2,
    'Ask how they have embedded test and manufacturability into a design. Look for yield, coverage, and field-reliability thinking.',
    'Probe specific DFT/DFM choices (test points, BIST, tolerancing) and how they balanced them against cost and schedule.'],
  ['low-power-strategy', 'Low-power and power-integrity strategy', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how they approached a tight power or thermal budget. Look for a systematic, measured approach.',
    'Probe how they quantified consumption and where the wins came from — clock gating, supply design, duty cycling.'],
  ['cross-team-hw-influence', 'Cross-discipline technical influence', 'leadership', 'exploration', 'if-time', 2,
    'Ask about building consensus on a contentious hardware decision across EE, firmware, mechanical, and manufacturing.',
    'Probe who opposed, what data settled it, and how dissent was incorporated.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-legacy-ece', 'Technical legacy and leadership impact', 'leadership', 'closing', 'must', 0,
    'Ask what hardware or technical legacy they are most proud of and what they hope to build here.',
    'Surface — connect their arc to the role.', 'Inability to articulate a technical vision is a red flag at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('electronics', 'technical', '0-2', entry, [
    'Signal-integrity or RF board architecture',
    'Cross-discipline or organizational design decisions',
    'Advanced communication-systems architecture (link budget, multi-path)',
    'VLSI tape-out or static-timing-closure depth',
    'Deep specialization in any one subsystem',
  ]),
  template('electronics', 'technical', '3-6', mid, [
    'Organizational hardware or radio strategy',
    'Board or executive-level program communication',
    'Team hiring or org-design decisions',
    'Pure textbook derivations with no hardware grounding',
    'Defaulting to "it depends" without committing to a tradeoff',
  ]),
  template('electronics', 'technical', '7+', senior, [
    'Basic op-amp or single-gate timing questions',
    'Individual bench-debug stories without architectural context',
    'Component or topology choices with only board-level scope',
    'Questions a mid-level engineer could answer equally well',
    'Clever circuit tricks without product, cost, or org context',
  ]),
]
