import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Electrical × Behavioral × 0-2 ──────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro-hardware', 'Intro and a hardware project you\'re proud of', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves and describe a circuit, board, or system they built. Look for genuine pride in making hardware work.',
    'Surface only — use to pick follow-up topics.', 'Capstone, internship, and personal projects are all expected at this level.'],
  ['motivation-ee', 'Why electrical engineering and hardware', 'motivation', 'warm-up', 'must', 0,
    'Ask what drew them to electrical engineering over software. Look for curiosity about how physical systems work.',
    'One follow-up at most — keep it warm.', 'Assess engineering mindset and coachability, not depth.'],
  ['board-didnt-work', 'A board or circuit that didn\'t work the first time', 'problem-solving', 'exploration', 'must', 2,
    'Ask about hardware that failed to work and how they diagnosed it. Look for methodical measurement, not guessing.',
    'Probe what they measured and what the actual root cause was — not just that it eventually worked.',
    'Coursework, capstone, and internship debugging stories are expected.'],
  ['lab-safety', 'Following a safety procedure in the lab', 'ownership', 'exploration', 'must', 2,
    'Ask about a time they followed lab safety or lock-out/tag-out even when it was inconvenient. Look for genuine respect for risk.',
    'Probe what could have gone wrong without the procedure — arc, shock, equipment damage.',
    'Awareness and instinct matter more than incident scale at this level.'],
  ['asked-for-help', 'Knowing when to ask before energizing', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a time they paused to ask a senior engineer before powering something up. Look for sound escalation instinct.',
    'Probe how they knew to stop and what they learned from the answer.',
    'Asking for help is a strength here, not a weakness.'],
  ['working-with-mech-fw', 'Working with mechanical or firmware on a project', 'collaboration', 'exploration', 'if-time', 1,
    'Ask about coordinating with a mechanical or firmware teammate on a shared design. Look for communication and service-mindset.',
    'Probe how they handled the interface or handoff between disciplines.'],
  ['hardware-pressure-junior', 'Handling a stressful bench or bring-up moment', 'adaptability', 'exploration', 'if-time', 2,
    'Ask about a time bring-up or a demo was going badly and they felt the pressure. Look for composure and asking for help.',
    'Probe how they stayed methodical instead of randomly swapping parts.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-hardware-excitement', 'What electrical problems excite you most', 'motivation', 'closing', 'must', 0,
    'Ask what kind of circuits, power, or control problems they want to tackle next. Assess enthusiasm and self-awareness.',
    'Surface — wrap up warmly and note growth signals.'],
]

// ─── Electrical × Behavioral × 3-6 ──────────────────────────────────────────
const mid: CompactSlot[] = [
  ['design-philosophy-evolution', 'How your view of robust design evolved', 'motivation', 'warm-up', 'must', 0,
    'Ask how their thinking on building reliable hardware changed with field experience. Calibrate engineering judgment.',
    'Surface — use to identify which deep-dives to pursue.', 'Must reflect on real hardware that shipped or was deployed.'],
  ['owned-subsystem', 'Owning a subsystem from schematic to production', 'ownership', 'exploration', 'must', 2,
    'Ask about a power stage, control loop, or board they owned end to end. Look for accountability through bring-up and field issues.',
    'Probe the hardest failure, the root cause, and what they changed in the design or process.',
    'Should own the design, not just assist — expect schematic-to-field ownership.'],
  ['cross-discipline-fix', 'Coordinating across mechanical/firmware/manufacturing', 'collaboration', 'exploration', 'must', 2,
    'Ask about a problem that required aligning with another discipline to resolve. Look for influence without authority.',
    'Probe where the interface broke down and how they aligned on the fix.',
    'Real cross-team friction resolved by data and shared goals differentiates here.'],
  ['field-failure', 'Debugging a failure in the field', 'problem-solving', 'exploration', 'must', 2,
    'Ask about hardware that failed after deployment and how they tracked it down. Look for systematic root-cause analysis.',
    'Probe how they reproduced it, what the true cause was, and how they prevented recurrence.',
    'Expect ownership of the root cause, not blaming the spec or manufacturing.'],
  ['raised-safety-concern', 'Escalating a safety or reliability concern', 'ownership', 'exploration', 'if-time', 2,
    'Ask about a time they flagged a safety or reliability risk against schedule pressure. Look for courage and framing.',
    'Probe how they made the case and what happened — did the concern hold up?'],
  ['defended-design-decision', 'Defending a design decision under pressure', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a contested electrical decision they made under cost or schedule pressure. Look for data-backed reasoning.',
    'Probe the trade-off they accepted and how it played out in the field.'],
  ['design-review-improvement', 'Improving design-review or documentation discipline', 'ownership', 'exploration', 'if-time', 2,
    'Ask about an initiative to improve reviews, documentation, or test coverage. Look for raising the bar beyond themselves.',
    'Probe how they got the team to adopt it and whether it actually caught issues.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retrospective-design-decision', 'A design decision you\'d make differently', 'self-awareness', 'closing', 'must', 0,
    'Ask what they\'d change knowing what they know now. Assess intellectual honesty and growth.',
    'Surface — one example suffices; wrap up warmly.'],
]

// ─── Electrical × Behavioral × 7+ ───────────────────────────────────────────
const senior: CompactSlot[] = [
  ['ee-strategic-discipline', 'Electrical engineering as a product discipline', 'leadership', 'warm-up', 'must', 0,
    'Ask how they connect electrical architecture to cost, reliability, and product outcomes. Look for multi-dimensional leadership thinking.',
    'Surface — calibrate scope and identify which leadership dimensions to probe.',
    'Must show impact across technical, people, process, and product dimensions.'],
  ['safety-culture-org', 'Raising safety and design-review culture across a team', 'ownership', 'exploration', 'must', 2,
    'Ask about driving safety or review discipline across a team or product line. Look for changing how engineers work, not a one-off rule.',
    'Probe the resistance they faced and how the change outlasted them.',
    'Scope must span a team or product line — not one personal habit.'],
  ['led-electrical-architecture', 'Owning a product line\'s electrical architecture', 'leadership', 'exploration', 'must', 2,
    'Ask about owning the electrical architecture of a product or platform. Look for systems thinking and long-horizon decisions.',
    'Probe how they balanced performance, cost, manufacturability, and field reliability.',
    'Multiplier impact across a product family is the right scope here.'],
  ['hard-engineering-call', 'A difficult electrical call under real constraints', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a high-stakes design decision made under cost, schedule, or reliability pressure. Look for judgment under ambiguity.',
    'Probe the trade-off, the risk they accepted, and the field outcome.',
    'High-stakes decisions with real business and reliability impact expected.'],
  ['field-reliability-crisis', 'Leading through a field-reliability crisis', 'leadership', 'exploration', 'must', 2,
    'Ask about a serious field failure or recall-level issue they led the response to. Look for decision-making with incomplete data.',
    'Probe: "Summarize each decision point in one sentence" — tests communication under fire.',
    'Multi-team, high-stakes failures with real customer impact expected.'],
  ['mentoring-ee-team', 'Growing junior electrical engineers', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they have developed junior EEs or raised the team\'s technical bar. Look for deliberate investment in others.',
    'Probe a specific engineer they grew and how they did it.'],
  ['standards-compliance-leadership', 'Driving standards or compliance across a product', 'leadership', 'exploration', 'if-time', 2,
    'Ask about leading a product through certification or standards compliance (UL, IEC, NEC, IPC). Look for systematic ownership.',
    'Probe how they planned for compliance early rather than retrofitting it.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['design-bet-failure', 'An architectural or technology bet that didn\'t pan out', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant electrical or architecture bet that failed or underdelivered. Look for organizational learning.',
    'Probe systemic changes, not just personal lessons.', 'Failure questions carry more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('electrical', 'behavioral', '0-2', entry, [
    'Owning a product line\'s electrical architecture or standards strategy',
    'Org-wide safety-culture or design-review transformation',
    'Deep circuit-analysis or control-theory quizzing (this is behavioral)',
    'Cross-org influence or product-level trade-off ownership',
    'Generic conflict questions without a hardware or safety context',
  ]),
  template('electrical', 'behavioral', '3-6', mid, [
    'Entry-level "first board that didn\'t work" framing',
    'Product-line architecture or org-wide safety strategy (senior territory)',
    'Generic teamwork stories without a hardware or cross-discipline context',
    'Accepting vague "we improved reliability" without root cause or metrics',
    'Pure circuit-theory quizzing instead of decision-making',
  ]),
  template('electrical', 'behavioral', '7+', senior, [
    'Individual board debugs or single-component choices',
    'Single design decisions without product or organizational context',
    'Generic leadership questions that could apply to any role',
    'Questions a mid-level EE could answer equally well',
    'Accepting "we improved safety" without probing the culture change and enforcement',
  ]),
]
