import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Finance × Behavioral × 0-2 ─────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro-finance', 'Intro and a financial analysis you\'re proud of', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves and an analysis that influenced a decision. Look for genuine interest in the numbers.',
    'Surface — use to pick follow-up topics.', 'Coursework, internships, and case competitions are all acceptable.'],
  ['motivation-finance', 'Why finance, and which area', 'motivation', 'warm-up', 'must', 0,
    'Ask what drew them to finance and which area excites them. Calibrate direction and curiosity.',
    'One follow-up at most — keep it warm.', 'Assess analytical orientation, not depth.'],
  ['delivering-bad-news', 'Delivering unfavorable financial news', 'communication', 'exploration', 'must', 2,
    'Ask about a time they had to present bad numbers to a stakeholder. Look for honesty and composure.',
    'Probe how they framed it and how the audience reacted — not just that it was hard.',
    'Small-scope stakeholder updates count at this level.'],
  ['spotted-a-risk', 'Identifying a financial risk others missed', 'analytical', 'exploration', 'must', 2,
    'Ask about catching a risk or error others overlooked. Look for diligence and escalation instinct.',
    'Probe how they validated it and who they raised it with.'],
  ['integrity-precision', 'Precision and integrity under pressure', 'ownership', 'exploration', 'must', 2,
    'Ask about a time accuracy mattered and they were under time or business pressure. Look for refusal to cut corners.',
    'Probe what they did when speed and correctness conflicted.'],
  ['communicating-numbers', 'Explaining numbers to a non-finance audience', 'communication', 'exploration', 'if-time', 1,
    'Ask about making financial information understandable to non-finance stakeholders. Look for clarity.',
    'Probe how they simplified without distorting.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-finance-excitement', 'What financial problems excite you most', 'motivation', 'closing', 'must', 0,
    'Ask what kind of financial problems they want to work on next. Assess enthusiasm and direction.',
    'Surface — wrap up warmly.'],
]

// ─── Finance × Behavioral × 3-6 ─────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['finance-career-evolution', 'How your finance focus evolved', 'motivation', 'warm-up', 'must', 0,
    'Ask how their specialization and judgment developed with experience. Calibrate maturity.',
    'Surface — use to choose deep-dives.', 'Must reflect on real work with real financial stakes.'],
  ['budget-conflict', 'Navigating budget conflicts between departments', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about mediating competing budget demands. Look for principled, data-grounded resolution.',
    'Probe how they kept it objective and what won alignment.',
    'Expect ownership of the outcome, not just attendance.'],
  ['ethical-dilemma-reporting', 'An ethical dilemma in financial reporting', 'ownership', 'exploration', 'must', 2,
    'Ask about pressure to present numbers in a misleading way. Look for backbone and a principled path.',
    'Probe exactly what the pressure was and how they held the line.',
    'The hard part is what they did when it was costly to be right.'],
  ['influence-via-insight', 'Influencing a business decision through financial insight', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about changing a business decision with analysis. Look for translating numbers into a recommendation.',
    'Probe the insight, how they framed it, and the outcome.'],
  ['difficult-findings', 'Presenting difficult findings to leadership', 'communication', 'exploration', 'if-time', 2,
    'Ask about delivering an unwelcome conclusion to senior leaders. Look for clarity and conviction.',
    'Probe how they handled pushback.'],
  ['forecast-miss', 'A forecast that was wrong and what changed', 'self-awareness', 'exploration', 'if-time', 2,
    'Ask about a significant forecast miss. Look for honesty and concrete process change.',
    'Probe what they changed in their method afterward.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retrospective-finance-decision', 'A financial call you\'d make differently', 'self-awareness', 'closing', 'must', 0,
    'Ask what they\'d reconsider now. Assess intellectual honesty.',
    'Surface — one example suffices.'],
]

// ─── Finance × Behavioral × 7+ ──────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['finance-leadership-philosophy', 'Finance leadership philosophy', 'leadership', 'warm-up', 'must', 0,
    'Ask how they see finance\'s role in strategy and how they lead a finance org. Calibrate scope.',
    'Surface — identify which leadership dimensions to probe.', 'Must show impact across decisions, people, and culture.'],
  ['audit-regulatory-leadership', 'Leading through an audit or regulatory challenge', 'leadership', 'exploration', 'must', 2,
    'Ask about leading a team through a major audit or regulatory event. Look for composure and process improvement.',
    'Probe what they changed structurally afterward.',
    'Multi-stakeholder, high-stakes scope expected.'],
  ['executive-board-influence', 'Influencing a CEO or board against resistance', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about moving an executive or board on a financial strategy they resisted. Look for data plus narrative.',
    'Probe how they framed the argument and built the coalition.',
    'Board-level influence is the right scope.'],
  ['integrity-culture', 'Building a finance culture around integrity', 'leadership', 'exploration', 'must', 2,
    'Ask about embedding integrity and rigor into a finance team. Look for systems, not slogans.',
    'Probe what concretely held when the team was under pressure.'],
  ['financial-crisis-leadership', 'Leading through financial uncertainty / crisis', 'leadership', 'exploration', 'if-time', 2,
    'Ask about steering through a downturn, liquidity crunch, or major write-down. Look for decisiveness under ambiguity.',
    'Probe the hardest tradeoff and how they communicated it.'],
  ['board-communication', 'Board-level financial communication', 'communication', 'exploration', 'if-time', 2,
    'Ask about communicating complex financial reality to a board. Look for executive clarity and candor.',
    'Probe how they handled a tough question they couldn\'t fully answer yet.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['finance-bet-failure', 'A financial strategy that didn\'t pan out', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant strategy that underdelivered. Look for organizational learning.',
    'Probe systemic changes, not just personal lessons.', 'Failure carries more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('finance', 'behavioral', '0-2', entry, [
    'Leading audits, boards, or finance orgs',
    'Building team culture or org-wide integrity programs',
    'Technical valuation or modeling exercises',
    'Executive/board influence scenarios',
    'Generic conflict questions without a financial context',
  ]),
  template('finance', 'behavioral', '3-6', mid, [
    'Entry-level "why finance" framing',
    'Board-level or finance-org leadership (senior territory)',
    'Generic teamwork stories without a financial context',
    'Accepting "the numbers were off" without probing integrity and process',
    'Pure modeling questions instead of judgment',
  ]),
  template('finance', 'behavioral', '7+', senior, [
    'Individual analysis tasks or single reports',
    'Questions a mid-level analyst could answer equally well',
    'Generic leadership questions with no financial stakes',
    'Accepting "we managed the audit" without probing the structural change',
  ]),
]
