import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Frontend × Technical × 0-2 ────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['html-css-background', 'HTML and CSS background', 'ux-engineering', 'warm-up', 'must', 0,
    'Ask about HTML/CSS work — semantic elements, layouts built. Calibrate fundamentals knowledge.',
    'Surface — note framework experience for follow-up topics.', 'HTML/CSS carry equal weight to JS at this level.'],
  ['js-framework-basics', 'JavaScript and framework basics', 'technical-depth', 'warm-up', 'must', 0,
    'Ask which JS framework they use and a component they built with it. Calibrate depth.',
    'Surface — use answer to calibrate which framework questions to probe.',
    'Expect React surface-level knowledge; one framework is sufficient.'],
  ['js-core-concepts', 'JavaScript core concepts', 'technical-depth', 'exploration', 'must', 2,
    'Ask about scope, closures, event loop, and var/let/const. Look for conceptual understanding.',
    'Probe: "What does this code output and why?" — event loop or closure example.',
    'Language fundamentals differentiate bootcamp grads; framework magic is not enough.'],
  ['css-layout-challenge', 'CSS layout challenge', 'ux-engineering', 'exploration', 'must', 2,
    'Ask to center an element vertically and horizontally, or build a responsive two-column layout.',
    'Probe: "Can you solve this a different way?" — Flexbox vs. Grid vs. absolute positioning.',
    'CSS layout ability is a strong differentiator; many bootcamp grads struggle with this.'],
  ['dom-manipulation', 'DOM manipulation and events', 'technical-depth', 'exploration', 'must', 2,
    'Ask about event delegation, querySelector, or creating/removing elements dynamically.',
    'Probe: "Why event delegation instead of listeners on each element?" — performance awareness.',
    'Practical DOM skill expected before relying on framework abstractions.'],
  ['react-framework-concepts', 'React props, state, and hooks basics', 'component-architecture', 'exploration', 'if-time', 1,
    'Ask about useState/useEffect, props vs. state, and component lifecycle. Surface-level is acceptable.',
    'Probe: "What does React do with your JSX under the hood?" — understanding vs. memorization.'],
  ['basic-accessibility', 'Basic accessibility awareness', 'accessibility', 'exploration', 'if-time', 1,
    'Ask about alt attributes, form labels, heading hierarchy, and keyboard navigation.',
    'Probe: "How would you make this component accessible for screen readers?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-what-different', 'What would you do differently', 'problem-solving', 'closing', 'must', 0,
    'Ask what they\'d change about their solution or what they\'d add if they had more time.',
    'Surface — assess reflection and polish instinct.'],
]

// ─── Frontend × Technical × 3-6 ────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['advanced-js-intro', 'Advanced JS and framework internals intro', 'technical-depth', 'warm-up', 'must', 0,
    'Ask about a JS concept they use daily and genuinely understand deeply. Calibrate internals knowledge.',
    'Surface — use answer to choose which internals to probe.',
    'JS and framework internals expected: reconciliation, fiber, hooks linked list.'],
  ['js-internals-deep', 'JavaScript internals depth', 'technical-depth', 'exploration', 'must', 2,
    'Probe event loop internals: microtasks vs macrotasks, prototypal inheritance, or closures in real scenarios.',
    'Probe: "Walk me through exactly what happens when this Promise chain resolves."',
    'TypeScript generics are the dividing line between junior and mid-level.'],
  ['react-reconciliation', 'React reconciliation and hooks internals', 'technical-depth', 'exploration', 'must', 2,
    'Ask how React knows when to re-render and how the hooks linked list works.',
    'Probe: "Why can\'t hooks be called conditionally? What breaks if they are?"',
    'Must go beyond "Virtual DOM" to reconciliation, fiber, and hooks rules.'],
  ['performance-optimization', 'Frontend performance optimization', 'performance', 'exploration', 'must', 2,
    'Ask about Core Web Vitals (LCP/INP/CLS), code splitting, memoization, and bundle analysis.',
    'Probe specific numbers: "LCP under what threshold? What tool showed you this? Before/after?"',
    'Expect specific numbers (LCP < 2.5s, CLS < 0.1, INP < 200ms) and real tools.'],
  ['state-management', 'State management architecture', 'component-architecture', 'exploration', 'must', 2,
    'Ask when they\'d choose Redux vs. Zustand vs. Context+useReducer vs. React Query.',
    'Probe: "When would Context suffice? What are the downsides of Redux? What about Zustand?"',
    'Decision-making and trade-off articulation distinguish mid from junior.'],
  ['typescript-depth', 'TypeScript generics and utility types', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about generics, Partial/Pick/Omit/Record, discriminated unions, and type narrowing.',
    'Probe: "Show how you\'d type a generic API response handler for any endpoint."'],
  ['testing-strategy', 'Testing strategy and tooling', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about unit vs. component vs. E2E testing, the testing pyramid, and mocking strategies.',
    'Probe: "Most valuable test you\'ve written? A test you deleted because it provided no value?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tooling', 'Build tools and CI/CD awareness', 'technical-depth', 'closing', 'must', 0,
    'Ask how they\'d set up an ideal CI pipeline for a React app. Assess operational awareness.',
    'Surface — conceptual familiarity with Vite/Webpack and testing gates is sufficient.'],
]

// ─── Frontend × Technical × 7+ ─────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['rendering-strategy', 'Rendering strategy architecture', 'technical-depth', 'warm-up', 'must', 0,
    'Ask when they\'d choose SSR vs. CSR vs. SSG vs. ISR for a product. Look for nuanced trade-offs.',
    'Surface — calibrate depth; note which areas to probe.',
    'Architecture over implementation: designing systems other engineers build.'],
  ['design-system-tech', 'Design system technical architecture', 'component-architecture', 'exploration', 'must', 2,
    'Ask how they\'d architect a component library for 10+ teams — tokens, versioning, Storybook, governance.',
    'Probe: "Team X won\'t adopt because it doesn\'t fit their use case. What do you do?"',
    'Governance and coordination are as important as technical choices.'],
  ['micro-frontend', 'Micro-frontend architecture', 'technical-depth', 'exploration', 'must', 2,
    'Ask about Module Federation — remote entries, shared dependency negotiation, deployment independence.',
    'Probe: "Downsides of Module Federation? When would you NOT recommend micro-frontends?"',
    'Knowing when not to use a pattern is a strong senior signal.'],
  ['performance-engineering', 'Performance engineering at scale', 'performance', 'exploration', 'must', 2,
    'Ask about performance budgets in CI, 100K+ row rendering, Web Workers, and INP optimization.',
    'Probe: "Walk through your performance budget process from detection to resolution. Thresholds?"',
    'Performance is organizational engineering, not per-sprint optimization.'],
  ['advanced-typescript', 'Advanced TypeScript type system', 'technical-depth', 'exploration', 'must', 2,
    'Ask about conditional types, infer, template literal types, branded types, and satisfies.',
    'Probe: "Show me how you\'d write DeepPartial<T> or a type-safe event emitter."'],
  ['frontend-observability', 'Frontend observability and reliability', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about error tracking, RUM, Core Web Vitals dashboards, and error boundary architecture.',
    'Probe: "How would you instrument a frontend for graceful degradation at scale?"'],
  ['build-pipeline-dx', 'Build pipeline and developer experience', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about monorepo tooling (Nx, Turborepo), build time optimization, and migration between build tools.',
    'Probe: "Frontend monorepo build takes 45 min. Walk me through diagnosis and an optimization plan."'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tradeoffs', 'Trade-offs and organizational impact', 'leadership', 'closing', 'must', 0,
    'Ask how they\'d improve DX across 10 frontend teams. Assess organizational thinking.',
    'Surface — tests strategic thinking beyond individual contribution.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('frontend', 'technical', '0-2', entry, [
    'State management libraries (Redux, Zustand)',
    'Build tools, webpack configuration, CI/CD pipelines',
    'SSR, SSG, or rendering strategies',
    'TypeScript generics or advanced type system',
    'Heavy algorithm or data structure questions',
  ]),
  template('frontend', 'technical', '3-6', mid, [
    'HTML/CSS fundamentals any entry-level candidate knows',
    'Micro-frontends, design systems at scale, or build pipeline architecture',
    'Pure algorithm questions disconnected from frontend',
    'Accepting "I\'d use Redux" without probing why and the alternatives',
  ]),
  template('frontend', 'technical', '7+', senior, [
    'Entry or mid-level CSS fundamentals, basic hooks, or JS basics',
    'Pure coding challenges testing speed rather than architecture',
    'Backend system design (databases, microservices) instead of frontend',
    'Single framework questions without cross-framework thinking',
    'Not asking about organizational impact',
  ]),
]
