import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Frontend × System Design × 0-2 ────────────────────────────────────────
const entry: CompactSlot[] = [
  ['ui-decomposition', 'Component decomposition of a UI', 'component-architecture', 'warm-up', 'must', 0,
    'Present simple UI (weather app, blog post page). Ask them to break it into a component tree.',
    'Surface — probe: "Which component owns this state and why?"',
    'Component thinking, not architecture — decomposition is the goal at this level.'],
  ['state-and-props-flow', 'State and props flow', 'component-architecture', 'warm-up', 'must', 0,
    'Ask where state lives and how data flows between parent and child components.',
    'Surface — look for parent-child communication clarity, not global state libraries.',
    'Understanding props vs. state and parent-child communication is sufficient.'],
  ['data-fetching-pattern', 'Simple data fetching pattern', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they\'d fetch data from an API and show loading, error, and success states.',
    'Probe: "How show the loading spinner? How display the error message? Empty state?"',
    'No expectation of caching strategies, service workers, or advanced optimization.'],
  ['form-state-management', 'Form component with state management', 'ux-engineering', 'exploration', 'must', 2,
    'Ask about form state, controlled vs. uncontrolled inputs, and basic validation.',
    'Probe: "User clicks Add to Cart — walk through the data flow step by step."',
    'Controlled vs. uncontrolled is a practical differentiator for junior candidates.'],
  ['routing-and-layout', 'Routing and shared page layout', 'component-architecture', 'exploration', 'must', 2,
    'Ask how pages relate, how navigation works, and where shared layout components live.',
    'Probe: "How do the header and product list communicate? Who owns the cart state?"'],
  ['csr-vs-ssr-basic', 'Basic rendering strategy awareness', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask if they\'ve heard of SSR and when it might be useful. Surface-level awareness is enough.',
    'Probe: "If the app needs to rank in Google search, does anything about your design change?"'],
  ['responsiveness-basic', 'Responsive design considerations', 'ux-engineering', 'exploration', 'if-time', 1,
    'Ask what would change in their component tree design if the app needed to work on mobile.',
    'Probe: "Which components might look completely different at mobile breakpoints?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-gaps', 'What they\'d add or improve', 'problem-solving', 'closing', 'must', 0,
    'Ask what they\'d improve or add to their design given more time. Assess self-awareness.',
    'Surface — one honest observation is sufficient; wrap up warmly.'],
]

// ─── Frontend × System Design × 3-6 ────────────────────────────────────────
const mid: CompactSlot[] = [
  ['requirements-radio', 'Requirements gathering (RADIO: R)', 'problem-solving', 'warm-up', 'must', 0,
    'Present a system design prompt (news feed, autocomplete, chat). Ask them to surface requirements first.',
    'Surface — probe what non-functional requirements they identify: mobile? offline? SEO? a11y?',
    'Core system design round — must demonstrate structured approach (RADIO or equivalent).'],
  ['architecture-component-hierarchy', 'Architecture and component hierarchy (RADIO: A)', 'component-architecture', 'exploration', 'must', 2,
    'Ask for high-level component diagram, routing strategy, and rendering decision (CSR/SSR/SSG/ISR).',
    'Probe: "Core Web Vitals implications of your rendering choice? Why not SSR here?"',
    'Must draw component hierarchy with data flow — verbal only is insufficient.'],
  ['data-model-and-caching', 'Data model and caching strategy (RADIO: D)', 'technical-depth', 'exploration', 'must', 2,
    'Ask about client-side state shape, server contracts, and caching approach (HTTP, SWR, IndexedDB).',
    'Probe: "Cache invalidation strategy — how do you know when the data is stale?"',
    'Caching strategies essential: HTTP cache, in-memory, React Query/SWR, IndexedDB.'],
  ['component-api-and-realtime', 'Component interface and real-time protocol (RADIO: I)', 'ux-engineering', 'exploration', 'must', 2,
    'Ask about component prop APIs, REST/GraphQL contracts, and real-time protocol choice.',
    'Probe: "Why WebSockets vs. SSE vs. long polling here? Walk through one character typed in search."',
    'Real-time patterns with clear reasoning distinguish mid from entry.'],
  ['performance-and-a11y', 'Optimization, performance, and accessibility (RADIO: O)', 'performance', 'exploration', 'must', 2,
    'Ask about lazy loading, code splitting, virtualization, and accessibility proactive coverage.',
    'Probe: "User on 3G — how does architecture change? What ARIA patterns for the feed?"',
    'Accessibility must be raised proactively — ARIA, keyboard nav, focus management.'],
  ['offline-and-error', 'Offline mode and error handling', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how architecture changes if offline mode is required and how network failures are surfaced.',
    'Probe: "Support offline mode — what changes? How tell user their data hasn\'t synced?"'],
  ['i18n-monitoring', 'Internationalization and monitoring', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about i18n strategy and how they\'d monitor the frontend in production.',
    'Probe: "How would you test this system? What would you mock? What metric proves it\'s working?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['migration-path', 'Migration path discussion', 'problem-solving', 'closing', 'must', 0,
    'Ask how they\'d migrate an existing CSR app to the architecture they designed.',
    'Surface — probe for phased approach awareness; one honest risk is sufficient.'],
]

// ─── Frontend × System Design × 7+ ─────────────────────────────────────────
const senior: CompactSlot[] = [
  ['deep-requirements-and-constraints', 'Deep requirements and non-functional constraints', 'problem-solving', 'warm-up', 'must', 0,
    'Present a complex scenario (Google Docs, Figma, Netflix frontend). Ask to surface all requirements.',
    'Surface — probe: "Latency budget? Offline tolerance? A11y standard? Primary user journey?"',
    'Must architect for millions of users AND dozens of engineering teams simultaneously.'],
  ['hld-and-rendering-strategy', 'High-level architecture and rendering strategy', 'technical-depth', 'exploration', 'must', 2,
    'Ask for system-level component diagram, CDN/edge placement, API layer, and rendering strategy with justification.',
    'Probe: "Streaming SSR? Partial hydration? Islands architecture? Downsides of your choice?"',
    'Rendering at scale: streaming SSR, partial hydration, resumability, islands architecture.'],
  ['state-and-sync-architecture', 'Client state topology and real-time sync', 'component-architecture', 'exploration', 'must', 2,
    'Ask about local vs. global vs. server cache split, conflict resolution, and offline sync strategy.',
    'Probe: "Conflict when two users edit the same paragraph? CRDT vs. OT trade-offs?"',
    'Advanced frontend concepts expected: CRDTs, service workers, Web Workers, SharedArrayBuffer.'],
  ['performance-at-scale', 'Performance engineering and observability', 'performance', 'exploration', 'must', 2,
    'Ask about performance budgets in CI, error tracking, RUM, and graceful degradation strategy.',
    'Probe: "Walk through request waterfall from URL to interactive. Where are the bottlenecks?"',
    'Must propose monitoring and observability — no observability story is a red flag.'],
  ['security-and-accessibility', 'Security and accessibility architecture', 'accessibility', 'exploration', 'must', 2,
    'Ask about XSS prevention, CSP, and accessibility at organizational scale.',
    'Probe: "How ensure a11y doesn\'t regress after initial compliance? Automated gates in CI?"',
    'Security is mandatory at this level: XSS, CSRF, CSP, subresource integrity.'],
  ['organizational-implications', 'Organizational and team boundary implications', 'leadership', 'exploration', 'if-time', 2,
    'Ask how their architecture affects team autonomy, deployment independence, and code ownership.',
    'Probe: "Prevent one team\'s bad code from crashing the entire frontend? Micro-frontend isolation?"'],
  ['failure-modes-and-degradation', 'Failure modes and graceful degradation', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask what happens when WebSocket fails, a micro-frontend doesn\'t load, or a CDN edge goes down.',
    'Probe: "Caching hierarchy — service worker to CDN to browser. How do they interact?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['success-metrics-senior', 'Success metrics and post-launch measurement', 'leadership', 'closing', 'must', 0,
    'Ask how they\'d measure whether the architecture succeeded 6 months after launch.',
    'Surface — probe for concrete metrics: Core Web Vitals thresholds, adoption rate, build times.',
    'Reference to real industry solutions (Figma, Google Docs, Meta) is a positive signal.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('frontend', 'system-design', '0-2', entry, [
    'Proposing micro-frontends or complex state management for a simple app',
    'Jumping to code without visual component decomposition',
    'Caching strategies, service workers, or advanced optimization',
    'Confusing client and server responsibilities',
    'Silence — not explaining reasoning for component choices',
  ]),
  template('frontend', 'system-design', '3-6', mid, [
    'Starting with framework choice before understanding requirements',
    'Over-engineering the backend (databases, message queues) in a frontend interview',
    'No component diagram — verbal description only',
    'Ignoring accessibility entirely',
    'One-size-fits-all state management regardless of complexity',
  ]),
  template('frontend', 'system-design', '7+', senior, [
    'Framework tunnel vision ("I\'d use React") without rendering strategy discussion',
    'Skipping security: no XSS, CSRF, or CSP mention',
    'No monitoring or observability story',
    'Shallow trade-off analysis ("SSR is better") without use-case specifics',
    'Backend envy: spending time on databases instead of frontend architecture',
  ]),
]
