import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Frontend × Case Study × 0-2 ───────────────────────────────────────────
const entry: CompactSlot[] = [
  ['problem-reading', 'Requirements reading and clarification', 'problem-solving', 'warm-up', 'must', 0,
    'Present a small UI spec (accordion, star rating, todo list). Observe what questions they ask.',
    'Surface — note what edge cases they identify before coding.',
    'The case study is a practical coding challenge; focus is on implementation, not architecture.'],
  ['component-planning', 'Component decomposition and planning', 'component-architecture', 'warm-up', 'must', 0,
    'Ask them to sketch component structure and identify state needs before writing code.',
    'Surface — probe: "Which component owns this state and why?"',
    'Emphasis on clean code, semantic HTML, and basic accessibility.'],
  ['core-implementation', 'Core feature implementation', 'ux-engineering', 'exploration', 'must', 2,
    'Let them build the primary feature (CRUD todo, interactive rating, accordion). Observe code structure.',
    'Probe edge cases as they code: "What if the input is empty? What if the list is empty?"',
    'Expected to handle basic state but not complex architecture.'],
  ['error-and-loading-states', 'Error, loading, and empty states', 'problem-solving', 'exploration', 'must', 2,
    'Ask how they handle API failure, loading spinner, and empty list. Look for happy-path awareness.',
    'Probe: "What happens if the API call fails? Show me the empty state."',
    'Accept missing error handling early — probe it; they should be able to add it.'],
  ['responsiveness', 'Responsive layout and mobile support', 'ux-engineering', 'exploration', 'must', 2,
    'Ask how they\'d make the component work on mobile. Look for media query and Flexbox/Grid usage.',
    'Probe: "If needed on mobile, what specifically changes?"',
    'CSS layout differentiation: many bootcamp grads struggle without a framework.'],
  ['accessibility-basics', 'Accessibility of the built component', 'accessibility', 'exploration', 'if-time', 1,
    'Ask how they\'d make the component accessible for keyboard and screen reader users.',
    'Probe: "What ARIA attributes would you add? Can a keyboard user trigger this?"'],
  ['edge-case-scaling', 'Edge case — scaling the list', 'performance', 'exploration', 'if-time', 2,
    'Ask what happens if the list has 10,000 items. Look for awareness of performance concerns.',
    'Probe: "Would you virtualize? How would you detect you need to?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['walkthrough-improvements', 'Solution walkthrough and improvements', 'problem-solving', 'closing', 'must', 0,
    'Ask them to walk through their solution, explain decisions, and name one thing they\'d improve.',
    'Surface — assess communication clarity and self-awareness about code quality.'],
]

// ─── Frontend × Case Study × 3-6 ───────────────────────────────────────────
const mid: CompactSlot[] = [
  ['requirements-and-scope', 'Requirements scoping and MVP definition', 'problem-solving', 'warm-up', 'must', 0,
    'Present scenario (real-time dashboard widget, autocomplete). Ask them to scope MVP vs. stretch.',
    'Surface — probe what functional and non-functional requirements they surface unprompted.',
    'Must demonstrate architectural thinking, not just implementation.'],
  ['architecture-planning', 'Component architecture and state management planning', 'component-architecture', 'warm-up', 'must', 0,
    'Ask for component tree, state management strategy, and API contracts before coding.',
    'Surface — probe: "Why that state management approach? When would Context suffice here?"',
    'State management trade-off discussion expected: Context vs. Redux vs. Zustand vs. React Query.'],
  ['core-implementation-mid', 'Core feature implementation with composition', 'ux-engineering', 'exploration', 'must', 2,
    'Let them build the primary feature. Observe component decomposition and prop API design.',
    'Probe: "If reusing this in another app, what would you change about the component API?"',
    'Code should show reusable, composable component design with clear prop APIs.'],
  ['performance-awareness', 'Performance and re-render optimization', 'performance', 'exploration', 'must', 2,
    'Ask about re-renders, memoization, and virtualization decisions for their implementation.',
    'Probe: "How would this perform with 100,000 rows? Would you virtualize now or wait?"',
    'Performance awareness mandatory: re-renders, memo, virtualization, debouncing.'],
  ['real-time-or-async', 'Real-time data or async patterns', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they\'d handle WebSocket/SSE updates or a WebSocket connection drop and recovery.',
    'Probe: "Trade-offs between polling and WebSockets here? What if the connection drops?"',
    'Must handle real-time data patterns with clear reasoning.'],
  ['testing-strategy-mid', 'Testing strategy for the component', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask what tests they\'d write for their implementation and at which layer.',
    'Probe: "Most valuable test here? What would you mock and why?"'],
  ['offline-degraded', 'Offline and degraded state handling', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how the component behaves when offline or in a degraded network state.',
    'Probe: "Two users edit the same item simultaneously — how do you handle that?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['tradeoffs-discussion', 'Trade-offs and alternatives discussion', 'problem-solving', 'closing', 'must', 0,
    'Ask what architectural decisions they\'d revisit and what alternative approaches they considered.',
    'Surface — probe for intellectual honesty; one alternative is sufficient.'],
]

// ─── Frontend × Case Study × 7+ ────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-problem-framing', 'Strategic problem framing', 'leadership', 'warm-up', 'must', 0,
    'Present ambiguous scenario (15 teams, 3 component libraries; Core Web Vitals down 40%). Let them frame it.',
    'Surface — observe whether they ask about business context, stakeholders, and timeline before solutions.',
    'Strategic architecture discussion, not coding; evaluates organizational thinking.'],
  ['options-and-tradeoffs', 'Presenting 2-3 architectural options with trade-offs', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to present at least two architectural approaches with concrete trade-offs for each.',
    'Probe: "What would you cut if you had 6 months instead of 18? What\'s the rollback plan?"',
    'Must balance technical idealism with pragmatic delivery.'],
  ['phased-migration-plan', 'Phased migration or rollout plan', 'technical-depth', 'exploration', 'must', 2,
    'Ask for an incremental adoption or migration plan — strangler fig, feature flags, parallel runs.',
    'Probe: "How do old and new coexist during transition? How do you measure migration success?"',
    'Multi-year technical strategy with clear phases expected.'],
  ['governance-and-adoption', 'Governance model and adoption strategy', 'leadership', 'exploration', 'must', 2,
    'Ask who owns the design system/platform, contribution process, and breaking change policy.',
    'Probe: "How do you get buy-in from teams that don\'t want to migrate?"',
    'Governance is as critical as technical design — own it, don\'t just propose it.'],
  ['organizational-impact', 'Organizational and team structure impact', 'leadership', 'exploration', 'must', 2,
    'Ask how their architecture affects team velocity, code ownership, and DX across teams.',
    'Probe: "How would you staff and organize the team? How prevent the design system from becoming a bottleneck?"',
    'Awareness of industry precedent (Airbnb, Spotify, Netflix) is a positive signal.'],
  ['failure-modes-rollback', 'Failure modes and rollback strategy', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask what could go wrong, kill criteria, and how they\'d detect the strategy is failing.',
    'Probe: "Rollback plan if new architecture performs worse? How communicate that to VP Eng?"'],
  ['communication-to-stakeholders', 'Communicating trade-offs to non-technical stakeholders', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they\'d explain the proposed approach to a VP of Engineering unfamiliar with the details.',
    'Probe: "What\'s your one-paragraph summary of the strategy and the biggest risk?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['success-metrics', 'Success metrics and observability', 'problem-solving', 'closing', 'must', 0,
    'Ask how they\'d measure whether the architecture succeeded 6 months after launch.',
    'Surface — probe for specific metrics: adoption rate, build times, Core Web Vitals, team NPS.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('frontend', 'case-study', '0-2', entry, [
    'Micro-frontends or complex state management for simple apps',
    'Architecture decisions without any implementation',
    'Redux for a single todo-list scenario',
    'Design system governance or component library strategy',
    'System design as a standalone round',
  ]),
  template('frontend', 'case-study', '3-6', mid, [
    'Choosing state management without justification',
    'Monolithic 500-line components with no decomposition',
    'Happy-path-only implementations ignoring error and offline states',
    'Premature optimization before identifying bottlenecks',
    'Not discussing trade-offs when only one solution is presented',
  ]),
  template('frontend', 'case-study', '7+', senior, [
    'Pure coding challenges when strategic reasoning is the goal',
    'All-or-nothing full rewrite without incremental migration plan',
    'Being dogmatic about one technology or framework',
    'No rollback or failure mode planning',
    'Treating it as a junior coding problem rather than a strategic scenario',
  ]),
]
