import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Frontend × Coding × 0-2 ───────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['js-fundamentals-warmup', 'JavaScript fundamentals warm-up', 'technical-depth', 'warm-up', 'must', 0,
    'Ask 1-2 short JS questions: var/let/const scoping, or output prediction of closure or event loop snippet.',
    'Surface — assess language foundations before moving to coding task.',
    'Language fundamentals are the primary signal; framework magic is not enough.'],
  ['css-layout-task', 'CSS layout task', 'ux-engineering', 'warm-up', 'must', 0,
    'Ask them to center a div or build a responsive two-column layout. Look for Flexbox or Grid confidence.',
    'Surface — observe first approach: does it work, is it clean?',
    'CSS layout ability is a strong differentiator; many bootcamp grads struggle here.'],
  ['dom-coding-task', 'DOM manipulation coding task', 'technical-depth', 'exploration', 'must', 2,
    'Give a DOM task: counter with +/- buttons, character countdown textarea, or form with email validation.',
    'Probe: "Why event delegation here? What if there are 1,000 items?"',
    'Evaluate approach over raw speed; semantic HTML and clean code matter.'],
  ['ui-component-build', 'Build a small UI component', 'ux-engineering', 'exploration', 'must', 2,
    'Ask them to build a simple component: accordion, star rating, todo list, or traffic light cycle.',
    'Probe: "What if the list is empty? What happens on invalid input?"',
    'Component tasks are intentionally simple — clean code, not architecture, is the signal.'],
  ['js-utility-function', 'Implement a JS utility function', 'problem-solving', 'exploration', 'must', 2,
    'Ask them to implement a basic utility: debounce, flatten array, remove duplicates, or Array.map polyfill.',
    'Probe: "What if input is null or an empty array?" — edge case thinking.',
    'Proves understanding of what libraries abstract, not just how to use them.'],
  ['basic-algorithm', 'Basic algorithm problem', 'problem-solving', 'exploration', 'if-time', 1,
    'Give a simple string/array problem: FizzBuzz, palindrome check, or object key count.',
    'Probe: "Can you do this without a loop? What\'s the time complexity?"'],
  ['accessibility-followup', 'Accessibility follow-up on built component', 'accessibility', 'exploration', 'if-time', 1,
    'After the component is built, ask how they\'d make it accessible for keyboard and screen reader users.',
    'Probe: "Would this work with Tab key only? What ARIA attributes would you add?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['code-review-cleanup', 'Review and clean up', 'problem-solving', 'closing', 'must', 0,
    'Ask them to look at their own code and name one thing they\'d improve or add.',
    'Surface — assess self-awareness about code quality and edge cases.'],
]

// ─── Frontend × Coding × 3-6 ───────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['problem-scoping', 'Problem scoping and API surface design', 'problem-solving', 'warm-up', 'must', 0,
    'Present a machine coding problem (autocomplete, modal, infinite scroll). Ask clarifying questions first.',
    'Surface — probe what edge cases they surface: keyboard nav, empty state, debouncing.',
    'Machine coding dominates: build complete working components in 30-45 min.'],
  ['js-utility-from-scratch', 'Implement JS utility from scratch', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to implement debounce (leading/trailing), throttle, Promise.all, deepClone, or EventEmitter.',
    'Probe: "Handle circular references in deepClone? Flush/cancel API for debounce?"',
    'Proving understanding of what libraries abstract separates mid from entry.'],
  ['machine-coding-component', 'Machine coding — UI component', 'ux-engineering', 'exploration', 'must', 2,
    'Build autocomplete with debounce, modal with focus trap, star rating with a11y, or infinite scroll.',
    'Probe after MVP: "Add keyboard navigation. Handle the network race condition."',
    'Components in 70% of rounds: star rating, modal, pagination, accordion, infinite scroll.'],
  ['react-custom-hook', 'React custom hook or optimization', 'component-architecture', 'exploration', 'must', 2,
    'Ask them to implement usePrevious, useDebounce, useLocalStorage, or useFetch with AbortController.',
    'Probe: "Why useCallback here? What\'s the stale closure risk in this dependency array?"',
    'Custom hooks are a differentiator; dependency arrays and cleanup reveal real React depth.'],
  ['async-patterns', 'Async patterns and error handling', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about fetch with AbortController, retry logic, polling with cleanup, or concurrency limits.',
    'Probe: "How prevent a race condition when two requests are in-flight?"',
    'No async cleanup (missing AbortController, memory leaks) is a red flag.'],
  ['performance-followup', 'Performance and scaling follow-up', 'performance', 'exploration', 'if-time', 2,
    'After component is built, ask how it performs with 10,000 items or a slow network.',
    'Probe: "When would you virtualize? How decide what to memoize?"'],
  ['accessibility-keyboard', 'Accessibility and keyboard navigation', 'accessibility', 'exploration', 'if-time', 2,
    'Ask them to add keyboard navigation and screen reader support to the built component.',
    'Probe: "What ARIA role? How manage focus when the modal opens and closes?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['tradeoffs-extension', 'Trade-offs and extension discussion', 'problem-solving', 'closing', 'must', 0,
    'Ask what they\'d add given more time and what architectural decision they\'d revisit.',
    'Surface — one honest trade-off articulation is sufficient.'],
]

// ─── Frontend × Coding × 7+ ────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['problem-scoping-senior', 'Open-ended problem scoping — candidate drives', 'problem-solving', 'warm-up', 'must', 0,
    'Give open-ended prompt: "Build an autocomplete" or "Implement simplified Virtual DOM." Candidate defines scope.',
    'Surface — scoping IS part of evaluation; probe what they choose to prioritize and why.',
    'You drive the interview; architectural decisions made while coding are the real signal.'],
  ['js-internals-implementation', 'Implement a JS internal or language primitive', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to implement simplified useState/useEffect (hooks linked list), Virtual DOM diff, or bind polyfill.',
    'Probe: "How does React know which hook is which? Walk me through the closure storage."',
    'Framework internals are fair game: understanding vs. usage is the distinction.'],
  ['system-level-component', 'Build a system-level UI component', 'ux-engineering', 'exploration', 'must', 2,
    'Ask to build virtualized list (100K rows), spreadsheet with formulas, rich text editor, or real-time Kanban.',
    'Probe: "Add undo/redo. Handle 100K rows. Now make it collaborative."',
    'Follow-up extensions are the real test — initial implementation should be quick.'],
  ['performance-profiling', 'Profile and optimize a slow component', 'performance', 'exploration', 'must', 2,
    'Give a slow-rendering React tree or a layout-thrashing DOM operation. Ask them to diagnose.',
    'Probe: "Walk me through how you\'d profile this live. What reflow/repaint risks do you see?"',
    'Performance is not theoretical — must work with DevTools, not just describe principles.'],
  ['advanced-typescript-types', 'Advanced TypeScript utility types', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to implement DeepPartial<T>, PathOf<T>, a type-safe event emitter, or branded types.',
    'Probe: "How does infer work inside conditional types? Walk me through the resolution."',
    'Writing `any` everywhere signals insufficient TypeScript mastery.'],
  ['architecture-in-code', 'Architecture-in-code: design and implement a core', 'component-architecture', 'exploration', 'if-time', 2,
    'Ask them to design and implement the core of a state management library, form framework, or plugin system.',
    'Probe: "How would you distribute this as an npm library? Testing strategy for the library itself?"'],
  ['advanced-async-concurrency', 'Advanced async — task scheduler or WebSocket manager', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask for task scheduler with priority+concurrency+cancellation, or WebSocket manager with reconnection buffering.',
    'Probe: "Exponential backoff with jitter — why jitter? How handle buffered messages across reconnect?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['architecture-discussion', 'Architecture, testing, and deployment discussion', 'leadership', 'closing', 'must', 0,
    'Ask how they\'d test their implementation, deploy it as a library, and scale it 10x.',
    'Surface — tests strategic thinking: beyond the code, what does production readiness look like?'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('frontend', 'coding', '0-2', entry, [
    'Using `var` everywhere instead of `let`/`const`',
    'All logic in a single function with no decomposition',
    'Using innerHTML for user content (XSS risk)',
    'Ignoring null/empty input edge cases',
    'System design or architecture questions',
  ]),
  template('frontend', 'coding', '3-6', mid, [
    'Building without planning or asking clarifying questions',
    'Using index as key in dynamic reorderable lists',
    'useEffect for everything including derived state',
    'Incorrect dependency arrays causing infinite loops or stale closures',
    'Over-engineering with Redux for useState scenarios',
  ]),
  template('frontend', 'coding', '7+', senior, [
    'Over-abstracting prematurely (framework when simple solution suffices)',
    'Treating as mid-level round — building without discussing architecture',
    'Framework tunnel vision: unable to use vanilla DOM APIs',
    'Dismissing accessibility as "nice to have"',
    'Gold-plating one area while ignoring others entirely',
  ]),
]
