import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Frontend × Behavioral × 0-2 ────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro-ui', 'Intro and a UI you\'re proud of', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves and describe a UI they built. Look for user-facing pride in their work.',
    'Surface only — use to pick follow-up topics.', 'Bootcamp projects, personal sites, and internships are all expected.'],
  ['motivation-frontend', 'Why frontend over backend/fullstack', 'motivation', 'warm-up', 'must', 0,
    'Ask what sparked interest in UI/UX development. Look for genuine curiosity about how users experience software.',
    'One follow-up at most — keep it warm.', 'Assess learning orientation and coachability.'],
  ['learning-framework', 'Learning a new framework or tool', 'problem-solving', 'exploration', 'must', 2,
    'Ask about picking up React, Vue, or a CSS framework for the first time. Look for learning strategy.',
    'Probe the hardest concept and how they got unstuck — independent vs. tutorial dependency.',
    'Accept bootcamp, course project, or self-study context.'],
  ['working-with-designer', 'Working with a designer on a mockup', 'collaboration', 'exploration', 'must', 2,
    'Ask about disagreeing on implementation of a design. Look for pixel-perfect vs. pragmatic tradeoff handling.',
    'Isolate their reasoning: "Walk me through the specific disagreement and the designer\'s perspective."',
    'Figma handoff and subjective visual feedback are unique frontend experiences.'],
  ['css-cross-browser-bug', 'Debugging a CSS or cross-browser bug', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a layout that broke in a specific browser or viewport. Look for systematic debugging approach.',
    'Probe tools used: DevTools, browser testing, BrowserStack. Not just "I Googled it."',
    'Limited blast-radius bugs expected; focus on approach over outcome.'],
  ['deadline-scope-cut', 'Shipping under a deadline — scope decisions', 'problem-solving', 'exploration', 'if-time', 1,
    'Ask about cutting visual polish or scope on a UI feature. Look for thoughtful prioritization.',
    'Probe what was cut and the reasoning, not just that they worked faster.'],
  ['receiving-ui-feedback', 'Receiving subjective feedback on visual work', 'self-awareness', 'exploration', 'if-time', 2,
    'Ask about receiving non-technical critique ("it doesn\'t feel right"). Unique to frontend.',
    'Probe what they changed and how they reconciled subjective vs. objective criteria.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-frontend-excitement', 'What frontend challenges excite you most', 'motivation', 'closing', 'must', 0,
    'Ask what kind of UI problems they want to tackle next. Assess enthusiasm and self-awareness.',
    'Surface — wrap up warmly and note growth signals.'],
]

// ─── Frontend × Behavioral × 3-6 ────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['career-direction', 'Career direction — why frontend evolved', 'motivation', 'warm-up', 'must', 0,
    'Ask how perspective on frontend vs. fullstack evolved with experience. Calibrate ownership lens.',
    'Surface — use to identify which deep-dives to pursue.', 'Must reflect on real products with real users.'],
  ['advocating-accessibility', 'Advocating for accessibility under pressure', 'ux-engineering', 'exploration', 'must', 2,
    'Ask about pushing for WCAG compliance when stakeholders wanted to skip it. Look for business case framing.',
    'Probe WCAG levels referenced, how violations were prioritized, and what won stakeholder buy-in.',
    'Measurable audit scores and impact on real users differentiates practitioners.'],
  ['design-performance-tradeoff', 'Design vs. performance tradeoff decision', 'ux-engineering', 'exploration', 'must', 2,
    'Ask about pushing back on a design that hurt performance (heavy animations, complex layouts). Look for alternatives proposed.',
    'Probe what metric was at stake and how the constraint was communicated to the designer.',
    'Must involve real products — not side projects.'],
  ['component-library-decision', 'Build vs. adopt component library decision', 'component-architecture', 'exploration', 'must', 2,
    'Ask about deciding to build custom vs. adopt an existing library. Look for trade-off analysis and adoption strategy.',
    'Probe why that library over alternatives and what the team migration looked like.',
    'Expect ownership of architectural decisions, not just implementation.'],
  ['performance-optimization-story', 'Core Web Vitals optimization story', 'performance', 'exploration', 'must', 2,
    'Ask about identifying and fixing a performance regression. Look for specific before/after metrics.',
    'Probe exact metric (LCP/CLS/INP), tooling used, and how improvement was measured.',
    'Vague "we optimized" without numbers is a red flag at this level.'],
  ['cross-functional-friction', 'Cross-functional friction — PM, designer, engineer', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about bridging design mockups with technical constraints involving PMs. Look for specific friction and resolution.',
    'Probe how they communicated constraints without killing design intent.'],
  ['tech-debt-ui', 'Balancing UI tech debt with feature delivery', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about advocating for refactoring time on legacy CSS or components alongside feature work.',
    'Probe the business case made and what actually changed in the codebase.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retrospective-decision', 'A frontend decision you\'d make differently', 'self-awareness', 'closing', 'must', 0,
    'Ask what they\'d change knowing what they know now. Assess intellectual honesty and growth.',
    'Surface — one example suffices; wrap up warmly.'],
]

// ─── Frontend × Behavioral × 7+ ─────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-frontend-role', 'Frontend as a strategic discipline', 'leadership', 'warm-up', 'must', 0,
    'Ask how they connect frontend craft to business outcomes. Look for multi-dimensional leadership thinking.',
    'Surface — calibrate scope and identify which leadership dimensions to probe.',
    'Must show impact across technical, people, process, and business dimensions.'],
  ['design-system-architecture', 'Leading design system creation or adoption', 'component-architecture', 'exploration', 'must', 2,
    'Ask about driving design system creation or org-wide adoption. Look for governance, versioning, and team autonomy.',
    'Probe how they handled teams that didn\'t want to adopt and what the governance model looked like.',
    'Scope must span multiple teams — not a single product\'s component library.'],
  ['rendering-strategy-decision', 'Frontend platform or rendering strategy decision', 'technical-depth', 'exploration', 'must', 2,
    'Ask about choosing SSR vs. CSR vs. ISR for an entire product line. Look for business and user context.',
    'Probe who disagreed, their argument, how consensus was built, and what they\'d do differently.',
    'Architecture affecting product suites is the right scope.'],
  ['accessibility-at-scale', 'Accessibility strategy at organizational scale', 'accessibility', 'exploration', 'must', 2,
    'Ask about building a11y into CI/CD or org standards. Look for process creation, not single fixes.',
    'Probe how WCAG was built into the Definition of Done and how regressions were prevented.',
    'Must show multiplier impact — making every team\'s work accessible.'],
  ['legacy-migration-leadership', 'Leading a legacy frontend migration', 'leadership', 'exploration', 'must', 2,
    'Ask about a jQuery/Angular to React migration or similar. Look for phased planning and team morale management.',
    'Probe: "Give a one-sentence summary of each phase" — tests executive communication.',
    'Multi-month arcs across multiple team members expected.'],
  ['dx-leadership', 'Developer experience or build pipeline leadership', 'leadership', 'exploration', 'if-time', 2,
    'Ask about improving build times, CI/CD, monorepo standards, or unified tooling. Look for org-wide impact.',
    'Probe what practices outlasted them and how they drove adoption across teams.'],
  ['business-impact-frontend', 'Connecting frontend decisions to business metrics', 'leadership', 'exploration', 'if-time', 2,
    'Ask about a UI decision with direct revenue, conversion, or engagement impact. Look for business framing.',
    'Probe: "Can you connect that frontend decision to a specific business metric?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['frontend-bet-failure', 'Biggest frontend bet that didn\'t pan out', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant initiative that failed or underdelivered. Look for organizational learning.',
    'Probe systemic changes, not just personal lessons.', 'Failure questions carry more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('frontend', 'behavioral', '0-2', entry, [
    'Leading teams or mentoring others',
    'Architecture decisions or design system ownership',
    'Production incident management or on-call',
    'Cross-team influence or org-wide standards',
    'Generic conflict questions without frontend context',
  ]),
  template('frontend', 'behavioral', '3-6', mid, [
    'Entry-level "learning a new framework" questions',
    'Org-wide platform strategy (senior territory)',
    'Generic teamwork stories without frontend context',
    'Accepting vague performance claims without probing for metrics',
    'Mentoring and team-building as primary topic',
  ]),
  template('frontend', 'behavioral', '7+', senior, [
    'Individual bug fixes or coding accomplishments',
    'Single technology choices without organizational context',
    'Generic leadership questions that could apply to any role',
    'Questions an IC3/IC4 could answer equally well',
    'Accepting "we migrated to React" without probing incremental plan and business case',
  ]),
]
