import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['coding-warmup', 'Problem introduction and clarification', 'problem-solving', 'warm-up', 'must', 0,
    'Present an easy data-shaping problem (group/filter records). Assess whether they clarify the data shape.',
    'Surface — note clarifying questions about input format and edge cases.', 'Hints are expected and acceptable.'],
  ['approach-discussion', 'Approach discussion', 'problem-solving', 'exploration', 'must', 2,
    'Ask them to describe the approach before coding. Assess whether they think about the data shape first.',
    'Probe time/space complexity and how they\'ll structure the transform.', 'A working straightforward approach is sufficient.'],
  ['coding-impl', 'Coding implementation', 'technical-depth', 'exploration', 'must', 2,
    'Candidate implements the transform/validation. Provide hints if stuck. Assess clean language usage.',
    'Probe variable naming, structure, and keeping parsing separate from formatting.'],
  ['edge-case-data', 'Edge-case data handling', 'problem-solving', 'exploration', 'must', 1,
    'Ask them to handle messy input: empty array, missing fields, nulls. Assess defensive coding.',
    'Probe what their function does on malformed input.'],
  ['follow-up-optimize', 'Optimization or extension follow-up', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask "What if the input is very large?" or "What if we add another field?" Assess adaptability.',
    'Probe scaling awareness and how easily the code extends.'],
  ['practical-endpoint', 'Practical endpoint shaping', 'technical-depth', 'exploration', 'if-time', 1,
    'If time, ask them to wrap the result into a response object a frontend would consume.',
    'Probe response shape and basic status/error conventions.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['coding-closing', 'Approach reflection', 'problem-solving', 'closing', 'must', 0,
    'Ask what they would do differently with more time. Assess self-awareness.',
    'Surface — wrap up.'],
]

const mid: CompactSlot[] = [
  ['problem-scoping', 'Problem scoping and clarification', 'problem-solving', 'warm-up', 'must', 0,
    'Present a medium problem (pagination, merging two data sources). Expect proactive edge-case questions.',
    'Surface — more ambiguous than junior, less hand-holding.', 'Engineering judgment is the key signal.'],
  ['multi-approach', 'Approach with tradeoffs', 'problem-solving', 'exploration', 'must', 2,
    'Expect a clear approach with complexity analysis and awareness of alternatives.',
    'Probe why this structure over another for the data and the access pattern.'],
  ['clean-implementation', 'Clean implementation', 'technical-depth', 'exploration', 'must', 2,
    'Assess code quality: readability, separation of parsing/transform/format, error handling, naming.',
    'Probe design decisions in the code structure.', 'Code quality matters as much as correctness.'],
  ['self-testing', 'Self-driven testing on messy data', 'problem-solving', 'exploration', 'must', 2,
    'Expect them to test corner cases unprompted: empty, missing matches, duplicates, out-of-range page.',
    'Probe testing strategy and self-correction.'],
  ['stateful-component', 'Small stateful component', 'technical-depth', 'exploration', 'if-time', 2,
    'A small LRU-style cache, a debounce/throttle, or a state reducer — practical full-stack building blocks.',
    'Probe production concerns: what happens on overflow, expiry, or repeated calls.'],
  ['response-contract', 'Shaping the response contract', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask them to shape output into a clean API response the frontend consumes (paged, with metadata).',
    'Probe over/under-fetching and error shapes.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['scaling-followup', 'Scaling and production follow-up', 'technical-depth', 'closing', 'must', 0,
    'Ask how the solution behaves with large inputs and how they\'d make it production-ready.',
    'Surface — assess awareness of real-world deployment.'],
]

const senior: CompactSlot[] = [
  ['requirements-gathering', 'Requirements gathering from a vague prompt', 'problem-solving', 'warm-up', 'must', 0,
    'Present a deliberately vague module-building prompt. Assess whether they drive scope and API shape.',
    'Surface — note quality of questions asked.', 'Candidate must drive the conversation.'],
  ['module-design', 'Module API and approach design', 'technical-depth', 'exploration', 'must', 2,
    'Expect interface design before implementation — a reusable cache, paginator, or query builder.',
    'Probe the public API, extensibility, and tradeoffs of the design.',
    'Design the module before implementing it.'],
  ['production-quality', 'Production-quality implementation', 'technical-depth', 'exploration', 'must', 2,
    'Assess input validation, clean abstractions, separation of concerns, and reusability.',
    'Probe "why this abstraction?" and how the rest of the app would use it.', 'Trade-off articulation is mandatory.'],
  ['comprehensive-testing', 'Comprehensive testing strategy', 'problem-solving', 'exploration', 'must', 2,
    'Expect non-obvious edge cases: concurrent access, expiry-vs-eviction interaction, cursor stability under inserts.',
    'Probe how they\'d test the module in isolation and under load.'],
  ['concurrency-state', 'Concurrency and shared state', 'technical-depth', 'exploration', 'if-time', 2,
    'If the module holds state (cache, rate counter), probe thread/async safety and race conditions.',
    'Probe what breaks under concurrent reads and writes.'],
  ['data-pipeline', 'Data transform pipeline', 'technical-depth', 'exploration', 'if-time', 2,
    'A streaming or batched transform over a larger dataset. Assess partitioning and memory awareness.',
    'Probe failure recovery and handling of partial/bad records.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['extension-monitoring', 'Extension and production readiness', 'operational', 'closing', 'must', 0,
    'How would the module evolve, get observed in production, and absorb new requirements?',
    'Surface — assess forward-looking production thinking.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('fullstack', 'coding', '0-2', entry, [
    'LeetCode hard problems',
    'Advanced graph or dynamic-programming puzzles',
    'Distributed systems concepts',
    'Concurrency and thread-safety internals',
    'Designing reusable modules with a public API',
  ]),
  template('fullstack', 'coding', '3-6', mid, [
    'Primarily trivial problems with hand-holding',
    'Ignoring code quality and structure',
    'Skipping edge-case and testing discussion',
    'Pure algorithmic puzzles without data/request context',
  ]),
  template('fullstack', 'coding', '7+', senior, [
    'LeetCode-style puzzles as the primary evaluation',
    'Simple transforms without any module or API design',
    'Ignoring production and reuse concerns',
    'Single correct answer problems',
    'Heavy algorithmic focus over design judgment',
  ]),
]
