import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Full-stack × Behavioral × 0-2 ─────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-introduction', 'Resume walkthrough', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves. Calibrate scope expectations for junior level.',
    'Surface only — move on after 2 minutes.', 'Stories from academics, internships, side projects are expected.'],
  ['motivation-curiosity', 'Motivation for full-stack', 'motivation', 'warm-up', 'must', 0,
    'Ask why full-stack rather than specializing. Look for genuine curiosity about the whole pipeline.',
    'Surface treatment — one follow-up at most.', 'Assess coachability and breadth of interest.'],
  ['first-feature', 'Shipping a first end-to-end feature', 'ownership', 'exploration', 'must', 2,
    'Ask about the first feature they shipped touching UI, API, and data. Look for what they personally built.',
    'Isolate their contribution across layers: "What did YOU write on the frontend vs the backend?"',
    'Academic and internship projects acceptable.'],
  ['cross-layer-debugging', 'Debugging across the stack', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a bug where they weren\'t sure if it was the UI or the API. Look for systematic isolation.',
    'Probe how they narrowed it down — network tab, logs, reproducing the request.',
    'Limited blast-radius stories expected.'],
  ['team-collaboration', 'Collaborating on a shared feature', 'collaboration', 'exploration', 'must', 2,
    'Ask about working with a teammate on a feature that crossed their code. Look for specifics, not "we did X."',
    'Probe how they coordinated the API contract or handed off between layers.',
    'Pairing and code review stories acceptable.'],
  ['handling-feedback', 'Handling code review feedback', 'self-awareness', 'exploration', 'if-time', 1,
    'Ask about critical feedback on a pull request and how it helped them improve.',
    'Probe what changed in their approach afterward.'],
  ['learning-new-tech', 'Learning a new part of the stack', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about ramping on an unfamiliar layer (e.g. a frontend dev learning the DB). Look for resourcefulness.',
    'Probe what resources they used and how fast they got productive.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-growth', 'Growth mindset', 'motivation', 'closing', 'must', 0,
    'Ask where they want to grow across the stack. Assess enthusiasm and self-awareness.',
    'Surface — wrap up the interview warmly.'],
]

// ─── Full-stack × Behavioral × 3-6 ─────────────────────────────────────────
const mid: CompactSlot[] = [
  ['project-ownership', 'End-to-end feature ownership', 'ownership', 'warm-up', 'must', 0,
    'Ask candidate to walk through a feature they owned across UI, API, and DB. Calibrate scope.',
    'Surface — use this to pick follow-up topics.', 'Must show ownership of the full slice, not one layer.'],
  ['where-logic-lives', 'Deciding where logic belongs', 'technical-depth', 'exploration', 'must', 2,
    'Ask about deciding whether logic went on the client or server, and how they evaluated tradeoffs.',
    'Probe why that side over the other — latency, trust, reuse, complexity.',
    'Expect references to real production features.'],
  ['api-contract-change', 'Changing an API contract', 'collaboration', 'exploration', 'must', 2,
    'Ask about changing an API the frontend depended on. Look for rollout and backward-compatibility care.',
    'Probe how they versioned, coordinated, or avoided breaking consumers.'],
  ['handling-ambiguity', 'Handling ambiguous requirements', 'problem-solving', 'exploration', 'must', 2,
    'Ask about building a feature with unclear requirements spanning UI and data. Look for initiative.',
    'Probe what they did when product specs didn\'t cover an edge case.'],
  ['cross-functional-collaboration', 'Cross-functional collaboration', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about working with PMs and designers on a feature. Look for friction points and resolution.',
    'Probe how they pushed back or reshaped a spec for technical reasons.'],
  ['incident-response', 'Production incident in an owned feature', 'operational', 'exploration', 'if-time', 2,
    'Ask about a production incident in a feature they owned end-to-end. Look for composure and root cause.',
    'Probe whether the fault was UI, API, or data — and what changed after.'],
  ['prioritization-tradeoffs', 'Prioritizing polish vs correctness', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a deadline where they traded UI polish against backend correctness (or vice versa).',
    'Probe the framework used, not just "I worked hard."'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['growth-mentoring', 'Growth and mentoring', 'leadership', 'closing', 'must', 0,
    'Ask about helping a teammate get comfortable on the other half of the stack. Assess investment in others.',
    'One example suffices — surface treatment.'],
]

// ─── Full-stack × Behavioral × 7+ ──────────────────────────────────────────
const senior: CompactSlot[] = [
  ['career-impact', 'Career narrative and impact trajectory', 'leadership', 'warm-up', 'must', 0,
    'Ask about the biggest impact in their career. This is a curated story, not a resume walkthrough.',
    'Surface — calibrate scope and leadership dimensions.', 'Must show impact spanning the stack and teams.'],
  ['architecture-change', 'Driving full-stack architecture change', 'technical-depth', 'exploration', 'must', 2,
    'Ask about driving a change spanning frontend and backend across teams (e.g. BFF, SSR migration).',
    'Probe opposition, how consensus was built, and the migration plan.',
    'Scope must extend beyond immediate team.'],
  ['influence-without-authority', 'Leading without authority', 'leadership', 'exploration', 'must', 2,
    'Ask about influencing a decision across frontend and backend teams without formal authority.',
    'Probe who opposed, what data was used, how they built consensus.'],
  ['boundary-conflict', 'Resolving frontend/backend boundary conflict', 'leadership', 'exploration', 'must', 2,
    'Ask about teams disagreeing on where complexity should live. Look for a resolution framework.',
    'Probe both sides of the conflict and how ownership was settled.'],
  ['mentorship-and-growth', 'Growing full-stack engineers', 'leadership', 'exploration', 'must', 2,
    'Ask how they\'ve grown engineers to work confidently across the stack. Look for systems, not one-offs.',
    'Probe pairing, rotations, and conventions that outlasted them.',
    'Must show multiplicative impact across a team.'],
  ['strategic-tech-decision', 'Strategic decision with product impact', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about a full-stack technical decision with significant product or business implications.',
    'Probe the business reasoning, not just technical merits.'],
  ['engineering-culture', 'Setting cross-stack conventions', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they established shared conventions spanning frontend and backend.',
    'Probe what practices outlasted them and how they drove adoption.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['failure-org-consequences', 'Failure with organizational consequences', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant failure in an end-to-end bet and what they did differently. Look for systemic learning.',
    'Probe systemic changes, not just personal growth.', 'Failure questions carry more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('fullstack', 'behavioral', '0-2', entry, [
    'Organizational strategy or direction-setting',
    'Cross-team influence with senior stakeholders',
    'Production incident command or on-call leadership',
    'Multi-month cross-team project ownership',
    'Setting engineering culture across teams',
  ]),
  template('fullstack', 'behavioral', '3-6', mid, [
    'Organizational-level strategy',
    'Building teams from scratch or hiring decisions',
    'Influencing company-level roadmap',
    'Setting org-wide engineering standards',
    'Pure academic or theoretical questions',
  ]),
  template('fullstack', 'behavioral', '7+', senior, [
    'Basic teamwork questions',
    'Individual debugging stories as the main signal',
    'Questions answerable with single-feature scope',
    'Learning a new framework as the primary topic',
    'Questions an IC3/IC4 could answer equally well',
  ]),
]
