import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['tech-background', 'Technical background chat', 'technical-depth', 'warm-up', 'must', 0,
    'Ask about the stack they know and a full feature they built. Calibrate level, no tricks.',
    'Surface — move on after 2 min.', 'Academic/bootcamp/side-project features are acceptable.'],
  ['request-lifecycle', 'End-to-end request lifecycle', 'technical-depth', 'exploration', 'must', 2,
    'Ask what happens from a form submit to the data being saved and the UI updating. Assess full round-trip.',
    'Probe each hop: client validation, HTTP request, server handling, DB write, response, re-render.',
    'Breadth across layers over depth in any one.'],
  ['rest-endpoint-design', 'REST endpoint plus its consumer', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to design a simple endpoint and the component that renders it. Assess both sides.',
    'Probe status codes, the response shape, and loading/empty states on the client.'],
  ['client-vs-server-state', 'Client vs server state', 'technical-depth', 'exploration', 'must', 2,
    'Ask what state lives on the client vs the server for a small feature. Assess the distinction.',
    'Probe what must be fetched vs what is local UI state.', 'Awareness that they differ is the key signal.'],
  ['sql-to-screen', 'SQL feeding a screen', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask for a basic query (JOIN/filter) that produces the data a screen needs.',
    'Probe how the query result maps to what the user sees.'],
  ['http-basics', 'HTTP and the network boundary', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask about HTTP methods, status codes, and what crosses the wire. Look for practical understanding.',
    'Probe what happens on a failed request and how the UI should react.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tech', 'Technology interests', 'motivation', 'closing', 'must', 0,
    'Ask which part of the stack they want to deepen and why. Assess enthusiasm.',
    'Surface — wrap up warmly.'],
]

const mid: CompactSlot[] = [
  ['feature-walkthrough', 'Full feature design walkthrough', 'technical-depth', 'warm-up', 'must', 0,
    'Ask them to walk through a feature they shipped across UI, API, and DB. Assess end-to-end thinking.',
    'Surface — let them drive; use it to pick deep-dive topics.', 'Key difference from entry level.'],
  ['api-contract-design', 'API contract design', 'technical-depth', 'exploration', 'must', 2,
    'Assess REST best practices, pagination, error contracts, versioning, and how the client consumes them.',
    'Probe why a response was shaped this way and how it avoids over/under-fetching.', 'Both sides must be considered.'],
  ['state-sync-caching', 'State sync and client caching', 'technical-depth', 'exploration', 'must', 2,
    'Ask how client state stays in sync after a mutation. Look for caching, invalidation, optimistic updates.',
    'Probe "What if the optimistic update fails?" and stale-cache edge cases.', 'Trade-off reasoning is critical.'],
  ['auth-sessions', 'Auth and sessions across the boundary', 'technical-depth', 'exploration', 'must', 2,
    'Probe cookie vs token sessions, where auth state lives, CSRF, and protecting both API and UI routes.',
    'Probe the request flow on a protected action and how the frontend handles a 401.'],
  ['data-modeling-for-ui', 'Data modeling driven by UI needs', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask how the data model supports the screens — denormalization, read patterns, the N+1 problem.',
    'Probe how they avoid fetching too much or too little for a given view.'],
  ['cross-layer-debugging', 'Debugging across layers', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask how they diagnose a bug when it is unclear whether the fault is UI, API, or DB.',
    'Probe their isolation method: network tab, server logs, reproducing the request.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['operational-concerns', 'Operational and deployment concerns', 'operational', 'closing', 'must', 0,
    'Ask about deploying a full-stack change safely — migrations, frontend/backend version skew, monitoring.',
    'Surface — conceptual awareness is sufficient.'],
]

const senior: CompactSlot[] = [
  ['arch-presentation', 'Full-stack architecture presentation', 'technical-depth', 'warm-up', 'must', 0,
    'Ask candidate to present a full-stack system they designed. Look for scope and tradeoff awareness.',
    'Surface — use this to calibrate depth for follow-ups.', 'Candidate drives the conversation.'],
  ['rendering-strategy', 'Rendering strategy per page', 'technical-depth', 'exploration', 'must', 2,
    'Probe SSR vs SSG vs CSR choices page by page, with data freshness and performance tradeoffs.',
    'Challenge "Why render this on the server?" and probe caching/revalidation strategy.',
    '3-5 year forward-looking reasoning expected.'],
  ['multi-client-api', 'API serving multiple clients', 'technical-depth', 'exploration', 'must', 2,
    'Discuss designing an API for web and mobile with different needs — BFF vs shared API, GraphQL tradeoffs.',
    'Probe over/under-fetching, versioning, and contract ownership across teams.'],
  ['consistency-across-boundary', 'Consistency between client and server', 'technical-depth', 'exploration', 'must', 2,
    'Probe how cached client state stays correct against the source of truth — invalidation, real-time, conflicts.',
    'Probe "What if two clients edit the same record?" and reconciliation strategy.'],
  ['perf-end-to-end', 'End-to-end performance', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about performance from DB query to Core Web Vitals — where the time goes and how to attack it.',
    'Probe real instrumentation: query plans, payload size, bundle splitting, perceived latency.'],
  ['architecture-evolution', 'Architecture strategy and evolution', 'technical-depth', 'exploration', 'if-time', 2,
    'Discuss monolith vs services, migration planning, and keeping a full-stack codebase coherent over time.',
    'Probe total cost of ownership and multi-team consensus building.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['tech-mentorship', 'Technical mentorship and standards', 'leadership', 'closing', 'must', 0,
    'Ask how they established conventions or onboarding that span frontend and backend.',
    'Surface — one example of systemic improvement.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('fullstack', 'technical', '0-2', entry, [
    'Distributed systems or CAP theorem',
    'Advanced rendering optimization (hydration internals, RSC streaming)',
    'Database internals (B-trees, execution plans)',
    'Designing an API for multiple clients (BFF/GraphQL federation)',
    'LeetCode hard problems',
  ]),
  template('fullstack', 'technical', '3-6', mid, [
    'Organizational-level architecture decisions',
    'Contract ownership across 5+ teams',
    'Multi-region or global consistency reasoning',
    'Problems solvable with a single CRUD endpoint',
  ]),
  template('fullstack', 'technical', '7+', senior, [
    'CSS or framework trivia as a primary signal',
    'A single endpoint plus component as the whole exercise',
    'Textbook definition questions',
    'Tooling trivia',
    'Problems with a single right answer',
  ]),
]
