import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['requirements-gathering', 'Requirements and user flows', 'problem-solving', 'warm-up', 'must', 0,
    'Present a well-defined feature (shared todo app). Guide candidate through users, flows, and pages.',
    'Surface — note whether candidate clarifies before jumping in.', 'Interviewer-driven format.'],
  ['page-and-component', 'Pages and UI structure', 'technical-depth', 'exploration', 'must', 2,
    'Ask what pages/components exist and what each shows. Assess structured client-side thinking.',
    'Probe loading, empty, and error states for the main view.', 'Clarity over polish.'],
  ['api-design-basic', 'API endpoint design', 'technical-depth', 'exploration', 'must', 2,
    'Ask for REST endpoints, methods, and request/response shapes that the UI will call.',
    'Probe status codes and how the response maps to what the screen renders.'],
  ['data-model', 'Data model design', 'technical-depth', 'exploration', 'must', 2,
    'Ask for tables, relationships, and keys that back the feature.',
    'Probe "What if you also need to store X?"', 'Basic and well-constrained scope.'],
  ['client-server-split', 'Client vs server responsibilities', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask what runs on the client vs the server for this feature. Assess the distinction.',
    'Probe where validation and state live.'],
  ['simple-refresh', 'Keeping the UI current', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask how the list updates after another user edits it. Awareness-level assessment.',
    'Knowing that polling or refetch exists and why is sufficient.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['scaling-awareness', 'Basic scaling awareness', 'technical-depth', 'closing', 'must', 0,
    'Ask "What if 10x more users?" Assess awareness that caching and load balancing exist.',
    'Surface — basic awareness is sufficient.'],
]

const mid: CompactSlot[] = [
  ['req-flows-estimation', 'Requirements, flows, and rough scale', 'problem-solving', 'warm-up', 'must', 0,
    'Present a feature (feed comments, file upload). Expect proactive questions on flows, scale, read/write mix.',
    'Surface — assess flow clarification and rough estimation.', 'Collaborative format.'],
  ['end-to-end-arch', 'End-to-end architecture', 'technical-depth', 'exploration', 'must', 2,
    'Full slice: UI structure, rendering choice, API, services, DB, cache. Should move quickly across layers.',
    'Probe rendering strategy and technology choices with justification.'],
  ['api-contract', 'API contract the frontend consumes', 'technical-depth', 'exploration', 'must', 2,
    'Design the contract: pagination, filtering, error shapes, and how the client uses them.',
    'Probe over/under-fetching and how the UI handles partial failures.'],
  ['state-sync', 'Client state sync and caching', 'technical-depth', 'exploration', 'must', 2,
    'Cache strategy, invalidation, optimistic updates after a mutation. Must go beyond name-dropping.',
    'Probe "What if the optimistic update fails?" and stale-cache handling.'],
  ['data-model-indexing', 'Data model and read patterns', 'technical-depth', 'exploration', 'if-time', 2,
    'Schema with indexing and read patterns that match the screens. Avoid N+1 and over-fetching.',
    'Probe index selection and denormalization tradeoffs for the main view.'],
  ['realtime-or-async', 'Real-time or async behavior', 'technical-depth', 'exploration', 'if-time', 2,
    'Live updates (polling, SSE, websockets) or background work (upload processing, notifications).',
    'Probe "What happens when the connection drops or a job fails?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['failure-modes', 'Failure modes and deployment', 'operational', 'closing', 'must', 0,
    'Ask "What happens when X fails?" and how a full-stack change ships safely (migrations, version skew).',
    'Surface — monitoring and rollout awareness.'],
]

const senior: CompactSlot[] = [
  ['scope-definition', 'Scope definition from a vague brief', 'problem-solving', 'warm-up', 'must', 0,
    'Present a deliberately broad feature (collaborative editor, live dashboard). Candidate drives scope.',
    'Surface — assess quality of trade-off decisions made during scoping.', 'Fully candidate-led.'],
  ['comprehensive-arch', 'Comprehensive full-stack architecture', 'technical-depth', 'exploration', 'must', 2,
    'UI surfaces, rendering strategy, API for one or more clients, services, data stores. Move fast to leave deep-dive time.',
    'Probe why specific patterns and rendering choices over alternatives.'],
  ['component-deep-dive', 'Critical component deep-dive', 'technical-depth', 'exploration', 'must', 2,
    'Deep dive into 2-3 critical pieces (real-time sync, search, auth, upload) with implementation-level detail.',
    'Probe "What if this component fails?" and cascading effects up to the UI.',
    'Where senior interviews are won or lost.'],
  ['consistency-realtime', 'Consistency between client and source of truth', 'technical-depth', 'exploration', 'must', 2,
    'Cached client state vs the DB: invalidation, real-time propagation, conflict resolution. Must choose tradeoffs.',
    'Probe "Two clients edit the same record — what happens?" with a justified strategy.'],
  ['multi-client-scaling', 'Multi-client and scaling strategy', 'technical-depth', 'exploration', 'if-time', 2,
    'BFF vs shared API, scaling reads vs writes, CDN/edge, caching layers across the stack.',
    'Probe capacity reasoning and where the bottleneck moves under 100x load.'],
  ['perf-and-cost', 'End-to-end performance and cost', 'operational', 'exploration', 'if-time', 2,
    'Performance from query plan to Core Web Vitals, and the cost of the chosen architecture.',
    'Probe instrumentation and the highest-leverage optimization.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['system-evolution', 'System evolution and tech debt', 'technical-depth', 'closing', 'must', 0,
    'How does this design change over 3 years across both layers? How does full-stack tech debt accumulate?',
    'Surface — assess long-term, forward-looking reasoning.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('fullstack', 'system-design', '0-2', entry, [
    'Distributed systems or CAP theorem',
    'Sharding or cross-region data replication',
    'Real-time conflict resolution (CRDTs, OT)',
    'Multi-client API architecture (BFF, GraphQL federation)',
    'Complex scaling beyond basic caching and refetch',
  ]),
  template('fullstack', 'system-design', '3-6', mid, [
    'Organizational-level architecture',
    'Multi-region global systems',
    'Consensus algorithms (Paxos, Raft)',
    'Designs that stay at surface level with no client-server detail',
  ]),
  template('fullstack', 'system-design', '7+', senior, [
    'Basic well-constrained features (too simple)',
    'Interviewer driving the conversation',
    'Surface-level designs without deep dives',
    'Single correct answer problems',
    'Pure backend distributed-systems trivia over end-to-end reasoning',
  ]),
]
