import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── General × Behavioral × 0-2 ────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro', 'Background and motivations', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves. Calibrate scope expectations; accept academic, internship, and volunteer context.',
    'Surface only — move on after 2 minutes.', 'School, part-time jobs, and extracurriculars are all fair game.'],
  ['learning-agility', 'Learning a new skill quickly', 'adaptability', 'warm-up', 'must', 0,
    'Ask about quickly picking up a new skill under time pressure. Look for self-directed learning and persistence.',
    'Surface treatment — one follow-up at most.', 'Accept any domain: academic course, sport, side project.'],
  ['teamwork-collaboration', 'Working in a team setting', 'collaboration', 'exploration', 'must', 2,
    'Ask about collaborating effectively in a group. Look for a specific personal role, not collective "we".',
    'Isolate their contribution: "You said we — what specifically did YOU do?"',
    'Academic group projects and hackathons acceptable.'],
  ['adaptability-change', 'Adapting to unexpected change', 'adaptability', 'exploration', 'must', 2,
    'Ask about a plan that changed significantly mid-way. Look for flexible problem-solving, not just endurance.',
    'Probe what they did differently once the change happened.'],
  ['conflict-peer', 'Resolving a conflict with a peer', 'communication', 'exploration', 'must', 2,
    'Ask about a disagreement with a teammate. Look for both perspectives acknowledged and constructive resolution.',
    'Probe what they said and did, not just how they felt.'],
  ['initiative-self-motivation', 'Taking initiative without being asked', 'self-awareness', 'exploration', 'if-time', 1,
    'Ask about going beyond what was required. Look for proactivity and ownership of outcomes.',
    'Probe what prompted the initiative and what happened as a result.'],
  ['time-management', 'Juggling multiple priorities', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about managing competing deadlines. Look for a deliberate prioritization approach, not just hard work.',
    'Probe the framework: urgency, impact, asking for help.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-growth', 'Self-awareness and growth', 'self-awareness', 'closing', 'must', 0,
    'Ask what they want to develop and what excites them. Assess coachability and self-awareness.',
    'Surface — wrap up warmly.'],
]

// ─── General × Behavioral × 3-6 ────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['project-ownership', 'End-to-end ownership narrative', 'ownership', 'warm-up', 'must', 0,
    'Ask candidate to walk through a project they owned fully. Calibrate scope and impact expectations.',
    'Surface — use this to select follow-up topics.', 'Must show personal accountability for outcomes.'],
  ['influence-without-authority', 'Leading without formal authority', 'leadership', 'warm-up', 'must', 0,
    'Ask about influencing a decision or team when they had no direct authority.',
    'Surface — note the influence mechanism (data, relationships, framing) for deeper probing.',
    'Cross-functional influence is the hallmark differentiator at this level.'],
  ['accountability-failure', 'Owning a mistake or failure', 'self-awareness', 'exploration', 'must', 2,
    'Ask about a meaningful mistake and how they handled it. Look for accountability, not deflection.',
    'Probe what they said to the team, what changed in their behavior, and quantified impact if any.'],
  ['difficult-feedback', 'Giving or receiving difficult feedback', 'communication', 'exploration', 'must', 2,
    'Ask about delivering or receiving feedback that was hard. Look for directness paired with empathy.',
    'Probe the specific words used, the reaction, and the outcome.'],
  ['ambiguity-navigation', 'Driving a project through ambiguity', 'problem-solving', 'exploration', 'must', 2,
    'Ask about navigating unclear requirements or missing direction. Look for proactive scope definition.',
    'Probe what they did when they lacked information and how they aligned stakeholders.'],
  ['competing-priorities', 'Managing competing stakeholder demands', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about too many conflicting priorities from different stakeholders. Look for structured trade-off making.',
    'Probe the framework: urgency vs. impact, stakeholder communication, explicit trade-offs made.'],
  ['mentoring-others', 'Mentoring or developing a colleague', 'leadership', 'exploration', 'if-time', 2,
    'Ask about helping a less experienced colleague grow. Look for investment in others, not just task delegation.',
    'Probe the approach: how they diagnosed the gap and what changed for the mentee.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-leadership', 'Leadership philosophy and growth edge', 'leadership', 'closing', 'must', 0,
    'Ask how they would describe their leadership style and what they are actively working to improve.',
    'Surface — wrap up the interview by connecting to the role context.'],
]

// ─── General × Behavioral × 7+ ─────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-impact', 'Biggest organizational impact', 'leadership', 'warm-up', 'must', 0,
    'Ask about the highest-impact thing they have done in their career. This frames scope and leadership philosophy.',
    'Surface — calibrate how they define impact (team vs. org vs. market).', 'Must show institutional-level impact.'],
  ['transformational-change', 'Leading transformational change', 'leadership', 'exploration', 'must', 2,
    'Ask about creating meaningful change in an organization. Look for vision, coalition-building, and sustained execution.',
    'Probe who resisted, how alignment was built, and what outlasted them.',
    'Impact must extend well beyond their team; evidence of institutional change is required.'],
  ['culture-building', 'Building or shaping team culture', 'leadership', 'exploration', 'must', 2,
    'Ask how they have shaped engineering or organizational culture. Look for systemic approaches, not one-off events.',
    'Probe what practices or norms they introduced and how adoption happened.',
    'Shift from individual/team impact to organizational impact.'],
  ['ethical-decision', 'Navigating an ethical or values conflict', 'self-awareness', 'exploration', 'must', 2,
    'Ask about a situation where business pressure conflicted with values. Look for principled decision-making.',
    'Probe what trade-offs they weighed and how they communicated the decision.'],
  ['executive-communication', 'Influencing C-suite or board-level stakeholders', 'communication', 'exploration', 'must', 2,
    'Ask about shaping a significant decision with senior executives or board members.',
    'Probe the narrative they used, the objections they faced, and the outcome.'],
  ['scaling-team', 'Building and scaling a high-performing team', 'leadership', 'exploration', 'if-time', 2,
    'Ask about growing or restructuring a team to meet a strategic goal. Look for systems thinking.',
    'Probe hiring philosophy, performance culture, and how the team changed over time.'],
  ['short-vs-long-term', 'Balancing short-term delivery with long-term strategy', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about managing delivery pressure while protecting long-term investments.',
    'Probe specific trade-offs made and how they maintained team trust and direction.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['leadership-philosophy', 'Leadership philosophy and lasting legacy', 'leadership', 'closing', 'must', 0,
    'Ask how they articulate their leadership philosophy and what they hope to be remembered for.',
    'Surface — connects personal narrative to role expectations.', 'Failure to articulate a philosophy is a red flag at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('general', 'behavioral', '0-2', entry, [
    'Organizational strategy or direction-setting',
    'Cross-team influence with senior stakeholders',
    'Production incident management',
    'Multi-quarter project ownership',
    'Building engineering or org culture',
  ]),
  template('general', 'behavioral', '3-6', mid, [
    'Organizational-level strategy or company roadmap',
    'Hiring decisions or building teams from scratch',
    'Board or C-suite communication',
    'Pure academic or theoretical questions',
    'Individual-contributor-only stories without organizational impact',
  ]),
  template('general', 'behavioral', '7+', senior, [
    'Basic teamwork or collaboration stories',
    'Individual coding or task-completion stories',
    'Questions answerable without cross-functional scope',
    'Learning a new technology as the primary topic',
    'Questions an IC3/IC4 level could answer equally well',
  ]),
]
