import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── General × System Design × 0-2 ─────────────────────────────────────────
const entry: CompactSlot[] = [
  ['requirements-clarification', 'Requirements clarification', 'problem-solving', 'warm-up', 'must', 0,
    'Present a simple system prompt (URL shortener, rate limiter). Observe whether candidate asks clarifying questions first.',
    'Surface — note what they ask and what they miss.', 'Focus is potential and foundational reasoning, not production-ready designs.'],
  ['component-overview', 'High-level component overview', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask them to sketch the main components and data flow at a high level before drilling in.',
    'Surface — look for client → server → database awareness and correct data direction.'],
  ['api-design-basics', 'Basic API design', 'technical-breadth', 'exploration', 'must', 2,
    'Ask them to define the core REST endpoints for the system. Look for correct verb and resource naming.',
    'Probe: "What does the response look like if that request fails?"',
    'REST basics and knowing why components exist are the core test — not NGINX vs. AWS ALB.'],
  ['data-modeling', 'Simple data modeling', 'technical-breadth', 'exploration', 'must', 2,
    'Ask them to sketch the primary data entities and relationships. Look for reasonable normalization.',
    'Probe: "How would you store [specific field] and why?"'],
  ['scalability-intuition', 'Basic scalability reasoning', 'problem-solving', 'exploration', 'must', 2,
    'Ask what happens when the system gets 10x more traffic. Look for vertical vs. horizontal scaling awareness.',
    'Probe: "What component would break first and why?" — test bottleneck intuition.',
    'Can excel with solid fundamentals and first-principles reasoning.'],
  ['caching-load-balancing', 'Caching and load balancing concepts', 'technical-breadth', 'exploration', 'if-time', 2,
    'Ask why caching might help and where they would put it. Look for correct use case, not implementation depth.',
    'Probe: "What could go wrong with a cache in this design?"'],
  ['data-flow-explanation', 'Explaining data flow between components', 'communication', 'exploration', 'if-time', 1,
    'Ask them to narrate the request-response lifecycle through their design. Look for component interaction clarity.',
    'Probe any gap where they jump between components without explaining the handoff.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-design-gaps', 'Reflection on design gaps', 'self-awareness', 'closing', 'must', 0,
    'Ask what they would improve with more time. Look for honest gap recognition and learning curiosity.',
    'Surface — wrap up warmly.'],
]

// ─── General × System Design × 3-6 ─────────────────────────────────────────
const mid: CompactSlot[] = [
  ['requirements-and-constraints', 'Requirements gathering and constraint definition', 'problem-solving', 'warm-up', 'must', 0,
    'Present a standard system (notification service, distributed cache). Observe how they define scope, scale, and non-functional requirements.',
    'Surface — probe capacity estimation: QPS, storage, bandwidth.', '"Can they build end-to-end?" is the central question at this level.'],
  ['hld-component-breakdown', 'High-level architecture and component breakdown', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask for a high-level architecture diagram with key components. Calibrate component interaction clarity.',
    'Surface — note which components they mention proactively and which they omit.'],
  ['database-selection', 'Database selection and schema with trade-offs', 'technical-breadth', 'exploration', 'must', 2,
    'Ask why they chose a specific database type and how they would schema it for the given load pattern.',
    'Probe: "What consistency guarantees does that give you and what do you sacrifice?"',
    'Every decision needs explicit trade-off discussion — NoSQL sacrificing consistency for availability.'],
  ['caching-strategy', 'Caching strategy and CDN integration', 'technical-breadth', 'exploration', 'must', 2,
    'Ask about cache placement, eviction policy, and invalidation. Look for invalidation strategy depth beyond name-dropping Redis.',
    'Probe: "What happens when the cache and database are out of sync?"'],
  ['scalability-patterns', 'Scalability patterns — sharding, replication, partitioning', 'problem-solving', 'exploration', 'must', 2,
    'Ask how they would scale the critical bottleneck they identified. Look for sharding key reasoning.',
    'Probe: "How would you rebalance shards if one gets hot?"'],
  ['operational-concerns', 'Monitoring, logging, and operational concerns', 'technical-breadth', 'exploration', 'if-time', 2,
    'Ask what they would instrument and alert on. Missing this signals lack of real production ownership.',
    'Probe: "How would you know the system is degrading before users complain?"'],
  ['lld-critical-component', 'Low-level design of a critical component', 'technical-breadth', 'exploration', 'if-time', 2,
    'Ask them to deep-dive one critical component (e.g. rate limiter, queue consumer). Look for API, data model, and concurrency reasoning.',
    'Probe: "What happens under concurrent writes from multiple instances?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tradeoff-summary', 'Trade-off summary and design evolution', 'communication', 'closing', 'must', 0,
    'Ask them to summarize the top two trade-offs in their design and how they would revisit them as scale grows.',
    'Surface — assess executive communication of design rationale.'],
]

// ─── General × System Design × 7+ ───────────────────────────────────────────
const senior: CompactSlot[] = [
  ['business-to-architecture', 'Business requirements to technical architecture translation', 'leadership', 'warm-up', 'must', 0,
    'Present a complex open-ended problem. Observe how they translate business goals into technical constraints before drawing boxes.',
    'Surface — look for business vocabulary alongside technical rationale.', 'Shift from "how to build it" to "how to make it succeed in a real organization."'],
  ['cross-cutting-concerns', 'Proactively addressing cross-cutting concerns', 'technical-breadth', 'warm-up', 'must', 0,
    'Without prompting, observe whether they raise security, privacy, compliance, and observability proactively.',
    'Surface — note gaps for follow-up; must address non-functional requirements without prompting.'],
  ['large-scale-distributed', 'Large-scale distributed system design', 'problem-solving', 'exploration', 'must', 2,
    'Ask how they would design the system for millions of users across regions. Look for global consistency and partition reasoning.',
    'Probe: "What happens if the primary region fails? Walk me through the failover."',
    'Must scope problems and limit blast radius of inevitable failures.'],
  ['conways-law-alignment', 'Organizational alignment with architecture', 'leadership', 'exploration', 'must', 2,
    'Ask how they would structure teams and ownership boundaries to match the proposed architecture.',
    'Probe: "What happens to the architecture if two of these teams merge?"',
    'Conway\'s Law awareness — team structure shaped by or shaping architecture.'],
  ['failure-mode-analysis', 'Failure mode analysis and disaster recovery', 'problem-solving', 'exploration', 'must', 2,
    'Ask them to enumerate the top failure modes and their recovery strategies. Look for structured fault taxonomy.',
    'Probe: "What\'s the RTO and RPO for each scenario and how do you test that?"'],
  ['technology-migration', 'Technology evaluation and migration strategy', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how they would evaluate replacing a core component and execute the migration with zero downtime.',
    'Probe: "How do you roll back if the new system performs worse under production load?"'],
  ['cost-optimization', 'Cost optimization at scale', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how they would identify and reduce infrastructure costs while maintaining reliability SLAs.',
    'Probe specific mechanisms: spot instances, caching, async offload, tiered storage.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-ownership-strategy', 'Multi-team ownership and long-term API contracts', 'leadership', 'closing', 'must', 0,
    'Ask how they would establish API contracts and ownership boundaries to allow independent team evolution.',
    'Surface — connect to their experience leading major design efforts at org level.', 'Missing team boundaries and ownership is a red flag at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('general', 'system-design', '0-2', entry, [
    'Advanced distributed systems (Paxos, Raft, two-phase commit)',
    'Microservices orchestration or service mesh configuration',
    'Multi-region replication strategies',
    'Candidate-led open-ended format without interviewer guidance',
    'Expecting production-ready designs with full operational coverage',
  ]),
  template('general', 'system-design', '3-6', mid, [
    'Org-level architectural strategy or multi-year roadmaps',
    'Conway\'s Law team alignment without prompting',
    'Board or executive-level communication scenarios',
    'Theoretical distributed systems without real-world constraint grounding',
    'Rushing into design without requirements — always stop and probe scope first',
  ]),
  template('general', 'system-design', '7+', senior, [
    'Narrow well-constrained problems without organizational context',
    'Basic CRUD API design without scale or failure mode discussion',
    'Reciting specific tool configurations without strategic rationale',
    'Treating the interview as a coding exercise rather than a strategic discussion',
    'Ignoring cost, security, or compliance dimensions',
  ]),
]
