import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── General × Technical × 0-2 ─────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['technical-background', 'Technical background and interests', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask the candidate to describe their technical background and what technologies excite them most.',
    'Surface only — calibrate scope; no deep probing yet.', 'Foundational reasoning and learning ability matter more than depth.'],
  ['problem-approach', 'Approaching an unfamiliar problem', 'problem-solving', 'warm-up', 'must', 0,
    'Ask how they break down a problem they have not seen before. Look for systematic decomposition.',
    'Surface — note if they ask clarifying questions before diving in.'],
  ['cs-fundamentals', 'Core CS concept explanation', 'technical-breadth', 'exploration', 'must', 2,
    'Ask them to explain a fundamental CS concept (data structures, memory, etc.) in plain terms.',
    'Probe the why behind the concept — can they explain trade-offs or real-world use?',
    'Conceptual clarity over encyclopedic coverage; accept any accessible analogy.'],
  ['debugging-method', 'Debugging a technical problem', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a time they were stuck on a bug and how they resolved it. Look for systematic methodology.',
    'Probe the actual diagnostic steps, not just the fix.',
    'Limited-scope debugging stories expected; academic context valid.'],
  ['learning-new-tech', 'Learning a new technology or tool', 'adaptability', 'exploration', 'must', 2,
    'Ask about picking up a technology they did not know. Look for a deliberate learning strategy.',
    'Probe what resources they used, how long it took, and where they got stuck.'],
  ['sdlc-awareness', 'Software development lifecycle understanding', 'technical-breadth', 'exploration', 'if-time', 1,
    'Ask how they understand the typical path from idea to shipped software. Look for awareness of testing, review, and deployment.',
    'Surface probe — not expecting production depth; assess conceptual completeness.'],
  ['technical-communication', 'Explaining a technical concept to a non-technical person', 'communication', 'exploration', 'if-time', 2,
    'Ask about a time they explained something technical to someone without a technical background.',
    'Probe the analogy or framing they used and whether it landed.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-curiosity', 'Technical curiosity and growth direction', 'self-awareness', 'closing', 'must', 0,
    'Ask what technical topic they are most curious about right now and how they are pursuing it.',
    'Surface — wrap up warmly; assess genuine enthusiasm.'],
]

// ─── General × Technical × 3-6 ─────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['system-thinking-intro', 'System design walk-through', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask candidate to walk through a system they built or contributed to. Calibrate scope and architectural awareness.',
    'Surface — listen for component interaction, not implementation details.', 'Must show end-to-end ownership and system-level thinking.'],
  ['architecture-decision', 'Key architectural or technical decision', 'problem-solving', 'warm-up', 'must', 0,
    'Ask about a significant technical decision they drove. Calibrate ability to weigh trade-offs.',
    'Surface — pick the most interesting decision for deeper follow-up.'],
  ['tradeoff-analysis', 'Trade-off reasoning in design', 'technical-breadth', 'exploration', 'must', 2,
    'Probe a specific decision from warm-up — why that approach over alternatives?',
    'Probe what constraints shaped the decision and what they would change with hindsight.',
    'Explicit trade-off discussion is the key differentiator at this level.'],
  ['scalability-reasoning', 'Scalability and performance considerations', 'technical-breadth', 'exploration', 'must', 2,
    'Ask how they approached scale or performance in a real project. Look for estimation and bottleneck analysis.',
    'Probe specific bottlenecks identified and how they were addressed.'],
  ['api-schema-design', 'API or data schema design', 'technical-breadth', 'exploration', 'must', 2,
    'Ask about designing an API or data model. Look for clarity, consistency, and forward-compatibility thinking.',
    'Probe how they handled versioning, validation, or evolving requirements.'],
  ['code-review-quality', 'Code review philosophy and quality standards', 'technical-breadth', 'exploration', 'if-time', 2,
    'Ask what they look for in code review and how they give feedback. Look for quality mindset beyond bug-finding.',
    'Probe a specific example of a code review that changed the direction of a design.'],
  ['debugging-complex', 'Debugging a multi-component production issue', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about isolating a hard bug in a distributed or multi-layer system. Look for systematic diagnosis.',
    'Probe timeline, tools used, and how they narrowed the blast radius.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-mentoring', 'Technical mentoring and growth', 'leadership', 'closing', 'must', 0,
    'Ask how they help less experienced engineers grow and what mentoring approach they use.',
    'Surface — one example suffices; assess investment in others.'],
]

// ─── General × Technical × 7+ ───────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['tech-strategy', 'Technology strategy and business alignment', 'leadership', 'warm-up', 'must', 0,
    'Ask how they have aligned a major technical initiative with business goals. Calibrate strategic scope.',
    'Surface — listen for business vocabulary alongside technical rationale.', 'Direction-setting distinguishes senior from mid-level.'],
  ['architecture-vision', 'Architecture vision and roadmap', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask about a technical roadmap or architecture vision they authored or drove. Calibrate planning horizon.',
    'Surface — note the planning horizon and how they secured buy-in.'],
  ['tech-evaluation', 'Technology evaluation and selection methodology', 'problem-solving', 'exploration', 'must', 2,
    'Ask how they approach evaluating and selecting technology for a significant investment.',
    'Probe the criteria used, how they managed organizational resistance, and the outcome.',
    'Must show a repeatable methodology, not just a one-off decision.'],
  ['cross-team-influence', 'Cross-team technical influence and consensus', 'leadership', 'exploration', 'must', 2,
    'Ask about building consensus on a technically contentious decision across teams.',
    'Probe who opposed, what data was used, and how dissent was incorporated.'],
  ['security-compliance', 'Security, privacy, and compliance in design', 'technical-breadth', 'exploration', 'must', 2,
    'Ask how they have embedded security and privacy requirements into a system\'s design.',
    'Probe specific threat models considered and how they balanced security with delivery speed.'],
  ['tech-debt-innovation', 'Managing technical debt while enabling innovation', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how they balance foundational investment with new feature delivery. Look for a systematic approach.',
    'Probe how they quantified debt cost and made the case for investment.'],
  ['org-design', 'Organizational design for engineering effectiveness', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they have structured teams or changed team topology to improve engineering outcomes.',
    'Probe Conway\'s Law awareness — how team structure shaped (or was shaped by) the architecture.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-legacy', 'Technical legacy and leadership impact', 'leadership', 'closing', 'must', 0,
    'Ask what technical or organizational legacy they are most proud of and what they hope to build here.',
    'Surface — connect their arc to the role.', 'Inability to articulate a technical vision is a red flag at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('general', 'technical', '0-2', entry, [
    'Production system ownership or on-call incidents',
    'Cross-team architectural decisions',
    'Advanced distributed systems concepts',
    'Technology strategy or roadmap planning',
    'Deep specialization in any one technology',
  ]),
  template('general', 'technical', '3-6', mid, [
    'Organizational technology strategy',
    'Board or executive-level communication',
    'Team hiring or org design decisions',
    'Pure algorithmic or academic theory',
    'Defaulting to "it depends" without committing to a trade-off',
  ]),
  template('general', 'technical', '7+', senior, [
    'Basic algorithm or data-structure questions',
    'Individual debugging stories without systemic context',
    'Technology decisions with only team-level scope',
    'Questions an IC4 could answer equally well',
    'Clever implementations without organizational context',
  ]),
]
