import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── General × Case Study × 0-2 ─────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['problem-comprehension', 'Problem comprehension and clarification', 'problem-solving', 'warm-up', 'must', 0,
    'Present a simple prompt (e.g. market sizing or basic profitability). Look for clarifying questions before structuring.',
    'Surface — note what they ask and what they miss.', 'Structured thinking matters far more than business expertise.'],
  ['framework-construction', 'Building a problem framework', 'problem-solving', 'warm-up', 'must', 0,
    'Ask candidate to organize the problem space before diving in. Look for MECE structure built from scratch.',
    'Surface — assess whether they adapt the framework or apply a memorized template rigidly.'],
  ['quantitative-estimation', 'Quantitative reasoning and estimation', 'problem-solving', 'exploration', 'must', 2,
    'Ask them to size the market or estimate a key number. Look for logical buildup from known anchors.',
    'Probe the assumptions: "Walk me through how you got that number."',
    'Simple arithmetic and clear logic under pressure are the core test.'],
  ['hypothesis-formation', 'Forming and testing a hypothesis', 'problem-solving', 'exploration', 'must', 2,
    'Ask what they believe the key driver is and how they would test it. Look for prioritized, falsifiable hypotheses.',
    'Probe: "What data would confirm or disprove that?" — avoid vague analytical gestures.'],
  ['data-interpretation', 'Interpreting provided data', 'problem-solving', 'exploration', 'must', 2,
    'Provide a simple table or chart mid-case. Look for insight extraction rather than description of numbers.',
    'Probe: "So what does that tell us?" — push toward a conclusion, not a summary.'],
  ['handling-ambiguity', 'Handling ambiguity with limited data', 'adaptability', 'exploration', 'if-time', 2,
    'Introduce a constraint or missing piece of information. Look for structured response, not freezing.',
    'Probe what reasonable assumptions they make and how they signal uncertainty.'],
  ['logical-recommendation', 'Communicating a logical recommendation', 'communication', 'exploration', 'if-time', 1,
    'Ask for a recommendation based on their analysis. Look for clear "so what" with supporting rationale.',
    'Probe whether they can defend it if challenged — look for conviction, not rigidity.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-process-reflection', 'Reflection on case approach', 'self-awareness', 'closing', 'must', 0,
    'Ask what they would do differently if they had more time. Look for self-awareness about structure and gaps.',
    'Surface — wrap up warmly.'],
]

// ─── General × Case Study × 3-6 ─────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['problem-framing', 'Multi-stakeholder problem framing', 'problem-solving', 'warm-up', 'must', 0,
    'Present an ambiguous business scenario with multiple stakeholders. Assess how they structure scope.',
    'Surface — note whether they map stakeholders and define success metrics before diving in.',
    'Shift from "can you structure" to "can you handle conflicting demands independently."'],
  ['hypothesis-issue-tree', 'Hypothesis-driven investigation', 'problem-solving', 'warm-up', 'must', 0,
    'Ask them to build an issue tree and prioritize the most likely root cause. Look for 80/20 reasoning.',
    'Surface — probe which branch they pursue first and why.'],
  ['scenario-analysis', 'Scenario analysis and sensitivity testing', 'problem-solving', 'exploration', 'must', 2,
    'Introduce a second scenario or changed constraint mid-case. Look for adaptive reasoning.',
    'Probe: "How does your recommendation change if that assumption is wrong?"',
    'Benchmarking against industry standards and root cause analysis expected.'],
  ['advanced-framework', 'Applying a strategic framework', 'problem-solving', 'exploration', 'must', 2,
    'Ask them to apply SWOT, Porter\'s Five Forces, or a value chain analysis to the case.',
    'Probe whether the framework choice is reasoned or reflexive — experienced interviewers spot memorization.',
    'Must synthesize data into a coherent narrative, not just fill in framework boxes.'],
  ['data-synthesis', 'Synthesizing data across multiple sources', 'problem-solving', 'exploration', 'must', 2,
    'Provide two or three data sources with partially conflicting signals. Look for triangulation and judgment.',
    'Probe: "These two data points conflict — which would you weight more and why?"'],
  ['strategic-recommendation', 'Strategic recommendation with roadmap', 'communication', 'exploration', 'if-time', 2,
    'Ask for a recommendation with implementation steps. Look for feasibility awareness alongside strategic logic.',
    'Probe: "What are the top two risks in executing this and how would you mitigate them?"'],
  ['risk-assessment', 'Risk assessment and mitigation planning', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask what could go wrong with their recommended approach. Look for structured risk mapping.',
    'Probe severity and likelihood framing — not just a list of bad things.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-stakeholder-comm', 'Communicating findings persuasively', 'communication', 'closing', 'must', 0,
    'Ask how they would present their recommendation to a skeptical senior leader. Look for audience-aware framing.',
    'Surface — wrap up by assessing their executive communication instinct.'],
]

// ─── General × Case Study × 7+ ──────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['org-transformation-framing', 'Organizational transformation framing', 'leadership', 'warm-up', 'must', 0,
    'Present an ambiguous transformation scenario (e.g. market disruption or M&A integration). Assess how they frame leadership context.',
    'Surface — note whether they probe organizational culture and people dimensions alongside strategy.',
    'Case is a leadership demonstration — not an academic exercise.'],
  ['strategic-vision', 'Strategic vision development and communication', 'leadership', 'warm-up', 'must', 0,
    'Ask how they would develop and communicate a compelling vision for the transformation.',
    'Surface — calibrate articulation clarity and stakeholder framing instinct.'],
  ['executive-decision-making', 'Executive decision-making under uncertainty', 'problem-solving', 'exploration', 'must', 2,
    'Introduce a key decision point mid-case where data is incomplete. Look for conviction with acknowledged uncertainty.',
    'Probe: "What would it take for you to change course?" — assess adaptability vs. stubbornness.',
    'Must demonstrate coalition and alignment building, not just analytical correctness.'],
  ['ma-evaluation', 'M&A evaluation or strategic partnership', 'problem-solving', 'exploration', 'must', 2,
    'Ask how they would evaluate a proposed acquisition or partnership. Look for strategic and cultural due diligence.',
    'Probe: "What integration risks are you most concerned about and why?"'],
  ['competitive-positioning', 'Market disruption response and competitive positioning', 'problem-solving', 'exploration', 'must', 2,
    'Introduce a competitive threat mid-case. Look for market anticipation thinking and option generation.',
    'Probe long-term positioning vs. short-term reaction trade-off.',
    'Strategic thinking: anticipate trends, identify threats, develop long-term positioning.'],
  ['program-governance', 'Cross-functional program design and governance', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they would design governance for a multi-team transformation. Look for clarity on RACI and decision rights.',
    'Probe: "How do you handle a business unit that does not cooperate?"'],
  ['value-creation', 'Long-term value creation vs. short-term performance', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how they manage pressure to deliver quarterly results while building long-term competitive position.',
    'Probe specific mechanisms: OKRs, resource allocation, board communication.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-alignment-legacy', 'Building alignment and lasting impact', 'leadership', 'closing', 'must', 0,
    'Ask how they would ensure the transformation outlasts their tenure. Look for institutional embedding instinct.',
    'Surface — connect to their leadership philosophy and evidence from past roles.', 'Strategy without evidence of execution capability is a red flag at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('general', 'case-study', '0-2', entry, [
    'Deep industry or domain expertise',
    'Multi-stakeholder political navigation',
    'M&A or advanced strategic framework application',
    'Board-level communication scenarios',
    'Expecting candidate-led format without guidance',
  ]),
  template('general', 'case-study', '3-6', mid, [
    'Memorized frameworks applied without adaptation',
    'Org-level transformation or executive board scenarios',
    'Multi-year strategic roadmaps',
    'Team-building or hiring decisions',
    'Analysis paralysis — always push for a converged recommendation',
  ]),
  template('general', 'case-study', '7+', senior, [
    'Basic market-sizing or profitability cases',
    'Narrow well-constrained problems',
    'Academic framework recitation without business context',
    'Individual-contributor execution stories without strategic scope',
    'Data-heavy analysis without people and culture dimension',
  ]),
]
