import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── General × Coding × 0-2 ─────────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['problem-clarification', 'Clarifying requirements before coding', 'problem-solving', 'warm-up', 'must', 0,
    'Present a problem and observe whether they ask clarifying questions before diving in. Look for systematic decomposition.',
    'Surface — note if they define inputs, outputs, and constraints proactively.', 'Problem-solving approach valued over an optimal solution.'],
  ['pattern-recognition', 'Pattern recognition and approach selection', 'problem-solving', 'warm-up', 'must', 0,
    'Ask what technique or pattern they recognize in the problem. Look for naming known patterns (sliding window, hashing, etc.).',
    'Surface — probe their reasoning for the pattern choice, not just the name.'],
  ['array-string-manipulation', 'Array or string manipulation problem', 'problem-solving', 'exploration', 'must', 2,
    'Assign an easy-medium array or string problem. Look for correct logic and communicated reasoning throughout.',
    'Probe: "Walk me through what your code does on this input" — silence while coding is a signal.',
    'Demonstrating systematic breakdown matters more than encyclopedic knowledge.'],
  ['hash-map-application', 'Hash map or set for lookup optimization', 'problem-solving', 'exploration', 'must', 2,
    'Assign a problem best solved with a hash map. Look for recognition of the O(n) vs. O(n²) trade-off.',
    'Probe: "Why did you choose that data structure over a simple loop?"'],
  ['edge-case-handling', 'Edge case identification and handling', 'problem-solving', 'exploration', 'must', 2,
    'After they reach a working solution, ask what edge cases they would test. Look for systematic enumeration.',
    'Probe specific cases: empty input, single element, duplicates, large values.',
    'Ignoring edge cases is one of the most common entry-level failure modes.'],
  ['complexity-analysis', 'Big O complexity analysis', 'technical-breadth', 'exploration', 'if-time', 1,
    'Ask for time and space complexity of their solution. Look for clear reasoning, not just a correct label.',
    'Probe: "Can you do better?" — assess if they recognize optimization opportunities.'],
  ['recursion-or-traversal', 'Basic recursion or tree traversal', 'problem-solving', 'exploration', 'if-time', 2,
    'Assign a simple recursion or binary tree problem. Look for base case identification and call stack reasoning.',
    'Probe: "What would happen if the input were very large?" — introduce stack overflow awareness.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-approach-reflection', 'Reflection on approach and alternatives', 'self-awareness', 'closing', 'must', 0,
    'Ask if they see any limitations in their solution and what they would improve with more time.',
    'Surface — look for self-awareness and intellectual curiosity about optimization.'],
]

// ─── General × Coding × 3-6 ─────────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['brute-force-to-optimal', 'Iterative optimization from brute force', 'problem-solving', 'warm-up', 'must', 0,
    'Present a medium problem. Ask for a brute-force solution first, then iterative optimization. Calibrate their optimization instinct.',
    'Surface — listen for them articulating the trade-off at each step.', 'Shift from "can they solve it" to "how well do they solve it."'],
  ['code-quality-structure', 'Code quality and modular structure', 'technical-breadth', 'warm-up', 'must', 0,
    'Observe code organization while they solve — helper functions, naming, DRY principles. Calibrate quality instinct.',
    'Surface — note messiness for a follow-up probe on refactoring.'],
  ['dynamic-programming', 'Dynamic programming or greedy approach', 'problem-solving', 'exploration', 'must', 2,
    'Assign a medium DP or greedy problem. Look for subproblem decomposition and clear recurrence relation.',
    'Probe: "How did you recognize this required DP?" — assess pattern literacy.',
    'Language mastery matters — use idioms and standard library, not just syntax.'],
  ['complex-data-structures', 'Heap, trie, or union-find application', 'problem-solving', 'exploration', 'must', 2,
    'Assign a problem requiring a heap or advanced structure. Look for correct structure selection with trade-off rationale.',
    'Probe: "What does using a heap buy you here versus sorting?"'],
  ['testing-debugging', 'Testing and debugging methodology', 'problem-solving', 'exploration', 'must', 2,
    'Introduce a subtle bug in a code snippet or ask them to write test cases for their solution.',
    'Probe their test case strategy: happy path, boundary, failure modes.',
    'Code quality is first-class at this level — testing approach reveals maturity.'],
  ['api-interface-design', 'API or interface design in code', 'technical-breadth', 'exploration', 'if-time', 2,
    'Ask them to design a class or function interface before implementing. Look for forward-compatibility thinking.',
    'Probe: "How would this interface need to change if we added feature X?"'],
  ['tradeoff-articulation', 'Time vs. space complexity trade-off articulation', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask them to compare two solutions to the same problem on time vs. space. Look for explicit trade-off language.',
    'Probe: "In what production scenario would you prefer the slower but space-efficient version?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-code-review', 'Code review perspective on their solution', 'communication', 'closing', 'must', 0,
    'Ask them to review their own solution as if they were a senior engineer reviewing a junior\'s PR.',
    'Surface — assess self-awareness and quality standard.'],
]

// ─── General × Coding × 7+ ──────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['architecture-in-code', 'Architectural thinking expressed in code', 'technical-breadth', 'warm-up', 'must', 0,
    'Present an open-ended design-and-implement problem. Assess how they establish module boundaries and interfaces first.',
    'Surface — observe whether they design before they code.', 'Coding becomes a vehicle to demonstrate architectural thinking.'],
  ['production-readiness-framing', 'Production-readiness framing', 'problem-solving', 'warm-up', 'must', 0,
    'Ask what they would consider to make their solution production-ready. Look for error handling, observability, fault tolerance.',
    'Surface — calibrate operational maturity; note gaps for follow-up.',
    'Bar is not just "correct and optimal" but "production-ready and maintainable by a team."'],
  ['complex-algorithm-design', 'Complex algorithm design', 'problem-solving', 'exploration', 'must', 2,
    'Assign a hard algorithm problem (advanced DP, graph, or optimization). Look for systematic approach and justification of choices.',
    'Probe: "Is there a different formulation of this problem that leads to a simpler algorithm?"',
    'Must demonstrate mentoring capability in how they approach and narrate the problem.'],
  ['scalable-code-patterns', 'Concurrency or distributed algorithm patterns', 'technical-breadth', 'exploration', 'must', 2,
    'Ask how their solution would change if multiple threads or processes ran it simultaneously.',
    'Probe race conditions, locking strategies, and idempotency.'],
  ['api-contract-design', 'API contract design and backward compatibility', 'technical-breadth', 'exploration', 'must', 2,
    'Ask them to design a public API for their solution with versioning and extensibility in mind.',
    'Probe: "How would you deprecate a field without breaking existing clients?"'],
  ['error-resilience', 'Error handling and fault tolerance in code', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how they would handle partial failures, retries, and timeouts in their implementation.',
    'Probe specific failure scenarios and recovery paths.'],
  ['code-review-mentoring', 'Code review and mentoring perspective', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they would review a junior engineer\'s solution to this problem. Look for teaching instinct.',
    'Probe: "What feedback would you prioritize and how would you phrase it?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-design-tradeoffs', 'Design trade-offs and evolution path', 'problem-solving', 'closing', 'must', 0,
    'Ask what assumptions they made that they would revisit and what the next evolution of the design would be.',
    'Surface — connects technical rigor to forward-thinking engineering judgment.', 'Clever but unreadable code or ignoring extensibility is a red flag.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('general', 'coding', '0-2', entry, [
    'Hard LeetCode problems or advanced algorithm design',
    'Concurrency, threading, or distributed system code',
    'Production-grade API design or versioning',
    'Questions requiring extensive domain knowledge',
    'Expecting polished or highly optimized code without guidance',
  ]),
  template('general', 'coding', '3-6', mid, [
    'Pure algorithmic trivia without real-world application context',
    'Problems requiring only beginner-level patterns (two-pointer, linear scan)',
    'Ignoring code quality — always probe for DRY and modular helpers',
    'Not discussing testing or edge cases after a working solution',
    'Over-optimizing before reaching a correct solution',
  ]),
  template('general', 'coding', '7+', senior, [
    'Easy or medium algorithm problems without architectural extension',
    'Coding without a design discussion first',
    'Solutions that work but ignore production concerns',
    'Clever implementations without readability or team-ownership considerations',
    'Individual optimization stories without mentoring or leadership dimension',
  ]),
]
