import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Marketing × Behavioral × 0-2 ───────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro-campaign', 'Intro and a campaign you\'re proud of', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves and a campaign they\'re proud of. Look for ownership of a real piece of it.',
    'Surface — use to pick follow-up topics.', 'Academic, internship, or personal-project campaigns are all acceptable.'],
  ['motivation-marketing', 'Why marketing, and which area', 'motivation', 'warm-up', 'must', 0,
    'Ask what drew them to marketing and whether they lean creative or analytical. Calibrate identity.',
    'One follow-up at most — keep it warm.', 'Assess curiosity and learning mindset over depth.'],
  ['campaign-underperformed', 'A campaign that underperformed', 'self-awareness', 'exploration', 'must', 2,
    'Ask about a campaign that missed. Look for honest diagnosis and what they changed after.',
    'Probe what the data said and what they did differently next time — not blame on the agency or budget.',
    'Small-scope campaigns count; focus on the learning.'],
  ['mid-execution-pivot', 'Pivoting a strategy mid-execution', 'adaptability', 'exploration', 'must', 2,
    'Ask about changing course on a live campaign. Look for decisiveness and a reason grounded in signal.',
    'Probe what triggered the pivot and how fast they moved.'],
  ['receiving-creative-feedback', 'Receiving tough feedback on creative work', 'self-awareness', 'exploration', 'must', 2,
    'Ask about subjective critique on their creative ("it doesn\'t land"). Look for non-defensiveness.',
    'Probe what they changed and how they reconciled taste with goals.'],
  ['cross-team-collab', 'Working with design or product on a campaign', 'collaboration', 'exploration', 'if-time', 1,
    'Ask about collaborating across functions to ship a campaign. Look for communication and give-and-take.',
    'Probe a specific friction and how they handled it.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-marketing-excitement', 'What marketing problems excite you most', 'motivation', 'closing', 'must', 0,
    'Ask what kind of marketing problems they want to work on next. Assess enthusiasm and direction.',
    'Surface — wrap up warmly.'],
]

// ─── Marketing × Behavioral × 3-6 ───────────────────────────────────────────
const mid: CompactSlot[] = [
  ['marketing-philosophy', 'How your marketing philosophy evolved', 'motivation', 'warm-up', 'must', 0,
    'Ask how their approach and identity developed with experience. Calibrate maturity and point of view.',
    'Surface — use to choose deep-dives.', 'Must reflect on real campaigns with real outcomes.'],
  ['fighting-for-budget', 'Fighting for marketing budget', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about winning budget against competing priorities. Look for an ROI-grounded argument.',
    'Probe how they quantified the case and what won the decision.',
    'Measurable ROI framing differentiates at this level.'],
  ['brand-crisis', 'Navigating a brand crisis or negative PR', 'leadership', 'exploration', 'must', 2,
    'Ask about handling a reputation hit or PR problem. Look for calm, structured response and recovery.',
    'Probe the first moves and how they measured recovery.'],
  ['brand-vs-performance', 'Navigating brand-vs-performance tension', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask about a time brand and performance goals conflicted. Look for principled tradeoff reasoning.',
    'Probe how they decided and what they gave up.'],
  ['influence-positioning', 'Influencing product on positioning', 'stakeholder-management', 'exploration', 'if-time', 2,
    'Ask about aligning with product when positioning views differed. Look for influence without authority.',
    'Probe how they built agreement on the message.'],
  ['creative-risk', 'Taking a creative risk', 'strategic-thinking', 'exploration', 'if-time', 2,
    'Ask about a bold creative bet. Look for a deliberate decision process, not recklessness.',
    'Probe how they de-risked it and what the outcome was.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retrospective-campaign-decision', 'A campaign decision you\'d make differently', 'self-awareness', 'closing', 'must', 0,
    'Ask what they\'d change knowing what they know now. Assess honesty and growth.',
    'Surface — one example suffices.'],
]

// ─── Marketing × Behavioral × 7+ ────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['marketing-leadership-philosophy', 'Marketing leadership philosophy', 'leadership', 'warm-up', 'must', 0,
    'Ask how they connect marketing to business strategy and how they lead a marketing org. Calibrate scope.',
    'Surface — identify which leadership dimensions to probe.', 'Must show impact across brand, growth, people, and business.'],
  ['building-marketing-org', 'Building a marketing organization', 'leadership', 'exploration', 'must', 2,
    'Ask about building a marketing team from early stage to mature. Look for hiring sequence and structure.',
    'Probe the first key hires and how the org evolved.',
    'Scope must span building a function, not running one campaign.'],
  ['product-marketing-alignment', 'Aligning product and marketing on positioning', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about resolving conflicting positioning views with product leadership. Look for a resolution framework.',
    'Probe how they got durable alignment, not a one-time compromise.'],
  ['leading-market-shift', 'Leading through a sudden market shift', 'leadership', 'exploration', 'must', 2,
    'Ask about steering marketing through a major market or category change. Look for decisiveness under ambiguity.',
    'Probe the hardest call and how they communicated it.'],
  ['brand-reputation-crisis', 'Managing a brand-reputation crisis at scale', 'leadership', 'exploration', 'if-time', 2,
    'Ask about leading through a serious brand crisis. Look for org-wide coordination and recovery.',
    'Probe what they changed structurally afterward.'],
  ['marketing-culture', 'Building marketing culture', 'leadership', 'exploration', 'if-time', 2,
    'Ask about shaping how a marketing team works and creates. Look for systems, not slogans.',
    'Probe what practices outlasted them.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['marketing-bet-failure', 'A marketing bet that didn\'t pan out', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant initiative that failed. Look for organizational learning.',
    'Probe systemic changes, not just personal lessons.', 'Failure carries more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('marketing', 'behavioral', '0-2', entry, [
    'Building marketing orgs or leading through market shifts',
    'Executive budget and board influence',
    'Deep martech or attribution methodology',
    'Org-wide brand-crisis leadership',
    'Generic conflict questions without a marketing context',
  ]),
  template('marketing', 'behavioral', '3-6', mid, [
    'Entry-level "why marketing" framing',
    'Building a marketing org from scratch (senior territory)',
    'Generic teamwork stories without a campaign context',
    'Accepting "the campaign failed" without probing the diagnosis',
    'Pure analytics methodology instead of judgment',
  ]),
  template('marketing', 'behavioral', '7+', senior, [
    'Individual campaign execution stories',
    'Questions a mid-level marketer could answer equally well',
    'Generic leadership with no marketing or brand stakes',
    'Accepting "we rebuilt the brand" without probing the org and culture change',
  ]),
]
