import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Mechanical × Technical × 0-2 ───────────────────────────────────────────
const entry: CompactSlot[] = [
  ['technical-background', 'Engineering background and interests', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask the candidate to describe their mechanical background and which disciplines (thermal, structures, CAD) they enjoy most.',
    'Surface only — calibrate scope; no deep probing yet.', 'Fundamentals and reasoning matter more than breadth at this level.'],
  ['problem-setup', 'Setting up an analysis problem', 'problem-solving', 'warm-up', 'must', 0,
    'Ask how they begin a hand analysis — free-body diagram, assumptions, units. Look for systematic setup.',
    'Surface — note whether they draw the FBD and state assumptions before computing.'],
  ['strength-of-materials', 'Beam stress and deflection', 'technical-depth', 'exploration', 'must', 2,
    'Pose a simple loaded-beam problem and ask them to reason to a stress and deflection estimate.',
    'Probe where the max stress is, what assumptions they made, and whether the answer\'s magnitude is plausible.',
    'Reward correct units and a clean FBD over a memorized formula constant.'],
  ['factor-of-safety', 'Factor of safety and material choice', 'technical-depth', 'exploration', 'must', 2,
    'Ask what a factor of safety means and how they would pick one and a material for a simple bracket.',
    'Probe static vs. fatigue, uncertainty in loads, and why they chose that material.',
    'Conceptual understanding over handbook values; "I\'d look up the yield strength" is fine.'],
  ['thermo-energy-balance', 'First-law energy balance', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to reason through a simple energy balance — heating water, a piston, or a heat load. Look for the first law applied correctly.',
    'Probe what they treated as the system, what flows in and out, and the units.',
    'Basic conduction/convection intuition is enough; depth not expected.'],
  ['cad-competence', 'CAD modeling approach', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask how they structure a CAD model — features, references, design intent. Look for parametric thinking, not click-recall.',
    'Surface probe — assess whether they design for changeability.'],
  ['manufacturing-basics', 'Basic manufacturing awareness', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask how a given part might be made — machined, cast, sheet metal — and one constraint that implies. Look for shop awareness.',
    'Probe one manufacturability consideration they\'d build into the design.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-curiosity', 'Technical curiosity and growth', 'self-awareness', 'closing', 'must', 0,
    'Ask which mechanical discipline they most want to deepen and how they\'re pursuing it.',
    'Surface — wrap up warmly; assess genuine enthusiasm.'],
]

// ─── Mechanical × Technical × 3-6 ───────────────────────────────────────────
const mid: CompactSlot[] = [
  ['design-walkthrough', 'Walk through a part they engineered', 'technical-breadth', 'warm-up', 'must', 0,
    'Ask candidate to walk through a component they analyzed and designed. Calibrate analysis depth and judgment.',
    'Surface — listen for loads, materials, and verification, not just CAD.', 'Must show end-to-end ownership from analysis to production.'],
  ['key-analysis-decision', 'A key analysis or material decision', 'problem-solving', 'warm-up', 'must', 0,
    'Ask about a significant analysis or material decision they drove. Calibrate ability to reason under constraints.',
    'Surface — pick the most interesting decision for deeper follow-up.'],
  ['fatigue-and-failure', 'Fatigue and failure-mode reasoning', 'technical-depth', 'exploration', 'must', 2,
    'Pose a cyclically loaded part and ask which failure mode worries them and how they\'d design against it.',
    'Probe fatigue limit, stress concentrations, surface finish, and how they\'d verify the design.',
    'Naming fatigue and stress concentration unprompted is the key differentiator here.'],
  ['fea-judgment', 'FEA setup and result skepticism', 'technical-depth', 'exploration', 'must', 2,
    'Present a suspicious FEA result (e.g. a 10x stress spike at a sharp corner) and ask whether it\'s real.',
    'Probe mesh refinement, singularities at sharp corners, boundary conditions, and hand-calc validation.',
    'When to trust vs. validate the model separates mid from entry.'],
  ['thermal-sizing', 'Thermal/heat-transfer estimate', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to estimate a heat load and reason about cooling (e.g. an enclosure or heat sink). Look for conduction/convection judgment.',
    'Probe assumptions, dominant resistance, and when they\'d validate with test.'],
  ['gdt-tolerance', 'GD&T and tolerance-stack reasoning', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask how they approach a tolerance stack or GD&T callout on an assembly. Look for functional thinking, not just tightening everything.',
    'Probe a real stack-up decision and how they balanced fit, cost, and producibility.'],
  ['analysis-to-manufacturing', 'Connecting analysis to manufacturing', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about a time a manufacturing constraint changed their analysis or design. Look for integrated thinking.',
    'Probe the constraint and what they changed.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-verification', 'Verification philosophy', 'problem-solving', 'closing', 'must', 0,
    'Ask how they decide when to trust a hand calc, when to run FEA, and when to test. Assess engineering judgment.',
    'Surface — one example suffices; assess rigor.'],
]

// ─── Mechanical × Technical × 7+ ────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['analysis-strategy', 'Framing analysis for an ambiguous problem', 'leadership', 'warm-up', 'must', 0,
    'Ask how they decide on an analysis approach for an ill-defined problem. Calibrate strategic engineering judgment.',
    'Surface — listen for how they bound the problem before computing.', 'Choosing the right question distinguishes senior from mid.'],
  ['failure-investigation', 'Leading a failure investigation', 'problem-solving', 'warm-up', 'must', 0,
    'Ask about a hard failure they investigated — especially a field failure that passed bench tests. Calibrate root-cause depth.',
    'Surface — note how they frame the test-vs-field gap.'],
  ['fea-validation-methodology', 'Validating FEA / analysis at scale', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they ensure FEA results across a team are trustworthy — validation against hand calcs and test.',
    'Probe the failure modes a junior misses, mesh/BC discipline, and how they catch a wrong answer.',
    'Must show a repeatable verification methodology, not a one-off.'],
  ['margin-cost-tradeoff', 'Margin, cost, and manufacturability tradeoffs', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a margin decision made against cost and manufacturing constraints. Look for systems-level judgment.',
    'Probe how they bounded the risk, what data they used, and how the decision held up.'],
  ['thermal-or-dynamics-systems', 'Systems-level thermal or dynamics problem', 'technical-depth', 'exploration', 'must', 2,
    'Pose a coupled system problem — thermal management, vibration/resonance, or multi-body dynamics. Look for second-order effects.',
    'Probe assumptions, dominant physics, and validation strategy.',
    'Naming resonance, thermal cycling, or coupling unprompted is expected.'],
  ['materials-process-selection', 'Materials and process selection methodology', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask how they approach material and manufacturing-process selection for a significant program.',
    'Probe the criteria — cost, fatigue, corrosion, producibility — and how they avoid over-spec.'],
  ['design-standards-rigor', 'Driving analysis rigor across a team', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they\'ve raised the analysis or DFMEA bar across engineers. Look for durable practice change.',
    'Probe what a junior engineer now does differently because of them.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-judgment', 'Hardest engineering call they\'ve made', 'problem-solving', 'closing', 'must', 0,
    'Ask about the hardest technical judgment call they\'ve made and how they reasoned through it.',
    'Surface — connect their reasoning to the role.', 'Inability to articulate a rigorous approach is a red flag at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('mechanical', 'technical', '0-2', entry, [
    'Field-failure investigation or program-level analysis ownership',
    'Advanced coupled-physics or multi-body dynamics',
    'Driving analysis standards across a team',
    'Obscure handbook constants or memorized material values',
    'Penalizing "I\'d look up the yield strength" — engineers look things up',
  ]),
  template('mechanical', 'technical', '3-6', mid, [
    'Org-wide analysis methodology or standards rollout',
    'Reciting formula derivations instead of applied reasoning',
    'Defaulting to "I\'d run FEA" without a hand-calc sanity check',
    'Penalizing a reasonable order-of-magnitude estimate for imprecision',
    'Pure CAD-tool trivia instead of design judgment',
  ]),
  template('mechanical', 'technical', '7+', senior, [
    'Basic beam-stress or single-formula questions',
    'Individual CAD or analysis tasks without systems context',
    'Material picks with only single-part scope',
    'Questions a mid-level engineer could answer equally well',
    'Accepting an FEA result without probing validation and failure modes',
  ]),
]
