import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Mechanical × Behavioral × 0-2 ──────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro-build', 'Intro and something they built', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves and describe a part, mechanism, or project they built. Look for genuine excitement about physical things.',
    'Surface only — use to pick follow-up topics.', 'Capstone, FSAE/Baja, internships, and personal builds all count.'],
  ['motivation-mechanical', 'Why mechanical engineering', 'motivation', 'warm-up', 'must', 0,
    'Ask what drew them to mechanical engineering. Look for hands-on curiosity about how things work and fail.',
    'One follow-up at most — keep it warm.', 'Assess mindset and coachability, not technical depth.'],
  ['first-design-iteration', 'A design whose first version failed', 'ownership', 'exploration', 'must', 2,
    'Ask about a part or assembly where the first attempt did not work and how they iterated. Look for diagnosis over guessing.',
    'Probe how they figured out what was wrong — measurement, test, or analysis — not just that they tried again.',
    'Class projects and prototypes are expected scope; look for systematic iteration.'],
  ['working-with-shop', 'Making a design manufacturable', 'collaboration', 'exploration', 'must', 2,
    'Ask about working with a machinist, technician, or supplier to actually build their design. Look for humility and learning from the floor.',
    'Probe what they changed about the design after talking to whoever made it.',
    'Even one shop conversation that changed a drawing counts at this level.'],
  ['hands-on-test', 'Running a test or measurement', 'ownership', 'exploration', 'must', 2,
    'Ask about a time they tested or measured something physical to check a design. Look for initiative to verify rather than assume.',
    'Probe what they were trying to learn and what the data told them.',
    'Lab and bench tests are valid; focus on the instinct to verify.'],
  ['teamwork-project', 'Working on a team project', 'collaboration', 'exploration', 'if-time', 1,
    'Ask about their role on a team build or design project. Look for reliability and clear handoffs.',
    'Probe how they handled a dependency or an integration with a teammate\'s part.'],
  ['safety-awareness-junior', 'A safety or tolerance moment', 'ownership', 'exploration', 'if-time', 2,
    'Ask about a time safety, a factor of safety, or a tolerance actually mattered in their work. Look for respect, not box-checking.',
    'Probe whether they understood why the requirement existed and what could go wrong.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-build-excitement', 'What they want to build next', 'motivation', 'closing', 'must', 0,
    'Ask what kind of products or mechanical problems they want to work on next. Assess enthusiasm and self-awareness.',
    'Surface — wrap up warmly and note growth signals.'],
]

// ─── Mechanical × Behavioral × 3-6 ──────────────────────────────────────────
const mid: CompactSlot[] = [
  ['design-philosophy-evolution', 'How their design judgment evolved', 'motivation', 'warm-up', 'must', 0,
    'Ask how their thinking about good mechanical design changed with experience — e.g. learning to design for manufacturing. Calibrate judgment.',
    'Surface — use to identify which deep-dives to pursue.', 'Must reflect on real hardware that shipped or was built.'],
  ['owned-field-failure', 'Owning a field or test failure', 'ownership', 'exploration', 'must', 2,
    'Ask about a failure they owned end-to-end. Look for structured root-cause work, not blaming a supplier or machinist.',
    'Probe how they isolated the cause — fractography, recreating the load case, DOE — and how they verified the fix.',
    'Should own the corrective action, not just report the symptom.'],
  ['cost-weight-tradeoff', 'A cost / weight / manufacturability tradeoff', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a design decision balancing competing constraints. Look for a reasoned, verified choice.',
    'Probe what data drove the call — analysis, cost rollup, supplier quotes — and what they would change with hindsight.',
    'Explicit tradeoff reasoning with verification differentiates at this level.'],
  ['supplier-quality-issue', 'Driving a supplier or quality issue', 'collaboration', 'exploration', 'must', 2,
    'Ask about working a supplier or quality problem on a part they owned. Look for influence and persistence.',
    'Probe how they got to the real cause with the supplier and what changed in the process or spec.',
    'Expect ownership of the resolution, not just escalation.'],
  ['design-review-pushback', 'Defending or revising a design under review', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about a design review where their approach was challenged. Look for openness to data and willingness to revise.',
    'Probe whether they changed their mind when the data warranted it, or held firm with evidence.'],
  ['safety-concern-raised', 'Raising a safety or quality concern', 'ownership', 'exploration', 'if-time', 2,
    'Ask about a time they pushed back on schedule pressure for a safety or quality reason. Look for backbone grounded in engineering.',
    'Probe how they made the case and what the outcome was.'],
  ['cross-discipline-work', 'Collaborating across disciplines', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about working with electrical, software, or industrial design on an integrated product. Look for systems-level give-and-take.',
    'Probe an interface or packaging conflict and how they resolved it.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retrospective-design-decision', 'A design decision they\'d make differently', 'self-awareness', 'closing', 'must', 0,
    'Ask what they would change knowing what they know now. Assess intellectual honesty and growth.',
    'Surface — one example suffices; wrap up warmly.'],
]

// ─── Mechanical × Behavioral × 7+ ───────────────────────────────────────────
const senior: CompactSlot[] = [
  ['mechanical-leadership-view', 'Mechanical engineering as a leadership discipline', 'leadership', 'warm-up', 'must', 0,
    'Ask how they connect mechanical design work to program, cost, and quality outcomes. Look for multi-dimensional leadership thinking.',
    'Surface — calibrate scope and identify which leadership dimensions to probe.',
    'Must show impact across technical, people, manufacturing, and business dimensions.'],
  ['led-program-gate', 'Leading a design through a gate or major review', 'leadership', 'exploration', 'must', 2,
    'Ask about leading a multidisciplinary design through a phase gate or critical design review. Look for alignment across teams.',
    'Probe a cross-discipline conflict — packaging, thermal, cost — and how they drove a decision.',
    'Scope should span multiple subsystems and disciplines, not one part.'],
  ['safety-critical-call', 'Making a safety-critical decision', 'ownership', 'exploration', 'must', 2,
    'Ask about a safety-critical call made with incomplete data — a recall, a stop-ship, a design margin decision. Look for sound judgment under risk.',
    'Probe how they bounded the risk, who they aligned, and how the decision held up.',
    'Real human-safety stakes with organizational pressure expected.'],
  ['set-design-standards', 'Establishing design standards or DFMEA practice', 'leadership', 'exploration', 'must', 2,
    'Ask about driving a standard — DFMEA, tolerance-stack discipline, design guidelines — across a team or org. Look for durable practice change.',
    'Probe the resistance they faced and whether the practice outlasted them.',
    'Multiplier impact across engineers is the right scope.'],
  ['major-redesign-recall', 'Owning a major redesign or recall', 'leadership', 'exploration', 'must', 2,
    'Ask about leading a significant redesign or recall response. Look for decisiveness, root-cause rigor, and stakeholder management.',
    'Probe: "Give a one-sentence summary of each key decision" — tests executive communication under pressure.',
    'High-stakes, multi-team programs with real business impact expected.'],
  ['mentoring-engineers', 'Developing other engineers', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they have grown mechanical engineers on their team. Look for deliberate investment, not just answering questions.',
    'Probe a specific engineer whose trajectory they changed and how.'],
  ['cost-or-quality-transformation', 'Driving a cost or quality transformation', 'leadership', 'exploration', 'if-time', 2,
    'Ask about a program-level cost-down or quality improvement they led. Look for change management and measured results.',
    'Probe: "Can you connect that work to a specific cost, warranty, or quality metric?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['design-bet-failure', 'A design or program bet that didn\'t pan out', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant initiative or design direction that failed or underdelivered. Look for organizational learning.',
    'Probe systemic changes, not just personal lessons.', 'Failure questions carry more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('mechanical', 'behavioral', '0-2', entry, [
    'Leading multidisciplinary programs or setting org design standards',
    'Recall management or program-gate leadership',
    'Deriving equations or solving statics problems (warm-up is not technical)',
    'Cross-org influence or design-standard strategy',
    'Generic conflict questions without an engineering context',
  ]),
  template('mechanical', 'behavioral', '3-6', mid, [
    'Entry-level "first project" framing',
    'Org-wide standards or program-gate leadership (senior territory)',
    'Generic teamwork stories without a hardware context',
    'Accepting vague "we fixed it" without root cause or verification',
    'Pure formula trivia instead of decision-making',
  ]),
  template('mechanical', 'behavioral', '7+', senior, [
    'Individual part designs or single CAD models',
    'Single-tool or single-component choices without program context',
    'Generic leadership questions that could apply to any role',
    'Questions a mid-level engineer could answer equally well',
    'Accepting "we improved quality" without probing the practice change and enforcement',
  ]),
]
