import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── ML Engineer × Behavioral × 0-2 ───────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-introduction', 'Background and path into ML engineering', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to walk through their background. Calibrate for academic/bootcamp/first-job context.',
    'Surface only — 2 minutes max.', 'Academic projects, bootcamp, internships all acceptable context.'],
  ['motivation-mle', 'Why ML engineering specifically', 'motivation', 'warm-up', 'must', 0,
    'Ask what draws them to ML engineering over pure data science or general backend. Look for interest in production.',
    'Surface — one follow-up at most.', 'Probe genuine interest in the engineering/production side, not just modeling.'],
  ['first-production-model', 'Taking a model or pipeline out of the notebook', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a project where they made a model run on a schedule or serve traffic. Look for production reality.',
    'Probe what broke when it left the notebook: "What did not work in production that worked locally?"',
    'Accept academic/bootcamp/internship projects — no large-scale production experience required.'],
  ['debugging-pipeline', 'Debugging a failed training job or data pipeline', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a training job or pipeline that failed and how they debugged it. Look for systematic approach.',
    'Probe how they isolated the cause: "Was it the data, the code, or the environment, and how did you tell?"'],
  ['collaborating-with-ds', 'Working with a data scientist or researcher', 'collaboration', 'exploration', 'must', 2,
    'Ask about a project where they worked with a data scientist. Look for their specific engineering contribution.',
    'Isolate their role: "You said we — what specifically did YOU build or own?"',
    'ML engineers often take a DS prototype and harden it; look for that ownership instinct.'],
  ['learning-new-tool', 'Learning a new ML tool or framework under pressure', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask how they taught themselves a new tool (PyTorch, a serving framework, an orchestrator) under time pressure.',
    'Probe specific resources used, blockers encountered, and how quickly they became productive.'],
  ['handling-feedback', 'Receiving feedback on production-readiness', 'collaboration', 'exploration', 'if-time', 1,
    'Ask about a time a reviewer flagged their model or pipeline as not production-ready. Look for growth mindset.',
    'Probe what they changed and whether they internalized the production standard going forward.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-curiosity', 'Learning goals and what excites them in ML systems', 'motivation', 'closing', 'must', 0,
    'Ask what they want to learn next and what excites them about ML engineering. Assess enthusiasm.',
    'Surface — wrap up warmly.'],
]

// ─── ML Engineer × Behavioral × 3-6 ───────────────────────────────────────
const mid: CompactSlot[] = [
  ['project-ownership-narrative', 'End-to-end ownership of a production model', 'problem-solving', 'warm-up', 'must', 0,
    'Ask about a model they owned fully: data → training → serving → monitoring → on-call. Calibrate scope.',
    'Surface — use to calibrate scope and pick follow-up topics.', 'Must demonstrate full-lifecycle ownership, not just training a model.'],
  ['serving-incident', 'Owning a model-serving incident', 'ml-engineering', 'exploration', 'must', 2,
    'Ask about a serving or pipeline incident they owned. Look for detection, mitigation, and permanent fix.',
    'Probe the timeline: "How did you detect it, what did you do in the first hour, and what stopped it recurring?"',
    'Incident ownership is the core mid-level signal — separates notebook engineers from production engineers.'],
  ['ds-disagreement', 'Disagreeing with a data scientist on ship-readiness', 'collaboration', 'exploration', 'must', 2,
    'Ask about disagreeing with a DS about whether a model was ready to ship. Look for productive resolution.',
    'Probe both positions: "What was their argument, what was yours, and what data settled it?"',
    'Must show they can push back on a researcher without making it adversarial.'],
  ['quality-vs-constraint', 'Trading model quality against latency, cost, or timeline', 'ml-engineering', 'exploration', 'must', 2,
    'Ask about choosing between model quality and a hard constraint (latency budget, serving cost, deadline).',
    'Probe the decision framework: "How did you frame the trade-off for the product stakeholder?"'],
  ['retraining-decision', 'Making a retraining or rollback judgment call', 'ml-engineering', 'exploration', 'must', 2,
    'Ask about a call to retrain, roll back, or hold a model in production. Look for risk-aware judgment.',
    'Probe the signal they acted on: "What told you it was time, and what was the cost of being wrong?"'],
  ['project-failure', 'A model or ML project that did not go as planned', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a model that failed in production or a project that missed expectations. Look for self-awareness.',
    'Probe what they would do differently — absence of any failure signals lack of self-awareness.'],
  ['mentoring-teammate', 'Mentoring a junior engineer on production ML', 'leadership', 'exploration', 'if-time', 1,
    'Ask about helping a junior colleague level up on deployment or pipeline practices. Look for investment in others.',
    'One example suffices — surface treatment. Probe what changed in the junior\'s work.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-production-mindset', 'Production mindset and what reliability means to them', 'ml-engineering', 'closing', 'must', 0,
    'Ask what makes an ML system reliable in their view and how they stay connected to production health.',
    'Surface — wrap up. Look for intrinsic ownership beyond shipping the first version.'],
]

// ─── ML Engineer × Behavioral × 7+ ────────────────────────────────────────
const senior: CompactSlot[] = [
  ['ml-strategy-narrative', 'Career trajectory and ML platform impact', 'leadership', 'warm-up', 'must', 0,
    'Ask how they have defined or influenced an ML engineering roadmap or platform aligned to business goals.',
    'Surface — calibrate scope, org size, and strategic leadership dimensions.',
    'Must show systems thinking: single model → team practices → org platform → company goals.'],
  ['mlops-standards', 'Establishing MLOps or deployment standards across teams', 'leadership', 'exploration', 'must', 2,
    'Ask about a deployment, monitoring, or MLOps standard they drove adoption of across multiple teams.',
    'Probe how they got buy-in without authority: "What did teams push back on, and how did you win them over?"',
    'Must articulate building durable practices, not just shipping their own models.'],
  ['build-vs-buy', 'Driving a build-vs-buy decision on ML infrastructure', 'ml-engineering', 'exploration', 'must', 2,
    'Ask about a build-vs-buy decision on ML infra (feature store, serving platform, training infra). Look for strategy.',
    'Probe the framing: "What did you intentionally NOT build, and why?"',
    'Stories must link to platform health, cost, velocity, or reliability — why the decision mattered.'],
  ['research-prod-friction', 'Navigating research-velocity vs production-reliability tension', 'leadership', 'exploration', 'must', 2,
    'Ask about org friction between research moving fast and production needing reliability. Look for influence.',
    'Probe who opposed, what evidence they marshaled, and what compromise held: "How did you keep both sides moving?"',
    'Must demonstrate influence without authority across research and engineering boundaries.'],
  ['building-scaling-team', 'Building or scaling an ML engineering team', 'leadership', 'exploration', 'must', 2,
    'Ask about hiring and developing ML engineers. Look for what they optimize for and multiplicative impact.',
    'Probe specific programs: hiring bar, onboarding, on-call culture, knowledge-sharing systems.',
    'Must show multiplicative impact — raising the whole team\'s production maturity, not just mentoring one person.'],
  ['strategic-bet-failure', 'A strategic ML infrastructure bet that did not pay off', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about a major platform or infra initiative that failed. Look for organizational learning, not just personal growth.',
    'Probe systemic changes made afterward. Absence of failure stories signals dishonesty or risk aversion.'],
  ['cost-reliability-tradeoff', 'Org-level trade-offs on serving cost vs reliability', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask about a major decision balancing serving cost, reliability, and model quality at org scale.',
    'Probe the decision process and what trade-offs were prioritized for long-term platform health.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-strategic-vision', 'Vision for ML engineering at this company', 'leadership', 'closing', 'must', 0,
    'Ask where they see ML engineering going here and what they would do differently in their first 90 days.',
    'Surface — wrap up. Look for strategic vision, not just tactical enthusiasm.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('ml-engineer', 'behavioral', '0-2', entry, [
    'Organizational strategy or platform direction-setting',
    'Multi-team MLOps standard rollout or roadmap ownership',
    'Build-vs-buy infrastructure decisions',
    'Influencing executive stakeholders or C-level decisions',
    'Building or scaling a team from scratch',
  ]),
  template('ml-engineer', 'behavioral', '3-6', mid, [
    'Organizational-level ML platform strategy or roadmap setting',
    'Hiring decisions or team structure design',
    'Company-level technical direction setting',
    'Pure modeling math or algorithm-internals questions',
    'Academic or hypothetical scenarios with no real example',
  ]),
  template('ml-engineer', 'behavioral', '7+', senior, [
    'Individual execution stories without strategic context',
    'IC-level model-training stories as the primary topic',
    'Questions an entry or mid engineer could answer equally well',
    'Generic teamwork or communication questions',
    'Pure implementation questions without organizational dimension',
  ]),
]
