import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── ML Engineer × Coding × 0-2 ───────────────────────────────────────────
const entry: CompactSlot[] = [
  ['clarify-problem-coding', 'Clarifying inputs, outputs, and edge cases', 'problem-solving', 'warm-up', 'must', 0,
    'Present a small NumPy/data problem. Ask them to clarify input shape, output format, and edge cases first.',
    'Surface — note if they ask about empty arrays, NaNs, and constant columns up front.', 'Correctness over optimization; a working brute-force loop is acceptable at entry level.'],
  ['basic-statistic', 'Computing a statistic from an array', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask them to compute mean, median, and standard deviation of a NumPy array without high-level helpers.',
    'Surface — verify they handle empty and single-element inputs.', 'Implementing the formula shows understanding versus calling a single library method.'],
  ['feature-normalization', 'Min-max or z-score normalization of a column', 'ml-engineering', 'exploration', 'must', 2,
    'Ask for a function that normalizes a NumPy column (min-max or z-score), handling the constant-column case.',
    'Probe: "What happens when every value is equal — does your code divide by zero?" (edge-case discipline).',
    'Feature normalization is a real ML transform; correctness on the degenerate case matters.'],
  ['train-test-split', 'Implementing a random train/validation split', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to split indices into train/validation by a given ratio and return index arrays.',
    'Probe reproducibility with a seed and that train and validation indices do not overlap.',
    'A correct split with no leakage is a core ML coding fundamental.'],
  ['simple-metric', 'Implementing accuracy or a confusion count', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask them to compute accuracy, or counts of true/false positives and negatives, from predicted and true labels.',
    'Probe how they handle mismatched lengths and an empty input before declaring done.'],
  ['vectorize-a-loop', 'Vectorizing a simple Python loop with NumPy', 'ml-engineering', 'exploration', 'if-time', 2,
    'Give a small element-wise loop and ask them to rewrite it as a vectorized NumPy operation.',
    'Probe: "Why is the vectorized version faster here?" (basic vectorization intuition).'],
  ['edge-case-walkthrough', 'Validating the solution with concrete inputs', 'problem-solving', 'exploration', 'if-time', 1,
    'After a solution, ask them to trace it on a concrete example including an edge case.',
    'Probe whether they check empty arrays, NaNs, and single-element inputs before saying done.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-coding-reflection', 'Reflecting on solution quality and alternatives', 'problem-solving', 'closing', 'must', 0,
    'Ask if there is another approach they considered and what the trade-offs would be.',
    'Surface — rewards honest self-assessment over assuming the first solution is optimal.'],
]

// ─── ML Engineer × Coding × 3-6 ───────────────────────────────────────────
const mid: CompactSlot[] = [
  ['approach-analysis', 'Defining the approach and comparing alternatives', 'problem-solving', 'warm-up', 'must', 0,
    'Present a slightly ambiguous problem. Ask them to name two approaches and weigh trade-offs before coding.',
    'Surface — penalize jumping straight to code; reward framing complexity and edge cases first.', 'Problems at this level leave scope decisions to the candidate.'],
  ['metric-from-scratch', 'Implementing precision, recall, and F1 from scratch', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask them to implement precision, recall, and F1 from predicted and true labels without sklearn.',
    'Probe division-by-zero handling (no positives predicted) and multi-class averaging (macro vs micro).',
    'Implementing the metric proves they understand it, not just that they can call a function.'],
  ['vectorized-encoder', 'Vectorized feature encoder with fit/transform', 'ml-engineering', 'exploration', 'must', 2,
    'Ask for a one-hot or ordinal encoder with a fit/transform pattern that handles unseen categories at transform.',
    'Probe: "What happens at serve time if a category was not seen in fit?" (train/serve consistency).',
    'The fit/transform pattern and unseen-category handling map directly to production feature pipelines.'],
  ['vectorized-numpy', 'Vectorizing a data transform with NumPy', 'ml-engineering', 'exploration', 'must', 2,
    'Give a per-row computation (pairwise distances, row-wise softmax, grouped aggregation) to vectorize.',
    'Probe: "Why not iterate row by row here?" and ask for the time/space complexity of their version.',
    'Vectorization is the core mid-level differentiator — Python loops over arrays are a red flag.'],
  ['sampling-or-split', 'Stratified or weighted sampling/split', 'ml-engineering', 'exploration', 'must', 2,
    'Ask for a stratified train/validation split that preserves class proportions, or weighted sampling.',
    'Probe correctness on imbalanced classes and reproducibility with a seed.'],
  ['follow-up-optimization', 'Optimizing or extending the solution', 'problem-solving', 'exploration', 'if-time', 2,
    'After the initial solution, ask: "What if the array is 100x larger?" or "Make this O(n) instead of O(n^2)."',
    'Probe runtime/space complexity and whether they reason about the bottleneck before refactoring.'],
  ['production-implication', 'Production implications of the code', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask what would need to change if this transform ran inside a production feature pipeline.',
    'Probe handling of NaNs, schema drift, and keeping fit-time state consistent at serve time.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-code-quality', 'Code quality, vectorization, and limitations', 'problem-solving', 'closing', 'must', 0,
    'Ask what they would refactor first and the biggest limitation of their current implementation.',
    'Surface — rewards intellectual honesty and engineering discipline over defending the first draft.'],
]

// ─── ML Engineer × Coding × 7+ ────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['problem-reframing', 'Reframing the problem and finding hidden constraints', 'problem-solving', 'warm-up', 'must', 0,
    'Present a numerical/ML coding scenario. Ask them to challenge assumptions and find the hardest sub-problem.',
    'Surface — note if they define scope, complexity, and memory limits before coding.', 'Shift from "can you implement?" to "can you reason about numerical code at scale?"'],
  ['auc-from-scratch', 'Implementing ROC-AUC from scratch', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask them to implement ROC-AUC given scores and binary labels, without sklearn.',
    'Probe tie handling in scores and getting to O(n log n) via sorting rather than O(n^2) pair counting.',
    'AUC from scratch separates engineers who understand the metric from those who only call it.'],
  ['memory-aware-transform', 'Memory-efficient transform over a large matrix', 'ml-engineering', 'exploration', 'must', 2,
    'Ask them to standardize or transform a 10M-row feature matrix in batches without loading it all at once.',
    'Probe streaming mean/variance (Welford) and numerical stability for the running statistics.',
    'Must reason about memory and numerical stability, not just produce a correct in-memory version.'],
  ['debug-numerical-code', 'Debugging broken numerical or training code', 'ml-engineering', 'exploration', 'must', 2,
    'Provide broken NumPy/training code (shape mismatch, wrong axis, unstable softmax, missing normalization).',
    'Probe a systematic approach: "How do you isolate whether it is the data, the shapes, or the math?"',
    'Debug-over-build is common at senior level; finding the bug tests real numerical fluency.'],
  ['vectorized-at-scale', 'Vectorized pairwise or batched computation at scale', 'ml-engineering', 'exploration', 'must', 2,
    'Ask for an efficient pairwise computation (cosine similarity, nearest neighbor) over many vectors.',
    'Probe memory blowup of the naive N-by-N matrix and how they batch or chunk to stay within memory.',
    'Must know the memory cost of the naive approach and a batched alternative.'],
  ['pipeline-component-as-code', 'Designing a reusable pipeline transform in code', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask them to design a small reusable transform (fit/transform) with serializable state for serving.',
    'Probe how fit-time state is persisted and applied identically at serve time (train/serve consistency).'],
  ['extend-at-scale', 'Extending the solution under new constraints', 'ml-engineering', 'exploration', 'if-time', 2,
    'After the initial solution, escalate: "Stream it instead of batch", "handle NaNs", or "make it run on 1B rows."',
    'Probe how the technical choice affects model quality and serving for real users (business alignment).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-engineering-judgment', 'Connecting code choices to maintainability and outcomes', 'data-communication', 'closing', 'must', 0,
    'Ask how their choices affect the team\'s ability to reuse this code and the reliability of the pipeline.',
    'Surface — look for engineering-leadership thinking: maintainability, correctness, and production outcomes.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('ml-engineer', 'coding', '0-2', entry, [
    'Implementing ROC-AUC or other advanced metrics from scratch',
    'Memory-aware or streaming transforms over large matrices',
    'System design or pipeline architecture questions',
    'Vectorized pairwise computation at scale',
    'Debugging broken training loops or numerical instability',
  ]),
  template('ml-engineer', 'coding', '3-6', mid, [
    'Streaming or out-of-core processing of billion-row data',
    'Implementing transformers or attention from scratch',
    'Distributed training or GPU memory management',
    'Latency-budget optimization for serving pipelines',
    'Designing serializable pipeline state for cross-team serving',
  ]),
  template('ml-engineer', 'coding', '7+', senior, [
    'Basic mean/median/normalization questions',
    'Simple random train/test split with no constraints',
    'Single-metric accuracy computation with no edge cases',
    'Trivial loop-to-vectorization rewrites',
    'Problems solvable with a single library call and no implementation',
  ]),
]
