import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── ML Engineer × System Design × 0-2 ────────────────────────────────────
const entry: CompactSlot[] = [
  ['pipeline-concept', 'Basic ML pipeline: data in to predictions out', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask them to describe a simple ML pipeline from data to serving predictions. Calibrate awareness.',
    'Surface — check they see ML as more than model.fit(); no infra depth expected.', 'Entry expectation: awareness of the pipeline stages, not infrastructure depth.'],
  ['data-and-labels', 'Where training data and labels come from', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask how they would collect and label data for a simple problem (spam, churn, sentiment).',
    'Surface — note whether they treat labeling as a first/hard step, not an afterthought.', 'Skipping data collection and labeling is the most common entry-level anti-pattern.'],
  ['batch-vs-realtime', 'Batch scoring vs simple real-time serving', 'ml-engineering', 'exploration', 'must', 2,
    'Ask whether the problem needs batch nightly scoring or real-time predictions, and why.',
    'Probe: "What changes if it must answer per-request in real time?" (serving-mode reasoning).',
    'Treating entry ML system design like backend microservices design is a disqualifier.'],
  ['model-and-evaluation', 'Choosing a model and an offline quality bar', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask which model they would start with and how they decide offline if it is good enough to deploy.',
    'Probe: "Why not a neural network for this?" (proportional complexity) and "What metric decides launch?"'],
  ['serving-the-prediction', 'Getting a prediction to the product', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how a prediction actually reaches the product (a table, an endpoint, a batch file).',
    'Probe: "What parts of the notebook would not work as a real service?" (engineering awareness).'],
  ['monitoring-intuition', 'Knowing if the deployed model is still working', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask what they would monitor to know the model is still doing its job after launch.',
    'Probe: "How would you even notice predictions got worse?" (monitoring without drift vocabulary).'],
  ['cold-start-intuition', 'Handling a brand-new user or item', 'ml-engineering', 'exploration', 'if-time', 1,
    'Ask how a simple recommendation or scoring system handles a user with no history.',
    'Probe: "What do you fall back to when you have no data on someone?" (cold-start intuition).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-pipeline-gaps', 'Gaps and what they would learn next', 'ml-engineering', 'closing', 'must', 0,
    'Ask which part of the pipeline they feel least confident about and how they would learn it.',
    'Surface — rewards self-awareness about the engineering-to-production gap.'],
]

// ─── ML Engineer × System Design × 3-6 ────────────────────────────────────
const mid: CompactSlot[] = [
  ['problem-formulation', 'Translating the business goal into an ML system objective', 'problem-solving', 'warm-up', 'must', 0,
    'Present a business goal (more engagement, less fraud). Ask how they turn it into an ML system objective.',
    'Surface — evaluate metric choice, proxy vs business metric, and success definition.', 'Product sense plus engineering rigor must combine before any architecture is drawn.'],
  ['metrics-offline-online', 'Offline and online metrics and why they diverge', 'experimentation', 'warm-up', 'must', 0,
    'Ask for offline metrics (AUC, NDCG, precision@k) and online metrics (CTR, revenue) for their system.',
    'Surface — probe: "Why might offline and online metrics disagree?" (production realism).',
    'Must separate training optimization from business outcomes and explain disagreement scenarios.'],
  ['data-feature-pipeline', 'Data pipeline, labeling, and feature store', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they design ingestion, labeling, feature engineering, and feature storage for the system.',
    'Probe: "Where do labels come from?" and "Feature store goes down — how does the system degrade?"',
    'Labeling and feature consistency are commonly skipped; missing them signals a notebook mindset.'],
  ['serving-and-latency', 'Serving architecture, batch vs real-time, latency budget', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how predictions are served with a latency/throughput target and a batch vs real-time decision.',
    'Probe: "Walk me through one request — where is the latency budget spent and where is the bottleneck?"'],
  ['train-serve-consistency', 'Train/serve skew and feature consistency', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how the same features are produced for training and online inference without skew.',
    'Probe: "How do you guarantee point-in-time correctness so you do not leak future data into training?"',
    'Train/serve skew is the canonical production ML failure; fluency here is a strong mid-level signal.'],
  ['monitoring-and-drift', 'Monitoring, drift detection, and retraining loop', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they detect data drift, alert, and trigger retraining in the system.',
    'Probe: "How do you detect drift, and what do you do when it fires?" (feedback loop design).'],
  ['deployment-and-rollback', 'Safe deployment: shadow, canary, A/B, rollback', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they roll out a new model version safely and what rollback criteria they set.',
    'Probe: "How do you compare the new model to the live one before fully switching?" (deployment hygiene).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-scaling', 'Scaling to 10x and what breaks first', 'ml-engineering', 'closing', 'must', 0,
    'Ask what breaks first at 10x traffic and what they would sacrifice — latency, freshness, or coverage.',
    'Surface — evaluate scaling trade-off awareness and production realism.'],
]

// ─── ML Engineer × System Design × 7+ ─────────────────────────────────────
const senior: CompactSlot[] = [
  ['business-platform-framing', 'Framing in business and platform terms before architecture', 'leadership', 'warm-up', 'must', 0,
    'Present a large-scale ML problem. Ask them to frame business goals and platform implications first.',
    'Surface — note stakeholder mapping, org-level success definition, and constraints they surface.', 'Must show industry awareness: reference how real companies solve similar problems.'],
  ['multi-model-architecture', 'Multi-model architecture: retrieval, ranking, re-ranking, business rules', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how multiple models interact in the design (retrieval + ranking + re-ranking + diversity/rules).',
    'Probe comparative analysis: "Why this architecture over alternative X? Walk me through the trade-offs."',
    'Senior must reason about model interactions served together under one latency budget.'],
  ['feature-platform-design', 'Feature platform: offline compute, online serving, point-in-time correctness', 'ml-engineering', 'exploration', 'must', 2,
    'Ask for a feature platform design: offline vs online compute paths, low-latency serving, point-in-time joins.',
    'Probe: "You propose X, a principal engineer argues Y — how do you evaluate which to build?"',
    'Point-in-time correctness and consistent offline/online features are the hard problems here.'],
  ['scale-and-reliability', 'Serving at scale: real-time latency, batching, caching, failure modes', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they hit a tight latency target (e.g. <50ms) for real-time inference at high throughput.',
    'Probe: "What is most likely to go wrong in production here?" (proactive failure-mode identification).',
    'Must proactively name failure modes without being asked — the senior differentiator.'],
  ['monitoring-remediation', 'Monitoring, observability, and automated remediation', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they detect silent model degradation across the platform, alert, and trigger remediation.',
    'Probe: "Metrics slowly degrade over 6 months — walk me through your diagnosis." (systematic approach).',
    'Must discuss concept drift, label delay, and feedback loops — not just dashboards.'],
  ['training-infra-tracking', 'Training infrastructure, experiment tracking, and model registry', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they design distributed training, experiment tracking, and a model registry that teams rely on.',
    'Probe: "How do you balance experimentation velocity against compute cost and model quality?" (org trade-off).'],
  ['organizational-dimension', 'Platform vs product trade-offs and enabling other teams', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they balance a shared ML platform against product-specific model work, and how teams onboard.',
    'Probe: "Self-serve or white-glove onboarding?" and "ROI of building this platform vs buying it?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-strategic-tradeoffs', 'Strategic trade-offs and scope cuts under constraints', 'leadership', 'closing', 'must', 0,
    'Ask: "Cut scope to 3 months instead of 6 — what do you drop and why?" Assess strategic prioritization.',
    'Surface — crisp trade-off reasoning tied to business value and team capability, not technical preference.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('ml-engineer', 'system-design', '0-2', entry, [
    'Multi-model architectures (retrieval + ranking + re-ranking)',
    'Feature store design or train/serve consistency at scale',
    'Distributed training or model compression techniques',
    'Experiment tracking at scale or model registry design',
    'Generic backend infrastructure (Kafka, Kubernetes, microservices) with no ML lifecycle',
  ]),
  template('ml-engineer', 'system-design', '3-6', mid, [
    'Org-wide platform strategy or build-vs-buy decisions',
    'Staff-level novel architectural trade-offs without clear answers',
    'Model governance frameworks across many teams',
    'Multi-modal ML systems (vision + language fusion)',
    'Autonomous-vehicle or robotics perception systems',
  ]),
  template('ml-engineer', 'system-design', '7+', senior, [
    'Single-model notebook-to-endpoint architecture questions',
    'Basic batch-scoring pipeline design without platform framing',
    'Simple evaluation-metric definition without system context',
    'Standard model-selection questions without production framing',
    'Questions that do not require cross-team or platform thinking',
  ]),
]
