import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── ML Engineer × Technical × 0-2 ────────────────────────────────────────
const entry: CompactSlot[] = [
  ['ml-lifecycle-basics', 'Training vs serving and the ML lifecycle', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask them to describe the difference between training a model and serving it. Calibrate depth.',
    'Surface — gauge whether they see ML as more than model.fit(); no infra depth required yet.', 'Conceptual understanding over implementation; awareness of the lifecycle is the gate.'],
  ['evaluation-basics', 'Model evaluation beyond accuracy', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask when accuracy is misleading and what they would use instead (precision/recall, AUC). Check intuition.',
    'Surface — probe: "99% accuracy on a fraud dataset — is that good?" (class imbalance).', 'Must move past accuracy to precision/recall trade-offs at a conceptual level.'],
  ['data-leakage', 'Data leakage and train/test discipline', 'ml-engineering', 'exploration', 'must', 2,
    'Ask what data leakage is and how they ensure their training pipeline avoids it.',
    'Probe a concrete case: "How could a future-looking feature sneak into training?" (leakage example).',
    'Leakage understanding separates candidates who just ran sklearn from those who understand pipelines.'],
  ['notebook-to-endpoint', 'From notebook model to a callable endpoint', 'ml-engineering', 'exploration', 'must', 2,
    'Ask the steps to take a trained model and make a service able to call it for predictions.',
    'Probe: "What parts of the notebook code would NOT work in production?" (serialization, dependencies).'],
  ['feature-encoding', 'Feature preprocessing and encoding consistency', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they preprocess features (scaling, categorical encoding) and apply the same transform at inference.',
    'Probe: "How do you make sure the same encoding is used at training and prediction time?" (early skew intuition).'],
  ['overfitting-regularization', 'Overfitting, regularization, and generalization', 'statistical-thinking', 'exploration', 'if-time', 2,
    'Ask about bias-variance, overfitting signs, and basic regularization (L1/L2, early stopping).',
    'Probe: "Train accuracy 99%, validation 70% — what is happening and what do you try?" (diagnosis).'],
  ['monitoring-intuition', 'Knowing whether a deployed model is working', 'ml-engineering', 'exploration', 'if-time', 1,
    'Ask what they would monitor to know a deployed model is still doing its job.',
    'Probe: "How would you even know the model started making bad predictions?" (monitoring awareness).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tool-knowledge', 'Tools, learning path, and next steps', 'ml-engineering', 'closing', 'must', 0,
    'Ask which ML tools they are most confident in and what they are actively learning.',
    'Surface — assess self-awareness about the engineering-to-production gap.'],
]

// ─── ML Engineer × Technical × 3-6 ────────────────────────────────────────
const mid: CompactSlot[] = [
  ['training-pipeline-design', 'Reproducible training pipeline design', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask how they design a training pipeline that is reproducible and re-runnable: data versioning, seeds, config.',
    'Surface — gauge production maturity, not just "I trained a model in a notebook."', 'Must go beyond fit/predict to reproducibility, data versioning, and experiment tracking.'],
  ['train-serve-skew', 'Train/serve skew and feature consistency', 'ml-engineering', 'exploration', 'must', 2,
    'Ask what train/serve skew is and how they design feature pipelines to prevent it.',
    'Probe point-in-time correctness and feature stores: "How do you avoid leaking future data into a training feature?"',
    'Train/serve skew is the canonical mid-level production ML failure — fluency here is a strong signal.'],
  ['evaluation-for-production', 'Production-aware evaluation: slicing, calibration, online vs offline', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask how they evaluate a model for production: metric choice, slicing by segment, calibration, offline vs online.',
    'Probe: "Why might offline AUC look great but online metrics disappoint?" (production realism).'],
  ['deployment-strategy', 'Safe deployment: shadow, canary, A/B, rollback', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they roll out a new model version that replaces a serving model. Look for staged rollout discipline.',
    'Probe: "What rollback criteria do you set, and how do you compare new vs old in production?" (deployment hygiene).',
    'Shadow/canary/A-B vocabulary and rollback criteria are expected at this level.'],
  ['serving-latency', 'Serving architecture and latency budgets', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how predictions are served with a latency/throughput target and batch vs real-time decision.',
    'Probe: "Where is the latency budget spent — feature fetch, model compute, or network?" (request walkthrough).'],
  ['drift-and-retraining', 'Drift detection and retraining triggers', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they detect drift, alert on it, and decide when to retrain in their system.',
    'Probe: "What signal triggers a retrain, and how do you avoid retraining on bad data?" (feedback loop design).'],
  ['distributed-or-scaling', 'Scaling training or handling large data', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they handle training that no longer fits on one machine or a dataset too large for memory.',
    'Probe data parallelism vs sharding and what breaks first as data grows 10x.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-technical-growth', 'Technical depth and what they have shipped recently', 'ml-engineering', 'closing', 'must', 0,
    'Ask which area they are investing in and what they have taken to production recently.',
    'Surface — assess production mindset and intentional skill development.'],
]

// ─── ML Engineer × Technical × 7+ ─────────────────────────────────────────
const senior: CompactSlot[] = [
  ['ml-platform-overview', 'End-to-end ML platform architecture', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask them to walk through an ML platform end-to-end: data → features → training → registry → serving → monitoring.',
    'Surface — identify which components they reach for and depth of production thinking.', 'Platform-level architecture fluency is the senior gate; expect opinions on each layer.'],
  ['training-infra-at-scale', 'Distributed training and cost-performance trade-offs', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they design training infra for distributed training, experiment tracking, and a model registry at scale.',
    'Probe: "How do you balance experimentation velocity against compute cost across many teams?" (org trade-off).',
    'Must discuss reproducibility, resource governance, and cost — not just "use more GPUs."'],
  ['feature-platform', 'Feature platform: offline compute, online serving, point-in-time correctness', 'ml-engineering', 'exploration', 'must', 2,
    'Ask for a feature platform design: offline vs online compute paths, low-latency serving, point-in-time joins.',
    'Probe: "Principal engineer prefers approach Y over your X — how do you evaluate which to build?" (trade-off depth).',
    'Point-in-time correctness and consistent offline/online features are the hard problems here.'],
  ['serving-at-scale', 'Low-latency serving at scale: batching, caching, compression', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they hit a tight latency target (e.g. <50ms) for real-time inference at high throughput.',
    'Probe: "What is most likely to go wrong in this serving path in production?" (proactive failure analysis).',
    'Must proactively name failure modes — the senior differentiator over reciting an architecture.'],
  ['observability-remediation', 'Observability and automated remediation for silent degradation', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they detect silent model degradation across many models, alert, and trigger remediation.',
    'Probe: "Metrics slowly degrade over 6 months — walk me through your diagnosis." (systematic approach).',
    'Must cover concept drift, label delay, and feedback-loop effects — not just dashboards.'],
  ['evaluation-standards', 'Establishing evaluation and deployment standards across teams', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they set modeling evaluation and deployment standards that many teams follow.',
    'Probe: "Two teams disagree on the right offline metric — how do you resolve it?" (technical leadership).'],
  ['research-to-production', 'Taking a research prototype to a production pipeline', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they take a research prototype or paper approach and deploy it reliably at scale.',
    'Probe: "What in the prototype almost never survives contact with production, and how do you harden it?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-technical-vision', 'Technical vision and industry awareness', 'ml-engineering', 'closing', 'must', 0,
    'Ask how they stay current with ML systems and which technical bets they think matter most now.',
    'Surface — look for genuine industry awareness and opinions on trade-offs.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('ml-engineer', 'technical', '0-2', entry, [
    'Distributed training or model compression techniques',
    'Feature store or feature platform architecture',
    'Multi-team MLOps standards or platform governance',
    'Advanced deployment orchestration at scale',
    'Cost-performance trade-offs across many models',
  ]),
  template('ml-engineer', 'technical', '3-6', mid, [
    'Org-wide ML platform architecture or governance',
    'Staff-level novel infra trade-offs without clear answers',
    'Research-paper derivation or deep-learning math from scratch',
    'Building a training platform many teams self-serve on',
    'Executive build-vs-buy infrastructure strategy',
  ]),
  template('ml-engineer', 'technical', '7+', senior, [
    'Basic train/test split or notebook-to-endpoint walkthrough',
    'Conceptual evaluation metrics without system context',
    'Simple feature encoding or preprocessing questions',
    'Entry-level overfitting or regularization basics',
    'Single-model deployment without platform framing',
  ]),
]
