import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── ML Engineer × Case Study × 0-2 ───────────────────────────────────────
const entry: CompactSlot[] = [
  ['clarify-problem', 'Clarifying the prediction target and scope', 'problem-solving', 'warm-up', 'must', 0,
    'Present a vague prompt (e.g. "score users for churn"). Ask them to clarify target, time frame, and output.',
    'Surface — note whether they define the prediction target and success up front or jump to modeling.', 'Clarity and end-to-end thinking matter far more than model sophistication at this level.'],
  ['data-and-labels', 'Where training data and labels come from', 'ml-engineering', 'warm-up', 'must', 0,
    'Ask how they would source and label data for the problem. Look for labeling treated as a first-class step.',
    'Surface — penalize treating data and labels as a given; reward asking where labels come from.', 'Not addressing data collection and labeling first is the most common entry-level miss.'],
  ['model-selection', 'Choosing a first model and justifying it', 'statistical-thinking', 'exploration', 'must', 2,
    'Ask which model they would try first and why. Look for proportional complexity, not "always deep learning."',
    'Probe: "Why not a neural network here?" — penalize reaching for the most complex model by default.',
    'Logistic regression or a tree before deep learning is the right instinct at this level.'],
  ['serving-the-model', 'How predictions reach the product', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how predictions get from the model to the product team or user (batch job, table, endpoint).',
    'Probe: "Batch nightly or real-time — which fits this problem and why?" (serving-mode reasoning).',
    'Understanding batch vs simple endpoint serving is the key engineering signal at entry.'],
  ['evaluation-and-launch', 'Knowing when the model is good enough to launch', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they evaluate offline and what would justify deploying. Look for an explicit quality bar.',
    'Probe: "What would you track to know it is working in production?" (monitoring awareness).'],
  ['drift-intuition', 'What happens when the world changes after launch', 'ml-engineering', 'exploration', 'if-time', 1,
    'Ask what they would do if the model starts making worse predictions weeks after launch.',
    'Probe: "How would you even notice it got worse?" (monitoring without the drift vocabulary).'],
  ['next-steps', 'What they would improve with more time', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask what they would build or improve next given another week. Look for engineering curiosity.',
    'Probe whether next steps connect to reliability or business value, not just a fancier model.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-takeaway', 'The single most important design decision', 'data-communication', 'closing', 'must', 0,
    'Ask what the one decision is that most determines whether this system succeeds, and why.',
    'Surface — a crisp answer signals real prioritization instincts.'],
]

// ─── ML Engineer × Case Study × 3-6 ───────────────────────────────────────
const mid: CompactSlot[] = [
  ['clarify-scope-live', 'Clarifying scope and constraints in a live case', 'problem-solving', 'warm-up', 'must', 0,
    'Present a deliberately open prompt (e.g. "design a real-time rec pipeline"). Ask them to clarify before designing.',
    'Surface — evaluate whether they define traffic, latency, freshness, and success before diving in.', 'Live interactive case; interviewer supplies constraints on request.'],
  ['ml-objective-framing', 'Translating the business goal into an ML objective and metrics', 'statistical-thinking', 'warm-up', 'must', 0,
    'Ask how they translate the business goal into an ML objective with offline and online metrics.',
    'Surface — probe proxy vs business metric and why offline and online metrics may diverge.', 'Must combine product sense with engineering: the metric drives the whole design.'],
  ['data-and-feature-pipeline', 'Data sourcing, labeling, and feature pipeline design', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they design data ingestion, labeling, feature engineering, and feature storage for the system.',
    'Probe: "Where do labels come from, and how do you keep training and serving features consistent?"',
    'Labeling and train/serve consistency are the most-skipped pieces; missing them signals a Kaggle mindset.'],
  ['serving-architecture', 'Serving architecture and latency budget', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how predictions are served with a concrete latency/throughput target and batch vs real-time decision.',
    'Probe: "Walk me through one prediction request — where does the latency budget go?" (request trace).'],
  ['deployment-and-rollout', 'Safe deployment and rollback strategy', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they roll out the model safely: shadow, canary, A/B, and rollback criteria.',
    'Probe: "How do you compare the new model to the current one before fully switching?" (deployment hygiene).',
    'Must show staged rollout discipline, not "deploy and hope."'],
  ['monitoring-retraining', 'Monitoring, drift detection, and retraining loop', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they detect drift, alert, and trigger retraining once the system is live.',
    'Probe: "What triggers a retrain, and how do you avoid retraining on corrupted or biased data?"'],
  ['cold-start-scaling', 'Cold start and scaling to 10x traffic', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they handle cold start (new users/items) and what breaks first at 10x traffic.',
    'Probe: "What do you sacrifice first — latency, freshness, or coverage?" (scaling trade-offs).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tradeoff-decision', 'The key engineering trade-off and the decision', 'ml-engineering', 'closing', 'must', 0,
    'Ask which trade-off most shapes the system (quality vs latency vs cost) and what they would decide.',
    'Surface — decision-quality reasoning tied to business and reliability, not just technical preference.'],
]

// ─── ML Engineer × Case Study × 7+ ────────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-framing', 'Framing the problem in business and platform terms first', 'leadership', 'warm-up', 'must', 0,
    'Present a large-scale ML scenario. Ask them to frame business goals and platform implications before designing.',
    'Surface — note stakeholder mapping, org-level success definition, and constraints they surface.', 'Less "build this model" → more "design the system and the platform around it."'],
  ['platform-and-feature-reuse', 'Shared feature/serving platform and reuse across teams', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they design shared feature and serving infrastructure so many models and teams reuse it safely.',
    'Probe: "How do you guarantee point-in-time correctness and consistent features across teams?" (platform depth).',
    'Must reason about reuse, governance, and consistency — not just one model\'s pipeline.'],
  ['multi-model-orchestration', 'Multi-model orchestration: candidate generation, ranking, re-ranking', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how multiple models interact in the design (retrieval + ranking + re-ranking + business rules).',
    'Probe comparative analysis: "Why this architecture over alternative X? Walk me through the trade-offs."',
    'Senior must reason about model interactions and serving them together under one latency budget.'],
  ['lifecycle-governance', 'Model lifecycle: governance, rollback, and retraining at scale', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they manage model lifecycle across many models: approval, monitoring, rollback, deprecation, retraining.',
    'Probe: "A model is accurate but produces biased or unsafe outputs — how does your process catch and stop it?"',
    'Must cover governance and automated safety, not just deployment mechanics.'],
  ['cost-reliability-scale', 'Cost-performance and reliability trade-offs at scale', 'ml-engineering', 'exploration', 'must', 2,
    'Ask how they balance serving cost, reliability, and model quality at high traffic across the platform.',
    'Probe: "What is most likely to go wrong in production here, and how do you contain blast radius?" (failure modes).',
    'Must proactively identify failure modes and cost levers without being asked.'],
  ['org-and-enablement', 'Organizational dimension: enabling teams, platform vs product', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they balance building shared ML infra against supporting product-specific model work.',
    'Probe: "How do you onboard a new team — self-serve or white-glove?" and "ROI of building vs buying this?"'],
  ['build-vs-buy', 'Build vs buy for a major piece of ML infrastructure', 'ml-engineering', 'exploration', 'if-time', 2,
    'Ask how they decide to build a piece of ML infra vs adopt a managed platform (SageMaker, Vertex, vendor).',
    'Probe: "What would you intentionally NOT build, and why?" (strategic prioritization).'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-scope-cut', 'Strategic scope cuts under a tighter timeline', 'leadership', 'closing', 'must', 0,
    'Ask: "Cut this to 3 months instead of 6 — what do you drop and why?" Assess strategic prioritization.',
    'Surface — crisp trade-off reasoning tied to business value and team capability, not technical preference.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('ml-engineer', 'case-study', '0-2', entry, [
    'Multi-model architectures (retrieval + ranking + re-ranking)',
    'Shared feature/serving platform or build-vs-buy decisions',
    'Organizational strategy or team resource allocation',
    'Model governance or lifecycle compliance at scale',
    'Distributed training or cost-performance trade-offs at scale',
  ]),
  template('ml-engineer', 'case-study', '3-6', mid, [
    'Organizational platform strategy or data-function design',
    'Multi-year roadmap planning or headcount decisions',
    'Model governance frameworks across many teams',
    'Staff-level novel architecture trade-offs without clear answers',
    'Pure algorithmic coding without a system context',
  ]),
  template('ml-engineer', 'case-study', '7+', senior, [
    'Single-model notebook-to-endpoint walkthroughs',
    'Basic target definition or model selection questions',
    'Standard batch-pipeline design without platform framing',
    'Pure implementation details without org or platform dimension',
    'Questions answerable without cross-team or platform thinking',
  ]),
]
