import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Mobile × Coding × 0-2 ─────────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['language-warmup', 'Language and fundamentals warm-up', 'technical-depth', 'warm-up', 'must', 0,
    'Ask 1-2 short questions in their language: array/dict basics, or predict the output of a small async snippet.',
    'Surface — assess language foundations before the coding task.',
    'Logic fundamentals are the primary signal; platform SDK knowledge is not the focus.'],
  ['data-shape-task', 'Shape a list for a screen', 'problem-solving', 'warm-up', 'must', 0,
    'Ask them to transform a flat list: group by a key, or sort/filter for a sectioned list view.',
    'Surface — observe first approach: does it work, is it clean?',
    'Practical list shaping is the kind of code that backs real screens.'],
  ['grouping-task', 'Group and aggregate items', 'problem-solving', 'exploration', 'must', 2,
    'Ask them to group items by a key and aggregate (count or sum) for a summary screen.',
    'Probe: "What if the list is empty? What if a key is missing on some items?"',
    'Evaluate approach over raw speed; clean handling of edge cases matters.'],
  ['pagination-math', 'Pagination math', 'problem-solving', 'exploration', 'must', 2,
    'Ask them to compute the page and offset to load given a scroll index and page size.',
    'Probe: "What about the last page if it is partial? Off-by-one at the boundary?"',
    'Pagination is everywhere in mobile lists; correctness at boundaries is the signal.'],
  ['simple-debounce', 'Implement a simple debounce', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to implement a basic debounce (trailing) for a search box and explain why a list screen needs it.',
    'Probe: "What if calls keep coming forever? When exactly does the callback fire?"',
    'Proves understanding of timers and why debouncing protects the network and UI.'],
  ['string-array-problem', 'Basic string/array problem', 'problem-solving', 'exploration', 'if-time', 1,
    'Give a simple string/array problem framed for a screen: format a duration, dedupe a list, count by category.',
    'Probe: "Can you do it in one pass? What is the time complexity?"'],
  ['edge-case-followup', 'Edge-case and null-input follow-up', 'problem-solving', 'exploration', 'if-time', 1,
    'After a solution, ask how it behaves with null, empty, or malformed input from an API.',
    'Probe: "API returns null for this field — does your code crash or degrade gracefully?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['code-review-cleanup', 'Review and clean up', 'problem-solving', 'closing', 'must', 0,
    'Ask them to look at their own code and name one thing they\'d improve or add.',
    'Surface — assess self-awareness about code quality and edge cases.'],
]

// ─── Mobile × Coding × 3-6 ─────────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['problem-scoping', 'Problem scoping and signature design', 'problem-solving', 'warm-up', 'must', 0,
    'Present a problem (debounce, paginated loader, cache merge). Ask clarifying questions and sketch the API first.',
    'Surface — probe what edge cases they surface: in-flight races, empty input, errors.',
    'Designing the function signature and edge cases up front separates mid from entry.'],
  ['debounce-cancel-flush', 'Debounce with cancel and flush', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to implement debounce supporting cancel() and flush(), plus leading/trailing options.',
    'Probe: "What does flush do mid-wait? How do you clean up the timer when the screen unmounts?"',
    'Cancel/flush and cleanup show real understanding of the async lifecycle.'],
  ['paginated-loader', 'Paginated loader with in-flight dedup', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to write a loader that fetches pages on demand and avoids firing the same page twice.',
    'Probe: "User scrolls fast and triggers page 3 twice — how do you dedup? What about a failed page?"',
    'In-flight deduplication and retry are the mid-level bar for list loading.'],
  ['cache-merge', 'Merge cache with server data', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to merge a local cache (a map by id) with a fresh server list: upserts, removals, and ordering.',
    'Probe: "Server omits an item that\'s in the cache — keep or delete? How do you know?"',
    'A clear upsert/remove rule, not a blind overwrite, distinguishes mid candidates.'],
  ['list-diff', 'Diff two lists into operations', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask them to diff an old and new list (by id) into insert/remove operations for minimal UI updates.',
    'Probe: "Why not just re-render the whole list? What does the diff save on a mobile screen?"',
    'Understanding why minimal updates matter on device reveals real performance sense.'],
  ['async-race', 'Async race and stale-result handling', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about two searches in flight where the slower (older) one resolves last.',
    'Probe: "How do you make sure the screen shows results for the latest query, not the stale one?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['tradeoffs-extension', 'Trade-offs and extension discussion', 'problem-solving', 'closing', 'must', 0,
    'Ask what they\'d add given more time and which decision they\'d revisit.',
    'Surface — one honest trade-off articulation is sufficient.'],
]

// ─── Mobile × Coding × 7+ ──────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['problem-scoping-senior', 'Open-ended scoping — candidate drives', 'problem-solving', 'warm-up', 'must', 0,
    'Give an open prompt: "Build an offline-sync reconciler" or "Implement a virtualized-list windower." Candidate scopes it.',
    'Surface — scoping IS part of evaluation; probe what they prioritize and why.',
    'You drive the interview; the abstractions chosen while coding are the real signal.'],
  ['sync-reconciler', 'Offline-sync reconciler with conflicts', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to reconcile local edits with server records and resolve conflicts deterministically.',
    'Probe: "Last-write-wins vs. version vectors — implement one. How do you represent a delete (tombstone)?"',
    'A correct, explainable conflict policy and tombstones are the senior bar.'],
  ['virtualized-window', 'Virtualized-list window calculator', 'performance', 'exploration', 'must', 2,
    'Ask them to compute which items are visible for a virtualized list given scroll offset, viewport, and item heights.',
    'Probe: "Now handle variable item heights. How do you keep lookups fast as the list grows to 100k?"',
    'Bounding the rendered window and handling variable heights distinguishes senior.'],
  ['request-scheduler', 'Request scheduler with concurrency and cancellation', 'technical-depth', 'exploration', 'must', 2,
    'Ask for a scheduler that runs at most N requests concurrently, supports priority, and cancellation.',
    'Probe: "A queued task is cancelled before it runs — how? Exponential backoff with jitter — why jitter?"',
    'Concurrency limits plus clean cancellation are the senior signal.'],
  ['diff-with-moves', 'List diff with move detection', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to diff two keyed lists into insert/remove/move operations (not just insert/remove).',
    'Probe: "Detect a moved item instead of remove+insert. Complexity? Why does a stable key matter?"',
    'Move detection and complexity awareness separate senior from mid here.'],
  ['design-a-core', 'Design and implement a small core abstraction', 'component-architecture', 'exploration', 'if-time', 2,
    'Ask them to design and implement the core of a sync queue, a cache layer, or an observable store.',
    'Probe: "How would you unit-test this in isolation? How is it consumed by a screen?"'],
  ['data-structure-tradeoff', 'Data-structure tradeoff for a hot path', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask them to pick and justify a data structure for a frequently-updated screen (e.g., a chat timeline).',
    'Probe: "Array vs. map vs. ordered structure — what does each cost on insert, lookup, and render?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['architecture-discussion', 'Architecture, testing, and production-readiness', 'leadership', 'closing', 'must', 0,
    'Ask how they\'d test their implementation, handle failure in production, and scale it 10x.',
    'Surface — tests strategic thinking: beyond the code, what does production readiness look like?'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('mobile', 'coding', '0-2', entry, [
    'Offline-sync reconciliation or conflict resolution',
    'Virtualized-list windowing or move-aware diffing',
    'Concurrency schedulers, priority queues, or cancellation',
    'All logic in a single function with no decomposition',
    'Ignoring null, empty, or malformed-API-input edge cases',
  ]),
  template('mobile', 'coding', '3-6', mid, [
    'Trivial array/string warm-ups any entry-level candidate solves instantly',
    'Building without clarifying the signature or surfacing edge cases',
    'Ignoring in-flight races or stale-result handling',
    'Blindly overwriting the cache instead of a merge rule',
    'No async cleanup (leaked timers, uncancelled requests)',
  ]),
  template('mobile', 'coding', '7+', senior, [
    'Treating it as a mid-level round — coding without discussing abstractions or tradeoffs',
    'Over-abstracting prematurely when a simple solution suffices',
    'Conflict resolution by blind last-write-wins with no reasoning about failure cases',
    'Re-rendering everything instead of diffing for minimal updates',
    'Gold-plating one area while ignoring cancellation, errors, or tests entirely',
  ]),
]
