import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Mobile × Technical × 0-2 ──────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['platform-background', 'Platform and language background', 'technical-depth', 'warm-up', 'must', 0,
    'Ask which platform and language they use (Swift/Kotlin/Dart/JS) and a screen they built. Calibrate fundamentals.',
    'Surface — note platform experience for follow-up topics.', 'One platform is sufficient at this level.'],
  ['lifecycle-basics', 'Screen and app lifecycle basics', 'technical-depth', 'warm-up', 'must', 0,
    'Ask what happens when a screen appears, goes to background, and returns. Calibrate lifecycle understanding.',
    'Surface — use answer to calibrate which lifecycle questions to probe.',
    'Expect awareness of lifecycle callbacks; depth on process death not required yet.'],
  ['state-and-rotation', 'State across rotation and config change', 'technical-depth', 'exploration', 'must', 2,
    'Ask where screen state lives and what happens on rotation or a configuration change. Look for ViewModel/@State use.',
    'Probe: "Where does that state go if the OS kills your process while backgrounded?" — restoration awareness.',
    'Surviving rotation is the practical differentiator for junior candidates.'],
  ['list-and-data-fetch', 'Build a list backed by an API', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to design a screen that fetches a list and shows loading, error, and empty states.',
    'Probe: "How do you cancel the request if the user leaves the screen mid-fetch?"',
    'No expectation of caching, pagination, or offline yet — clean states are the signal.'],
  ['ui-toolkit-basics', 'UI toolkit and layout basics', 'ux-engineering', 'exploration', 'must', 2,
    'Ask about building a responsive layout in their toolkit (Compose/SwiftUI/XML/Flutter widgets).',
    'Probe: "How does it adapt to different screen sizes and a notch/safe area?"',
    'Layout confidence across device sizes is a strong differentiator at this level.'],
  ['async-basics', 'Async and main-thread basics', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask why you must not block the main thread and how they run work off it (coroutine, async/await, GCD).',
    'Probe: "What does the user see if you do heavy work on the main thread?" — ANR/dropped-frame awareness.'],
  ['permissions-basics', 'Permissions and a platform API', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask about requesting a runtime permission (camera, location) and handling the denied case.',
    'Probe: "What happens if the user denies it permanently? How does the UI respond?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-what-different', 'What would you do differently', 'problem-solving', 'closing', 'must', 0,
    'Ask what they\'d change about their approach or add with more time.',
    'Surface — assess reflection and polish instinct.'],
]

// ─── Mobile × Technical × 3-6 ──────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['architecture-intro', 'App architecture and state intro', 'technical-depth', 'warm-up', 'must', 0,
    'Ask which architecture they use (MVVM, MVI, TCA, unidirectional) and why. Calibrate state-management depth.',
    'Surface — use answer to choose which internals to probe.',
    'Expect a real opinion on state flow, not just "we use MVVM because the template did."'],
  ['process-death-restoration', 'Process death and state restoration', 'technical-depth', 'exploration', 'must', 2,
    'Ask what survives process death vs. config change and how they restore a multi-step flow.',
    'Probe: "User is on step 3 of a form, OS kills the app in background — what do they see on return?"',
    'Restoring across process death (SavedStateHandle, state restoration) separates mid from junior.'],
  ['offline-cache-sync', 'Offline cache and background sync', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they design an offline-first screen: local DB as source of truth, background sync, stale handling.',
    'Probe: "Two devices edit the same record offline — how do you reconcile on reconnect?"',
    'Single-source-of-truth and a real conflict policy distinguish mid candidates.'],
  ['list-performance', 'List and rendering performance', 'performance', 'exploration', 'must', 2,
    'Ask about a janky list: diffing (DiffUtil/Lazy keys), image loading, recycling, and over-recomposition.',
    'Probe: "How do you measure frame drops? What tool, and what is your target frame budget?"',
    'Expect a frame budget (16ms / 60fps) and a real profiler, not "we added a cache."'],
  ['concurrency-cancellation', 'Concurrency and structured cancellation', 'technical-depth', 'exploration', 'must', 2,
    'Ask about coroutines/async-await/Combine: cancelling in-flight work, scoping to the screen, avoiding leaks.',
    'Probe: "Two searches in flight, the second returns first — how do you avoid showing stale results?"',
    'No cancellation story (leaked jobs, stale results) is a red flag at this level.'],
  ['push-and-background', 'Push notifications and background work', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about push delivery, deep-link routing from a notification, and scheduling background work (WorkManager/BGTask).',
    'Probe: "OS throttles background execution — how do you guarantee the sync eventually runs?"'],
  ['memory-battery', 'Memory and battery awareness', 'performance', 'exploration', 'if-time', 2,
    'Ask about a memory leak they fixed or a battery regression (wakelocks, location, polling).',
    'Probe: "How did you find the leak? What retained the reference?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tooling', 'Build, release, and CI awareness', 'technical-depth', 'closing', 'must', 0,
    'Ask how they\'d set up CI for a mobile app: tests, signing, and a staged rollout. Assess operational awareness.',
    'Surface — conceptual familiarity with device testing and release tracks is sufficient.'],
]

// ─── Mobile × Technical × 7+ ───────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['architecture-strategy', 'App architecture strategy', 'technical-depth', 'warm-up', 'must', 0,
    'Ask how they\'d modularize a large app and structure the data layer. Look for nuanced tradeoffs.',
    'Surface — calibrate depth; note which areas to probe.',
    'Architecture over implementation: designing systems other engineers build on.'],
  ['offline-first-data-layer', 'Offline-first data layer design', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to design a data layer that works fully offline and reconciles on reconnect across many entities.',
    'Probe: "What is the source of truth? Last-write-wins vs. server-authoritative vs. CRDT — when each?"',
    'Knowing when each sync/conflict strategy fails is a strong senior signal.'],
  ['modularization-di', 'Modularization and dependency injection', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they\'d split a monolith app into feature modules, manage build times, and wire DI across them.',
    'Probe: "How do feature modules share state without depending on each other? Build-time impact?"',
    'Coordination across teams matters as much as the technical split.'],
  ['cross-platform-decision', 'Native vs. cross-platform technical decision', 'technical-depth', 'exploration', 'must', 2,
    'Ask when they\'d choose native vs. Flutter/React Native/KMP and the technical limits of each.',
    'Probe: "When would you NOT recommend cross-platform? Where does the bridge/perf cost bite?"',
    'Knowing when not to use a pattern is a strong senior signal.'],
  ['release-engineering', 'Release engineering and rollout strategy', 'technical-depth', 'exploration', 'must', 2,
    'Ask about staged rollout, feature flags, kill switches, crash-gated promotion, and rollback constraints.',
    'Probe: "A 2% crash spike appears at 10% rollout — walk me through your response. You can\'t recall the binary."',
    'Release is organizational engineering, not a per-sprint task.'],
  ['observability-crash', 'Crash reporting and observability', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about crash-free-rate targets, symbolication, ANR tracking, and performance monitoring in production.',
    'Probe: "How do you instrument for graceful degradation when the backend is down at scale?"'],
  ['mobile-ci-build', 'Mobile CI/CD and build pipeline', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about device-farm testing, code signing automation, build caching, and reducing app size.',
    'Probe: "CI build takes 40 minutes and app size grew 30MB — walk me through diagnosis and a plan."'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-tradeoffs', 'Trade-offs and organizational impact', 'leadership', 'closing', 'must', 0,
    'Ask how they\'d raise the bar on stability and velocity across multiple mobile teams. Assess org thinking.',
    'Surface — tests strategic thinking beyond individual contribution.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('mobile', 'technical', '0-2', entry, [
    'Offline-first data-layer architecture or conflict-resolution strategy',
    'Modularization, dependency injection, or build pipeline design',
    'Staged rollout, feature flags, or release engineering',
    'Cross-platform vs. native strategic tradeoffs at org scale',
    'Backend system design or heavy algorithm questions',
  ]),
  template('mobile', 'technical', '3-6', mid, [
    'Basic lifecycle callbacks any entry-level candidate knows',
    'Org-wide modularization, DI architecture, or release strategy (senior territory)',
    'Pure algorithm questions disconnected from mobile',
    'Accepting "I\'d cache it locally" without probing the sync and conflict story',
  ]),
  template('mobile', 'technical', '7+', senior, [
    'Entry or mid-level lifecycle, basic state, or single-screen questions',
    'Pure coding challenges testing speed rather than architecture',
    'Backend system design (databases, microservices) instead of the mobile data layer',
    'Single-platform questions without cross-platform tradeoff thinking',
    'Not asking about organizational impact or release strategy',
  ]),
]
