import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Mobile × System Design × 0-2 ──────────────────────────────────────────
const entry: CompactSlot[] = [
  ['screen-decomposition', 'Screens and navigation breakdown', 'component-architecture', 'warm-up', 'must', 0,
    'Present a simple app (notes, feed reader). Ask them to break it into screens and a navigation flow.',
    'Surface — probe: "Which screen owns this data and how does the next screen get it?"',
    'Screen thinking, not architecture — decomposition is the goal at this level.'],
  ['local-data-model', 'Local data model', 'technical-depth', 'warm-up', 'must', 0,
    'Ask what the data looks like on the device and where it is stored (in-memory, a local DB).',
    'Surface — look for a clear model and where it lives, not a full persistence framework.',
    'A reasonable entity shape and storage choice is sufficient.'],
  ['data-fetching-states', 'Data fetching with loading/error/empty', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they fetch the list from an API and show loading, error, and empty states.',
    'Probe: "What does the screen show while loading? On a failed request? With zero items?"',
    'No expectation of caching, pagination, or offline — clean states are the signal.'],
  ['network-failure-basic', 'Handling a failed network request', 'problem-solving', 'exploration', 'must', 2,
    'Ask what happens when the request fails or the phone has no connection.',
    'Probe: "User taps refresh with airplane mode on — what do they see and what can they do?"',
    'Awareness that the network fails (not full offline support) is enough here.'],
  ['navigation-state', 'Passing state between screens', 'component-architecture', 'exploration', 'must', 2,
    'Ask how data and state pass from the list screen to the detail screen and back.',
    'Probe: "User edits the detail and goes back — how does the list reflect the change?"'],
  ['caching-basic', 'Basic caching awareness', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask if they\'d cache the last fetch and why. Surface-level awareness is enough.',
    'Probe: "If the user reopens the app with no network, can they see anything? Should they?"'],
  ['responsiveness-basic', 'Different device sizes', 'ux-engineering', 'exploration', 'if-time', 1,
    'Ask what changes in their layout for a small phone vs. a tablet, or with a notch/safe area.',
    'Probe: "Which screens look different on a tablet? Does the navigation change?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-gaps', 'What they\'d add or improve', 'problem-solving', 'closing', 'must', 0,
    'Ask what they\'d improve or add given more time. Assess self-awareness.',
    'Surface — one honest observation is sufficient; wrap up warmly.'],
]

// ─── Mobile × System Design × 3-6 ──────────────────────────────────────────
const mid: CompactSlot[] = [
  ['requirements-gathering', 'Requirements and constraints', 'problem-solving', 'warm-up', 'must', 0,
    'Present a prompt (chat, upload queue, sync). Ask them to surface requirements before designing.',
    'Surface — probe non-functional needs: offline? real-time? ordering guarantees? battery?',
    'Core system design round — must demonstrate a structured approach before diving in.'],
  ['source-of-truth', 'Source of truth and local data model', 'technical-depth', 'exploration', 'must', 2,
    'Ask where the source of truth lives. Look for a local DB the UI reads from, with the network feeding it.',
    'Probe: "Does the UI ever read directly from the network? Why is that a problem?"',
    'A single source of truth (DB) the UI observes distinguishes mid from entry.'],
  ['offline-and-sync', 'Offline support and background sync', 'technical-depth', 'exploration', 'must', 2,
    'Ask how the app behaves offline and how it syncs when connectivity returns.',
    'Probe: "User sends a message offline — outbox? ordering? What does the delivery status show?"',
    'An outbox/queue with retry and a status model is the mid-level bar.'],
  ['conflict-handling', 'Conflict handling on reconnect', 'problem-solving', 'exploration', 'must', 2,
    'Ask what happens when local and server state diverge after an offline edit.',
    'Probe: "Two clients edited the same record — last-write-wins, merge, or server-authoritative? Tradeoffs?"',
    'A real conflict policy with reasoning is expected, not "the server just wins."'],
  ['performance-lists-media', 'List, image, and startup performance', 'performance', 'exploration', 'must', 2,
    'Ask about pagination, diffing, image loading/caching, and keeping scroll at the frame budget.',
    'Probe: "Feed has 10k items and large images — how do you keep it at 60fps and bound memory?"',
    'Pagination + image caching + diffing raised proactively is the signal.'],
  ['push-realtime', 'Push and real-time updates', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask how the app receives updates: push notifications, polling, or a socket, and how it routes deep links.',
    'Probe: "Push vs. socket here — why? What happens to a notification tap from a cold start?"'],
  ['lifecycle-restoration', 'Lifecycle and state restoration', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask how the design survives backgrounding and process death mid-flow.',
    'Probe: "OS kills the app during an upload — does it resume? How does the user know?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['migration-path', 'Rollout and instrumentation', 'problem-solving', 'closing', 'must', 0,
    'Ask how they\'d roll this out safely and prove it works in production.',
    'Surface — probe for staged rollout awareness and one metric that proves health.'],
]

// ─── Mobile × System Design × 7+ ───────────────────────────────────────────
const senior: CompactSlot[] = [
  ['deep-requirements', 'Deep requirements and non-functional constraints', 'problem-solving', 'warm-up', 'must', 0,
    'Present a complex scenario (multi-device sync, live tracking, collaborative notes). Surface all requirements.',
    'Surface — probe: "Offline tolerance? Consistency model? Battery budget? Real-time latency target?"',
    'Must architect for many devices, flaky networks, and multiple engineering teams at once.'],
  ['sync-architecture', 'Sync and conflict architecture', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to design the sync engine: source of truth, change tracking, and conflict resolution at scale.',
    'Probe: "Server-authoritative vs. LWW vs. CRDT — when does each fail? How do you tombstone deletes?"',
    'Advanced concepts expected: operation logs, vector clocks/CRDTs, tombstones, idempotent sync.'],
  ['outbox-reliability', 'Outbox, queueing, and delivery guarantees', 'technical-depth', 'exploration', 'must', 2,
    'Ask about a durable outbox for writes/uploads: retries, ordering, idempotency, and process-death survival.',
    'Probe: "Guarantee exactly-once-ish delivery when the OS kills you mid-upload? Dedup on the server?"',
    'Durability across process death and idempotency keys are the senior bar.'],
  ['realtime-reconnection', 'Real-time transport and reconnection', 'technical-depth', 'exploration', 'must', 2,
    'Ask about the real-time layer: socket vs. push, reconnection with backoff, catch-up after a gap.',
    'Probe: "Socket drops for 30s in a tunnel — how do you resync missed events without a full reload?"',
    'Backoff with jitter, gap detection, and catch-up strategy expected.'],
  ['performance-at-scale', 'Performance, memory, and battery at scale', 'performance', 'exploration', 'must', 2,
    'Ask about startup time, frame budget, memory ceilings on low-end devices, and battery (location, wakelocks).',
    'Probe: "App is janky and drains battery on a low-end device — walk me through diagnosis and budgets."',
    'Must propose measurable budgets and monitoring — no observability story is a red flag.'],
  ['modularization-rollout', 'Modularization, rollout, and observability', 'leadership', 'exploration', 'if-time', 2,
    'Ask how the architecture maps to feature modules, staged rollout, kill switches, and crash gating.',
    'Probe: "Prevent one feature team\'s bug from crashing the whole app? How do you gate a rollout on crash rate?"'],
  ['failure-modes', 'Failure modes and graceful degradation', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask what happens when sync is permanently behind, storage is full, or the API contract changes.',
    'Probe: "Local DB schema migration on a corrupted store — how do you avoid bricking the user\'s data?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['success-metrics-senior', 'Success metrics and post-launch measurement', 'leadership', 'closing', 'must', 0,
    'Ask how they\'d measure whether the architecture succeeded 6 months after launch.',
    'Surface — probe concrete metrics: crash-free rate, sync latency, p95 startup, retention.',
    'Reference to real industry approaches (WhatsApp offline queue, Notion/Figma sync) is a positive signal.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('mobile', 'system-design', '0-2', entry, [
    'Designing a full offline sync engine or CRDT for a simple read-only app',
    'Jumping to data models before laying out screens and navigation',
    'Conflict resolution, outbox queues, or real-time transports',
    'Backend infrastructure (sharding, replication, message-queue internals)',
    'Silence — not explaining reasoning for screen or storage choices',
  ]),
  template('mobile', 'system-design', '3-6', mid, [
    'Designing the backend (database scaling, queues) instead of the on-device architecture',
    'No source of truth — UI reading from network and DB inconsistently',
    'Treating the network as always available; no offline or failure path',
    'Ignoring process death, lifecycle, or app backgrounding',
    'One-size-fits-all sync without naming a conflict policy',
  ]),
  template('mobile', 'system-design', '7+', senior, [
    'Platform tunnel vision ("I\'d use Compose") without a sync/offline architecture',
    'Skipping reliability: no outbox durability, idempotency, or process-death handling',
    'No monitoring, crash gating, or staged-rollout story',
    'Shallow conflict analysis ("server wins") without naming the failure cases',
    'Backend envy: designing server topology instead of the client data layer',
  ]),
]
