import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Mobile × Behavioral × 0-2 ──────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro-app', 'Intro and an app you\'re proud of', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves and describe an app they built. Look for pride in the user-facing result.',
    'Surface only — use to pick follow-up topics.', 'Side projects, internships, and store-published apps are all expected.'],
  ['motivation-mobile', 'Why mobile over web/backend', 'motivation', 'warm-up', 'must', 0,
    'Ask what sparked interest in mobile development. Look for genuine curiosity about apps people carry everywhere.',
    'One follow-up at most — keep it warm.', 'Assess learning orientation and coachability.'],
  ['learning-platform-sdk', 'Learning a new platform SDK or framework', 'problem-solving', 'exploration', 'must', 2,
    'Ask about picking up SwiftUI, Jetpack Compose, Flutter, or React Native for the first time. Look for learning strategy.',
    'Probe the hardest concept and how they got unstuck — independent vs. tutorial dependency.',
    'Accept bootcamp, course project, or self-study context.'],
  ['working-with-designer', 'Working with a designer on a touch interaction', 'collaboration', 'exploration', 'must', 2,
    'Ask about disagreeing on a gesture, animation, or screen transition. Look for pragmatic tradeoff handling.',
    'Isolate their reasoning: "Walk me through the specific disagreement and the designer\'s perspective."',
    'Gestures, haptics, and platform-native patterns are unique mobile collaboration points.'],
  ['device-specific-bug', 'Debugging a device- or OS-specific bug', 'problem-solving', 'exploration', 'must', 2,
    'Ask about a bug that reproduced only on one device, screen size, or OS version. Look for systematic approach.',
    'Probe tools used: device logs, crash reports, a physical test device. Not just "I Googled it."',
    'Limited blast-radius bugs expected; focus on approach over outcome.'],
  ['deadline-scope-cut', 'Shipping a release under a deadline — scope decisions', 'problem-solving', 'exploration', 'if-time', 1,
    'Ask about cutting polish or a feature to make a release date. Look for thoughtful prioritization.',
    'Probe what was cut and the reasoning, not just that they worked faster.'],
  ['receiving-app-feedback', 'Receiving a poor app-store rating or user complaint', 'self-awareness', 'exploration', 'if-time', 2,
    'Ask about reacting to a one-star review or a user complaint about their feature. Unique to mobile.',
    'Probe what they changed and how they separated signal from noise in the feedback.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-mobile-excitement', 'What mobile challenges excite you most', 'motivation', 'closing', 'must', 0,
    'Ask what kind of mobile problems they want to tackle next. Assess enthusiasm and self-awareness.',
    'Surface — wrap up warmly and note growth signals.'],
]

// ─── Mobile × Behavioral × 3-6 ──────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['career-direction', 'Career direction — why mobile evolved', 'motivation', 'warm-up', 'must', 0,
    'Ask how perspective on mobile vs. web/backend evolved with experience. Calibrate ownership lens.',
    'Surface — use to identify which deep-dives to pursue.', 'Must reflect on real apps with real users.'],
  ['advocating-offline', 'Advocating for offline support under pressure', 'product-sense', 'exploration', 'must', 2,
    'Ask about pushing for offline-first or sync when product wanted online-only. Look for business case framing.',
    'Probe the user scenario that justified it, how the conflict was handled, and what won stakeholder buy-in.',
    'Concrete user impact (flaky network, transit usage) differentiates practitioners.'],
  ['crash-incident', 'Handling a production crash spike', 'operational', 'exploration', 'must', 2,
    'Ask about a crash spike they could not hotfix instantly. Look for diagnosis, comms, and rollback handling.',
    'Probe the crash rate before/after, how they triaged without a hotfix, and the store-review constraint.',
    'Must involve real production users — not a local repro.'],
  ['platform-parity-tension', 'Navigating iOS/Android parity tension', 'collaboration', 'exploration', 'must', 2,
    'Ask about a feature where the two platforms diverged and they had to decide on parity vs. native UX.',
    'Probe how they communicated the tradeoff to PM and design, and what they ultimately shipped.',
    'Expect ownership of the decision, not just deferral to "whatever design said."'],
  ['performance-optimization-story', 'App performance optimization story', 'performance', 'exploration', 'must', 2,
    'Ask about fixing a jank, slow-startup, or battery/memory regression. Look for specific before/after metrics.',
    'Probe exact metric (startup time, frame drops, memory), the profiler used, and how it was measured.',
    'Vague "we made it faster" without numbers is a red flag at this level.'],
  ['cross-functional-friction', 'Cross-functional friction — PM, backend, design', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about bridging a backend API or design mock with mobile constraints. Look for specific friction and resolution.',
    'Probe how they negotiated an API contract or payload shape without stalling the release.'],
  ['tech-debt-mobile', 'Balancing mobile tech debt with feature delivery', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about advocating for refactoring legacy navigation, a god-ViewController, or a brittle sync layer.',
    'Probe the business case made and what actually changed in the codebase.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retrospective-decision', 'A mobile decision you\'d make differently', 'self-awareness', 'closing', 'must', 0,
    'Ask what they\'d change knowing what they know now. Assess intellectual honesty and growth.',
    'Surface — one example suffices; wrap up warmly.'],
]

// ─── Mobile × Behavioral × 7+ ───────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-mobile-role', 'Mobile as a strategic discipline', 'leadership', 'warm-up', 'must', 0,
    'Ask how they connect mobile craft (crash-free rate, app size, retention) to business outcomes. Look for multi-dimensional thinking.',
    'Surface — calibrate scope and identify which leadership dimensions to probe.',
    'Must show impact across technical, people, process, and business dimensions.'],
  ['native-vs-crossplatform-leadership', 'Leading a native vs. cross-platform decision', 'technical-depth', 'exploration', 'must', 2,
    'Ask about driving an org decision on native vs. Flutter/React Native/KMP. Look for who disagreed and how consensus formed.',
    'Probe the deciding factors (team skills, hiring, performance) and what they\'d do differently.',
    'Scope must span multiple teams or the whole app — not one screen.'],
  ['release-train-leadership', 'Owning the mobile release train and rollback', 'leadership', 'exploration', 'must', 2,
    'Ask about establishing release cadence, staged rollout, feature flags, and rollback strategy across teams.',
    'Probe how they handled the fact that you cannot instantly recall a bad binary from users\' phones.',
    'Must show process creation — phased rollout and kill switches, not single releases.'],
  ['platform-migration-leadership', 'Leading a large platform migration', 'leadership', 'exploration', 'must', 2,
    'Ask about a UIKit-to-SwiftUI, Java-to-Kotlin, or hybrid-to-native migration. Look for phased planning and morale.',
    'Probe: "Give a one-sentence summary of each phase" — tests executive communication.',
    'Multi-month arcs across multiple team members expected.'],
  ['mobile-infra-leadership', 'Mobile infrastructure or CI/CD leadership', 'leadership', 'exploration', 'if-time', 2,
    'Ask about improving build times, device-farm testing, code signing, or a mobile CI pipeline. Look for org-wide impact.',
    'Probe what practices outlasted them and how they drove adoption across teams.'],
  ['business-impact-mobile', 'Connecting mobile decisions to business metrics', 'leadership', 'exploration', 'if-time', 2,
    'Ask about a mobile decision with direct retention, conversion, or revenue impact. Look for business framing.',
    'Probe: "Can you connect that mobile decision to a specific business metric?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['mobile-bet-failure', 'Biggest mobile bet that didn\'t pan out', 'self-awareness', 'closing', 'must', 0,
    'Ask about a significant initiative (a rewrite, a framework bet) that failed or underdelivered. Look for organizational learning.',
    'Probe systemic changes, not just personal lessons.', 'Failure questions carry more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('mobile', 'behavioral', '0-2', entry, [
    'Leading teams or mentoring others',
    'Native-vs-cross-platform architecture decisions or release-train ownership',
    'Production incident management or on-call',
    'Cross-team influence or org-wide standards',
    'Generic conflict questions without mobile context',
  ]),
  template('mobile', 'behavioral', '3-6', mid, [
    'Entry-level "learning a new SDK" questions',
    'Org-wide platform strategy (senior territory)',
    'Generic teamwork stories without mobile context',
    'Accepting vague performance claims without probing for metrics',
    'Mentoring and team-building as primary topic',
  ]),
  template('mobile', 'behavioral', '7+', senior, [
    'Individual bug fixes or coding accomplishments',
    'Single technology choices without organizational context',
    'Generic leadership questions that could apply to any role',
    'Questions an IC3/IC4 could answer equally well',
    'Accepting "we rewrote in Flutter" without probing rollout plan and business case',
  ]),
]
