import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Operations × Technical × 0-2 ───────────────────────────────────────────
const entry: CompactSlot[] = [
  ['metric-fundamentals', 'Core operations metric fundamentals', 'analytical', 'warm-up', 'must', 0,
    'Ask them to define cycle time, utilization, and on-time delivery and what each tells you.',
    'Surface — probe whether they understand what the metric drives, not just the formula.',
    'Conceptual grasp of core metrics is the baseline expectation at this level.'],
  ['simple-bottleneck', 'Identifying a bottleneck in a simple line', 'analytical', 'warm-up', 'must', 0,
    'Present a 3-4 station line with different rates. Ask for line output and where to focus.',
    'Surface — walk through their reasoning. Approach matters more than the exact number.',
    'Process over precision — must grasp that the slowest step governs output.'],
  ['throughput-math', 'Throughput and capacity calculation', 'analytical', 'exploration', 'must', 2,
    'Give a small throughput or capacity problem (units/hour, available hours). Have them work it out loud.',
    'Probe: "Double-check that — if a station runs 7 hours not 8, how does output change?"',
    'The #1 math mistake is dropping a unit or a zero — always sanity-check against common sense.'],
  ['inventory-basics', 'Inventory and lead-time fundamentals', 'operational', 'exploration', 'must', 2,
    'Ask how lead time and demand variability drive safety stock and reorder points.',
    'Probe: "If lead time doubles but demand is steady, what happens to your safety stock?"',
    'Conceptual understanding of buffers, not full optimization — lead time, safety stock, reorder point.'],
  ['kpi-reading', 'Reading an operational KPI dashboard', 'analytical', 'exploration', 'must', 2,
    'Show a small set of KPIs (throughput, error rate, on-time). Ask what the data tells them and what to check.',
    'Probe: "Two of these moved in opposite directions — which would you investigate first and why?"',
    'Strongest candidates generate a hypothesis, not just read the numbers off the board.'],
  ['process-mapping', 'Mapping a simple process to find waste', 'analytical', 'exploration', 'if-time', 1,
    'Ask how they would map a routine process to spot a wasteful or redundant step.',
    'Probe: "What would tell you that step is waste versus necessary?"'],
  ['root-cause-basic', 'Basic root-cause reasoning', 'analytical', 'exploration', 'if-time', 2,
    'Give a recurring small defect. Ask them to walk a 5 Whys chain to a plausible root cause.',
    'Probe: "How would you confirm that\'s really the cause before you change anything?"',
    'Tests whether they dig past the symptom — first answer is rarely the root cause.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['explaining-analysis', 'Explaining the fix to a frontline team', 'communication', 'closing', 'must', 0,
    'Ask how they would explain their proposed change to operators who do not think in metrics.',
    'Surface — tests translation of quantitative findings into a clear, actionable instruction.'],
]

// ─── Operations × Technical × 3-6 ───────────────────────────────────────────
const mid: CompactSlot[] = [
  ['problem-scoping', 'Scoping an operational problem', 'analytical', 'warm-up', 'must', 0,
    'Present a vague operational problem. Assess whether they ask about scope, data, and the metric at stake.',
    'Surface — better scoping equals a better diagnosis. Note what they ask for and ignore.',
    'Analysis must drive a decision — "throughput is down" is an observation, not a diagnosis.'],
  ['constraint-analysis', 'Theory-of-constraints flow analysis', 'analytical', 'exploration', 'must', 2,
    'Present a multi-step process with a hidden bottleneck. Ask them to find and exploit the constraint.',
    'Probe: "You sped up the bottleneck and it moved downstream. Now what?"',
    'Must understand that improving non-constraints doesn\'t add output — the signature mid-level test.'],
  ['capacity-planning', 'Capacity planning under variable demand', 'analytical', 'exploration', 'must', 2,
    'Ask them to plan capacity for a line facing variable demand. Look for utilization and buffer reasoning.',
    'Probe: "At 95% utilization throughput is falling — explain the queueing dynamic at play."',
    'Must grasp that very high utilization increases variability and wait time, not just output.'],
  ['inventory-optimization', 'Inventory and replenishment optimization', 'operational', 'exploration', 'must', 2,
    'Ask them to set reorder points and safety stock for an item, balancing stockout risk against holding cost.',
    'Probe: "Service level target jumps from 95% to 99%. What happens to inventory and cost?"',
    'Quantitative intuition expected — should reason about the cost of each extra nine of service level.'],
  ['kpi-diagnosis', 'Diagnosing a degrading KPI to its driver', 'analytical', 'exploration', 'if-time', 2,
    'Give a KPI that dropped (on-time delivery, fill rate). Ask them to decompose it to the root driver.',
    'Probe: "Two signals conflict — labor hours are flat but output fell. How do you resolve that?"',
    'Expected to go beyond descriptive to diagnostic — decompose the metric into its components.'],
  ['process-improvement', 'Designing a measurable improvement program', 'analytical', 'exploration', 'if-time', 2,
    'Ask them to design an improvement for a process running 500bp below target. Tests quantified intervention.',
    'Probe: "How would you measure that the change worked and didn\'t just shift the problem?"'],
  ['recommendation-synthesis', 'Synthesizing an operational recommendation', 'analytical', 'exploration', 'must', 2,
    'Ask for their recommendation from the analysis, with expected impact and the metric it moves.',
    'Probe: "Walk me through the first 30 days of rolling this out on the floor."',
    'Must connect the analysis to a number — "this should cut cycle time ~15%" with the reasoning.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['implementation-risks', 'Implementation risks and mitigation', 'collaboration', 'closing', 'must', 0,
    'Ask what could go wrong rolling out their change and how they would de-risk it.',
    'Surface — "good analysis, now how do you execute without disrupting throughput?" separates mid from entry.'],
]

// ─── Operations × Technical × 7+ ────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['system-scoping', 'System-level operational scoping and hypothesis', 'analytical', 'warm-up', 'must', 0,
    'Present a network- or multi-site-level problem. Assess incisive scoping and an upfront hypothesis.',
    'Surface — financial and flow reasoning should be embedded, not asked for separately.',
    'Experience-formed point of view expected — "I\'d have to research it" is no longer sufficient.'],
  ['network-flow-design', 'Designing flow across a network', 'operational', 'exploration', 'must', 2,
    'Ask them to design the flow for a multi-node fulfillment or manufacturing network.',
    'Probe: "Where do you place the buffers, and why there and not at the constraint itself?"',
    'Must reason about end-to-end flow, buffer placement, and decoupling points across nodes.'],
  ['capacity-inventory-tradeoff', 'Capacity vs inventory vs labor tradeoff', 'analytical', 'exploration', 'must', 2,
    'Present a demand surge. Ask how they choose among adding a shift, adding capacity, or holding inventory.',
    'Probe: "Two of these have lower cost-to-serve but higher risk. How do you decide under uncertainty?"',
    'Tests system-level cost-to-serve reasoning, not single-lever optimization.'],
  ['metric-system-design', 'Designing an operational measurement system', 'analytical', 'exploration', 'must', 2,
    'Ask them to design the KPI system for a region or network and how the metrics ladder up.',
    'Probe: "An operator can game on-time delivery by shipping incomplete orders. How do you prevent that?"',
    'Must address metric integrity, balancing tensions, and laddering site metrics to network outcomes.'],
  ['s-and-op-design', 'Designing the S&OP / planning process', 'operational', 'exploration', 'if-time', 2,
    'Ask how they would design the sales-and-operations planning process for a large operation.',
    'Probe: "Demand and supply plans disagree by 20% every cycle. How do you reconcile and who decides?"'],
  ['automation-decision', 'Automation and capex investment decision', 'financial-acumen', 'exploration', 'if-time', 2,
    'Ask how they evaluate a major automation investment against the labor and throughput status quo.',
    'Probe: "The payback is 4 years but volume forecasts are soft. How do you frame the risk to the board?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['exec-recommendation', 'Executive operational recommendation', 'communication', 'closing', 'must', 0,
    'Ask them to frame their recommendation for an executive audience in under 3 minutes.',
    'Probe: "This redesign won\'t show savings for 12 months. How do you justify it to a quarterly-focused CFO?"',
    'Must frame flow, cost, and risk concisely with quantified impact and an explicit resource ask.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('operations', 'technical', '0-2', entry, [
    'Network-level flow design or multi-site buffer placement',
    'Designing a full KPI measurement system from scratch',
    'Capex/automation investment analysis with payback modeling',
    'S&OP or sales-and-operations planning process design',
    'Theory-of-constraints across a multi-node network',
  ]),
  template('operations', 'technical', '3-6', mid, [
    'Reciting lean/Six Sigma tools without doing the underlying math',
    'Recommending "add capacity" without first diagnosing the constraint',
    'Analysis without a recommendation — describing data with no operational conclusion',
    'Treating very high utilization as purely good (ignoring queueing effects)',
    'Designing a network-wide measurement system (senior-level scope)',
  ]),
  template('operations', 'technical', '7+', senior, [
    'Same depth as mid-level — running the analysis instead of designing the system',
    'A measurement system with no defense against metric gaming',
    'Capacity or inventory analysis with no cost-to-serve or financial framing',
    'Ignoring frontline adoption and change management in the rollout',
    'Single-site optimization that does not scale to the network',
  ]),
]
