import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Operations × Behavioral × 0-2 ──────────────────────────────────────────
const entry: CompactSlot[] = [
  ['background-motivation', 'Background and motivation for operations', 'communication', 'warm-up', 'must', 0,
    'Ask candidate to walk through their background and why operations. Assess clarity and bias for action.',
    'Surface — use to calibrate scope. What did they actually own day to day.',
    'Potential over track record — assess ownership instinct and attention to detail.'],
  ['owning-a-task', 'Owning a small operational task end-to-end', 'execution', 'warm-up', 'must', 0,
    'Ask about a task they owned start to finish. Tests follow-through and accountability.',
    'Surface — one follow-up. Did they close the loop or hand it off and forget.',
    'End-to-end ownership of even a small thing is the highest-signal trait at this level.'],
  ['handling-a-problem', 'Reacting when something went wrong', 'execution', 'exploration', 'must', 2,
    'Ask about a time something broke on their shift or in their process. Tests calm and escalation judgment.',
    'Probe: "At the moment you realized it was wrong, what was the very first thing you did?"',
    'Knowing when to escalate versus fix it themselves is the key entry-level distinction.'],
  ['coordinating-with-others', 'Coordinating across teams or shifts', 'collaboration', 'exploration', 'must', 2,
    'Ask about coordinating with another team or shift to deliver on time.',
    'Isolate their role: "You said we — what specifically did YOU do versus the others?"',
    'Internship, part-time, or hourly-role stories are expected and acceptable.'],
  ['attention-to-detail', 'Catching an error before it became a problem', 'execution', 'exploration', 'must', 2,
    'Ask about a time they caught a mistake (wrong count, wrong label, missed step) before it shipped.',
    'Probe what made them double-check and what the consequence would have been.',
    'Tests vigilance and quality instinct — central to operations even at the lowest level.'],
  ['following-process', 'Working within or improving a process', 'execution', 'exploration', 'if-time', 1,
    'Ask about a time they suggested a better way to do a routine task. Tests improvement instinct.',
    'Probe whether they raised it, who they raised it to, and whether anything changed.'],
  ['handling-pressure', 'Staying organized under time pressure', 'execution', 'exploration', 'if-time', 2,
    'Ask about a busy period where they had to keep things on track. Tests composure and prioritization.',
    'Probe how they decided what to do first when everything felt urgent.',
    'Tests grit and prioritization under a deadline — peak or rush context is ideal.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['motivation-fit', 'Motivation and team fit', 'communication', 'closing', 'must', 0,
    'Ask why this operations role and what kind of environment they do their best work in.',
    'Surface — wrap up warmly. Quality of their closing questions also evaluated.'],
]

// ─── Operations × Behavioral × 3-6 ──────────────────────────────────────────
const mid: CompactSlot[] = [
  ['career-story', 'Operations career arc and scope', 'communication', 'warm-up', 'must', 0,
    'Ask for extended walkthrough — scale they ran, key transitions, what they want next.',
    'Surface — more scrutiny than entry. Probe team size, sites, and volume managed.',
    'Stories must feature real responsibility and metrics — "I helped out" is not a story.'],
  ['managing-disruption', 'Running a process through a disruption', 'execution', 'exploration', 'must', 2,
    'Ask about keeping a process or team running through a disruption. The signature mid-level question.',
    'Probe: "What broke first, and what was the decision you made that you weren\'t sure about?"',
    'Must show they made calls, not just followed a runbook — composure plus judgment.'],
  ['cross-functional-conflict', 'Aligning functions with competing priorities', 'collaboration', 'exploration', 'must', 2,
    'Ask about aligning two functions with conflicting goals (e.g., sales speed vs. warehouse accuracy).',
    'Probe: "Who specifically was pushing back? What was their underlying concern?"',
    'Must map the other side\'s incentives and describe deliberate, not lucky, resolution.'],
  ['driving-process-change', 'Driving a change the frontline resisted', 'execution', 'exploration', 'must', 2,
    'Ask about a process change the frontline team initially resisted. Tests adoption, not just design.',
    'Probe: "Walk me through the conversation with the most resistant person on the floor."',
    'Engagement at the frontline expected — change that no one adopted is not a win.'],
  ['making-a-tradeoff', 'Making a cost/speed/quality tradeoff', 'execution', 'exploration', 'if-time', 2,
    'Ask about a call where they had to trade off cost, speed, or quality with imperfect information.',
    'Probe what alternatives they weighed and why they chose this one.'],
  ['developing-frontline', 'Coaching a frontline team member or lead', 'leadership', 'exploration', 'if-time', 1,
    'Ask about developing a frontline team member or shift lead. Tests investment in team capability.',
    'Probe: "How did you handle the underperformer? What specifically changed?"'],
  ['sustaining-improvement', 'An improvement that actually stuck', 'execution', 'exploration', 'must', 2,
    'Ask about an operational improvement they drove that held up over time. Tests durability thinking.',
    'Probe: "How did you measure it? Where was the metric 6 months later?"',
    'Quantified, durable impact expected — cycle time, error rate, cost per unit with numbers.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['navigating-pushback', 'Holding the line under pressure to cut corners', 'execution', 'closing', 'must', 0,
    'Ask about a time they were pressured to compromise standards (safety, accuracy) and how they handled it.',
    'Surface — one clear example. Probe outcome and whether the relationship survived.'],
]

// ─── Operations × Behavioral × 7+ ───────────────────────────────────────────
const senior: CompactSlot[] = [
  ['leadership-trajectory', 'Leadership arc across operations', 'leadership', 'warm-up', 'must', 0,
    'Ask about career arc with emphasis on scope of operations led, business impact, and key choices.',
    'Surface — leader-level read: "Would I trust this person to run a network or a site P&L?"',
    'Focus shifts from running a process to building the operation and the team that runs it.'],
  ['crisis-at-scale', 'Leading an operation through a major shock', 'execution', 'exploration', 'must', 2,
    'Ask about leading through a major shock — supplier collapse, demand surge, peak that nearly broke.',
    'Probe: "What did you choose to protect, and what did you knowingly let slip?"',
    'Must show executive-level triage and communication, not just hands-on firefighting.'],
  ['cross-functional-at-exec', 'Aligning executive peers on an operational call', 'collaboration', 'exploration', 'must', 2,
    'Ask how they aligned peer executives (commercial, finance, supply) on a contentious operational decision.',
    'Probe: "How did you frame the tradeoff for the CFO versus the head of sales?"',
    'Influence without authority at the leadership table — tailored framing per stakeholder.'],
  ['transformation', 'Transforming how an operation works', 'execution', 'exploration', 'must', 2,
    'Ask about transforming an operation — restructuring, automation rollout, network redesign, lean program.',
    'Probe: "How did you make it stick? What happened after you stopped pushing it personally?"',
    'Must address culture, frontline adoption, and sustained execution — not just a project plan.'],
  ['pl-or-budget', 'Operational P&L or cost accountability', 'financial-acumen', 'exploration', 'if-time', 2,
    'Ask about accountability for an operational budget or cost-to-serve. Tests commercial operating sense.',
    'Probe: "Walk me through the biggest cost line you owned and how you moved it."'],
  ['building-leaders', 'Building the next layer of operations leaders', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they identified, developed, and promoted frontline supervisors into managers.',
    'Probe: "Who did you develop who now runs an operation? What was your approach?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['failure-at-scale', 'A significant operational failure with org consequences', 'leadership', 'closing', 'must', 0,
    'Ask about a major operational failure (recall, outage, safety event) and how they handled the aftermath.',
    'Probe: "What did the organization change? What did YOU personally change?"',
    'At this level failures have organizational consequences — tests accountability and institutional learning.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('operations', 'behavioral', '0-2', entry, [
    'Running a P&L, network, or multi-site operation',
    'Leading cross-functional executive alignment',
    'Designing a transformation or automation program',
    'Building and developing a layer of frontline leaders',
    'Expecting large-scale quantified impact — accept small-scale or qualitative metrics',
  ]),
  template('operations', 'behavioral', '3-6', mid, [
    'School projects or classroom examples (must be a real operational context)',
    'Basic task ownership without any coordination or influence component',
    'Executive-peer alignment or board-level operational decisions',
    'Multi-site network redesign or P&L ownership',
    'Building a leadership pipeline of managers',
  ]),
  template('operations', 'behavioral', '7+', senior, [
    'Individual-contributor task execution without organizational scope',
    'Basic coordination across two shifts (entry-level topic)',
    'A single process change at the team level without business impact',
    'Learning to escalate appropriately (entry-level topic)',
    'Running one process through a disruption (mid-level topic)',
  ]),
]
