import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Operations × Case Study × 0-2 ──────────────────────────────────────────
const entry: CompactSlot[] = [
  ['case-clarifying-questions', 'Clarifying questions before structuring', 'analytical', 'warm-up', 'must', 0,
    'Present the operational scenario. Observe — does the candidate ask 2-3 clarifying questions first?',
    'Surface — jumping to "add people" without clarifying scope and the metric is the #1 entry mistake.',
    'Building structure from the actual flow beats reaching for a memorized template.'],
  ['case-structure', 'Structuring the problem into flow or cost drivers', 'analytical', 'warm-up', 'must', 0,
    'Give 60-90 seconds of silence. Look for a structure broken into flow steps or cost drivers.',
    'Surface — assess whether they lay out 3-4 logical branches before diving in.',
    'Taking structured silence to organize the flow is expected and rewarded.'],
  ['case-bottleneck', 'Diagnosing the bottleneck', 'analytical', 'exploration', 'must', 2,
    'Provide station rates or step data when asked. Have them identify the constraint step.',
    'Probe: "You think station 3 is the issue — what number proves it governs the line\'s output?"',
    'Math must be done out loud — silent calculation is the fastest way to fail an ops case.'],
  ['case-quantification', 'Quantitative exercise within the case', 'analytical', 'exploration', 'must', 2,
    'Insert a calculation: line output, utilization, or units lost per shift from the bottleneck.',
    'Probe: "That number looks high — walk me through the units-per-hour math again."',
    'The #1 math mistake is dropping a unit or a zero — always sanity-check the result.'],
  ['case-insight', 'Interpreting the data for an operational insight', 'analytical', 'exploration', 'must', 2,
    'Provide an exhibit (throughput, error, or cost data). Ask what it means operationally, not just numerically.',
    'Probe: "If you could check one more thing before recommending a fix, what would it be?"',
    'Stating numbers with no "so what" — no operational meaning — is a red flag.'],
  ['case-new-constraint', 'Adapting to a new constraint mid-case', 'analytical', 'exploration', 'if-time', 1,
    'Introduce a new constraint (overtime ban, space limit) mid-case. Tests whether they re-plan.',
    'Probe: "The plant manager needs your answer in 30 seconds. What\'s your call?"'],
  ['case-risk', 'Identifying risks to the recommendation', 'analytical', 'exploration', 'if-time', 2,
    'Ask what the biggest risk to their fix is and how they would mitigate it.',
    'Probe: "What\'s the worst case if your assumption about the bottleneck is wrong?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['case-recommendation', 'Decisive final recommendation', 'communication', 'closing', 'must', 0,
    'Ask for a final recommendation: clear lever, expected metric impact, 1-2 risks, mitigation.',
    'Surface — "it depends" is not a recommendation. Synthesis must be decisive and executable.'],
]

// ─── Operations × Case Study × 3-6 ──────────────────────────────────────────
const mid: CompactSlot[] = [
  ['mid-case-scoping', 'Case scoping and context-setting', 'analytical', 'warm-up', 'must', 0,
    'Present a multi-layered operational case. Assess scoping questions — operational experience shows here.',
    'Surface — better scoping reveals real floor experience. Note what they ask for and what they skip.',
    'Cases integrate threads — throughput plus capacity plus cost, not a single-framework exercise.'],
  ['throughput-diagnosis', 'Diagnosing a throughput or service drop', 'analytical', 'exploration', 'must', 2,
    'Present a center whose on-time delivery fell after volume grew. Ask for a constraint-aware diagnosis.',
    'Probe: "You sped up picking and the backup moved to shipping. Now what?"',
    'Must show the constraint moved, not vanished — improving a non-bottleneck adds no output.'],
  ['supply-disruption', 'Responding to a supply-chain disruption', 'operational', 'exploration', 'must', 2,
    'Present a supplier announcing a multi-week delay. Ask for the operational and inventory response.',
    'Probe: "Expedite, dual-source, or draw down safety stock — what do you do first and why?"',
    'Must weigh inventory cost, lead-time risk, and customer impact, not just react.'],
  ['capacity-cost-analysis', 'Capacity and cost-per-unit analysis', 'analytical', 'exploration', 'must', 2,
    'Present a site whose cost per unit is above target. Ask for diagnosis and a quantified improvement.',
    'Probe: "How does your plan change if you optimize for unit cost versus on-time delivery?"',
    'Must quantify each lever — "improve efficiency" without numbers fails at this level.'],
  ['multi-exhibit', 'Integrating multiple operational exhibits', 'analytical', 'exploration', 'if-time', 2,
    'Provide 2-3 exhibits (volume, labor hours, error rate). Ask for an integrated diagnosis.',
    'Probe: "Labor hours are flat but output fell and errors rose. What single cause ties these together?"',
    'Mid-level cases test integration across signals, not single-exhibit reading.'],
  ['implementation-plan', 'Implementation and rollout planning', 'collaboration', 'exploration', 'if-time', 2,
    'Ask how they would roll out their fix on the floor without disrupting current throughput.',
    'Probe: "Walk me through the first 90 days, including how you get the shift leads on board."'],
  ['kpi-tradeoff', 'Navigating a KPI tradeoff', 'analytical', 'exploration', 'must', 2,
    'Present a fix that improves one metric but risks another (speed vs. accuracy). Ask how they decide.',
    'Probe: "Faster picking lifts throughput 8% but error rate rises 2%. Do you ship it?"',
    'Industry context matters — generic answers without the actual cost of each metric fail.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['mid-case-synthesis', 'Synthesized recommendation with quantified impact', 'communication', 'closing', 'must', 0,
    'Ask for the final recommendation with quantified impact, risks, and an implementation timeline.',
    'Surface — "we should probably" instead of "this recovers ~6 pts of on-time delivery" is inadequate here.'],
]

// ─── Operations × Case Study × 7+ ───────────────────────────────────────────
const senior: CompactSlot[] = [
  ['senior-scoping', 'System-level scoping as a peer conversation', 'analytical', 'warm-up', 'must', 0,
    'Present a real (anonymized) network- or transformation-scale operational scenario. Observe their entry.',
    'Surface — the best senior candidates reach the core operational insight in 2 min, then structure around it.',
    'The case IS the conversation — a rigid 4-step framework walk-through signals not ready for the level.'],
  ['network-capacity-plan', 'Network-level capacity planning under a surge', 'operational', 'exploration', 'must', 2,
    'Present a peak with forecast volume up sharply. Ask for a capacity plan across the network.',
    'Probe: "The board wants it done with no new capex. What do you flex and what do you protect?"',
    'Must address shift/capacity/inventory tradeoffs, buffer placement, and cross-site balancing.'],
  ['cost-transformation', 'Multi-site cost-per-unit transformation', 'analytical', 'exploration', 'must', 2,
    'Present cost per unit creeping above target across three sites. Ask for the improvement program.',
    'Probe: "This requires $5M over 3 years and you have $3M and competing priorities. How do you sequence?"',
    'Must choose the right lever per site and tie each to a measurable cost and service outcome.'],
  ['disruption-at-scale', 'Major supply disruption response under time pressure', 'operational', 'exploration', 'must', 2,
    'Present a sole-source supplier failure threatening fulfillment. Design the response under time pressure.',
    'Probe: "You\'re 3 weeks in and the alternate source is 30% short. What do you do now?"',
    'Organizational and execution dimensions mandatory — 70% execution design, 30% analysis.'],
  ['operating-model-redesign', 'Redesigning the operating model post-change', 'leadership', 'exploration', 'if-time', 2,
    'Ask for an operating-model redesign after a merger, automation rollout, or network reconfiguration.',
    'Probe: "The two sites have incompatible processes and both leaders want theirs to win. How do you decide?"'],
  ['cost-to-serve', 'Cost-to-serve and value-creation plan', 'financial-acumen', 'exploration', 'if-time', 2,
    'Ask for a value-creation plan with measurable cost-to-serve targets over 100 days.',
    'Probe: "If you\'re wrong about this lever, what\'s the cost, and what\'s your hedge?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['exec-pitch', 'Executive pitch on the operational plan', 'communication', 'closing', 'must', 0,
    'Ask them to pitch the recommendation and its tradeoffs to an executive audience in under 5 minutes.',
    'Probe: "A board member asks how confident you are this hits the number. How do you answer?"',
    'C-suite communication tested — concise, data-backed, explicit risk/reward and resource requests.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('operations', 'case-study', '0-2', entry, [
    'Network-level capacity planning across multiple sites',
    'Multi-site cost transformation with capex sequencing',
    'Operating-model redesign after a merger',
    'Sole-source supply disruption at network scale',
    'Expecting an executive board-level pitch (keep recommendations operational)',
  ]),
  template('operations', 'case-study', '3-6', mid, [
    'Recommending "add capacity" without first finding the constraint',
    'Doing the throughput or cost math silently',
    'Analysis without quantified impact — "we should probably" with no number',
    'Ignoring the implementation and frontline-adoption dimension',
    'Full network capacity strategy or multi-site cost program (senior scope)',
  ]),
  template('operations', 'case-study', '7+', senior, [
    'Treating the case like a junior exercise with a rigid 4-step framework',
    'A plan with no implementation or change-management dimension',
    'Cost or capacity analysis with no financial / cost-to-serve framing',
    'Solving the presenting symptom instead of the structural constraint',
    'A recommendation that works at one site but does not scale to the network',
  ]),
]
