import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['self-intro', 'Tell me about yourself', 'motivation', 'warm-up', 'must', 0,
    'Current role/studies, interest in product, why this company. Calibrate scope.',
    'Surface — 2 min max.', 'Non-PM stories (school, internships) are expected and fine.'],
  ['product-curiosity', 'Product curiosity and user empathy', 'product-sense', 'warm-up', 'must', 0,
    'Ask about a product they love and why. Look for instinctive user-perspective thinking.',
    'Probe "How did you know this was what the user needed?"', 'User empathy is the differentiator.'],
  ['handling-ambiguity', 'Handling ambiguity', 'problem-solving', 'exploration', 'must', 2,
    'Ask about making progress with unclear requirements. Highest-signal topic for APMs.',
    'Probe "What did you do when you didn\'t have enough information?"',
    'Comfort with ambiguity is the single highest-signal topic.'],
  ['cross-functional-first', 'Cross-functional collaboration', 'collaboration', 'exploration', 'must', 2,
    'Ask about working with people from a different discipline. Test communication without authority.',
    'Isolate contribution: "You said we — what specifically did YOU do?"'],
  ['analytical-thinking', 'Problem-solving and analytical thinking', 'problem-solving', 'exploration', 'must', 2,
    'Ask about cracking a tough problem or using data to make a decision.',
    'Probe "What data did you look at?" Test structured thinking.'],
  ['learning-failure', 'Learning from failure', 'self-awareness', 'exploration', 'if-time', 2,
    'Ask about a time they failed. Test self-awareness and growth mindset.',
    'Probe "What would you do differently?" Look for ownership over blaming.'],
  ['initiative-scrappiness', 'Initiative and scrappiness', 'motivation', 'exploration', 'if-time', 1,
    'Ask about taking initiative outside responsibilities. APM programs look for proactive behavior.',
    'Probe opportunity identification, not just task execution.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['candidate-questions', 'Candidate questions', 'motivation', 'closing', 'must', 0,
    'Quality of questions is evaluated — product curiosity about roadmap, users, challenges.',
    'Surface — note quality of questions asked.'],
]

const mid: CompactSlot[] = [
  ['pm-journey', 'PM journey walkthrough', 'ownership', 'warm-up', 'must', 0,
    'Ask candidate to walk through their PM journey. Calibrate ownership scope and product types.',
    'Surface — calibration only.', 'Ownership scope is the dividing line from junior.'],
  ['product-launch', 'Product launch ownership', 'ownership', 'exploration', 'must', 2,
    'Ask about shipping a product end-to-end. Full lifecycle: discovery to launch to measurement.',
    'Probe "Who made that decision — you or your manager?" Isolate ownership.',
    'Must demonstrate personal ownership — "I drove" not "I contributed."'],
  ['stakeholder-conflict', 'Stakeholder conflict and influence', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about managing conflicting stakeholder requirements. Look for genuine tension.',
    'Probe underlying stakeholder motivations and data used to de-personalize.'],
  ['saying-no', 'Saying no and prioritization', 'execution', 'exploration', 'must', 2,
    'Ask about killing a feature or saying no. Test conviction and frameworks.',
    'Probe exact framework used (RICE, impact/effort) and relationship maintenance.'],
  ['data-driven', 'Data-driven decision making', 'data-driven', 'exploration', 'must', 2,
    'Ask about using data to change product direction. Expect metrics fluency.',
    'Probe north star metric, counter-metrics, and outcome validation.',
    'Naturally weave metrics into every story — fluency expected.'],
  ['user-advocacy', 'User advocacy against business pressure', 'product-sense', 'exploration', 'if-time', 2,
    'Ask about championing user perspective against business pressure.',
    'Probe genuine user obsession vs metrics obsession.'],
  ['product-failure', 'Handling product failure', 'self-awareness', 'exploration', 'if-time', 2,
    'Ask about a product or feature that failed. Test accountability and early detection.',
    'Probe stakeholder communication and process changes afterward.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['pm-philosophy', 'Product philosophy reflection', 'strategy', 'closing', 'must', 0,
    'Ask "What\'s your product philosophy?" or "How has your PM approach changed?"',
    'Surface — assess coherent PM worldview.'],
]

const senior: CompactSlot[] = [
  ['strategic-narrative', 'Product leadership journey', 'strategy', 'warm-up', 'must', 0,
    'Strategic narrative: biggest strategic bets, increasing scope. Not standard self-introduction.',
    'Surface — calibrate scope and strategic thinking depth.', 'Stories must be org/company scope.'],
  ['product-vision', 'Product vision and multi-year strategy', 'strategy', 'exploration', 'must', 2,
    'Ask about a product vision championed over multiple planning cycles. 1-3 year strategies.',
    'Probe "How did that hold up over 12-18 months? What changed in the market?"'],
  ['executive-alignment', 'Executive stakeholder alignment', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about aligning executive team on a controversial product direction.',
    'Probe "How did you get CEO/board on board? Data in that conversation?"',
    'VP vs SVP/CEO dynamics — hold ground with data while maintaining trust.'],
  ['turnaround', 'Turning around underperforming product', 'execution', 'exploration', 'must', 2,
    'Ask about a failing product and how they changed its trajectory.',
    'Probe root cause diagnosis: wrong strategy, people, process, or market?'],
  ['people-leadership', 'People leadership and PM development', 'leadership', 'exploration', 'must', 2,
    'Ask how they\'ve developed PMs. Coaching frameworks, career conversations, performance management.',
    'Probe specific systems built, not one-off mentoring instances.',
    'People leadership is non-negotiable at this level.'],
  ['market-strategy', 'Market strategy and business impact', 'strategy', 'exploration', 'if-time', 2,
    'Ask about identifying a new market opportunity and building product strategy.',
    'Probe P&L dynamics, unit economics, competitive positioning.'],
  ['hard-tradeoffs', 'Making hard tradeoffs', 'execution', 'exploration', 'if-time', 2,
    'Ask about the hardest product decision ever. Existential tradeoffs.',
    'Probe "What if you\'d made the other choice? Argument against your strategy?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['legacy-reflection', 'Legacy and impact reflection', 'self-awareness', 'closing', 'must', 0,
    'Ask about biggest product achievement and a decision they\'d make differently.',
    'Surface — durable impact vs launch celebrations.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('pm', 'behavioral', '0-2', entry, [
    'Managing product P&L or revenue impact',
    'Organizational strategy or team building',
    'Navigating boardroom politics',
    'Multi-quarter roadmap ownership',
    'Prioritization frameworks (RICE, MoSCoW)',
  ]),
  template('pm', 'behavioral', '3-6', mid, [
    'Org design or team-of-teams structure',
    'Multi-year vision or market entry strategy',
    'Hiring or developing other PMs',
    'P&L ownership or board communication',
    'Pure project management without product decisions',
  ]),
  template('pm', 'behavioral', '7+', senior, [
    'Individual feature prioritization or sprint decisions',
    'Personal time management stories',
    'Product sense exercises (design a product)',
    'Stories executing someone else\'s strategy',
    'Daily standups or agile ceremony discussions',
  ]),
]
