import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['clarify-scope', 'Clarify and scope', 'problem-solving', 'warm-up', 'must', 0,
    'Present an "improve X" prompt. Assess whether candidate asks about users, constraints, platform.',
    'Surface — note that they don\'t jump straight to solutions.', 'Structured thinking, not domain expertise.'],
  ['user-segmentation', 'User segmentation', 'product-sense', 'exploration', 'must', 2,
    'Ask candidate to identify 2-3 user segments and pick one with reasoning.',
    'Probe "Why that user segment over the others?"',
    'Creativity matters more than business sophistication.'],
  ['pain-points', 'Pain points and prioritization', 'product-sense', 'exploration', 'must', 2,
    'Ask for 3-5 pain points, prioritized by severity and frequency.',
    'Probe for user empathy — real people and real problems, not abstract personas.'],
  ['solution-brainstorm', 'Solution brainstorm and recommend', 'problem-solving', 'exploration', 'must', 2,
    'Ask for 3 solutions, then pick one using simple impact vs effort framework.',
    'Probe "Biggest risk with your solution?" and tradeoff awareness.'],
  ['metrics-success', 'Define success metrics', 'data-driven', 'exploration', 'if-time', 1,
    'Ask for 1 north-star metric + 2-3 supporting metrics.',
    'Probe concrete metric definitions, not just "track engagement."'],
  ['product-teardown', 'Product teardown', 'product-sense', 'exploration', 'if-time', 1,
    'Ask what makes a familiar product\'s experience work and what doesn\'t.',
    'Probe actionable recommendations, not just observations.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['wrap-up-tradeoffs', 'Summary and tradeoffs', 'problem-solving', 'closing', 'must', 0,
    'Ask to summarize and acknowledge tradeoffs. Assess self-awareness about limitations.',
    'Surface — wrap up.'],
]

const mid: CompactSlot[] = [
  ['business-context', 'Clarify business context', 'strategy', 'warm-up', 'must', 0,
    'Present a product strategy or design problem. Expect questions about business goals and constraints.',
    'Surface — note whether they ask "What\'s the company\'s strategic priority?"',
    'Business context matters — must ask before designing.'],
  ['market-users', 'Market and user analysis', 'product-sense', 'exploration', 'must', 2,
    'Expect competitive landscape awareness and behavioral segmentation (not just demographics).',
    'Probe "How different if optimizing revenue instead of growth?"'],
  ['problem-structuring', 'Problem structuring', 'problem-solving', 'exploration', 'must', 2,
    'Expect problem tree or opportunity map with 3-4 areas and sizing intuition.',
    'Probe quantitative reasoning: "This could affect ~20% of our DAU."',
    'Quantitative intuition expected.'],
  ['solution-design', 'Solution design with detail', 'product-sense', 'exploration', 'must', 2,
    'Expect 2-3 solutions with user flows, key screens, technical feasibility.',
    'Probe "Engineering says 6 months. Get 80% of value in 6 weeks?"'],
  ['prioritization-framework', 'Prioritization with framework', 'execution', 'exploration', 'if-time', 2,
    'Expect RICE, ICE, or weighted scoring with quantitative intuition.',
    'Probe tradeoff articulation — not the right solution, but clearest analysis.'],
  ['gtm-rollout', 'Go-to-market and rollout', 'execution', 'exploration', 'if-time', 2,
    'Expect phased rollout, A/B test design, launch-day vs week-4 metrics.',
    'Probe "Walk me through first 30 days after launch."'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['edge-cases-risks', 'Edge cases and risks', 'problem-solving', 'closing', 'must', 0,
    'Ask about cannibalization, tech debt, regulatory, international considerations.',
    'Surface — assess risk awareness.'],
]

const senior: CompactSlot[] = [
  ['strategic-framing', 'Strategic context framing', 'strategy', 'warm-up', 'must', 0,
    'Present a strategic problem (market entry, portfolio allocation). Expect reframing in company strategy terms.',
    'Surface — note whether they understand WHY this is being asked now.',
    'Strategy, not features. Never "design a feature."'],
  ['market-analysis', 'Market analysis', 'strategy', 'exploration', 'must', 2,
    'Expect TAM/SAM/SOM with reasoning. Competitive moats. Industry trends.',
    'Probe "Competitor announces same strategy next week. Now what?"'],
  ['strategic-options', 'Strategic options with conviction', 'strategy', 'exploration', 'must', 2,
    'Expect 2-3 strategies (not features) with thesis, assumptions, resources, risk profile.',
    'Probe "CEO disagrees. Convince me in 60 seconds." Test conviction under pressure.',
    'Mid-level PMs hedge. Senior PMs take a position and defend it.'],
  ['execution-roadmap', 'Execution roadmap', 'execution', 'exploration', 'must', 2,
    'Expect phased plan: Phase 0 validate, Phase 1 MVP, Phase 2 scale. Team + key hires.',
    'Probe "Board wants ROI in 12, not 18 months. What changes?"'],
  ['measurement-governance', 'Measurement and kill criteria', 'data-driven', 'exploration', 'if-time', 2,
    'Leading indicators per phase. Kill criteria — what data makes you abandon.',
    'Probe "What makes you kill this 6 months in?"'],
  ['second-order', 'Second-order effects', 'strategy', 'exploration', 'if-time', 2,
    'Impact on existing products, brand, talent, competitive response, regulatory.',
    'Probe "If we do X, competitors respond with Y, so we pre-invest in Z."'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['stress-test', 'Stress test / skeptical board member', 'stakeholder-management', 'closing', 'must', 0,
    'Play skeptical board member or CEO. THIS is the test at senior levels.',
    'Surface — assess composure and conviction under challenge.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('pm', 'case-study', '0-2', entry, [
    'Framework robot recitation without insight',
    'Solving for all users instead of picking a segment',
    'Solution-first without understanding the problem',
    'Metric hand-waving without concrete definitions',
  ]),
  template('pm', 'case-study', '3-6', mid, [
    'Generic frameworks without context adaptation',
    'Ignoring business model or monetization',
    'Single-metric myopia',
    'No competitive awareness',
    'Skipping rollout or experimentation strategy',
  ]),
  template('pm', 'case-study', '7+', senior, [
    'Feature-level thinking for strategic questions',
    'Analysis paralysis with no recommendation',
    'Ignoring organizational reality',
    'No kill criteria or abandonment conditions',
    'Abstract strategy without execution specifics',
  ]),
]
