import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['self-intro', 'Tell me about yourself', 'motivation', 'warm-up', 'must', 0,
    'Current role/studies, path into analytics, why this company. Calibrate scope.',
    'Surface — 2 min max.', 'Non-analytics stories (school, internships) are expected and fine.'],
  ['data-curiosity', 'Curiosity about why products behave as they do', 'product-sense', 'warm-up', 'must', 0,
    'Ask about a product behavior or number that surprised them. Look for instinct to dig into the "why."',
    'Probe "How did you figure out what was actually going on?"', 'Curiosity to investigate is the differentiator.'],
  ['analysis-to-decision', 'Turning an analysis into a decision', 'data-driven', 'exploration', 'must', 2,
    'Ask about an analysis that informed what the team did next. Highest-signal topic for junior analysts.',
    'Probe "Did anyone actually act on it? What changed?" Separate output from outcome.',
    'Connecting a number to an action is the single highest-signal topic.'],
  ['explaining-to-nontech', 'Explaining a finding to a non-technical person', 'communication', 'exploration', 'must', 2,
    'Ask about communicating a result to a PM, designer, or stakeholder without a data background.',
    'Probe "How did you know they understood it? What did they do with it?"'],
  ['working-with-pm', 'Collaborating with a PM to scope a question', 'collaboration', 'exploration', 'must', 2,
    'Ask about partnering with a PM to turn a vague request into an answerable question.',
    'Isolate contribution: "You said we — what specifically did YOU do?"'],
  ['sanity-checking', 'Catching an error in your own numbers', 'self-awareness', 'exploration', 'if-time', 2,
    'Ask about a time they found a mistake in their analysis before or after sharing it.',
    'Probe "What made you double-check?" Look for rigor and ownership over defensiveness.'],
  ['initiative-analysis', 'Initiative beyond the request', 'motivation', 'exploration', 'if-time', 1,
    'Ask about a time they surfaced something nobody asked for. Proactive analysts spot opportunities.',
    'Probe whether they identified the question themselves, not just executed a ticket.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['candidate-questions', 'Candidate questions', 'motivation', 'closing', 'must', 0,
    'Quality of questions is evaluated — curiosity about the data stack, the product, how decisions get made.',
    'Surface — note quality of questions asked.'],
]

const mid: CompactSlot[] = [
  ['analyst-journey', 'Analyst journey walkthrough', 'ownership', 'warm-up', 'must', 0,
    'Ask candidate to walk through their analytics journey. Calibrate ownership scope and product areas.',
    'Surface — calibration only.', 'Owning a metric vs answering tickets is the dividing line from junior.'],
  ['inconvenient-finding', 'Delivering an inconvenient finding', 'self-awareness', 'exploration', 'must', 2,
    'Ask about an analysis that contradicted what a PM or exec wanted to hear. Look for genuine tension.',
    'Probe "How did you deliver it? Did you soften it?" Test honesty under pressure.',
    'Holding the line on an unwelcome truth is the signature mid-level signal.'],
  ['metric-disagreement', 'Resolving a metric definition disagreement', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about two stakeholders defining the same metric differently. Look for how they reconciled it.',
    'Probe who owns the canonical definition now and how it gets enforced.'],
  ['prioritizing-requests', 'Prioritizing competing analysis requests', 'execution', 'exploration', 'must', 2,
    'Ask about a heavy request backlog with multiple stakeholders. Test framework and saying no.',
    'Probe "How did you decide what NOT to do, and how did you communicate that?"'],
  ['influence-roadmap', 'Influencing a product decision with data', 'data-driven', 'exploration', 'must', 2,
    'Ask about using analysis to change a product direction. Expect them to weave in the metrics.',
    'Probe the narrative used and whether the decision actually moved.',
    'Naturally tie the story to specific metrics — fluency expected.'],
  ['ignored-recommendation', 'When a recommendation was ignored', 'self-awareness', 'exploration', 'if-time', 2,
    'Ask about a time their analysis was overruled or ignored. Test composure and follow-through.',
    'Probe whether they understood the other side and how they responded.'],
  ['analysis-was-wrong', 'Owning an analysis that was wrong', 'ownership', 'exploration', 'if-time', 2,
    'Ask about a finding that turned out to be incorrect. Test accountability and detection.',
    'Probe how they found out and what changed in their process afterward.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['analytics-philosophy', 'Analytics philosophy reflection', 'strategy', 'closing', 'must', 0,
    'Ask "What\'s your philosophy on how analytics should serve product?" or how their approach has changed.',
    'Surface — assess a coherent analyst worldview.'],
]

const senior: CompactSlot[] = [
  ['analytics-narrative', 'Analytics leadership journey', 'strategy', 'warm-up', 'must', 0,
    'Strategic narrative: biggest measurement bets, increasing scope. Not a standard self-introduction.',
    'Surface — calibrate scope and strategic depth.', 'Stories must be team/org scope, not single analyses.'],
  ['strategy-shift', 'Shifting strategy with analysis', 'strategy', 'exploration', 'must', 2,
    'Ask about an analysis that moved the roadmap or strategy, not a single feature. Multi-quarter impact.',
    'Probe "How did that hold up over time? What did you have to convince leadership of?"'],
  ['measurement-trust', 'Building trust in the team\'s metrics', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about a time teams reported different numbers and they established trusted, canonical metrics.',
    'Probe governance built: ownership, definitions, review cadence.',
    'Metric governance is the senior-level differentiator.'],
  ['exec-influence', 'Influencing executives with data', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about aligning execs on a contested direction using analysis.',
    'Probe "How did you frame uncertainty? What was the data in that conversation?"',
    'Hold ground with data while maintaining executive trust.'],
  ['developing-analysts', 'Developing other analysts', 'leadership', 'exploration', 'must', 2,
    'Ask how they have grown analysts — review of work, raising the bar on rigor, career conversations.',
    'Probe specific systems built (analysis reviews, standards), not one-off mentoring.',
    'People and standards leadership is non-negotiable at this level.'],
  ['measurement-culture', 'Building a measurement culture', 'strategy', 'exploration', 'if-time', 2,
    'Ask about making an org more data-driven. Self-serve, literacy, decision rituals.',
    'Probe how they changed behavior, not just shipped dashboards.'],
  ['hard-data-tradeoff', 'A hard call under data ambiguity', 'execution', 'exploration', 'if-time', 2,
    'Ask about the hardest decision they drove when the data was incomplete or conflicting.',
    'Probe "What would the argument against your call have been?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['legacy-reflection', 'Legacy and impact reflection', 'self-awareness', 'closing', 'must', 0,
    'Ask about the analytics work they are most proud of and a call they would make differently.',
    'Surface — durable measurement impact vs one-off dashboards.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('product-analyst', 'behavioral', '0-2', entry, [
    'Owning a team-wide metrics framework or governance',
    'Influencing executive or board-level strategy',
    'Mentoring or developing other analysts',
    'Multi-quarter measurement program ownership',
    'Establishing canonical metric definitions org-wide',
  ]),
  template('product-analyst', 'behavioral', '3-6', mid, [
    'Building an analytics org or hiring analysts',
    'Board-level or company-strategy influence',
    'Establishing org-wide metric governance from scratch',
    'Pure ticket execution with no decision impact',
    'Setting measurement vision across many teams',
  ]),
  template('product-analyst', 'behavioral', '7+', senior, [
    'Single ad-hoc query or one-off dashboard stories',
    'Personal time-management anecdotes',
    'SQL or tooling trivia framed as a behavioral story',
    'Stories executing someone else\'s analysis plan',
    'Daily standup or ticket-grooming discussions',
  ]),
]
