import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Product Designer × Technical × 0-2 ────────────────────────────────────
const entry: CompactSlot[] = [
  ['process-fundamentals', 'End-to-end UX process fundamentals', 'design-process', 'warm-up', 'must', 0,
    'Ask them to outline how they take a problem from research to validated design. Assess vocabulary and clarity.',
    'Surface — use the answer to calibrate depth for the session.', 'Graded on thinking clarity, not mastery — a thoughtful junior beats a sloppy mid-level.'],
  ['portfolio-deep-dive', 'Portfolio project deep dive', 'design-process', 'warm-up', 'must', 0,
    'Ask them to walk through a project including the decisions behind it. The portfolio IS the technical exam at entry.',
    'Surface — this is the launching pad for technical follow-ups.', 'Case study must show process (research, IA, iterations), not just final mockups.'],
  ['research-method-choice', 'Choosing a research method', 'user-research', 'exploration', 'must', 2,
    'Ask which research method they would pick to answer a given design question and why.',
    'Probe: "What would that method tell you that another one would not?"',
    'Method-to-question fit matters more than naming many methods.'],
  ['ia-and-navigation', 'Information architecture and navigation', 'design-process', 'exploration', 'must', 2,
    'Ask how they would structure navigation for a new feature. Tests IA logic and mental-model thinking.',
    'Probe: "How would you check that this structure matches how users actually think about it?"',
    'Look for grouping logic tied to users, not an arbitrary sitemap.'],
  ['interaction-states', 'Designing interaction states', 'design-process', 'exploration', 'must', 2,
    'Ask what states a screen needs beyond the happy path. Tests completeness of interaction thinking.',
    'Probe: "What happens with no data? With an error? While it is loading?"',
    'Awareness of empty, loading, and error states signals real product thinking.'],
  ['accessibility-basics', 'Accessibility awareness', 'visual-design', 'exploration', 'if-time', 1,
    'Ask what accessibility considerations they apply. Awareness, not expert audit.',
    'Probe: "What changes for a screen reader user or a color-blind user here?"'],
  ['prototype-fidelity', 'Choosing prototype fidelity', 'design-process', 'exploration', 'if-time', 2,
    'Ask when they would use a lo-fi sketch versus a clickable prototype. Tests deliberate fidelity choices.',
    'Probe: "What are you trying to learn, and why does that fidelity answer it?"',
    'Look for matching fidelity to the question, not always going high-fidelity.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['iteration-evidence', 'Evidence of iteration', 'design-process', 'closing', 'must', 0,
    'Ask them to describe an earlier version of a design and what changed and why. Tests iteration mindset.',
    'Surface — one clear before/after with reasoning suffices.'],
]

// ─── Product Designer × Technical × 3-6 ────────────────────────────────────
const mid: CompactSlot[] = [
  ['case-study-presentation', 'End-to-end case study presentation', 'design-process', 'warm-up', 'must', 0,
    'Ask them to present their strongest project end-to-end. The case study IS the technical interview at mid-level.',
    'Surface — set expectation you will interrupt with probing questions throughout.', 'Problem framing, research rigor, design rationale, and measured impact determine the outcome.'],
  ['usability-study-method', 'Running a usability study end-to-end', 'user-research', 'exploration', 'must', 2,
    'Ask about a usability study: recruiting, screening, task design, synthesis. Tests methodology depth.',
    'Probe: "How many participants? How did you recruit? How did findings become specific decisions?"',
    'Process depth, not awareness — discuss what worked, what failed, and how the approach adapted.'],
  ['ia-validation', 'Information architecture and validation', 'design-process', 'exploration', 'must', 2,
    'Ask how they structure IA for a feature-rich product and validate it. Tests card sorting and tree testing.',
    'Probe: "How did you confirm the hierarchy matched users\' mental models — what method, what result?"',
    'Expect a validation method, not just an asserted structure.'],
  ['interaction-state-matrix', 'Designing the full interaction state matrix', 'design-process', 'exploration', 'must', 2,
    'Ask how they handle all states of a complex interaction. Tests completeness and edge-case rigor.',
    'Probe: "Walk me through the empty, loading, partial, error, and success states for this flow."',
    'Strong candidates map states systematically rather than designing only the happy path.'],
  ['accessibility-in-practice', 'Accessibility from wireframe stage', 'visual-design', 'exploration', 'must', 2,
    'Ask how they build accessibility in from wireframes, not as a retrofit. Tests WCAG 2.1 AA fluency.',
    'Probe: "Walk me through how a screen reader user completes this task in your design."',
    'Accessibility is a design skill — semantic hierarchy, focus order, color independence from the start.'],
  ['research-to-decision', 'Turning research into design decisions', 'user-research', 'exploration', 'if-time', 2,
    'Ask how a specific research finding changed a design. Tests synthesis, not just data collection.',
    'Probe: "What did you do with a finding that contradicted what you already believed?"'],
  ['prototype-and-test', 'Prototype fidelity and validation strategy', 'design-process', 'exploration', 'must', 2,
    'Ask how they pick fidelity and what they validate before building. Tests deliberate process choices.',
    'Probe: "What is the cheapest prototype that would answer your riskiest question here?"',
    'Quantified impact expected — "task time dropped from 90s to 40s after the redesign" is the bar.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['impact-measurement', 'Measuring quantified design impact', 'design-process', 'closing', 'must', 0,
    'Ask for a concrete example of design impact with a metric. Tests analytical maturity.',
    'Surface — push for numbers if they speak only in qualitative terms.'],
]

// ─── Product Designer × Technical × 7+ ─────────────────────────────────────
const senior: CompactSlot[] = [
  ['process-strategy', 'Designing the team\'s UX process', 'design-process', 'warm-up', 'must', 0,
    'Ask how they shape the research-to-validation process for a team. Tests strategic range over personal craft.',
    'Surface — calibrate whether they think in systems and outcomes or default to craft language.', 'Process design and judgment matter more than individual execution at this level.'],
  ['research-practice-strategy', 'Building a research and validation practice', 'user-research', 'exploration', 'must', 2,
    'Ask how they stand up a research practice for a team that has none. Look for repeatable infrastructure.',
    'Probe: "How do you decide between foundational research and tactical usability testing?"',
    'Research ops expected — repository, insight taxonomy, democratization vs. specialization.'],
  ['ia-at-product-scale', 'Information architecture across a product', 'design-process', 'exploration', 'must', 2,
    'Ask how they reason about IA and navigation across a whole product, not one feature. Tests systems thinking.',
    'Probe: "Two teams want conflicting navigation models. How do you resolve it and validate the call?"',
    'Look for a coherent system and a validation method, not local optimizations.'],
  ['process-judgment', 'Knowing when to skip steps', 'design-process', 'exploration', 'must', 2,
    'Ask how they decide what fidelity is needed and when to skip research entirely. Tests mature judgment.',
    'Probe: "Give me a case where the right call was to NOT run research. How did you de-risk it?"',
    'Senior judgment is knowing which steps add signal and which add only delay.'],
  ['accessibility-strategy', 'Accessibility as a program, not a checklist', 'visual-design', 'exploration', 'if-time', 2,
    'Ask how they move a team from accessibility-as-compliance to accessibility-as-default. Tests program thinking.',
    'Probe: "How do you get engineering to prioritize accessibility against a feature backlog?"'],
  ['interaction-system', 'Interaction patterns as a reusable system', 'design-systems', 'exploration', 'if-time', 2,
    'Ask how they define interaction patterns so they stay consistent across a product and team.',
    'Probe: "How do you keep state and interaction behavior consistent when five designers ship in parallel?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['emerging-tools-perspective', 'Perspective on emerging tools and methods', 'design-process', 'closing', 'must', 0,
    'Ask how they evaluate AI-assisted design or new research and prototyping methods. Tests pragmatic adoption.',
    'Surface — look for neither dismissive nor hype-driven; pragmatic, evidence-led thinking.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('product-designer', 'technical', '0-2', entry, [
    'Research operations, repositories, or insight taxonomies at scale',
    'Information architecture across an entire product portfolio',
    'Deciding when to skip research — assume juniors should validate',
    'Defining reusable interaction systems across multiple teams',
    'Accessibility program strategy or engineering prioritization tactics',
  ]),
  template('product-designer', 'technical', '3-6', mid, [
    'Basic process vocabulary (what is a wireframe, what is a persona)',
    'Tool mechanics (how to use a specific prototyping feature)',
    'Org-level research operations or research strategy infrastructure',
    'Hiring, performance management, or career leveling for designers',
    'When to skip research entirely — expect them to validate at this level',
  ]),
  template('product-designer', 'technical', '7+', senior, [
    'Individual execution tasks (structure the IA for this single screen)',
    'Tool mechanics or prototyping feature questions',
    'Basic process steps or design vocabulary',
    'Naming research methods without applying judgment',
    'Designing the happy-path states of one feature',
  ]),
]
