import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Product Designer × Case Study × 0-2 ───────────────────────────────────
const entry: CompactSlot[] = [
  ['clarify-and-scope', 'Clarifying questions and problem scoping', 'design-process', 'warm-up', 'must', 0,
    'Present a narrow prompt. Assess whether they ask clarifying questions before sketching anything.',
    'Surface — jumping straight to screens without asking is a red flag at any level.', 'Narrating thinking aloud matters as much as what they draw.'],
  ['define-user-problem', 'Defining the user and the problem', 'user-research', 'warm-up', 'must', 0,
    'Ask them to define the primary user, their goal, and key pain points before designing.',
    'Surface — this grounds everything that follows.', 'Asking who the user is comes first — skipping it fails the exercise.'],
  ['explore-approaches', 'Exploring 2-3 approaches', 'design-process', 'exploration', 'must', 2,
    'Ask them to sketch 2-3 rough approaches and explain tradeoffs before committing to one.',
    'Probe: "You picked option A — what was option B, and why did you reject it?"',
    'Exploring alternatives is the key signal — divergent thinking before converging.'],
  ['key-screens-and-states', 'Key screens and their states', 'visual-design', 'exploration', 'must', 2,
    'Ask them to sketch the core screens and annotate interaction notes. Look for non-happy-path states.',
    'Probe: "What does this look like with no data? What does the error state do?"',
    'Scope is intentionally narrow — reward depth of thinking within a small scope.'],
  ['ground-in-user', 'Grounding decisions in user needs', 'user-research', 'exploration', 'must', 2,
    'Ask why each choice was made. Look for user-centered reasoning, not "it is best practice."',
    'Probe: "Who is this for specifically, and how does that change the choice?"',
    'Every decision should reference the user, not a remembered pattern.'],
  ['research-first-step', 'What they would research first', 'user-research', 'exploration', 'if-time', 1,
    'Ask what they would want to learn before designing and how. Tests early research instinct.',
    'Probe: "What is the one thing you most need to know, and how would you find out cheaply?"'],
  ['adapt-to-curveball', 'Adapting to a mid-exercise constraint', 'design-process', 'exploration', 'if-time', 2,
    'Introduce a curveball (e.g., poor connectivity, a visual impairment). Tests adaptability.',
    'Probe: "The user can only use this with one hand on a tiny screen. What changes?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['prioritize-first-ship', 'Prioritizing the first thing to ship', 'design-process', 'closing', 'must', 0,
    'Ask what part ships first given two weeks of engineering time. Tests prioritization.',
    'Surface — one clear decision with rationale suffices.'],
]

// ─── Product Designer × Case Study × 3-6 ───────────────────────────────────
const mid: CompactSlot[] = [
  ['reframe-scope', 'Scope negotiation and problem reframing', 'design-process', 'warm-up', 'must', 0,
    'Present a broad prompt. Assess whether they negotiate scope and reframe rather than just execute.',
    'Surface — the best candidates reframe the prompt, not just answer it.', 'End-to-end ownership expected — framing, research, IA, interaction, and measurement.'],
  ['research-plan', 'Research strategy and problem framing', 'user-research', 'exploration', 'must', 2,
    'Ask what research they would run before designing. Tests depth beyond "I would do interviews."',
    'Probe: "What questions? How many users, and why that many? What data already exists?"',
    'Problem framing is the differentiator — strong answers dwell in the problem space first.'],
  ['information-architecture', 'Information architecture and navigation', 'design-process', 'exploration', 'must', 2,
    'Ask them to structure the IA for a feature-rich flow. Tests grouping logic and mental-model alignment.',
    'Probe: "How would you validate this hierarchy matches how users think about it?"',
    'Expect rough quantitative reasoning — "this likely affects ~30% of DAUs."'],
  ['solution-with-tradeoffs', 'Solution with annotated tradeoffs and states', 'visual-design', 'exploration', 'must', 2,
    'Ask for key screens with annotated interaction states and tradeoffs. Look for multi-stakeholder awareness.',
    'Probe: "You chose X over Y — what did you sacrifice, and why was it worth it?"',
    'Tradeoff articulation separates strong from adequate — "I chose X accepting the cost of W."'],
  ['validation-and-metrics', 'Usability testing and success metrics', 'user-research', 'exploration', 'must', 2,
    'Ask how they would test the design and what they would track. Tests analytical thinking.',
    'Probe: "Define the metric precisely. What goes up, and what is the guardrail that must not drop?"',
    'Look for a real validation plan, not just "I would test it with users."'],
  ['stakeholder-curveball', 'Handling a stakeholder curveball', 'collaboration', 'exploration', 'if-time', 2,
    'Introduce a stakeholder constraint mid-exercise (e.g., a VP wants a promo on this screen).',
    'Probe: "What do you push back on and what do you accommodate, and how do you decide?"'],
  ['edge-and-accessibility', 'Edge cases and accessibility', 'design-process', 'exploration', 'must', 2,
    'Ask how the design holds up for edge cases and assistive-technology users. Tests completeness.',
    'Probe: "Walk me through a screen reader user completing this. Where does your design break?"',
    'Accessibility and edge states are part of the design, not a later pass.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['phasing-first-release', 'Implementation phasing and first release', 'collaboration', 'closing', 'must', 0,
    'Ask what ships first and what comes later. Tests prioritization under time pressure.',
    'Surface — clear milestones with rationale. Time management is a meta-skill being tested.'],
]

// ─── Product Designer × Case Study × 7+ ────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-scoping', 'Strategic context and scoping', 'design-process', 'warm-up', 'must', 0,
    'Present a complex, org-level challenge. Assess the incisiveness of their scoping questions.',
    'Surface — quality of questions shows strategic sophistication. A rigid framework signals IC, not leadership.', 'Strategic framing is the whole evaluation — design as a business function, not just craft.'],
  ['diagnostic-research', 'Diagnostic framing and research strategy', 'user-research', 'exploration', 'must', 2,
    'Ask what they need to learn first and how. Look for stakeholder interviews, audit, and a research plan.',
    'Probe: "What specifically would you ask, and what do you already expect to find?"',
    'Business fluency under pressure — answers framed in ROI, retention, or quarter goals.'],
  ['system-and-roadmap', 'System-level design and phased roadmap', 'design-process', 'exploration', 'must', 2,
    'Ask them to lay out a phased approach (30/60/90) and reason about second-order effects across the product.',
    'Probe: "The board wants this in six months, not twelve. What do you cut and why?"',
    'Look for systems thinking — how this flow affects the rest of the product.'],
  ['validation-at-scale', 'Validation and measurement at scale', 'user-research', 'exploration', 'must', 2,
    'Ask how they would validate the design and measure impact across a large user base.',
    'Probe: "What is your leading indicator before the lagging business metric moves?"',
    'Expect a measurement plan tied to business metrics, not just usability scores.'],
  ['migration-and-change', 'Migration and change management', 'collaboration', 'exploration', 'if-time', 2,
    'Ask how they would roll out a redesign without alienating existing power users. Tests change management.',
    'Probe: "Power users hate the change. What is your rollout and communication plan?"'],
  ['executive-pitch', 'Pitching the approach to executives', 'collaboration', 'exploration', 'if-time', 2,
    'Ask them to pitch the design strategy to a simulated executive audience in under three minutes.',
    'Probe: "The CFO asks why this redesign is worth the cost. What is your pitch?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['recovery-plan', 'Recovery plan when it is not working', 'design-process', 'closing', 'must', 0,
    'Ask what they do if, three months in, the redesign is not moving the metrics. Tests resilience.',
    'Surface — look for diagnostic thinking and stakeholder communication, not just doubling down.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('product-designer', 'case-study', '0-2', entry, [
    'Jumping to UI without asking who the user is',
    'Designing one solution without exploring alternatives',
    'Focusing on visual polish over interaction logic',
    'Ignoring edge cases (error, empty, and loading states)',
    'Treating the exercise as a solo performance without engaging the interviewer',
  ]),
  template('product-designer', 'case-study', '3-6', mid, [
    'Skipping research and problem framing and jumping to screens',
    'Designing only the happy path with no error, empty, or edge states',
    'No success metrics or validation strategy',
    'Using frameworks (Double Diamond, Design Thinking) as buzzwords without applying them',
    'Spending all the time on IA without showing any concrete UI',
  ]),
  template('product-designer', 'case-study', '7+', senior, [
    'Treating the exercise as an IC task (wireframing specific features)',
    'Proposing a direction without connecting it to business metrics',
    'Generic design-thinking platitudes without concrete actions',
    'Proposing a redesign without a migration or change-management plan',
    'No measurement plan or leading indicators',
  ]),
]
