import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['clarify-metric', 'Clarify the metric and scope', 'problem-solving', 'warm-up', 'must', 0,
    'Present a "metric dropped" prompt. Assess whether they clarify the metric, timeframe, and what changed.',
    'Surface — note they don\'t jump straight to a cause.', 'Structured first move matters more than the answer.'],
  ['hypotheses', 'Forming hypotheses', 'analytical', 'exploration', 'must', 2,
    'Ask for 2-3 plausible explanations for the movement before pulling any data.',
    'Probe "Which would you check first and why?"',
    'Hypothesis-first beats data-dredging.'],
  ['segmentation', 'Segmenting the problem', 'analytical', 'exploration', 'must', 2,
    'Ask how they would break the metric down — new vs returning, platform, geo, cohort.',
    'Probe "If new users dropped but returning held, what does that tell you?"'],
  ['success-metrics', 'Defining success metrics', 'data-driven', 'exploration', 'must', 2,
    'Switch to a "measure this feature" prompt. Ask for one north-star plus 2-3 supporting metrics.',
    'Probe concrete definitions, not "track engagement," and leading vs lagging.'],
  ['simple-recommendation', 'Reaching a recommendation', 'problem-solving', 'exploration', 'if-time', 1,
    'Ask what they would conclude and recommend given what they checked.',
    'Probe willingness to commit with a caveat rather than hedge forever.'],
  ['data-gaps', 'Acknowledging data gaps', 'data-driven', 'exploration', 'if-time', 1,
    'Ask what they cannot yet conclude and what data they are missing.',
    'Probe intellectual honesty about the limits of the analysis.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['wrap-up-summary', 'Summary and caveats', 'problem-solving', 'closing', 'must', 0,
    'Ask them to summarize the finding and name the biggest caveat.',
    'Surface — assess self-awareness about limitations.'],
]

const mid: CompactSlot[] = [
  ['frame-investigation', 'Frame the investigation', 'analytical', 'warm-up', 'must', 0,
    'Present a metric-divergence prompt. Expect them to clarify the business context before diving in.',
    'Surface — note whether they ask "What decision will this inform?"',
    'Business context matters — must ask before investigating.'],
  ['hypothesis-tree', 'Hypothesis tree', 'analytical', 'exploration', 'must', 2,
    'Expect a structured tree of candidate causes (product, user mix, external, instrumentation).',
    'Probe quantitative sizing: "This could explain ~3 of the 8 points — how would you confirm?"',
    'Quantitative intuition expected.'],
  ['confounders', 'Confounders and mix shift', 'analytical', 'exploration', 'must', 2,
    'Present a flat-retention / rising-engagement divergence. Expect mix-shift and seasonality awareness.',
    'Probe Simpson\'s paradox and "Could a logging change explain this?"'],
  ['measurement-plan', 'Designing a measurement plan', 'experimentation', 'exploration', 'must', 2,
    'Switch to "did this redesign work?" Expect hypothesis, success + guardrail metrics, and a read plan.',
    'Probe "What result would make you NOT ship?" and how long to run.'],
  ['recommendation-confidence', 'Recommendation with confidence', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask for a recommendation with an explicit confidence level and the evidence behind it.',
    'Probe tradeoff articulation — not the perfect answer, but the clearest reasoning.'],
  ['next-data', 'Next data to pull', 'data-driven', 'exploration', 'if-time', 2,
    'Ask what the single most informative next query would be and why.',
    'Probe prioritization of analysis effort against decision value.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['risks-validity', 'Risks and validity threats', 'analytical', 'closing', 'must', 0,
    'Ask about novelty effects, instrumentation gaps, and what could invalidate the conclusion.',
    'Surface — assess validity awareness.'],
]

const senior: CompactSlot[] = [
  ['strategic-framing', 'Strategic framing of the question', 'strategy', 'warm-up', 'must', 0,
    'Present a tangled metric scenario. Expect reframing around the decision and the product strategy.',
    'Surface — note whether they understand WHY this matters now.',
    'Frame around the decision, not just the number.'],
  ['prioritized-investigation', 'Prioritized investigation', 'analytical', 'exploration', 'must', 2,
    'Expect a fast path to the likely driver — order checks by information value, not exhaustiveness.',
    'Probe "Competitor launch, seasonality, and a logging change all overlap — sequence your checks."'],
  ['causal-isolation', 'Causal isolation', 'experimentation', 'exploration', 'must', 2,
    'Expect separation of correlation from cause when an A/B test isn\'t available.',
    'Probe diff-in-diff, pre/post with controls, and stating assumptions.',
    'Senior PAs isolate cause; juniors list correlates.'],
  ['metrics-strategy', 'Success-metric strategy with no history', 'strategy', 'exploration', 'must', 2,
    'Expect a metric framework for a new product line — proxies, early signals, and a north star.',
    'Probe "No baseline exists. What\'s your first read of success in week one?"'],
  ['decision-framing', 'Framing the finding for a decision', 'stakeholder-management', 'exploration', 'must', 2,
    'Expect them to turn the analysis into a crisp recommendation an exec can act on.',
    'Probe how they convey uncertainty without losing the call to action.'],
  ['prevent-recurrence', 'Preventing the next blind spot', 'data-driven', 'exploration', 'if-time', 2,
    'Ask how they would instrument or guardrail so the same surprise is caught earlier next time.',
    'Probe alerting, canonical definitions, and measurement debt.'],
  ['second-order', 'Second-order metric effects', 'strategy', 'exploration', 'if-time', 2,
    'Ask how a fix to one metric could distort another (gaming, cannibalization, guardrail breach).',
    'Probe systemic thinking across the metric tree.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['stress-test', 'Stress test / skeptical exec', 'stakeholder-management', 'closing', 'must', 0,
    'Play a skeptical exec who distrusts the number. Test composure and defense of the analysis.',
    'Surface — assess conviction and honesty under challenge.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('product-analyst', 'case-study', '0-2', entry, [
    'Causal-inference methods or quasi-experiments',
    'Designing a metric framework for a whole product line',
    'Untangling three simultaneous confounders',
    'Open-ended product design with no measurement core',
    'Pure business-strategy or market-entry cases',
  ]),
  template('product-analyst', 'case-study', '3-6', mid, [
    'Metric strategy for a product with zero history',
    'Org-wide metric governance design',
    'Pure feature-design cases with no metrics',
    'Single-cause diagnosis with no segmentation',
    'Market-entry or P&L strategy questions',
  ]),
  template('product-analyst', 'case-study', '7+', senior, [
    'Defining DAU or a single funnel metric from scratch',
    'One-segment diagnosis with no confounders',
    'Reciting a framework with no recommendation',
    'Pure feature-design prompts with no measurement',
    'Basic "name three metrics" warm-up drills',
  ]),
]
