import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

const entry: CompactSlot[] = [
  ['metric-definitions', 'Core metric definitions', 'data-driven', 'warm-up', 'must', 0,
    'Ask candidate to define DAU and retention precisely. Distinguish vanity from actionable metrics.',
    'Probe "Two users open the app 10 times each — is DAU 2 or 20? Why?"',
    'Precision and structured thinking, not memorized formulas.'],
  ['sql-basics', 'SQL joins and aggregation', 'analytical', 'exploration', 'must', 2,
    'Give a small sessions/users schema. Ask for conversion rate by signup week with a GROUP BY + JOIN.',
    'Probe duplicate-session handling and "What does a fan-out join do to your count?"',
    'Correct, sanity-checked SQL is the gating skill at this level.'],
  ['funnel-reading', 'Reading a conversion funnel', 'analytical', 'exploration', 'must', 2,
    'Present a 4-step funnel with a drop. Look for isolating the leakiest stage before guessing causes.',
    'Probe segmentation thinking: new vs returning, platform, geo.'],
  ['ab-testing-basics', 'A/B testing fundamentals', 'experimentation', 'exploration', 'must', 2,
    'Ask what a control/treatment split is and how they would know the result is real, not noise.',
    'Probe significance intuition and sample-size awareness — not statistical depth.',
    'NOT forgiven for not knowing what an A/B test compares.'],
  ['vanity-vs-actionable', 'Vanity vs actionable metrics', 'data-driven', 'exploration', 'if-time', 1,
    'Present a metric that went up while users churned. Ask whether they would celebrate.',
    'Probe instinct to check whether the metric reflects real value.'],
  ['data-sanity-check', 'Sanity-checking a query', 'analytical', 'exploration', 'if-time', 1,
    'Ask how they would verify a number before trusting it. Look for spot-checks against raw rows.',
    'Probe "Your total is 2x what you expected — what do you check first?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['metric-tradeoff-simple', 'Simple metric tradeoff', 'data-driven', 'closing', 'must', 0,
    'Ask which single metric they would watch for a feature and why. Look for pros/cons reasoning.',
    'Surface — structured thinking, not a full framework.'],
]

const mid: CompactSlot[] = [
  ['metric-framework', 'Metric framework for a feature', 'data-driven', 'warm-up', 'must', 0,
    'Ask "You own the search experience. Define its metrics." North star → input → guardrails.',
    'Surface — calibrate metric sophistication.', 'Shift from knowing metrics to designing a coherent set.'],
  ['sql-windows-cohorts', 'SQL window functions and cohorts', 'analytical', 'exploration', 'must', 2,
    'Ask for a cohort-retention query using CTEs + window functions on an events table.',
    'Probe ROW_NUMBER vs RANK, sessionization, and execution-order reasoning.',
    'Fluent window-function SQL is the mid-level gate.'],
  ['metric-drop-diagnosis', 'Diagnosing a metric drop', 'analytical', 'exploration', 'must', 2,
    'Present an 8% WAU drop. Expect segmentation (new vs returning, geo, platform, cohort) and queries.',
    'Probe mix-shift analysis and Simpson\'s paradox awareness.',
    'The canonical mid-level diagnosis question.'],
  ['experiment-read', 'Designing and reading an experiment', 'experimentation', 'exploration', 'must', 2,
    'Ask to design an A/B test and read a borderline result (e.g. +2% lift, p=0.08).',
    'Probe guardrails, MDE, duration, novelty effects, and the ship/no-ship call.',
    'Reading a messy result is more telling than designing a clean one.'],
  ['metric-definition-edge', 'Metric definition edge cases', 'data-driven', 'exploration', 'must', 2,
    'Ask them to define activation or a "qualified" event, then poke at the boundary cases.',
    'Probe "What about users who do it twice in one session? Refunds? Bots?"'],
  ['instrumentation', 'Instrumentation and event taxonomy', 'data-driven', 'exploration', 'if-time', 2,
    'Ask what events and properties to log for a new feature. Look for a proactive event taxonomy.',
    'Probe property selection and avoiding gaps that block future analysis.'],
  ['segmentation-depth', 'Segmentation and slicing', 'analytical', 'exploration', 'if-time', 2,
    'Ask how they would slice a flat conversion number to find where the change actually lives.',
    'Probe aggregation traps and choosing dimensions that matter.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retention-modeling', 'Retention and cohort interpretation', 'data-driven', 'closing', 'must', 0,
    'Ask how they read a retention curve and distinguish activation from habit formation.',
    'Surface — cohort thinking and curve-shape interpretation.'],
]

const senior: CompactSlot[] = [
  ['metrics-architecture', 'Metrics architecture for a product area', 'data-driven', 'warm-up', 'must', 0,
    'Ask "Five teams, no shared metric definitions. Design the framework." Hierarchy cascading from goals.',
    'Surface — calibrate systems-level metrics thinking.', 'Designing the system, not solving one instance.'],
  ['experiment-pitfalls', 'Advanced experiment interpretation', 'experimentation', 'exploration', 'must', 2,
    'Ask about interaction effects, peeking, novelty, and trusting results across many concurrent tests.',
    'Probe "Two experiments overlap on the same surface — how do you read either?"'],
  ['causal-inference', 'Causal inference without A/B', 'experimentation', 'exploration', 'must', 2,
    'Ask how they estimate impact when A/B testing is impossible (diff-in-diff, synthetic control, pre/post).',
    'Probe when each method is appropriate and its limitations.',
    'Causal reasoning beyond A/B is the senior gate.'],
  ['metric-governance', 'Metric governance and trust', 'data-driven', 'exploration', 'must', 2,
    'Present "Three teams report different DAU." Ask how they establish canonical, trusted definitions.',
    'Probe semantic layer, ownership, and review cadence — not just a one-time fix.',
    'Making a whole org\'s numbers trustworthy is the marquee senior skill.'],
  ['complex-diagnosis', 'Diagnosing a confounded metric movement', 'analytical', 'exploration', 'must', 2,
    'Present a metric move tangled with a launch, a seasonality shift, and a logging change at once.',
    'Probe how they isolate the real driver and quantify each contribution.'],
  ['instrumentation-strategy', 'Instrumentation strategy at scale', 'data-driven', 'exploration', 'if-time', 2,
    'Ask how they design event schemas that survive product changes and stay analyzable.',
    'Probe versioning, backfills, and avoiding measurement debt.'],
  ['measurement-constraints', 'Privacy and measurement constraints', 'data-driven', 'exploration', 'if-time', 2,
    'GDPR/ATT or consent gaps broke core measurement. Ask how they keep analysis trustworthy.',
    'Probe aggregated reporting, modeled metrics, and stating uncertainty.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['cross-team-alignment', 'Cross-functional data alignment', 'leadership', 'closing', 'must', 0,
    'Ask how they resolve teams reporting different numbers and align on canonical definitions.',
    'Surface — assess the org politics around data.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('product-analyst', 'technical', '0-2', entry, [
    'Causal inference or quasi-experimental methods',
    'Designing a metrics framework across many teams',
    'Window functions on chained CTEs without scaffolding',
    'ML modeling, training, or hyperparameter tuning',
    'Experimentation program governance at org scale',
  ]),
  template('product-analyst', 'technical', '3-6', mid, [
    'Training classifiers or deep-learning modeling',
    'Org-wide metric governance design from scratch',
    'Distributed systems or data-platform architecture',
    'Reading a tiny or one-day A/B test as conclusive',
    'Defining metrics with no guardrails',
  ]),
  template('product-analyst', 'technical', '7+', senior, [
    'Basic SQL syntax or single-table GROUP BY drills',
    'Defining DAU or retention from scratch',
    'Reading one clean A/B result with no nuance',
    'Naming metrics without a hierarchy or owner',
    'Tool trivia divorced from a measurement system',
  ]),
]
