import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Product Designer × Behavioral × 0-2 ───────────────────────────────────
const entry: CompactSlot[] = [
  ['intro-motivation', 'Motivation for product design', 'design-process', 'warm-up', 'must', 0,
    'Ask why they chose product design and what kind of user problems energize them. Look for user curiosity, not just craft.',
    'Surface — use the answer to pick follow-up threads.', 'Coachability and curiosity matter more than depth at this level.'],
  ['portfolio-walkthrough', 'Portfolio walkthrough and personal role', 'design-process', 'warm-up', 'must', 0,
    'Ask them to walk through a favorite project and what they personally did on it.',
    'Surface — one clear story sets up the rest of the interview.', 'School, bootcamp, and internship projects are expected and fine.'],
  ['starting-without-brief', 'Starting a project without a clear brief', 'adaptability', 'exploration', 'must', 2,
    'Ask about a time they had to begin with no clear direction. Tests early comfort with ambiguity.',
    'Probe: "What did you do FIRST? How did you decide where to even start?"',
    'Look for a step toward defining the problem, not paralysis or waiting for instructions.'],
  ['handling-feedback', 'Handling feedback that changed the design', 'design-process', 'exploration', 'must', 2,
    'Ask about a time feedback significantly changed their direction. Tests ego resilience and growth.',
    'Probe what specifically changed in the design and how they felt about it.',
    'Willingness to iterate matters more than being right at this level.'],
  ['user-first-instinct', 'Centering a decision on a real user need', 'user-research', 'exploration', 'must', 2,
    'Ask about a time they advocated for what a user needed over what was easiest to build.',
    'Probe: "How did you know that was what the user actually needed?"',
    'User-centricity separates the pack — strongest juniors anchor stories on people, not tools.'],
  ['collaborating-with-eng', 'Working with a PM or engineer for the first time', 'collaboration', 'exploration', 'if-time', 1,
    'Ask about a project where they partnered with a PM or engineer. Look for communication and constraint awareness.',
    'Isolate their role: "You said we — what did YOU specifically do to keep it aligned?"'],
  ['design-that-missed', 'A design that did not land as expected', 'design-process', 'exploration', 'if-time', 2,
    'Ask about a design that failed or missed the mark. Look for self-awareness and iteration instinct.',
    'Probe what they think the root cause was versus what they would do differently.',
    'Honest reflection beats a flawless story with no learning in it.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-growth', 'Where they want to grow', 'design-process', 'closing', 'must', 0,
    'Ask what part of product design they most want to get better at. Assess self-awareness and ambition.',
    'Surface — wrap up the interview warmly.'],
]

// ─── Product Designer × Behavioral × 3-6 ───────────────────────────────────
const mid: CompactSlot[] = [
  ['ownership-narrative', 'End-to-end ownership narrative', 'design-process', 'warm-up', 'must', 0,
    'Ask about a project they drove from problem to ship. Calibrate scope and depth of ownership.',
    'Surface — use to pick follow-up topics.', 'Must show ownership of the problem, not just execution of someone else\'s spec.'],
  ['advocating-for-user', 'Advocating for a user need against business pressure', 'user-research', 'exploration', 'must', 2,
    'Ask about championing a user need when the team wanted to cut it for speed or revenue.',
    'Probe the exact evidence they used and the compromise they reached.',
    'Influence through evidence is the signal — "I felt strongly" without data is weak here.'],
  ['navigating-shifting-problem', 'Keeping momentum on a shifting problem', 'adaptability', 'exploration', 'must', 2,
    'Ask about a project where the problem kept changing under them. Tests independent problem scoping.',
    'Probe how they defined success when no one handed them criteria, and how they validated the framing.',
    'Expected to own the problem definition, not just the pixels.'],
  ['disagreement-with-partner', 'Disagreement with a PM or engineer', 'collaboration', 'exploration', 'must', 2,
    'Ask about a real disagreement over a design decision. Look for evidence-based persuasion, not stubbornness.',
    'Probe who specifically resisted, their underlying concern, and what shifted the conversation.',
    'Must speak PM and engineering language — vague "I communicated better" fails.'],
  ['research-invalidated-direction', 'When research invalidated a committed direction', 'user-research', 'exploration', 'if-time', 2,
    'Ask about a time testing or data contradicted a direction they had already committed to.',
    'Probe how quickly they let go of the old idea and what they did next.',
    'Look for intellectual honesty over sunk-cost defensiveness.'],
  ['mentoring-a-peer', 'Helping a less experienced designer', 'leadership', 'exploration', 'if-time', 1,
    'Ask how they have helped a junior designer grow. Look for investment in others.',
    'Probe a specific critique or coaching moment that changed how a peer worked.'],
  ['quality-vs-deadline', 'Holding quality under deadline pressure', 'design-process', 'exploration', 'must', 2,
    'Ask about a time quality and the deadline collided. Tests judgment about what to protect and what to cut.',
    'Probe what they were willing to ship rough and what they refused to compromise, and why.',
    'Look for principled tradeoffs, not perfectionism or pure pragmatism.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['decision-to-reverse', 'A decision they would reverse today', 'design-process', 'closing', 'must', 0,
    'Ask about a design decision they would make differently now. Look for honest self-assessment.',
    'Surface — one clear example with the lesson suffices.'],
]

// ─── Product Designer × Behavioral × 7+ ────────────────────────────────────
const senior: CompactSlot[] = [
  ['setting-direction', 'Setting direction on an unframed problem space', 'leadership', 'warm-up', 'must', 0,
    'Ask about a fuzzy problem space they framed and set direction for. Must be concrete, not aspirational.',
    'Surface — calibrate org-level scope and how they talk about their team.', 'Listen for "I" vs "my team achieved X" — it reveals leadership character.'],
  ['aligning-divided-stakeholders', 'Aligning stakeholders who fundamentally disagree', 'collaboration', 'exploration', 'must', 2,
    'Ask about building alignment when leaders wanted genuinely different things. Tests influence without authority.',
    'Probe each side\'s real interest and how they found the path that held.',
    'Business fluency expected — connect the design call to revenue, retention, or strategy.'],
  ['influencing-strategy', 'Influencing roadmap or product strategy', 'leadership', 'exploration', 'must', 2,
    'Ask about a time their design thinking changed the product direction, not just the UI.',
    'Probe the argument and evidence that moved a PM lead or exec.',
    'Strategic range — design should shape what gets built, not only how it looks.'],
  ['mentoring-through-ambiguity', 'Coaching a designer through deep ambiguity', 'leadership', 'exploration', 'must', 2,
    'Ask how they helped someone navigate a genuinely ambiguous project. Tests teaching vs deciding-for-them.',
    'Probe what they taught versus what they decided themselves, and how they knew the difference.',
    'Look for creating conditions for good design, not just doing it personally.'],
  ['user-advocacy-at-scale', 'Embedding user advocacy across a team', 'user-research', 'exploration', 'if-time', 2,
    'Ask how they made user evidence a habit across product decisions, not a one-off they pushed.',
    'Probe the rituals or systems they created so advocacy did not depend on them being in the room.'],
  ['recovering-from-org-failure', 'Recovering from a failure with team-wide impact', 'design-process', 'exploration', 'if-time', 2,
    'Ask about a significant failure and how they led through it. Failure questions carry more weight here.',
    'Probe the systemic change they introduced, not just personal growth.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-design-impact', 'How they think about design impact', 'leadership', 'closing', 'must', 0,
    'Ask how they judge whether design is making a real difference for users and the business.',
    'Surface — look for outcomes language, not activity language.', 'Expect outcomes tied to users AND the business.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('product-designer', 'behavioral', '0-2', entry, [
    'Org-wide design strategy or design vision',
    'Aligning C-suite or VP stakeholders who disagree',
    'Hiring, team structure, or design operations',
    'Mentoring or leading other designers',
    'Influencing product roadmap or strategy',
  ]),
  template('product-designer', 'behavioral', '3-6', mid, [
    'Building a design org from scratch or org-wide design vision',
    'Board-level or C-suite design strategy persuasion',
    'Hiring and managing a team of designers',
    'Design operations or tooling decisions at org scale',
    'Setting direction across multiple unframed problem spaces',
  ]),
  template('product-designer', 'behavioral', '7+', senior, [
    'First-time collaboration with a PM or engineer',
    'Receiving basic design feedback gracefully',
    'Portfolio walkthrough of individual project details',
    'Tool mechanics or wireframing a single flow',
    'How they handle being a junior on a team',
  ]),
]
