import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Sales × Behavioral × 0-2 ───────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['self-intro-sales', 'Intro and a win you\'re proud of', 'motivation', 'warm-up', 'must', 0,
    'Ask candidate to introduce themselves and a deal or win they\'re proud of. Look for genuine energy and competitive drive.',
    'Surface — use to pick follow-up topics.', 'Early-career wins, internships, and any persuasion experience are acceptable.'],
  ['why-sales', 'Why sales, and what energizes them', 'motivation', 'warm-up', 'must', 0,
    'Ask what drew them to sales and what type of environment brings out their best. Calibrate hunger and coachability.',
    'One follow-up at most — keep it warm.', 'Assess raw enthusiasm and competitive mindset, not polish.'],
  ['biggest-lost-deal', 'Your biggest lost deal and what you learned', 'adaptability', 'exploration', 'must', 2,
    'Ask about a deal they lost. Look for honest ownership and concrete learning rather than excuses.',
    'Probe what they\'d do differently and whether they applied the lesson since.',
    'Small deals or early-career losses count fully at this level.'],
  ['turning-around-a-deal', 'Turning around a deal going sideways', 'execution', 'exploration', 'must', 2,
    'Ask about a deal that was slipping and how they recovered it. Look for specific tactics, not luck.',
    'Probe the exact moves they made and what changed the buyer\'s position.'],
  ['handling-rejection', 'Handling rejection and staying motivated', 'adaptability', 'exploration', 'must', 2,
    'Ask how they bounce back after a string of no\'s. Look for grit and a repeatable reset, not bravado.',
    'Probe what they actually do after a hard rejection to keep activity up.'],
  ['basic-objection', 'Working through a tough objection', 'communication', 'exploration', 'if-time', 1,
    'Ask about a memorable objection and how they handled it. Look for listening before responding.',
    'Probe whether they uncovered the real concern behind the stated objection.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-sales-drive', 'What drives you in sales beyond commission', 'motivation', 'closing', 'must', 0,
    'Ask what motivates them beyond the commission check. Assess intrinsic drive and direction.',
    'Surface — wrap up warmly.'],
]

// ─── Sales × Behavioral × 3-6 ───────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['sales-identity-evolution', 'How your selling style evolved', 'motivation', 'warm-up', 'must', 0,
    'Ask how their sales identity (hunter vs farmer, SMB vs enterprise) developed with experience. Calibrate self-awareness.',
    'Surface — use to choose deep-dives.', 'Must reflect on real quota-carrying experience.'],
  ['buying-committee', 'Navigating a complex buying committee', 'strategy', 'exploration', 'must', 2,
    'Ask about a deal with multiple stakeholders. Look for stakeholder mapping and multi-threading.',
    'Probe how they identified the economic buyer and neutralized blockers.',
    'Expect ownership of the deal strategy, not just attendance at meetings.'],
  ['pipeline-dry-spell', 'Rebuilding a pipeline during a dry spell', 'execution', 'exploration', 'must', 2,
    'Ask about a period when pipeline ran dry and how they rebuilt it. Look for disciplined prospecting.',
    'Probe the specific activities and the activity math behind the recovery.',
    'The signal is what they changed in their own behavior, not waiting for leads.'],
  ['churning-account', 'Recovering a difficult or churning account', 'execution', 'exploration', 'must', 2,
    'Ask about saving an account that was slipping or threatening to leave. Look for relationship repair.',
    'Probe how they diagnosed the root cause and rebuilt trust.'],
  ['internal-deal-conflict', 'Navigating internal conflict over deal terms', 'stakeholder-management', 'exploration', 'if-time', 2,
    'Ask about a time they had to push internally for a deal (pricing, terms, resources). Look for principled advocacy.',
    'Probe how they balanced the customer\'s needs against the company\'s.'],
  ['significant-loss', 'A significant loss and what changed', 'adaptability', 'exploration', 'if-time', 2,
    'Ask about a major deal loss and its aftermath. Look for honest reflection and a concrete change.',
    'Probe what they changed in their approach afterward.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['retrospective-sales-call', 'A deal you\'d run differently now', 'self-awareness', 'closing', 'must', 0,
    'Ask what they\'d reconsider about a past deal. Assess intellectual honesty.',
    'Surface — one example suffices.'],
]

// ─── Sales × Behavioral × 7+ ────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['sales-leadership-philosophy', 'Sales leadership philosophy', 'leadership', 'warm-up', 'must', 0,
    'Ask how they build and lead a high-performing sales team. Calibrate scope across hiring, coaching, and culture.',
    'Surface — identify which leadership dimensions to probe.', 'Must show impact across people, deals, and culture.'],
  ['coaching-struggling-rep', 'Coaching a struggling rep to quota', 'leadership', 'exploration', 'must', 2,
    'Ask about turning around an underperforming rep. Look for diagnosis before intervention.',
    'Probe how they identified the root cause and the specific coaching plan.',
    'Multi-quarter, people-development scope expected.'],
  ['impossible-quarter', 'Leading a team through an impossible quarter', 'leadership', 'exploration', 'must', 2,
    'Ask about steering a team through a quarter where hitting target seemed out of reach. Look for motivation tactics under pressure.',
    'Probe how they kept the team focused and what they prioritized.',
    'Team-wide revenue stakes are the right scope.'],
  ['sales-culture', 'Building a resilient sales culture', 'leadership', 'exploration', 'must', 2,
    'Ask about embedding resilience and accountability into a sales team. Look for systems, not slogans.',
    'Probe what concretely held when the team was missing target.'],
  ['enterprise-deal-leadership', 'Leading a high-stakes enterprise deal', 'strategy', 'exploration', 'if-time', 2,
    'Ask about personally driving a marquee enterprise deal. Look for orchestration across many stakeholders.',
    'Probe the hardest moment and how they kept the deal alive.'],
  ['revenue-adversity', 'Leading through revenue adversity', 'leadership', 'exploration', 'if-time', 2,
    'Ask about leading through a downturn, churn wave, or missed-number stretch. Look for decisiveness under pressure.',
    'Probe the hardest call they made and how they communicated it.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['sales-bet-failure', 'A sales strategy that didn\'t pan out', 'self-awareness', 'closing', 'must', 0,
    'Ask about a strategy or team bet that underdelivered. Look for organizational learning.',
    'Probe systemic changes, not just personal lessons.', 'Failure carries more weight at this level.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('sales', 'behavioral', '0-2', entry, [
    'Coaching reps, leading teams, or building sales culture',
    'Designing comp plans or territory strategy',
    'Sales methodology theory (MEDDIC, Challenger) or CRM mechanics',
    'Enterprise buying-committee orchestration',
    'Generic conflict questions without a selling context',
  ]),
  template('sales', 'behavioral', '3-6', mid, [
    'Entry-level "why sales" framing',
    'Team-leadership or sales-org building (senior territory)',
    'Generic teamwork stories without a deal context',
    'Accepting "the deal just fell through" without probing ownership and learning',
    'Pure methodology theory instead of lived deal craft',
  ]),
  template('sales', 'behavioral', '7+', senior, [
    'Individual deal tactics a junior rep would describe',
    'Questions a mid-level rep could answer equally well',
    'Generic leadership questions with no revenue stakes',
    'Accepting "we hit the number" without probing how the team was led there',
  ]),
]
