import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── SDET × Technical × 0-2 ────────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['testing-fundamentals', 'Testing types and when to use each', 'test-strategy', 'warm-up', 'must', 0,
    'Ask candidate to explain unit, integration, E2E, smoke, and regression testing and when to choose each.',
    'Surface — calibrate whether they know principles or just tool names.', 'Solid foundation in principles is the differentiator over mere tool proficiency.'],
  ['test-pyramid', 'Test pyramid shape and cost tradeoffs', 'test-strategy', 'warm-up', 'must', 0,
    'Ask them to explain the test pyramid and why the shape matters. Look for cost reasoning, not just recall.',
    'Surface — probe "why more unit tests than E2E?" if they recite without reasoning.'],
  ['test-case-design', 'Test case design techniques', 'technical-depth', 'exploration', 'must', 2,
    'Ask about boundary value analysis, equivalence partitioning, error guessing, or decision tables.',
    'Probe: "Apply boundary value analysis to this login form — walk me through it."',
    'Must show thinking about edge cases, not just happy path.'],
  ['bug-lifecycle', 'Bug lifecycle and reporting', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask them to walk through the full bug lifecycle and describe what makes a good bug report.',
    'Probe: "What must a bug report contain for a developer to reproduce without talking to you?"'],
  ['basic-automation', 'Basic automation with Selenium/Cypress/Playwright', 'automation', 'exploration', 'must', 2,
    'Ask about writing automated tests: element location, assertions, and handling waits.',
    'Probe: "Test fails in CI but passes locally — how do you debug it?"',
    'SDET vs. manual QA: must show coding comfort alongside testing principles.'],
  ['manual-vs-automation', 'Deciding what to automate vs. keep manual', 'test-strategy', 'exploration', 'if-time', 2,
    'Ask how they decide what to automate. Look for ROI thinking, not "automate everything."',
    'Probe: "Give me a scenario where automation would be the wrong choice."'],
  ['basic-api-testing', 'Basic API testing and HTTP fundamentals', 'technical-depth', 'exploration', 'if-time', 1,
    'Ask about testing REST endpoints: HTTP methods, status codes, and what to assert beyond status 200.',
    'Probe: "What would you assert in a POST /users response beyond the 201 status?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['tool-selection-reasoning', 'Tool selection and why', 'technical-depth', 'closing', 'must', 0,
    'Ask which tool they\'d choose for a new web app and why — look for trade-off reasoning.',
    'Surface — wrap up the interview.'],
]

// ─── SDET × Technical × 3-6 ────────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['framework-architecture', 'Test framework architecture patterns', 'automation', 'warm-up', 'must', 0,
    'Ask them to describe their preferred test framework architecture and why. Look for POM, Screenplay, patterns.',
    'Surface — calibrate design thinking vs. just tool usage.', 'Shift from "can you use tools" to "can you design test systems."'],
  ['cicd-testing-integration', 'CI/CD pipeline testing integration', 'automation', 'exploration', 'must', 2,
    'Ask how their tests integrate into CI/CD: what runs on commit, merge, and pre-release. Quality gates.',
    'Probe: "Suite takes 45 min, team wants 10 — what\'s your approach to parallelization and selection?"'],
  ['flaky-test-management', 'Flaky test management strategy', 'technical-depth', 'exploration', 'must', 2,
    'Ask about their approach to diagnosing and managing flaky tests. Look for root cause rigor, not just retry.',
    'Probe: "Walk me through a flaky test you diagnosed end-to-end — what was the root cause?"',
    'Key FAANG dimension: must have a strategy since ~16% of tests are statistically flaky.'],
  ['api-testing-depth', 'API and contract testing', 'technical-depth', 'exploration', 'must', 2,
    'Ask about testing REST APIs in depth: contract testing with Pact, schema validation, auth flows.',
    'Probe: "POM breaks down with complex dynamic components — what do you use instead?"'],
  ['test-data-management', 'Test data management across environments', 'automation', 'exploration', 'if-time', 2,
    'Ask how they manage test data across multiple environments. Look for factories over fixtures, isolation.',
    'Probe: "How do parallel tests avoid stomping on each other\'s data?"'],
  ['performance-testing', 'Performance testing basics', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about load testing tools and approach: JMeter/Gatling/k6, bottleneck analysis, thresholds.',
    'Probe: "What metrics tell you a performance test is meaningful and not just noise?"'],
  ['design-patterns-test-code', 'Design patterns in test code', 'automation', 'exploration', 'must', 2,
    'Ask about patterns they use — Singleton (WebDriver), Factory (data), Builder (page objects).',
    'Probe: "When does POM become a liability? How do you know when to abandon it?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['quality-metrics', 'Meaningful quality metrics', 'quality-advocacy', 'closing', 'must', 0,
    'Ask what metrics they use to measure whether automation investment is paying off.',
    'Surface — look for defect escape rate, automation ROI, not just line coverage.'],
]

// ─── SDET × Technical × 7+ ─────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['test-platform-architecture', 'Test platform architecture for multiple teams', 'technical-depth', 'warm-up', 'must', 0,
    'Ask about designing test infrastructure that serves multiple teams with different stacks.',
    'Surface — calibrate platform vs. framework thinking.', 'Assesses architectural ownership: designs test platforms, not just frameworks.'],
  ['quality-engineering-at-scale', 'Shared testing SDKs and self-service environments', 'automation', 'exploration', 'must', 2,
    'Ask about building shared libraries or internal testing SDKs adopted by engineering teams.',
    'Probe: "How did you handle teams that had different needs or resisted adopting the shared platform?"',
    'Test infrastructure as a product with users, roadmaps, and adoption metrics.'],
  ['advanced-cicd-quality-gates', 'Advanced CI/CD quality gates and release strategies', 'automation', 'exploration', 'must', 2,
    'Ask about canary testing, feature flag validation, blue-green, and rollback trigger design.',
    'Probe: "How distinguish between a product regression and a test infrastructure failure in CI?"'],
  ['chaos-resilience-testing', 'Chaos engineering and resilience testing', 'technical-depth', 'exploration', 'must', 2,
    'Ask about fault injection, game days, and distributed failure mode testing.',
    'Probe: "How did you get buy-in for chaos engineering? How did you scope and manage experiment risk?"'],
  ['quality-metrics-leadership', 'Quality metrics for engineering leadership', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask about defining MTTD, defect escape rate, test effectiveness ratio, and leadership dashboards.',
    'Probe: "What\'s on your engineering leadership quality dashboard and how do they use it to make decisions?"'],
  ['shift-left-strategy', 'Shift-left testing strategy and developer culture', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about embedding quality into developer habits: TDD advocacy, code review for testability, quality defaults.',
    'Probe: "What changed developer behavior — carrots, gates, culture? What didn\'t work?"'],
  ['ai-assisted-testing', 'Emerging practices: AI testing and observability-driven QA', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask for their opinion on AI-assisted testing, self-healing locators, or testing in production.',
    'Probe: "Where do you see AI actually changing your workflow today vs. hype?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['technical-standards-adoption', 'Setting and driving technical quality standards', 'leadership', 'closing', 'must', 0,
    'Ask how they define and enforce quality standards across teams with different maturity levels.',
    'Surface — look for adoption strategy, not just standards definition.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('sdet', 'technical', '0-2', entry, [
    'Framework architecture or design patterns — too advanced',
    'CI/CD pipeline ownership or quality gate design',
    'Contract testing or performance engineering',
    'Test data management strategy across environments',
    'Metrics programs or ROI measurement for tooling investments',
  ]),
  template('sdet', 'technical', '3-6', mid, [
    'Test platform architecture for multiple teams',
    'Chaos engineering or production resilience testing',
    'AI-assisted testing and emerging practices',
    'Leadership dashboards or executive-level metrics',
    'Designing internal SDKs as products with roadmaps',
  ]),
  template('sdet', 'technical', '7+', senior, [
    'Basic testing pyramid recall or definition questions',
    'Single-tool proficiency without architectural context',
    'Entry-level automation mechanics (locators, waits)',
    'Bug lifecycle or reporting basics',
    'Questions a junior SDET could answer equally well',
  ]),
]
