import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── SDET × Case Study × 0-2 ───────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['scenario-clarification', 'Clarifying the scenario before testing', 'test-strategy', 'warm-up', 'must', 0,
    'Present a feature spec. Assess whether candidate asks about users, platforms, acceptance criteria, and edge cases.',
    'Surface — look for question quality before they start planning.', 'Assessed on structured thinking and basic risk awareness, not deep strategy.'],
  ['test-plan-design', 'Designing a test plan for a feature', 'test-strategy', 'warm-up', 'must', 0,
    'Ask candidate to create test scenarios for a concrete feature. Look for categories beyond happy path.',
    'Surface — observe how they naturally organize: functional, boundary, negative, security.'],
  ['edge-case-identification', 'Identifying edge cases without prompting', 'technical-depth', 'exploration', 'must', 2,
    'Ask them to enumerate edge cases for a login form or checkout flow. Look for systematic coverage.',
    'Probe: "What if the user has a slow network connection? What about concurrent sessions?"',
    'Must think beyond happy path without prompting — this is the core differentiator.'],
  ['test-case-structure', 'Structuring test cases in categories', 'test-strategy', 'exploration', 'must', 2,
    'Ask them to organize their test cases. Look for functional/boundary/negative/security groupings.',
    'Probe: "What\'s the most important test case and why? Walk me through your prioritization reasoning."'],
  ['risk-based-prioritization', 'Risk-based test prioritization under time pressure', 'test-strategy', 'exploration', 'must', 2,
    'Constrain the scenario: "You have 2 hours before release. What do you test first?"',
    'Probe: "What did you consciously skip? How would you communicate that risk to the team?"'],
  ['bug-investigation', 'Bug investigation walkthrough', 'problem-solving', 'exploration', 'if-time', 2,
    'Present a bug report ("search returns no results"). Ask how they investigate end-to-end.',
    'Probe: "What do you check first? How do you isolate whether it\'s frontend, backend, or data?"'],
  ['automation-candidate-selection', 'Deciding what to automate in this scenario', 'automation', 'exploration', 'if-time', 1,
    'Given their test plan, ask which tests to automate first and why.',
    'Probe: "What would you leave manual, and for how long?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-what-missed', 'Reflection on what they might have missed', 'quality-advocacy', 'closing', 'must', 0,
    'Ask what areas they think they underexplored. Assess self-awareness and quality mindset.',
    'Surface — wrap up warmly.'],
]

// ─── SDET × Case Study × 3-6 ───────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['scenario-constraints', 'Clarifying constraints and system context', 'test-strategy', 'warm-up', 'must', 0,
    'Present a complex quality challenge. Assess depth of clarifying questions: team size, deploy frequency, existing infra.',
    'Surface — use questions asked to calibrate systems thinking.', 'Must handle complicating constraints without restarting — adaptability is key.'],
  ['flaky-test-strategy', 'Flaky test strategy for microservices', 'automation', 'exploration', 'must', 2,
    'Present: "Your microservice suite has 30% flakiness." Ask for a systematic fix strategy.',
    'Probe: "How do you measure whether your flakiness strategy is working? What\'s your success metric?"',
    'Ignoring flakiness as "just retry" is a disqualifying anti-pattern.'],
  ['cicd-quality-gate-redesign', 'CI/CD quality gate redesign', 'automation', 'exploration', 'must', 2,
    'Present: "Team moving from bi-weekly to daily deploys. Redesign quality gates."',
    'Probe: "Smoke suite vs. full regression — how do you decide what goes where? Cost of false negative?"'],
  ['test-pyramid-applied', 'Test pyramid applied to a specific architecture', 'test-strategy', 'exploration', 'must', 2,
    'Give a system architecture (e.g. Order + Payment microservices). Ask how to apply the test pyramid.',
    'Probe: "Where does contract testing fit? How do you decide the boundary between integration and E2E?"',
    'Test pyramid applied to specific system architecture is the key mid-level differentiator.'],
  ['regression-optimization', 'Regression suite optimization', 'automation', 'exploration', 'if-time', 2,
    'Present: "Suite takes 4 hours. Reduce to 30 minutes without losing critical coverage."',
    'Probe: "What data do you use to identify which tests to cut? What\'s the risk framework?"'],
  ['complication-handling', 'Responding to added constraints mid-scenario', 'problem-solving', 'exploration', 'if-time', 2,
    'Add a complication to their plan: "Budget just got cut in half" or "You lost your automation engineer."',
    'Probe: "What changes? What do you protect? How do you communicate new risk to stakeholders?"'],
  ['test-data-strategy', 'Test data strategy across environments', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they manage test data isolation in the scenario (e.g. parallel runs, multiple environments).',
    'Probe: "How do parallel tests avoid stomping on shared state? How do you clean up after failures?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['measuring-strategy-success', 'Measuring success of the strategy', 'quality-advocacy', 'closing', 'must', 0,
    'Ask what metrics would tell them their approach is working after 30 days and after 90 days.',
    'Surface — look for leading indicators, not just lagging defect counts.'],
]

// ─── SDET × Case Study × 7+ ────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['problem-framing', 'Framing the problem as a quality opportunity', 'leadership', 'warm-up', 'must', 0,
    'Present an organizational quality challenge. Assess whether they map stakeholders and restate as opportunity.',
    'Surface — calibrate business framing vs. technical framing.', 'Scenarios are organizational, not team-level — quality as an engineering capability.'],
  ['phased-quality-strategy', 'Phased quality strategy design (crawl-walk-run)', 'test-strategy', 'exploration', 'must', 2,
    'Ask for a phased strategy for a 200-person org with no shared QA standards.',
    'Probe: "What does success look like after 90 days? After 18 months? How do you avoid big-bang failure?"',
    'Must articulate phased adoption — big-bang transformation is a disqualifying anti-pattern.'],
  ['business-language-framing', 'Articulating quality in business terms', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask how they would justify the quality investment to a CFO or engineering VP.',
    'Probe: "Cost of defects, deployment confidence, engineering velocity — how do you quantify these?"'],
  ['organizational-adoption', 'Driving adoption across resistant teams', 'collaboration', 'exploration', 'must', 2,
    'Add: "One team says they don\'t need QA — they write unit tests." Ask how they handle this.',
    'Probe: "What approach worked? What didn\'t? How do you handle this without mandate authority?"'],
  ['quality-metrics-program', 'Defining quality metrics for leadership decisions', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask what metrics they\'d put on an engineering leadership dashboard and how leaders use them.',
    'Probe: "How do you avoid vanity metrics? What decisions should these metrics drive?"'],
  ['test-infrastructure-as-product', 'Test infrastructure as a self-service internal product', 'technical-depth', 'exploration', 'if-time', 2,
    'Present: "Build self-service test infra for teams using React, mobile native, and Go services."',
    'Probe: "How do you avoid the platform becoming a bottleneck? What\'s your adoption vs. mandate strategy?"'],
  ['culture-change-measurement', 'Measuring quality culture change', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they measure whether engineering culture has genuinely shifted toward quality ownership.',
    'Probe: "What\'s a leading indicator that culture is changing vs. just compliance with a mandate?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['organizational-impact-reflection', 'Organizational impact and what they\'d do differently', 'leadership', 'closing', 'must', 0,
    'Ask what they\'d do differently in retrospect and what surprised them most about the organizational challenge.',
    'Surface — look for genuine learning and honest self-assessment.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('sdet', 'case-study', '0-2', entry, [
    'Multi-team strategy or organizational scope',
    'CI/CD redesign or deployment pipeline decisions',
    'Test data isolation across environments at scale',
    'Flaky test systemic strategy beyond a single test',
    'Metrics programs or ROI measurement',
  ]),
  template('sdet', 'case-study', '3-6', mid, [
    'Organizational-level quality transformation',
    'Executive stakeholder influence or budget justification',
    'Building QA teams or defining org-wide standards',
    'Phased adoption strategy across multiple product lines',
    'Culture change measurement or quality as business strategy',
  ]),
  template('sdet', 'case-study', '7+', senior, [
    'Single-feature test plan design',
    'Happy path vs. edge case identification at test-case level',
    'Tool selection without organizational strategy context',
    'Questions answerable without cross-team or cross-org scope',
    'Bug lifecycle or basic test case structure',
  ]),
]
