import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── SDET × System Design × 0-2 ────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['test-organization-thinking', 'Test organization for a simple application', 'test-strategy', 'warm-up', 'must', 0,
    'Ask how they would structure tests for a simple web app. Look for pyramid awareness, not tool enumeration.',
    'Surface — probe "why more unit tests than E2E?" if they recite layers without reasoning.', 'Demonstrate test organization thinking, not infrastructure architecture.'],
  ['test-pyramid-application', 'Applying the test pyramid to a given system', 'test-strategy', 'warm-up', 'must', 0,
    'Give a simple system (to-do app or REST API). Ask where unit, integration, and E2E tests live.',
    'Surface — look for WHERE each test type runs, not just what it covers.'],
  ['basic-automation-setup', 'Setting up automated tests for a web app', 'automation', 'exploration', 'must', 2,
    'Ask how they would set up a first automated test suite for a web app from scratch.',
    'Probe: "Which layer do you start with? How do you get the team to maintain it over time?"',
    'Awareness that automation requires maintenance is the key differentiator from tool-droppers.'],
  ['test-environment-basics', 'Test environment needs and test data management', 'technical-depth', 'exploration', 'must', 2,
    'Ask what environments they would need and how they would keep test data clean between runs.',
    'Probe: "Test fails only in CI, passes locally — why? How do you diagnose environment differences?"'],
  ['ci-integration-awareness', 'Where and how tests run in CI', 'automation', 'exploration', 'must', 2,
    'Ask how tests fit into CI: when triggered, what blocks a merge, where results appear.',
    'Probe: "How do you handle a test suite that makes CI 20 minutes slower?"'],
  ['test-maintenance-awareness', 'Keeping tests maintainable over time', 'test-strategy', 'exploration', 'if-time', 1,
    'Ask what breaks in a test suite as the app grows and how they\'d prevent it.',
    'Probe: "What\'s the first sign a test suite is becoming a liability rather than an asset?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['design-reflection', 'What would you add with more time', 'quality-advocacy', 'closing', 'must', 0,
    'Ask what they\'d improve in their design with another week. Assess honest gap awareness.',
    'Surface — wrap up warmly.'],
]

// ─── SDET × System Design × 3-6 ────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['framework-architecture-design', 'Test automation framework architecture', 'automation', 'warm-up', 'must', 0,
    'Ask them to design a test automation framework for a microservices e-commerce platform. They drive.',
    'Surface — look for layers: driver, page objects, test logic, data, reporting. Note if CI/CD mentioned unprompted.', 'Amazon, Google, Microsoft all ask "design a test automation framework" at this level — this IS the interview.'],
  ['parallel-execution-design', 'Parallel test execution and data isolation', 'automation', 'exploration', 'must', 2,
    'Ask how their framework handles parallel test execution without tests interfering with each other.',
    'Probe: "100 tests → 10,000 tests — what breaks in your design? What do you fix first?"',
    'Custom framework design, not off-the-shelf tool usage, is the key differentiator.'],
  ['flaky-test-management-system', 'Flaky test management in the framework', 'technical-depth', 'exploration', 'must', 2,
    'Ask how their framework design handles flakiness: detection, quarantine, retry policy, reporting.',
    'Probe: "How does a test author know their test is flaky vs. revealing a real intermittent bug?"'],
  ['cicd-integration-design', 'CI/CD integration and quality gate design', 'automation', 'exploration', 'must', 2,
    'Ask how their framework integrates with CI/CD: what runs on commit vs. merge vs. pre-release.',
    'Probe: "How do you detect whether a failure is a product bug or a test infrastructure bug?"'],
  ['test-data-isolation', 'Test data management and environment isolation', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about test data strategy in their design: factories vs. fixtures, cleanup, environment scoping.',
    'Probe: "New team member writes their first test — how easy is it to create the test data they need?"'],
  ['performance-testing-infra', 'Performance testing infrastructure design', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask them to design load testing infrastructure: generation, metrics collection, baseline comparison.',
    'Probe: "How do you distinguish a real performance regression from infrastructure variance?"'],
  ['framework-developer-experience', 'Framework developer experience', 'collaboration', 'exploration', 'must', 2,
    'Ask how they ensure the framework is easy for test authors to use and extend.',
    'Probe: "When the framework needs to change, how do you migrate existing tests without breaking them?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['scaling-reflection', 'Scaling from 100 to 10,000 tests', 'test-strategy', 'closing', 'must', 0,
    'Ask what changes architecturally when the suite grows 100x. Look for honest recognition of design limits.',
    'Surface — look for parallelization, sharding, test selection, and reporting challenges.'],
]

// ─── SDET × System Design × 7+ ─────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['self-service-platform-design', 'Self-service test platform for the organization', 'technical-depth', 'warm-up', 'must', 0,
    'Ask them to design self-service test infrastructure for an org with 50 engineering teams. They drive.',
    'Surface — look for platform thinking: users, APIs, onboarding, adoption, and roadmap.', 'Platform thinking — test infra as an internal product with users, roadmaps, and adoption metrics.'],
  ['multi-tenancy-design', 'Multi-tenancy and scaling across teams and stacks', 'technical-depth', 'exploration', 'must', 2,
    'Ask how their platform handles 5 teams today and 50 teams in 18 months with different stacks.',
    'Probe: "Design for 5 to 50 teams — what changes architecturally? What assumptions break?"',
    'Must reason about multi-tenancy, extensibility, cost models, and developer experience.'],
  ['quality-metrics-framework', 'Quality metrics and SLO framework', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask how their platform defines, collects, and reports quality metrics for engineering leadership.',
    'Probe: "What\'s on the leadership dashboard? How do leaders use it to make investment decisions?"'],
  ['intelligent-test-selection', 'Intelligent test selection and change-impact analysis', 'automation', 'exploration', 'must', 2,
    'Ask how their platform selects which tests to run based on code changes — dependency graphs, risk scoring.',
    'Probe: "How do you reduce CI time by 70% without increasing escaped defect rate?"'],
  ['platform-observability', 'Test infrastructure observability — monitoring the monitors', 'technical-depth', 'exploration', 'must', 2,
    'Ask how the test platform itself is monitored: latency, queue depth, flakiness rate, resource utilization.',
    'Probe: "How do you know the platform has a problem before an engineering team reports it to you?"'],
  ['chaos-engineering-integration', 'Chaos engineering and production resilience testing', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask how they\'d integrate chaos engineering into the platform: fault injection, game days, safety guardrails.',
    'Probe: "How do you manage experiment blast radius? How do you get skeptical teams to participate?"'],
  ['adoption-strategy', 'Platform adoption strategy and handling resistant teams', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they drive adoption when teams have existing legacy test suites or resist the platform.',
    'Probe: "What\'s the migration path? How do you prove value fast enough to maintain momentum?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['platform-cost-and-tradeoffs', 'Cost modeling and build-vs-buy tradeoffs', 'leadership', 'closing', 'must', 0,
    'Ask how they model the platform\'s infrastructure cost and when to adopt open-source vs. build custom.',
    'Surface — look for articulated gaps that justify custom builds, not NIH instinct.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('sdet', 'system-design', '0-2', entry, [
    'Multi-team or multi-service test infrastructure architecture',
    'Custom framework design with parallel execution or data isolation',
    'Flaky test management at a systemic level',
    'CI/CD quality gate design with pipeline ownership',
    'Performance testing infrastructure or load generation design',
  ]),
  template('sdet', 'system-design', '3-6', mid, [
    'Self-service test platform serving 50 engineering teams',
    'Multi-tenancy and cost modeling for test infrastructure',
    'Intelligent test selection with dependency graph algorithms',
    'Quality metrics as a leadership reporting program',
    'Chaos engineering integration and production resilience strategy',
  ]),
  template('sdet', 'system-design', '7+', senior, [
    'Single-app test organization without architectural depth',
    'Basic CI integration without quality gate design',
    'Test pyramid explanation without system-specific application',
    'Tool selection without infrastructure design context',
    'Questions answerable at team level without org-scale thinking',
  ]),
]
