import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── SDET × Behavioral × 0-2 ───────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['motivation-quality', 'Motivation for QA/testing', 'quality-advocacy', 'warm-up', 'must', 0,
    'Ask why QA and testing. Look for genuine instinct to ask "what could go wrong?" before "does it work?"',
    'Surface only — one follow-up at most.', 'Bootcamp, internship, or first-job stories are expected.'],
  ['first-bug-discovery', 'First critical bug discovery', 'quality-advocacy', 'warm-up', 'must', 0,
    'Ask about finding and reporting a critical bug. Look for communication of impact, not just discovery.',
    'Surface — use this to calibrate analytical depth.', 'Quality mindset differentiator: natural edge-case instinct.'],
  ['developer-collaboration', 'Collaborating with developers on bugs', 'collaboration', 'exploration', 'must', 2,
    'Ask about joint debugging or making a developer take a bug seriously. Look for evidence-based framing.',
    'Probe: "How did the developer respond? What evidence did you provide to support the report?"'],
  ['speaking-up-quality', 'Speaking up about quality concerns', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask about first push-back when something wasn\'t ready to ship. Look for willingness to advocate.',
    'Probe: "Who pushed back? How did you frame the risk? What was the outcome?"',
    'Limited org-level stories expected — intern or first-job scope is fine.'],
  ['learning-testing-approach', 'Learning a systematic testing approach', 'test-strategy', 'exploration', 'must', 2,
    'Ask about learning to think systematically about breaking software. Look for deliberate thinking.',
    'Probe the specific techniques adopted and what changed in their approach afterward.'],
  ['handling-conflicting-info', 'Handling ambiguous or contradictory requirements', 'problem-solving', 'exploration', 'if-time', 2,
    'Ask about contradictory acceptance criteria. Look for initiative in clarifying rather than guessing.',
    'Probe: "What specifically was contradictory? Who did you go to for resolution?"'],
  ['balancing-thoroughness', 'Balancing thoroughness with deadlines', 'test-strategy', 'exploration', 'if-time', 1,
    'Ask about deciding what to test under time pressure. Look for a triage framework.',
    'Probe: "What framework did you use? What did you consciously skip and why?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['quality-mindset-growth', 'Quality mindset reflection', 'quality-advocacy', 'closing', 'must', 0,
    'Ask where their thinking about quality has evolved most. Assess self-awareness and learning orientation.',
    'Surface — wrap up warmly.'],
]

// ─── SDET × Behavioral × 3-6 ───────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['qa-philosophy-evolution', 'QA philosophy evolution', 'test-strategy', 'warm-up', 'must', 0,
    'Ask how their approach to QA has changed. Look for shift from executing tests to owning strategy.',
    'Surface — calibrate ownership level.', 'Key differentiator: influence without authority over quality.'],
  ['test-strategy-overhaul', 'Leading a major test strategy overhaul', 'test-strategy', 'exploration', 'must', 2,
    'Ask about driving a significant change in automation approach. Look for data-backed justification.',
    'Probe: "What prompted the change? How did you measure whether the new approach was better?"',
    'Expects ownership of strategy, not just execution.'],
  ['flaky-suite-resolution', 'Resolving systemic flaky tests', 'automation', 'exploration', 'must', 2,
    'Ask about systematically fixing a flaky suite that was blocking deployments. Look for root cause rigor.',
    'Probe: "Walk me through diagnosis end-to-end. How did you know when it was truly fixed?"'],
  ['quality-advocacy-pressure', 'Quality advocacy under release pressure', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask about convincing a team to delay a release for quality. Look for evidence-based persuasion.',
    'Probe: "What evidence did you use? Who resisted? How did you frame the risk in business terms?"'],
  ['cross-team-qa-influence', 'Influencing quality standards across teams', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about standards or practices adopted by other teams. Look for influence without authority.',
    'Probe: "How did you gain buy-in? What resistance did you face? What stuck?"'],
  ['automation-roi-decision', 'Data-backed automation ROI decision', 'test-strategy', 'exploration', 'if-time', 2,
    'Ask about deciding what to automate vs. keep manual. Look for metrics and explicit reasoning.',
    'Probe: "What data did you use? What did you consciously choose not to automate and why?"'],
  ['disagreement-resolution', 'Resolving disagreement with developers', 'collaboration', 'exploration', 'must', 2,
    'Ask about conflict with a developer over a test failure or scope decision. Look for both-sides framing.',
    'Probe: "What was the developer\'s position? How did you find common ground?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['mentoring-junior-testers', 'Mentoring junior testers', 'leadership', 'closing', 'must', 0,
    'Ask about teaching a testing approach or reviewing test code with a junior. Assess investment in others.',
    'One specific example suffices — surface treatment.'],
]

// ─── SDET × Behavioral × 7+ ────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['quality-culture-vision', 'Vision for world-class quality culture', 'leadership', 'warm-up', 'must', 0,
    'Ask what world-class quality culture looks like. Look for rituals, metrics, and embedding quality by default.',
    'Surface — calibrate organizational scope.', 'Must translate technical quality concerns into business language.'],
  ['quality-culture-transformation', 'Driving org-wide quality culture change', 'leadership', 'exploration', 'must', 2,
    'Ask about changing how quality is valued across an organization. Look for rituals and systemic change.',
    'Probe: "What rituals changed how the org thinks about quality? What outlasted your involvement?"',
    'Must show org-level impact, not just team-level.'],
  ['executive-influence', 'Influencing executive investment in quality', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask about convincing leadership to invest in test infrastructure over features. Look for business framing.',
    'Probe: "How did you frame ROI? What was the executive\'s objection? How did you handle resistance?"'],
  ['building-qa-teams', 'Building and structuring quality engineering teams', 'leadership', 'exploration', 'must', 2,
    'Ask about hiring and structuring a QA team. Look for intentional design — roles, career ladders, culture.',
    'Probe: "What did you get wrong early? What would you do differently in your next team build?"'],
  ['quality-metrics-program', 'Defining quality metrics that drive improvement', 'quality-advocacy', 'exploration', 'must', 2,
    'Ask about defining metrics that changed decision-making. Look for business-linked measurements.',
    'Probe: "How did leadership use these metrics? What decisions changed as a result?"'],
  ['shift-left-advocacy', 'Shift-left culture transformation', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about changing engineering habits to move quality earlier in the process.',
    'Probe: "What resistance did you face from developers? What changed their behavior?"'],
  ['crisis-quality-decision', 'High-stakes ship-or-hold decision', 'quality-advocacy', 'exploration', 'if-time', 2,
    'Ask about a high-pressure decision to ship or hold under time pressure. Look for a clear framework.',
    'Probe: "What was your framework? Who disagreed? What would you do differently?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['failure-org-consequences', 'Quality failure with organizational consequences', 'leadership', 'closing', 'must', 0,
    'Ask about a significant quality failure and what systemic change followed. Look for org-level learning.',
    'Probe systemic changes, not just personal growth.', 'Quality as an engineering capability, not a gatekeeping function.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('sdet', 'behavioral', '0-2', entry, [
    'Organizational strategy or cross-team direction-setting',
    'Executive influence or budget-level quality investment',
    'Ship-or-hold decisions with business consequences',
    'Building QA teams or defining career ladders',
    'Quality metrics that influence leadership decisions',
  ]),
  template('sdet', 'behavioral', '3-6', mid, [
    'Organizational-level quality transformation',
    'Hiring or structuring QA teams',
    'Influencing executive investment decisions',
    'Cross-org standards with no team-level application',
    'Pure manual testing execution with no strategy ownership',
  ]),
  template('sdet', 'behavioral', '7+', senior, [
    'Individual bug reports or test case execution',
    'Team-scoped automation without organizational reach',
    'Tool selection without strategic justification',
    'Questions an SDET II could answer equally well',
    'Pure technical mechanics without leadership or influence angle',
  ]),
]
