import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── SDET × Coding × 0-2 ───────────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['problem-approach', 'Approaching a coding problem out loud', 'technical-depth', 'warm-up', 'must', 0,
    'Ask candidate to think aloud before coding. Look for edge case questions before implementation begins.',
    'Surface — assess whether they ask about nulls, boundaries, and invalid inputs before writing.', 'Evaluates "thinking in tests" — natural edge-case instinct before touching the keyboard.'],
  ['basic-dsa', 'Basic algorithm problem (LeetCode Easy)', 'problem-solving', 'warm-up', 'must', 0,
    'Present a standard Easy problem (e.g. two-sum, valid parentheses). Look for clean logic and edge handling.',
    'Surface — note if they handle empty input, duplicates, and type edge cases unprompted.'],
  ['test-case-writing', 'Writing unit tests for a given function', 'automation', 'exploration', 'must', 2,
    'Give a function signature (e.g. email validator). Ask for 10+ test cases as actual assertions.',
    'Probe: "What about empty string? Unicode? Domains with hyphens? Extremely long input?"',
    'THE distinguishing factor from SWE: must cover edge cases, boundaries, and negative cases.'],
  ['bug-finding', 'Finding bugs in a code snippet', 'technical-depth', 'exploration', 'must', 2,
    'Present a buggy code snippet with off-by-one error, null pointer, or race condition. Ask for identification.',
    'Probe: "How would you write a test that catches this specific bug? What would the assertion be?"'],
  ['test-organization', 'Test organization with setup and teardown', 'automation', 'exploration', 'must', 2,
    'Ask how they structure tests: setup/teardown, test grouping, test independence.',
    'Probe: "How do you ensure tests don\'t depend on execution order? Walk me through a test file structure."'],
  ['simple-automation-script', 'Writing a simple automation or parsing script', 'automation', 'exploration', 'if-time', 2,
    'Ask them to write a script: parse a log file, count error types, or validate a CSV structure.',
    'Probe: "What if the file is malformed? What if it\'s very large? How does your code handle that?"'],
  ['api-test-validation', 'Writing assertions for an API response', 'automation', 'exploration', 'if-time', 1,
    'Give a JSON API contract. Ask them to write test assertions beyond status code 200.',
    'Probe: "What would you assert about the response body shape? What about missing optional fields?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['coding-reflection', 'Reflecting on code quality and test coverage', 'quality-advocacy', 'closing', 'must', 0,
    'Ask what they\'d add if given more time — missing tests, refactors, or edge cases they skipped.',
    'Surface — look for honest self-assessment of coverage gaps.'],
]

// ─── SDET × Coding × 3-6 ───────────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['medium-dsa', 'Medium algorithm problem', 'problem-solving', 'warm-up', 'must', 0,
    'Present a LeetCode Medium (e.g. merge intervals, LRU cache). Look for clean code and optimization awareness.',
    'Surface — assess code quality: naming, edge handling, no magic numbers.', 'Shift from "can you write tests" to "can you design testable, reusable test infrastructure."'],
  ['test-framework-design', 'Designing and implementing a mini test framework', 'automation', 'exploration', 'must', 2,
    'Ask them to implement a mini framework: @Test annotation, @BeforeEach, result collector.',
    'Probe: "How does your runner handle a test that throws vs. a test that returns false? Show the code."',
    'THE signature mid-level SDET challenge — architecture beats raw algorithm score.'],
  ['data-driven-test-harness', 'Data-driven or parameterized test harness', 'automation', 'exploration', 'must', 2,
    'Ask them to write a data-driven test suite for an API endpoint with multiple input/output pairs.',
    'Probe: "How does your harness report which cases failed? How is test data separated from logic?"'],
  ['retry-and-flake-handling', 'Retry mechanism for flaky integration tests', 'automation', 'exploration', 'must', 2,
    'Ask them to implement retry logic with exponential backoff and max attempts for a flaky test.',
    'Probe: "How do you distinguish a real failure from infrastructure noise in your retry logic?"'],
  ['mocking-and-stubbing', 'When and how to mock vs. use real dependencies', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask about their mocking strategy for the API test suite they designed. Look for judicious use.',
    'Probe: "When would mocking actually make your tests less reliable? Show me an example."'],
  ['custom-assertion-library', 'Fluent assertion API design', 'automation', 'exploration', 'if-time', 2,
    'Ask them to implement a fluent assertion: expect(response).toHaveStatus(200).toMatchSchema(schema).',
    'Probe: "How does chaining work? How do you produce a meaningful failure message when an assertion fails?"'],
  ['test-code-quality', 'Code review: test code readability and DRY principles', 'technical-depth', 'exploration', 'must', 2,
    'Present a test file with copy-paste duplication and hard-coded data. Ask them to refactor.',
    'Probe: "What\'s the clearest signal that test code needs refactoring? Show me the before and after."'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['framework-tradeoffs', 'Framework design tradeoffs and extensibility', 'technical-depth', 'closing', 'must', 0,
    'Ask what they\'d add to make their framework production-grade — plugin hooks, parallel support, reporters.',
    'Surface — look for awareness of maintenance cost and developer experience.'],
]

// ─── SDET × Coding × 7+ ────────────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['medium-hard-dsa', 'Medium-Hard algorithm with testing twist', 'problem-solving', 'warm-up', 'must', 0,
    'Present a LeetCode Medium-Hard. After solving, ask them to write property-based tests proving correctness.',
    'Surface — assess production-grade code quality: observability, error handling, resource management.', 'Evaluated as a platform engineer: test code must be production-grade infrastructure.'],
  ['distributed-test-orchestrator', 'Distributed test orchestration system', 'automation', 'exploration', 'must', 2,
    'Ask them to design and implement core logic for a test orchestrator: distribute tests across machines, aggregate results.',
    'Probe: "How do you handle partial machine failure? How do you distinguish infra failure from product failure?"',
    'This IS the senior evaluation — platform-level architecture implemented in working code.'],
  ['flakiness-detection-algorithm', 'Statistical flakiness detection', 'technical-depth', 'exploration', 'must', 2,
    'Give a test results DB schema. Ask them to implement a classifier: stable / flaky / broken with confidence scores.',
    'Probe: "What\'s the minimum sample size for a reliable classification? How do you handle seasonality?"'],
  ['change-impact-test-selector', 'Change-impact test selection algorithm', 'automation', 'exploration', 'must', 2,
    'Ask them to implement test selection: changed files + dependency graph → minimal prioritized test set.',
    'Probe: "How do you handle transitive dependencies? How do you fall back when the graph is stale?"'],
  ['plugin-architecture', 'Plugin architecture for a test runner', 'technical-depth', 'exploration', 'if-time', 2,
    'Ask them to implement a plugin system: hook points (beforeAll/Each/afterAll async), reporter interface.',
    'Probe: "How does a reporter hook in without being coupled to runner internals? Show the interface."'],
  ['performance-test-harness', 'Performance testing utility with percentile analysis', 'automation', 'exploration', 'if-time', 2,
    'Ask them to write a harness that runs N concurrent requests and reports p50/p95/p99 latency.',
    'Probe: "How do you auto-flag regressions against a stored baseline? How do you handle outliers?"'],
  ['backwards-compatibility', 'Backwards-compatible framework API evolution', 'technical-depth', 'exploration', 'must', 2,
    'Ask how they would evolve a framework API without breaking existing test suites — versioning, deprecation.',
    'Probe: "Show me what the migration path looks like in code for teams on the old API."'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['developer-experience-design', 'Developer experience for test authors', 'leadership', 'closing', 'must', 0,
    'Ask how they ensure the platform is easy to adopt — onboarding, documentation, first-test experience.',
    'Surface — look for empathy toward test authors as platform users.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('sdet', 'coding', '0-2', entry, [
    'Test framework design or architecture',
    'Distributed systems or concurrency in test infrastructure',
    'Custom assertion library or runner implementation',
    'Data-driven harness or fixture factory design',
    'LeetCode Medium or harder algorithm problems',
  ]),
  template('sdet', 'coding', '3-6', mid, [
    'Distributed test orchestration or cluster scheduling',
    'Statistical flakiness detection algorithms',
    'Change-impact test selection with dependency graphs',
    'Property-based testing framework design',
    'LeetCode Hard problems as the primary evaluation',
  ]),
  template('sdet', 'coding', '7+', senior, [
    'Basic unit test writing or happy-path-only tests',
    'Simple automation scripts or log parsing',
    'Recall of assertion library APIs without design',
    'Bug finding in trivial code without architectural discussion',
    'LeetCode Easy problems as the primary challenge',
  ]),
]
