import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Strategy × Technical × 0-2 ─────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['market-sizing', 'Market sizing from first principles', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a market-sizing prompt. Tests structured decomposition and comfort with assumptions and arithmetic.',
    'Surface — walk through the approach before they calculate. Approach matters more than the number.',
    'Process over precision — a well-reasoned estimate within 2x of reality is a pass.'],
  ['mece-structuring', 'MECE structuring of a business problem', 'strategic-thinking', 'warm-up', 'must', 0,
    'Ask how they\'d structure an analysis of a falling-profit or market-entry question. Tests MECE instinct.',
    'Surface — look for 3-4 mutually exclusive branches with clear logic before any analysis.',
    'A tailored issue tree beats a robotically applied textbook framework.'],
  ['profitability-logic', 'Profitability decomposition', 'financial-acumen', 'exploration', 'must', 2,
    'Ask what could cause revenue to rise while profit falls. Tests revenue-vs-cost and price-vs-volume logic.',
    'Probe: "Which cost line would you look at first, and what data would confirm your hypothesis?"',
    'Conceptual margin understanding, not full modeling — revenue vs. cost, price vs. volume.'],
  ['mental-math', 'Quantitative reasoning out loud', 'financial-acumen', 'exploration', 'must', 2,
    'Pose a quick math problem (percentage change, break-even, revenue impact). Ask them to talk through it.',
    'Probe: "Can you double-check that? Walk me through the multiplication step by step."',
    'The #1 math mistake is losing zeros — always sanity-check the result against common sense.'],
  ['framework-selection', 'Selecting and adapting a framework', 'strategic-thinking', 'exploration', 'must', 2,
    'Give a strategic question and ask which framework they\'d use and why. Tests selection over recitation.',
    'Probe: "That framework assumes X — what if X is not true in this context?"',
    'Knowing when a framework fits matters more than naming many frameworks.'],
  ['competitive-basics', 'Reading a competitive landscape', 'strategic-thinking', 'exploration', 'if-time', 1,
    'Ask how they\'d analyze the competitive dynamics of a simple industry. Tests Porter-style thinking.',
    'Probe which force or competitor they\'d worry about most and why.'],
  ['data-interpretation', 'Interpreting a chart or exhibit', 'financial-acumen', 'exploration', 'if-time', 2,
    'Provide a chart or table. Ask what story it tells and what they\'d investigate next.',
    'Probe whether they generate a hypothesis unprompted or just read the numbers back.',
    'Strongest candidates extract an insight and a hypothesis, not just a description.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['communicate-finding', 'Communicating a finding to a non-expert', 'communication', 'closing', 'must', 0,
    'Ask how they\'d present their analysis to a client who isn\'t analytical. Tests translation into a narrative.',
    'Surface — tests turning quantitative work into a clear, actionable "so what."'],
]

// ─── Strategy × Technical × 3-6 ─────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['problem-scoping', 'Scoping and clarifying a strategic question', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a complex business scenario. Assess whether they clarify objectives and data before structuring.',
    'Surface — better scoping yields a better analysis. Note the quality of their questions.',
    'Analysis must drive strategy — "revenue is declining" is an observation, not an insight.'],
  ['market-entry-analysis', 'Market entry evaluation', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask how they\'d evaluate whether a company should enter a new market. Look for TAM plus financial logic.',
    'Probe: "What ROI threshold makes this worth the investment, and what would kill the deal?"',
    'Should integrate sizing, competition, and economics — not a generic checklist.'],
  ['competitive-analysis', 'Competitive analysis with real data', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask for a competitive landscape analysis of an industry. Tests Porter\'s Five Forces with real specifics.',
    'Probe: "How does your read change if the landscape shifts in 12 months?"',
    'Must reference real competitors and share dynamics — generic SWOT with no data fails.'],
  ['profitability-deep-dive', 'Profitability diagnosis', 'financial-acumen', 'exploration', 'must', 2,
    'Present a margin-decline scenario. Ask them to diagnose the driver and prioritize where to look.',
    'Probe: "You have two conflicting signals — how do you resolve which one is the real driver?"',
    'Expected to move from descriptive to diagnostic — find the cause, not just describe the symptom.'],
  ['framework-adaptation', 'Adapting a framework when assumptions break', 'strategic-thinking', 'exploration', 'if-time', 2,
    'Hand them a framework and then break one of its assumptions mid-analysis. Tests flexibility.',
    'Probe how they\'d modify the structure rather than abandon it.'],
  ['pricing-logic', 'Pricing and value-based reasoning', 'financial-acumen', 'exploration', 'if-time', 2,
    'Ask how they\'d analyze a pricing change for a company losing deals on price. Tests value-based pricing.',
    'Probe: "How would you estimate willingness-to-pay without running a full survey?"'],
  ['recommendation-synthesis', 'Synthesizing analysis into a recommendation', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask for the final recommendation from the exercise. Tests synthesis across multiple threads.',
    'Probe: "Walk me through the first 30 days of implementing this."',
    'Must convert analysis into a decisive, quantified "so what" — not a data summary.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['risk-and-execution', 'Key risks and execution', 'stakeholder-management', 'closing', 'must', 0,
    'Ask what could go wrong with their recommendation and how they\'d mitigate it.',
    'Surface — "good answer, now how do you execute it?" separates mid from entry level.'],
]

// ─── Strategy × Technical × 7+ ──────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-hypothesis', 'Scoping and forming an upfront hypothesis', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a multi-business-unit strategic crossroads. Assess incisive scoping and an upfront hypothesis.',
    'Surface — quantitative reasoning embedded in strategic questions, not asked in isolation.',
    'Experience-formed opinions expected — "I don\'t know, I\'d research it" is no longer sufficient.'],
  ['ma-strategic-fit', 'Assessing M&A strategic fit', 'financial-acumen', 'exploration', 'must', 2,
    'Ask how they\'d assess a large acquisition beyond the financials. Tests strategic and integration judgment.',
    'Probe: "What\'s the one number you give the board on deal health, and what do you refuse to collapse?"',
    'Strategic fit, synergy realism, and integration risk — not just a valuation multiple.'],
  ['portfolio-allocation', 'Portfolio strategy and capital allocation', 'strategic-thinking', 'exploration', 'must', 2,
    'Present a multi-business-unit portfolio. Ask which to invest in, hold, or divest and why.',
    'Probe: "Two units have conflicting priorities that can\'t both be funded. How do you resolve it?"',
    'Tests Three Horizons thinking, growth-share logic, and portfolio-level tradeoffs.'],
  ['build-buy-partner', 'Build-vs-buy-vs-partner framework', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask for their framework for a build-vs-buy-vs-partner decision and when each option wins.',
    'Probe: "What changes your answer — speed to market, control, capability, or risk?"',
    'Must reason from strategic context, not default to one option.'],
  ['planning-process', 'Designing the strategic planning process', 'strategic-thinking', 'exploration', 'if-time', 2,
    'Ask how they\'d design the annual strategic-planning process for a large company.',
    'Probe: "The chief strategy officer left and the process stalled. What are your first 30 days?"'],
  ['org-for-strategy', 'Aligning org design to strategy', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they\'d restructure an organization to execute a strategic shift.',
    'Probe: "This requires cutting 2,000 roles. How do you present that to the board and to employees?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['board-synthesis', 'Board-level synthesis of a recommendation', 'communication', 'closing', 'must', 0,
    'Ask them to pitch their recommendation to a simulated board in under 3 minutes. Tests executive narrative.',
    'Probe: "This won\'t show impact for 18 months. How do you justify it to a quarterly-focused board?"',
    'Must frame complex tradeoffs concisely with quantified impact, key risks, and the resource ask.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('strategy', 'technical', '0-2', entry, [
    'DCF valuation, WACC, or complex financial modeling',
    'Advanced statistics (regression, hypothesis testing)',
    'M&A analysis, due diligence, or deal structuring',
    'Multi-scenario models with sensitivity analysis',
    'P&L management or investment-thesis development',
  ]),
  template('strategy', 'technical', '3-6', mid, [
    'Reciting frameworks without adapting to context (generic Porter\'s with no data)',
    'Doing math silently — the interviewer cannot follow the reasoning',
    'Analysis without a recommendation — data description with no strategic conclusion',
    'Over-precision without acknowledging uncertainty ranges',
    'Single-metric myopia that ignores tradeoffs',
  ]),
  template('strategy', 'technical', '7+', senior, [
    'Same analytical depth as mid-level — executing analysis instead of designing the approach',
    'Strategy with no implementation path — the framework is not the answer',
    'Ignoring organizational resistance and change management',
    'Analysis with no executive "so what" (analyst-level math with no CEO-level conclusion)',
    'Recommendations that do not scale beyond a single business unit',
  ]),
]
