import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Strategy × Case Study × 0-2 ────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['clarifying-questions', 'Clarifying questions before structuring', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a case prompt, then wait. Does the candidate ask 2-3 clarifying questions before structuring?',
    'Surface — jumping to analysis without clarifying is the #1 entry-level mistake.',
    'A tailored structure beats a memorized profitability tree applied robotically.'],
  ['framework-structure', 'Building a MECE case structure', 'strategic-thinking', 'warm-up', 'must', 0,
    'Give 60-90 seconds of silence to structure. Look for a MECE framework tailored to this specific case.',
    'Surface — assess whether they present 3-4 branches with clear logic before diving in.',
    'Taking structured silence is expected and rewarded — not a sign of hesitation.'],
  ['branch-analysis', 'Hypothesis-driven branch analysis', 'financial-acumen', 'exploration', 'must', 2,
    'Ask them to work the structure branch by branch. Release data in response to good questions.',
    'Probe: "You think it\'s a revenue problem. How do you narrow it to price versus volume?"',
    'Math must be done out loud — silent calculation is the fastest way to fail a case.'],
  ['case-quantification', 'A quantitative exercise within the case', 'financial-acumen', 'exploration', 'must', 2,
    'Insert a quantitative exercise — break-even, market sizing, or revenue impact.',
    'Probe: "That number seems off — can you walk me through the calculation again?"',
    'The #1 math mistake is losing zeros — always sanity-check large-number multiplications.'],
  ['insight-from-data', 'Generating insight from an exhibit', 'strategic-thinking', 'exploration', 'must', 2,
    'Provide a chart or exhibit. Ask what it means strategically, not just numerically.',
    'Probe: "If you could investigate one more thing before recommending, what would it be?"',
    'Stating numbers with no strategic "so what" is a red flag.'],
  ['new-information', 'Incorporating new information mid-case', 'strategic-thinking', 'exploration', 'if-time', 1,
    'Introduce a new data point or constraint mid-case. Tests adapting the structure and updating the hypothesis.',
    'Probe: "The client is in 5 minutes — give me your recommendation in 30 seconds."'],
  ['risk-identification', 'Identifying the key risk', 'strategic-thinking', 'exploration', 'if-time', 2,
    'Ask what the biggest risk to their recommendation is and how they\'d mitigate it.',
    'Probe: "What\'s the worst case if your assumption about volume is wrong?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['final-recommendation', 'Decisive final recommendation', 'communication', 'closing', 'must', 0,
    'Ask for a final recommendation — clear direction, 2-3 reasons, acknowledged risks, and a mitigation.',
    'Surface — "it depends" is not a recommendation. The synthesis must be decisive.'],
]

// ─── Strategy × Case Study × 3-6 ────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['case-scoping', 'Scoping a multi-layered case', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a complex, multi-layered case. Quality of scoping questions reveals strategic awareness.',
    'Surface — better scoping shows experience. Note what they ask for and what they ignore.',
    'Cases integrate multiple threads — sizing plus competition plus financial logic.'],
  ['ma-or-entry', 'M&A or market-entry deep analysis', 'strategic-thinking', 'exploration', 'must', 2,
    'Present an M&A or market-entry case requiring a comprehensive, quantified evaluation.',
    'Probe: "The buyer expects a 3x return in 5 years. Does the deal work at this valuation?"',
    'Goes deeper than entry-level — regulation, required investment, and a multi-year projection.'],
  ['competitive-response', 'Competitive response strategy', 'strategic-thinking', 'exploration', 'must', 2,
    'Present a disruptive entrant. Ask the candidate to design the client\'s competitive response.',
    'Probe: "When do you compete directly versus acquire versus partner versus concede the segment?"',
    'Game-theoretic thinking expected — anticipate competitor moves and defensive vs. offensive posture.'],
  ['margin-improvement', 'Operational and margin diagnosis', 'financial-acumen', 'exploration', 'must', 2,
    'Present a company with margins well below the industry average. Ask for a diagnosis and an improvement plan.',
    'Probe: "How does your answer change if we optimize for revenue instead of market share?"',
    'Must quantify each recommendation — "we should improve efficiency" with no numbers fails.'],
  ['multi-exhibit', 'Integrating multiple exhibits', 'financial-acumen', 'exploration', 'if-time', 2,
    'Provide 2-3 exhibits at once. Ask the candidate to integrate them into one coherent diagnosis.',
    'Probe: "A test shows +5% conversion but -2% retention. What do you do?"'],
  ['implementation-plan', 'Implementation and go-to-market', 'stakeholder-management', 'exploration', 'if-time', 2,
    'Ask how they\'d execute the recommendation. Tests change management and milestone thinking.',
    'Probe: "Walk me through the first 90 days after the client approves your recommendation."'],
  ['portfolio-choice', 'Portfolio prioritization', 'strategic-thinking', 'exploration', 'must', 2,
    'Present a multi-business-unit portfolio. Ask which to invest in, hold, or divest and why.',
    'Probe: "How does this fit the company\'s broader portfolio strategy?"',
    'Sector context matters — generic frameworks with no industry adaptation fail.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['synthesis-quantified', 'Quantified synthesized recommendation', 'communication', 'closing', 'must', 0,
    'Ask for a final recommendation with quantified impact, risks, and an implementation timeline.',
    'Surface — "we should probably" instead of "this would generate $XM" is inadequate at this level.'],
]

// ─── Strategy × Case Study × 7+ ─────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['peer-scoping', 'Strategic scoping as a peer conversation', 'strategic-thinking', 'warm-up', 'must', 0,
    'Present a real (anonymized) complex engagement. Does the candidate jump to the strategic insight?',
    'Surface — the best senior candidates reach the insight in 2 minutes, then structure around it.',
    'The case IS the conversation — a rigid 4-step framework signals not-ready-for-partner.'],
  ['transformation-strategy', 'CEO-level transformation strategy', 'strategic-thinking', 'exploration', 'must', 2,
    'Present a full corporate transformation. Ask for a 3-year repositioning strategy.',
    'Probe: "The board wants this in 6 months, not 12. What do you cut and what do you protect?"',
    'Must address portfolio reconfiguration, org redesign, investment sequencing, and board buy-in.'],
  ['portfolio-rationalization', 'Portfolio rationalization and reallocation', 'financial-acumen', 'exploration', 'must', 2,
    'Ask which of 6 divisions to invest in, divest, or restructure and why.',
    'Probe: "This needs $200M over 3 years. The company has $300M and 4 competing priorities."',
    'Three Horizons expected — balance short-term performance with long-term positioning.'],
  ['disruption-response', 'Disruption response under time pressure', 'strategic-thinking', 'exploration', 'must', 2,
    'Present a venture-funded disruptor with an 18-month runway to material impact. Design the response.',
    'Probe: "You\'re 6 months in and results are 40% below projections. What do you do?"',
    'Organizational and execution dimensions mandatory — 70% execution design, 30% analytics.'],
  ['org-restructuring', 'Post-merger organizational restructuring', 'leadership', 'exploration', 'if-time', 2,
    'Ask for an org-restructuring design after a merger or strategic pivot. Tests org-design judgment.',
    'Probe: "The acquired CEO demands to stay — brilliant but culturally misaligned. What do you do?"'],
  ['value-creation-plan', 'PE-style value-creation plan', 'financial-acumen', 'exploration', 'if-time', 2,
    'Ask for a 100-day value-creation plan with measurable EBITDA targets.',
    'Probe: "If you\'re wrong about this recommendation, what\'s the cost and what\'s your hedge?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['board-pitch', 'Board pitch on a strategic pivot', 'communication', 'closing', 'must', 0,
    'Ask them to pitch a complex tradeoff recommendation to a board in under 5 minutes.',
    'Probe: "A board member asks the probability this works. How do you answer?"',
    'C-suite communication explicitly tested — concise, data-backed, explicit risk/reward and the ask.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('strategy', 'case-study', '0-2', entry, [
    'Memorized frameworks applied without adaptation (robotic profitability tree)',
    'Doing math silently — the interviewer cannot follow the reasoning',
    'Forgetting to ask clarifying questions before structuring',
    'Wishy-washy "we could do A or B, it depends" with no commitment',
    'Over-engineering the structure and leaving no time for insight or synthesis',
  ]),
  template('strategy', 'case-study', '3-6', mid, [
    'Generic frameworks with no adaptation to the case context',
    'Ignoring business-model and monetization implications',
    'No competitive awareness — analyzing in a vacuum',
    'Skipping implementation and go-to-market',
    'Analysis with no quantification — "we should probably" instead of "this would generate $XM"',
  ]),
  template('strategy', 'case-study', '7+', senior, [
    'Treating the case like a junior exercise with a rigid 4-step framework',
    'Strategy with no implementation — the slide deck is not the deliverable',
    'Ignoring organizational resistance, cultural integration, and change management',
    'Defaulting to a generic framework (Porter\'s Five Forces for a restructuring)',
    'Solving the presenting symptom instead of the structural cause',
  ]),
]
