import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── Strategy × Behavioral × 0-2 ────────────────────────────────────────────
const entry: CompactSlot[] = [
  ['resume-motivation', 'Resume walkthrough and why consulting', 'communication', 'warm-up', 'must', 0,
    'Ask the candidate to walk through their background and why consulting. Assess communication clarity and structure.',
    'Surface — calibrate scope. Why consulting, why this firm, why now.',
    'Potential over track record — assess analytical horsepower and learning speed.'],
  ['structured-thinking', 'Breaking down a hard problem', 'strategic-thinking', 'warm-up', 'must', 0,
    'Ask about a time they broke down a complex, unfamiliar problem to make progress. Tests structured-thinking instinct.',
    'Surface — one follow-up at most on how they decomposed it.',
    'Structured thinking is the single highest-signal trait at this level.'],
  ['handling-ambiguity', 'Acting with incomplete information', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask about a time they had to act or recommend without complete information. Tests comfort with ambiguity.',
    'Probe: "At the point where you didn\'t have enough info, what did you actually do?"',
    'STAR structure expected — candidates who ramble stand out negatively.'],
  ['cross-functional-collab', 'Working across different stakeholders', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about working with people from very different backgrounds or functions toward a shared goal.',
    'Isolate their contribution: "You said we — what specifically did YOU do versus the team?"',
    'Internship, school, club, and volunteer stories are expected and acceptable.'],
  ['initiative-no-title', 'Taking initiative without a title', 'leadership', 'exploration', 'must', 2,
    'Ask about leading or driving something without formal authority. The PEI leadership dimension.',
    'Probe what they did to mobilize others and what the measurable outcome was.',
    'Shows proactive drive — internship, club, or volunteer context is fine.'],
  ['explaining-clearly', 'Explaining something complex simply', 'communication', 'exploration', 'if-time', 1,
    'Ask about explaining a complex idea to a non-expert audience. Tests translation over jargon.',
    'Probe what they changed in their communication based on the audience\'s reaction.'],
  ['overcoming-setback', 'Resilience after a setback', 'stakeholder-management', 'exploration', 'if-time', 2,
    'Ask about a meaningful setback and how they responded. The PEI drive dimension.',
    'Probe what they did differently afterward and what they learned about themselves.',
    'Tests grit, ownership, and learning from failure rather than blame.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['motivation-fit', 'Motivation and firm fit', 'communication', 'closing', 'must', 0,
    'Ask why consulting and why this firm specifically. Evaluate authenticity and quality of research.',
    'Surface — wrap up warmly. The quality of their closing questions is also evaluated.'],
]

// ─── Strategy × Behavioral × 3-6 ────────────────────────────────────────────
const mid: CompactSlot[] = [
  ['career-narrative', 'Career arc and path to consulting', 'communication', 'warm-up', 'must', 0,
    'Ask for an extended career walkthrough — key transitions, why consulting now, what they want next.',
    'Surface — more scrutiny than entry-level. Career intentionality matters at this level.',
    'Stories must feature real responsibility and consequences — "I worked hard" is not a story.'],
  ['difficult-client', 'Managing a difficult client relationship', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about managing a demanding or skeptical client. The signature mid-level consulting question.',
    'Probe: "How did the client react when you delivered that message? What did you do next?"',
    'Client-facing credibility is the differentiator — hard truths while keeping trust.'],
  ['stakeholder-alignment', 'Aligning conflicting stakeholders', 'stakeholder-management', 'exploration', 'must', 2,
    'Ask about aligning stakeholders with directly competing interests behind one recommendation.',
    'Probe: "Who specifically was resistant? What was their underlying concern?"',
    'Must map stakeholder incentives and describe a deliberate coalition-building strategy.'],
  ['leading-ambiguous-workstream', 'Running a workstream through ambiguity', 'leadership', 'exploration', 'must', 2,
    'Ask about leading a vague, high-stakes workstream. Tests translation of ambiguity into action.',
    'Probe: "Walk me through the exact conversation where you pushed back on the partner or client."',
    'EM expectations — ran workstreams, managed juniors, interfaced with client sponsors.'],
  ['hard-recommendation', 'Delivering an unwelcome recommendation', 'strategic-thinking', 'exploration', 'if-time', 2,
    'Ask about making a recommendation the client or leadership did not want to hear. Tests courage and framing.',
    'Probe what alternatives they considered and how they framed the message to land it.'],
  ['developing-juniors', 'Coaching a junior team member', 'leadership', 'exploration', 'if-time', 1,
    'Ask about developing or turning around a junior team member. Tests investment in team capability.',
    'Probe: "How did you handle the underperformer? What specifically changed?"'],
  ['lasting-impact', 'Work that produced lasting change', 'strategic-thinking', 'exploration', 'must', 2,
    'Ask about work that led to durable change at a client or organization. Tests implementation thinking.',
    'Probe: "How did you measure success? What was true 6 months later?"',
    'Quantified impact expected — cost savings, cycle time, or revenue with specific numbers.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['navigating-politics', 'Navigating organizational politics', 'stakeholder-management', 'closing', 'must', 0,
    'Ask about influencing a decision in a politically charged environment. Tests courage and constructiveness.',
    'Surface — one clear example. Probe for the outcome and whether relationships were preserved.'],
]

// ─── Strategy × Behavioral × 7+ ─────────────────────────────────────────────
const senior: CompactSlot[] = [
  ['leadership-trajectory', 'Career arc and leadership trajectory', 'leadership', 'warm-up', 'must', 0,
    'Ask about their career arc with emphasis on leadership trajectory, client impact, and strategic choices.',
    'Surface — partner-level read: "Would I trust this person with a $10M+ client relationship?"',
    'Questions shift from solving problems to building systems, teams, and books of business.'],
  ['building-a-practice', 'Building a practice or capability', 'leadership', 'exploration', 'must', 2,
    'Ask about building something from scratch — a practice, capability, team, or market offering.',
    'Probe: "How large was the team? What was the budget? What measurable impact did it produce?"',
    'Commercial track record is non-negotiable — revenue generation or P&L ownership.'],
  ['board-communication', 'Communicating strategy to C-suite or board', 'communication', 'exploration', 'must', 2,
    'Ask how they communicate a strategic decision to a board or C-suite audience. Tests tailored, top-down framing.',
    'Probe: "How did you frame this for the board? What did they push back on?"',
    'Not just presenting — shaping the decision. Frame tradeoffs concisely with an explicit ask.'],
  ['leading-transformation', 'Leading organizational transformation', 'leadership', 'exploration', 'must', 2,
    'Ask about leading a major change — restructuring, transformation, or strategic pivot.',
    'Probe: "How did you make this stick? What happened after you left the room?"',
    'Must address culture, communication, and sustained execution — not just project management.'],
  ['commercial-accountability', 'Revenue or P&L accountability', 'financial-acumen', 'exploration', 'if-time', 2,
    'Ask about ownership of a revenue target, book of business, or P&L. Tests commercial acumen.',
    'Probe: "Walk me through how you won that client. What was your approach to the relationship?"'],
  ['developing-leaders', 'Developing the next generation of leaders', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they identified, developed, and promoted talent. Tests pipeline thinking, not just managing reports.',
    'Probe: "Who did you develop who is now in a leadership role? What was your approach?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['failure-at-scale', 'A failure with organizational consequences', 'leadership', 'closing', 'must', 0,
    'Ask about a significant professional failure and how they handled the aftermath at an organizational level.',
    'Probe: "What did the organization change? What did YOU personally change?"',
    'At this level failures have org-wide consequences — tests accountability and institutional learning.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('strategy', 'behavioral', '0-2', entry, [
    'Managing P&L, revenue targets, or organizational budgets',
    'Building or leading a consulting practice or business unit',
    'Board-level communication or C-suite stakeholder management',
    'Multi-year transformation or organizational restructuring',
    'Expecting quantified impact in the millions — accept qualitative or small-scale results',
  ]),
  template('strategy', 'behavioral', '3-6', mid, [
    'School or classroom examples (must be a professional context)',
    'Basic teamwork with no leadership or influence component',
    'Purely technical execution with no client or strategic judgment',
    'Building a practice, generating revenue, or firm-level leadership',
    'Board-level relationship management or P&L ownership',
  ]),
  template('strategy', 'behavioral', '7+', senior, [
    'Individual-contributor tasks with no organizational scope',
    'Basic teamwork or collaboration with no leadership dimension',
    'Project execution with no strategic context or business impact',
    'Learning from feedback as the headline (entry-level topic)',
    'Client management at the workstream level (mid-level topic)',
  ]),
]
