import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── UI Designer × Behavioral × 0-2 ────────────────────────────────────────
const entry: CompactSlot[] = [
  ['ui-motivation', 'Motivation for UI design', 'design-process', 'warm-up', 'must', 0,
    'Ask why UI specifically — what about visual craft pulls them. Look for genuine taste, not just tool interest.',
    'Surface — use to calibrate follow-up topics.', 'Coachability and a developing eye matter more than polish at this level.'],
  ['admired-ui-walkthrough', 'A piece of UI they admire', 'visual-design', 'warm-up', 'must', 0,
    'Ask them to describe UI they think is well done and why. Tests whether taste is articulable, not just felt.',
    'Surface — one example with reasoning is enough.', 'Bootcamp/school/side projects are expected and fine here.'],
  ['taking-visual-critique', 'Taking critique on visual work', 'design-process', 'exploration', 'must', 2,
    'Ask about a screen they were proud of that got torn apart in critique. Tests ego resilience.',
    'Probe what specifically changed in the spacing, type, or layout after the feedback.',
    'Willingness to iterate beats being right — defensiveness is the failure mode.'],
  ['using-someone-elses-system', 'Working in a design system they did not build', 'design-systems', 'exploration', 'must', 2,
    'Ask about adhering to a component library or style guide someone else owned. Tests discipline over ego.',
    'Probe a moment they wanted to break a pattern: "What made you want to deviate, and what did you do?"',
    'Look for respect for consistency, not "I just did my own thing."'],
  ['developer-handoff-basics', 'First handoff to a developer', 'collaboration', 'exploration', 'must', 2,
    'Ask about handing a design to an engineer and what got lost in translation. Tests communication.',
    'Isolate their role: "You said we aligned — what did YOU specifically do to make the spec clear?"',
    'Academic or internship handoff context is acceptable.'],
  ['accessibility-awareness-moment', 'A time accessibility changed a design', 'visual-design', 'exploration', 'if-time', 1,
    'Ask about a time contrast, touch targets, or keyboard nav made them change a visual choice.',
    'Probe whether they caught it themselves or were told — both are fine, hiding it is not.'],
  ['ui-iteration-story', 'A UI that did not work and got reworked', 'design-process', 'exploration', 'if-time', 2,
    'Ask about a layout or component that missed the mark and how they revised it. Tests self-awareness.',
    'Probe what they identified as the root cause versus what they would do differently.',
    'Process and reflection over a beautiful final screen with no reasoning.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['closing-craft-growth', 'Where they want to grow in craft', 'design-process', 'closing', 'must', 0,
    'Ask what UI skill they most want to sharpen next. Assess self-awareness and learning hunger.',
    'Surface — wrap up warmly with one clear growth area.'],
]

// ─── UI Designer × Behavioral × 3-6 ────────────────────────────────────────
const mid: CompactSlot[] = [
  ['ui-ownership-narrative', 'A UI they owned end-to-end', 'design-process', 'warm-up', 'must', 0,
    'Ask about a screen or feature whose visual design they drove from rough to shipped. Calibrate ownership.',
    'Surface — use to pick follow-up threads.', 'Must show personal ownership of the visual outcome, not just executing someone\'s spec.'],
  ['defending-ui-decision', 'Defending a visual decision with rationale', 'design-process', 'exploration', 'must', 2,
    'Ask about a UI choice a PM or designer disagreed with. Look for rationale, not "it looked better."',
    'Probe the exact argument and what evidence or principle shifted the conversation.',
    'Holding a bar without being precious is the core signal.'],
  ['eng-feasibility-negotiation', 'Negotiating with engineering on feasibility', 'collaboration', 'exploration', 'must', 2,
    'Ask about a time engineering said a UI was too expensive to build. Tests pragmatic collaboration.',
    'Probe: "What did you protect, what did you let go, and how did you decide the line?"',
    'Must speak engineering\'s language — cost, complexity, reuse — not just defend the pixels.'],
  ['accessibility-advocacy-pressure', 'Advocating for accessibility under deadline', 'visual-design', 'exploration', 'must', 2,
    'Ask about pushing back when the team wanted to ship a pattern they knew was inaccessible.',
    'Probe what evidence they used and what compromise shipped.',
    'Expect specifics — WCAG, contrast, focus order — not generic "I care about a11y."'],
  ['component-reuse-vs-oneoff', 'Reuse vs. one-off component tension', 'design-systems', 'exploration', 'if-time', 2,
    'Ask about a time they had to choose between reusing a system component and building a one-off.',
    'Probe how they weighed consistency against the specific need and who they consulted.'],
  ['mentoring-junior-craft', 'Helping a junior designer level up craft', 'leadership', 'exploration', 'if-time', 1,
    'Ask how they\'ve helped a less experienced designer improve their visual work. Tests investment in others.',
    'Probe a specific critique that changed a peer\'s spacing, type, or layout habits.'],
  ['cross-functional-ui-alignment', 'Aligning design, PM, and eng on a UI', 'collaboration', 'exploration', 'must', 2,
    'Ask about building alignment when PM, eng, and design wanted different things on one screen.',
    'Probe who specifically resisted, their underlying concern, and how it resolved.',
    'Stakeholder fluency required — vague "I communicated well" fails.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['ui-decision-reversal', 'A UI decision they would reverse', 'design-process', 'closing', 'must', 0,
    'Ask about a visual decision they fought for that they\'d reverse today. Look for honest self-assessment.',
    'Surface — one clear example suffices.'],
]

// ─── UI Designer × Behavioral × 7+ ─────────────────────────────────────────
const senior: CompactSlot[] = [
  ['critique-culture-building', 'Building a critique and quality culture', 'leadership', 'warm-up', 'must', 0,
    'Ask how they established healthy critique and a visual quality bar on a team. Must be concrete.',
    'Surface — calibrate team-level scope and how they talk about "I" vs "the team."', 'How they describe the team reveals leadership character — credit-sharing vs credit-taking.'],
  ['mediating-designer-conflict', 'Mediating a designer-vs-designer pattern dispute', 'leadership', 'exploration', 'must', 2,
    'Ask about two designers disagreeing on a core UI pattern. Tests conflict mediation and durable decisions.',
    'Probe how they made the call stick and avoided relitigating it every sprint.',
    'Must resolve on principle and evidence, not seniority or loudest voice.'],
  ['design-system-governance-conflict', 'Governing system consistency across squads', 'design-systems', 'exploration', 'must', 2,
    'Ask about a product squad wanting to fork or one-off the design system. Tests governance vs autonomy.',
    'Probe how they balanced consistency with team velocity and what adoption signals they watched.',
    'Design ops maturity expected — contribution model, RFC/exception process, adoption tracking.'],
  ['raising-team-craft-bar', 'Raising the visual quality bar across a team', 'leadership', 'exploration', 'must', 2,
    'Ask about a team shipping inconsistent UI and how they lifted the craft level systematically.',
    'Probe the rituals and standards they introduced and how they measured improvement.',
    'Look for systems, not heroics — they cannot polish every screen themselves.'],
  ['advocating-craft-to-leadership', 'Advocating for craft investment to leadership', 'collaboration', 'exploration', 'if-time', 2,
    'Ask about convincing leadership to fund polish, accessibility, or a system rebuild over features.',
    'Probe the business case they made — retention, support cost, brand, velocity.'],
  ['hiring-developing-ui-designers', 'Hiring and developing UI designers', 'leadership', 'exploration', 'if-time', 2,
    'Ask how they hire for and grow visual craft on a team. Tests judgment about talent and growth paths.',
    'Probe what they look for in a portfolio and how they coach an eye that is not there yet.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['systemic-craft-failure', 'A craft or consistency failure with team consequences', 'leadership', 'closing', 'must', 0,
    'Ask about a significant quality/consistency failure and what changed at the team or system level.',
    'Probe systemic changes introduced — process, tooling, standards — not just personal growth.', 'Expect systems-level accountability, not "one designer messed up."'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('ui-designer', 'behavioral', '0-2', entry, [
    'Design system governance or org-wide consistency strategy',
    'Mediating conflicts between other designers',
    'Hiring, leveling, or managing a design team',
    'Funding decisions or making the business case for craft investment',
    'Setting a visual quality bar for a whole team',
  ]),
  template('ui-designer', 'behavioral', '3-6', mid, [
    'Building a design org or hiring a team from scratch',
    'Org-wide design system governance across many squads',
    'Executive or board-level pitches for design investment',
    'Performance-managing or leveling other designers',
    'Setting team-wide critique culture and standards',
  ]),
  template('ui-designer', 'behavioral', '7+', senior, [
    'Tool-specific mechanics (how to use Figma auto layout or variants)',
    'Individual handoff details of a single screen',
    'Basic design principles or critique etiquette for juniors',
    'Walking through one portfolio project\'s pixel decisions',
    'Whiteboard or live design exercise',
  ]),
]
