import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── UI Designer × Case Study × 0-2 ────────────────────────────────────────
const entry: CompactSlot[] = [
  ['case-clarify-scope', 'Clarifying questions before designing', 'design-process', 'warm-up', 'must', 0,
    'Present a narrow UI prompt (e.g., redesign a settings screen). Check whether they clarify before sketching.',
    'Surface — jumping straight to pixels without asking is a red flag at any level.', 'Narrating thinking aloud matters as much as what they draw.'],
  ['user-context-grounding', 'Defining the user and the core action', 'user-research', 'warm-up', 'must', 0,
    'Ask who uses this screen and what their primary action is before any layout work.',
    'Surface — this anchors every hierarchy decision that follows.', 'Skipping this and designing for no one is an early failure signal.'],
  ['hierarchy-layout-approach', 'Establishing hierarchy and layout', 'visual-design', 'exploration', 'must', 2,
    'Ask them to lay out the screen and explain the hierarchy — what is primary, secondary, tertiary, and why.',
    'Probe: "Why is that the primary action? What pulls the eye there — size, color, position?"',
    'Look for principled hierarchy, not a wall of equally-weighted elements.'],
  ['explore-ui-alternatives', 'Exploring 2-3 layout approaches', 'design-process', 'exploration', 'must', 2,
    'Ask them to rough out 2-3 layout directions and the tradeoffs before committing.',
    'Probe: "You went with option A — what was option B? Why did you reject it?"',
    'Exploring alternatives differentiates — divergent thinking is the key signal.'],
  ['states-and-edge-cases', 'States and edge cases', 'visual-design', 'exploration', 'must', 2,
    'Ask them to design beyond the default — empty, loading, and error states. Tests completeness.',
    'Probe: "What does this look like with no data? What does the error state look like?"',
    'Scope is intentionally narrow — reward depth of state thinking within it.'],
  ['accessibility-curveball', 'Adapting for accessibility mid-exercise', 'visual-design', 'exploration', 'if-time', 1,
    'Introduce a constraint (low-vision user, must work without color). Tests adaptability.',
    'Probe: "This needs 4.5:1 contrast and to work without color cues. What changes?"'],
  ['defending-ui-choices', 'Presenting and defending the UI', 'collaboration', 'exploration', 'if-time', 2,
    'Ask them to walk the solution and handle pushback. Tests conviction without stubbornness.',
    'Probe: "A teammate says the button should be lower. What\'s your case for keeping it where it is?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['ship-first-prioritization', 'What ships first given limited time', 'design-process', 'closing', 'must', 0,
    'Ask which part of the design ships first given 2 weeks of engineering time. Tests prioritization.',
    'Surface — one clear decision with rationale suffices.'],
]

// ─── UI Designer × Case Study × 3-6 ────────────────────────────────────────
const mid: CompactSlot[] = [
  ['scope-reframe', 'Scoping and reframing the prompt', 'design-process', 'warm-up', 'must', 0,
    'Present a broader UI prompt (e.g., a dashboard table). Check whether they scope and reframe before building.',
    'Surface — the best candidates reframe and constrain the prompt, not just execute it.', 'End-to-end ownership expected — hierarchy, component design, states, and accessibility.'],
  ['component-structure-plan', 'Structuring the core component', 'design-systems', 'exploration', 'must', 2,
    'Ask them to design a data-dense component (table, form, card) and explain its structure and reuse.',
    'Probe: "How do you handle overflow, sorting, and selection? Is this one component or a family?"',
    'System thinking — they should design a reusable component, not a one-off snapshot.'],
  ['layout-type-decisions', 'Type, spacing, and layout decisions', 'visual-design', 'exploration', 'must', 2,
    'Ask them to make deliberate type, spacing, and grid choices and justify them. Tests craft depth.',
    'Probe: "Why that type size and spacing here? What scale or grid are you working from?"',
    'Quantitative reasoning required — base unit, scale, grid columns, not arbitrary pixels.'],
  ['full-state-coverage', 'Full interaction-state coverage', 'visual-design', 'exploration', 'must', 2,
    'Ask for every state of the key component — hover, focus, active, disabled, loading, empty, error.',
    'Probe: "Walk me through focus order and keyboard nav — how does this work without a mouse?"',
    'Default-only fails — full state set and keyboard path are the bar at this level.'],
  ['accessibility-built-in', 'Accessibility designed in, not retrofitted', 'visual-design', 'exploration', 'if-time', 2,
    'Ask how they bake WCAG AA into the design from the start. Tests practical a11y craft.',
    'Probe: "How does a screen reader user understand this table? What\'s the contrast and color-independence story?"'],
  ['tradeoff-articulation', 'Articulating design tradeoffs', 'design-process', 'exploration', 'if-time', 2,
    'Ask them to name a tradeoff they made and what they sacrificed. Tests honest reasoning.',
    'Probe: "You chose density over whitespace — what did that cost, and for which user?"'],
  ['stakeholder-curveball-mid', 'Handling a stakeholder constraint', 'collaboration', 'exploration', 'must', 2,
    'Introduce a mid-exercise constraint (e.g., a PM wants an extra column / promo slot crammed in).',
    'Probe: "What do you push back on and what do you accommodate without breaking hierarchy?"',
    'Multi-stakeholder awareness — engineering feasibility, content, accessibility, and visual order.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['phasing-first-release', 'Phasing the first release', 'collaboration', 'closing', 'must', 0,
    'Ask what ships in the first release and what comes later. Tests prioritization under time pressure.',
    'Surface — clear milestones and rationale. Time management is a meta-skill being tested.'],
]

// ─── UI Designer × Case Study × 7+ ─────────────────────────────────────────
const senior: CompactSlot[] = [
  ['strategic-ui-scoping', 'Strategic scoping of a system-level prompt', 'design-systems', 'warm-up', 'must', 0,
    'Present a system-level prompt (e.g., a shared component system for two teams). Assess incisive scoping.',
    'Surface — quality of questions signals seniority. Treating it as one-screen IC work is a downgrade.', 'Tests UI as a systems function — tokens, components, governance — not single-screen craft.'],
  ['component-system-architecture', 'Designing the component and token system', 'design-systems', 'exploration', 'must', 2,
    'Ask them to design a small shared system (buttons, inputs, cards) with tokens and theming. Tests architecture.',
    'Probe: "How do two brands share this? What\'s a token swap vs. a fork?"',
    'Expect primitive/semantic token layering and a clear theming and reuse strategy.'],
  ['consistency-governance-plan', 'Consistency and governance across teams', 'design-systems', 'exploration', 'must', 2,
    'Ask how they\'d keep the system consistent as two+ teams adopt it. Tests governance and change management.',
    'Probe: "A team wants to fork a core component for their market. How do you decide and document that?"',
    'Hub-and-spoke governance — contribution model, exception process, adoption and drift metrics.'],
  ['migration-without-breakage', 'Migrating a legacy UI without alienating users', 'design-process', 'exploration', 'must', 2,
    'Ask how they modernize a legacy enterprise UI for a new audience while keeping power users productive.',
    'Probe: "Power users have muscle memory for the old layout. How do you migrate without a revolt?"',
    'Phased rollout, opt-in periods, and consistency planning expected — not a big-bang redesign.'],
  ['accessibility-at-scale', 'Accessibility as a system default', 'visual-design', 'exploration', 'if-time', 2,
    'Ask how they make every component in the system accessible by default. Tests a11y-as-infrastructure.',
    'Probe: "How do you guarantee a team using your components ships accessible UI without thinking about it?"'],
  ['handoff-quality-at-scale', 'Handoff and pixel parity at scale', 'collaboration', 'exploration', 'if-time', 2,
    'Ask how they ensure the system ships pixel-accurate across teams. Tests quality infrastructure.',
    'Probe: "What process or tooling catches drift between Figma and production across many teams?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['system-rollout-recovery', 'When system adoption stalls — recovery plan', 'design-systems', 'closing', 'must', 0,
    'Ask what they do if 6 months in, teams are ignoring the system and forking components. Tests resilience.',
    'Surface — look for diagnostic thinking and re-engagement, not just mandating compliance.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('ui-designer', 'case-study', '0-2', entry, [
    'Designing a shared multi-team component system or token architecture',
    'Laying out pixels before asking who the user is',
    'Designing only the default state with no empty, loading, or error states',
    'Ignoring accessibility (contrast, focus order, keyboard, color cues)',
    'Treating the exercise as a solo performance without engaging the interviewer',
  ]),
  template('ui-designer', 'case-study', '3-6', mid, [
    'Org-wide system governance across 8+ teams',
    'Designing only the happy path with no states or edge cases',
    'No accessibility consideration in the design',
    'Arbitrary type/spacing with no scale, grid, or base unit behind it',
    'Spending all the time talking and showing no concrete UI',
  ]),
  template('ui-designer', 'case-study', '7+', senior, [
    'Treating it as an IC task (laying out a single screen pixel by pixel)',
    'Designing a component system with no tokens, theming, or governance plan',
    'Proposing a migration with no rollout or change-management plan',
    'Generic design-thinking platitudes without concrete component decisions',
    'Ignoring accessibility as a system-level default',
  ]),
]
