import { template, DEEP_DIVE_1, DEEP_DIVE_2, type CompactSlot } from '../slotBuilder'
import type { FlowTemplate } from '../types'

// ─── UI Designer × Technical × 0-2 ─────────────────────────────────────────
const entry: CompactSlot[] = [
  ['visual-fundamentals', 'Visual hierarchy and layout fundamentals', 'visual-design', 'warm-up', 'must', 0,
    'Ask them to explain how they create hierarchy on a screen — size, weight, color, space. Tests vocabulary.',
    'Surface — use the answer to calibrate depth for the rest of the session.', 'Judged on reasoning clarity, not mastery — a thoughtful junior beats a sloppy mid-level.'],
  ['portfolio-ui-deepdive', 'Portfolio UI deep dive', 'visual-design', 'warm-up', 'must', 0,
    'Ask them to walk through the visual decisions on a recent screen. The portfolio IS the exam at entry level.',
    'Surface — this is the launching pad for technical follow-ups.', 'Look for documented decisions about type, spacing, and color — not just a pretty final frame.'],
  ['type-spacing-scale', 'Setting up a type and spacing scale', 'visual-design', 'exploration', 'must', 2,
    'Ask how they\'d set up a type scale and spacing system for a new app. Tests systematic thinking.',
    'Probe: "Why that base unit and those ratios? What breaks if you pick arbitrary values?"',
    'Fundamentals over tools — base unit, modular scale, consistent spacing tokens.'],
  ['figma-components-variants', 'Figma components vs. variants', 'design-systems', 'exploration', 'must', 2,
    'Ask how they organize a Figma file and when they reach for variants vs. separate components. Tests practical craft.',
    'Probe: "How would you set up a button that needs sizes, states, and an icon option?"',
    'Auto layout, variants, and basic library hygiene signal professionalism.'],
  ['accessibility-contrast-basics', 'Contrast and accessibility checks', 'visual-design', 'exploration', 'must', 2,
    'Ask what accessibility checks they run before shipping a screen. Awareness, not full audit.',
    'Probe: "What contrast ratio does body text need? What happens for a color-blind user here?"',
    'Know AA contrast (4.5:1), touch targets, keyboard nav — not expected to audit AAA.'],
  ['component-states-basics', 'Designing component states', 'visual-design', 'exploration', 'if-time', 1,
    'Ask them to name the states a component needs beyond default. Tests state-completeness instinct.',
    'Probe: "What does the disabled, loading, and error version look like and why?"'],
  ['screen-critique-entry', 'Critiquing a screen', 'visual-design', 'exploration', 'if-time', 2,
    'Show a screen and ask what works and what they\'d fix in type, spacing, and contrast. Tests critical eye.',
    'Probe: "You said the hierarchy is off — what specifically would you change and in what order?"',
    'Look for principle-grounded critique, not aesthetic opinions.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['iteration-before-after', 'An earlier version of a design', 'design-process', 'closing', 'must', 0,
    'Ask them to show or describe an earlier version of a screen and what visually changed. Tests iteration.',
    'Surface — one clear before/after with reasoning suffices.'],
]

// ─── UI Designer × Technical × 3-6 ─────────────────────────────────────────
const mid: CompactSlot[] = [
  ['ui-case-presentation', 'UI case presentation', 'visual-design', 'warm-up', 'must', 0,
    'Ask them to present their strongest UI work end-to-end. The case IS the technical interview at mid-level.',
    'Surface — set expectation you\'ll interrupt with probing questions on type, tokens, and states.', 'The decisions behind the pixels — scale, system, states, accessibility — determine the outcome.'],
  ['token-architecture', 'Design token architecture', 'design-systems', 'exploration', 'must', 2,
    'Ask how they structure tokens and where the line sits between primitive and semantic. Tests system depth.',
    'Probe: "How do you handle dark mode? What changes — the token values or the references?"',
    'Expected to be a system contributor — naming conventions, semantic layering, theming, docs.'],
  ['all-states-interaction', 'All-states interaction design', 'visual-design', 'exploration', 'must', 2,
    'Ask them to walk every state of a non-trivial component (e.g., a select or data row). Tests completeness.',
    'Probe: "Walk me through focus order and keyboard behavior — how does this work without a mouse?"',
    'Default-only designs fail — hover, focus, active, disabled, loading, empty, error all expected.'],
  ['accessibility-by-design', 'Accessibility built in from wireframe', 'visual-design', 'exploration', 'must', 2,
    'Ask how they bake WCAG AA in from the start rather than retrofitting. Tests practical a11y craft.',
    'Probe: "Walk me through how a screen reader and keyboard user complete this task in your design."',
    'A11y is a design skill — contrast, focus order, semantic hierarchy, color-independence from the start.'],
  ['responsive-adaptive-layout', 'Responsive and adaptive layout', 'visual-design', 'exploration', 'if-time', 2,
    'Ask how they design a complex layout across breakpoints. Tests grid and reflow reasoning.',
    'Probe: "What reflows, what hides, and what reorders from desktop to mobile, and why?"'],
  ['component-api-thinking', 'Designing a flexible component', 'design-systems', 'exploration', 'if-time', 2,
    'Ask how they design a component meant to be reused across many contexts. Tests system thinking.',
    'Probe: "A team needs this component to look different for their use case — extend it or fork it?"'],
  ['handoff-spec-quality', 'Design-to-engineering handoff', 'collaboration', 'exploration', 'must', 2,
    'Ask how they spec a complex component for engineering so it ships pixel-accurate. Tests handoff rigor.',
    'Probe: "How do you specify spacing, responsive behavior, and every state so nothing gets guessed?"',
    'Quantified fidelity expected — they should care about pixel parity and catching drift.'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['craft-impact-measurement', 'Measuring the impact of a UI improvement', 'design-process', 'closing', 'must', 0,
    'Ask for a concrete UI change with a measured result — task time, error rate, conversion. Tests rigor.',
    'Surface — one precise example. Push for numbers if they speak only qualitatively.'],
]

// ─── UI Designer × Technical × 7+ ──────────────────────────────────────────
const senior: CompactSlot[] = [
  ['system-vision', 'Vision for a design system and visual language', 'design-systems', 'warm-up', 'must', 0,
    'Ask how they develop a visual language and system strategy tied to product and brand goals. Tests range.',
    'Surface — calibrate whether they think in systems and governance or default to single-screen craft.', 'Systems and governance thinking outweigh individual pixel craft at this level.'],
  ['multibrand-token-architecture', 'Multi-brand, multi-platform token architecture', 'design-systems', 'exploration', 'must', 2,
    'Ask how they\'d architect tokens to serve multiple brands across web, iOS, and Android. Tests scale.',
    'Probe: "How do you layer tokens so a brand swap is one change, not a thousand?"',
    'Expect primitive/semantic/component token layers and a clear theming strategy.'],
  ['system-governance-scale', 'Governing a component library at scale', 'design-systems', 'exploration', 'must', 2,
    'Ask how they govern a shared library across 8+ teams. Tests change management and contribution model.',
    'Probe: "A team wants to fork a core component for a new market. How do you handle that request?"',
    'Hub-and-spoke governance — RFC process, contribution model, adoption metrics, deprecation policy.'],
  ['pixel-parity-quality-gates', 'Enforcing pixel parity and quality gates', 'design-systems', 'exploration', 'must', 2,
    'Ask how they keep Figma and production in sync and catch visual drift. Tests quality infrastructure.',
    'Probe: "What process or tooling catches a 4px regression before users see it? What\'s the metric?"',
    'Look for visual-regression tooling, design-review gates, and a defect/parity metric.'],
  ['accessibility-program', 'Accessibility as a program, not a checkbox', 'visual-design', 'exploration', 'if-time', 2,
    'Ask how they move an org from accessibility-as-compliance to accessibility-as-default. Tests strategy.',
    'Probe: "How do you get engineering to prioritize a11y fixes against a full feature backlog?"'],
  ['emerging-tools-stance', 'Stance on emerging design tools and motion', 'design-process', 'exploration', 'if-time', 2,
    'Ask how they evaluate AI-assisted design, new prototyping tools, or emerging interaction paradigms.',
    'Probe: "Where does AI help your craft and where does it hurt visual quality?"'],
  DEEP_DIVE_1,
  DEEP_DIVE_2,
  ['system-roi-to-leadership', 'Proving the value of system and craft investment', 'collaboration', 'closing', 'must', 0,
    'Ask how they justify investment in a design system or quality work to leadership. Tests business framing.',
    'Surface — look for velocity, consistency, support-cost, and brand arguments with rough numbers.'],
]

export const TEMPLATES: FlowTemplate[] = [
  template('ui-designer', 'technical', '0-2', entry, [
    'Multi-brand or multi-platform token architecture',
    'Governing a component library across many teams',
    'Front-end coding or CSS implementation questions',
    'Design-system ROI or business-case framing for leadership',
    'Pixel-parity tooling or visual-regression infrastructure',
  ]),
  template('ui-designer', 'technical', '3-6', mid, [
    'Basic vocabulary (what is hierarchy, what is contrast, what is a variant)',
    'Tool-level how-tos (how to use Figma auto layout — assume proficiency)',
    'Org-level system governance across 8+ teams',
    'Hiring, performance management, or leveling designers',
    'Front-end coding or CSS implementation questions',
  ]),
  template('ui-designer', 'technical', '7+', senior, [
    'Individual execution tasks (lay out this one screen, design this one button)',
    'Tool-level mechanics (Figma variants, auto layout how-tos)',
    'Basic visual principles or accessibility 101',
    'Single-screen critique exercises (appropriate for mid-level)',
    'Front-end coding or CSS implementation questions',
  ]),
]
