import { NextRequest, NextResponse } from 'next/server'
import mongoose from 'mongoose'
import { getServerSession } from 'next-auth'
import { authOptions } from '@shared/auth/authOptions'
import { connectDB } from '@shared/db/connection'
import { InterviewSession } from '@shared/db/models'
import { logger } from '@shared/logger'
import type { AnswerEvaluation, FeedbackData } from '@shared/types'
import { getDomainLabel } from '@interview/config/interviewConfig'
import { generateIdealAnswerForQuestion } from '@learn/services/idealAnswerBackfill'

/**
 * Below this average score we treat the question as "weak enough" to
 * warrant a strong-answer outline. Matches the threshold in
 * `weakestQuestionContext` (app/api/generate-feedback/route.ts:161) so
 * the batch enrichment and the JIT backfill never disagree about which
 * questions deserve coaching.
 */
const WEAK_QUESTION_SCORE_THRESHOLD = 60

function avgEvaluationScore(evaluation: AnswerEvaluation): number {
  return Math.round(
    ((Number(evaluation.relevance) || 0) +
      (Number(evaluation.structure) || 0) +
      (Number(evaluation.specificity) || 0) +
      (Number(evaluation.ownership) || 0)) /
      4,
  )
}

export const dynamic = 'force-dynamic'

/**
 * GET /api/learn/drill/context/question?sessionId=<id>&questionIndex=<n>
 *
 * Returns the per-question coach context the drill page needs to render
 * `IdealAnswerComparisonCard` (when `ideal_answers` is present for the
 * question) or the `QuestionInsightStrip` fallback (when it isn't).
 *
 * Pathway P2 Wave 5 (feature 5B) — surfaces existing data; zero new LLM
 * calls. `AnswerEvaluation.primaryGap` is precomputed during scoring;
 * `feedback.ideal_answers` is generated by the post-interview enrichment
 * step. The drill page previously had no path to either, so users
 * retried weak answers with no idea WHY the answer scored low or what
 * a strong version would have looked like.
 *
 * Auth: standard session-based + per-document ownership check.
 * Cross-user access returns 404 (not 403) to avoid confirming the
 * session id exists for a different user.
 */
export async function GET(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { searchParams } = new URL(req.url)
    const sessionId = searchParams.get('sessionId')?.trim()
    const questionIndexRaw = searchParams.get('questionIndex')

    if (!sessionId || !mongoose.Types.ObjectId.isValid(sessionId)) {
      return NextResponse.json({ error: 'sessionId is required and must be a valid ObjectId' }, { status: 400 })
    }
    // Guard against the `Number(null) === 0` / `Number('') === 0`
    // foot-gun: a missing/empty param would otherwise silently parse
    // to questionIndex=0 (a valid request for the first question).
    // Caller must explicitly send a digit string.
    if (questionIndexRaw === null || !/^\d+$/.test(questionIndexRaw.trim())) {
      return NextResponse.json({ error: 'questionIndex is required and must be a non-negative integer' }, { status: 400 })
    }
    const questionIndex = Number(questionIndexRaw)

    await connectDB()

    const doc = await InterviewSession.findOne({
      _id: new mongoose.Types.ObjectId(sessionId),
      userId: new mongoose.Types.ObjectId(session.user.id),
    })
      .select({
        'config.role': 1,
        'config.interviewType': 1,
        evaluations: 1,
        'feedback.ideal_answers': 1,
      })
      .lean<{
        config?: { role?: string; interviewType?: string }
        evaluations?: AnswerEvaluation[]
        feedback?: Pick<FeedbackData, 'ideal_answers'>
      }>()

    if (!doc) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 })
    }

    const evaluation = (doc.evaluations ?? []).find((e) => e.questionIndex === questionIndex)
    let idealAnswer = (doc.feedback?.ideal_answers ?? []).find(
      (ia) => ia.questionIndex === questionIndex,
    )

    // JIT backfill — the batch enrichment in /api/generate-feedback
    // routinely produces partial coverage (the LLM picks the worst few
    // weak questions and skips others) even though the prompt asks for
    // one entry per weak question. Pre-2026-05-19 sessions also only
    // have top-3 outlines from the older enrichment path. When this
    // route is asked about a weak question (avg < 60) that has no
    // outline, generate ONE on demand and persist it to the session.
    //
    // Costs: ~$0.0005 per backfilled question on haiku; capped at 6s
    // wall-clock so the drill page never feels frozen. Race-safe via
    // a $ne update filter — concurrent requests for the same question
    // result in at most one DB write; the loser wastes its LLM call
    // (~$0.0005) but doesn't corrupt state.
    if (!idealAnswer && evaluation) {
      const avg = avgEvaluationScore(evaluation)
      if (avg < WEAK_QUESTION_SCORE_THRESHOLD && evaluation.question && doc.config?.role) {
        const role = doc.config.role
        const interviewType = doc.config.interviewType ?? 'screening'
        let domainLabel: string
        try {
          domainLabel = getDomainLabel(role)
        } catch {
          domainLabel = role
        }
        const generated = await generateIdealAnswerForQuestion({
          question: evaluation.question,
          candidateAnswer: String(evaluation.answer ?? ''),
          domainLabel,
          interviewType,
          sessionId,
          questionIndex,
        })
        if (generated) {
          const entry = {
            questionIndex,
            strongAnswer: generated.strongAnswer,
            keyElements: generated.keyElements,
          }
          try {
            // Conditional $push — only writes if no entry for this
            // questionIndex already exists. Two concurrent backfills:
            // the second's filter doesn't match and updateOne returns
            // matchedCount=0, leaving the first write intact.
            await InterviewSession.updateOne(
              {
                _id: new mongoose.Types.ObjectId(sessionId),
                userId: new mongoose.Types.ObjectId(session.user.id),
                'feedback.ideal_answers.questionIndex': { $ne: questionIndex },
              },
              { $push: { 'feedback.ideal_answers': entry } },
            )
          } catch (persistErr) {
            // Persist failure is non-fatal — we still return the
            // generated outline so the user sees it on THIS request.
            // The next visit re-triggers JIT backfill.
            logger.warn(
              { err: persistErr, sessionId, questionIndex },
              'ideal_answer backfill: persist failed; returning ephemeral outline',
            )
          }
          idealAnswer = entry
        }
      }
    }

    return NextResponse.json({
      primaryGap: evaluation?.primaryGap ?? null,
      // Ship the 4-dim scores too so the fallback `QuestionInsightStrip`
      // can call `deriveCoachingTip` (which needs the whole evaluation
      // shape, not just the gap name). Cheap — we already loaded the
      // evaluations array via .lean(); we just project the slice the
      // client needs and discard the rest.
      scores: evaluation
        ? {
            relevance: evaluation.relevance,
            structure: evaluation.structure,
            specificity: evaluation.specificity,
            ownership: evaluation.ownership,
          }
        : null,
      domain: doc.config?.role ?? null,
      interviewType: doc.config?.interviewType ?? null,
      // Returned only if it actually exists on the session OR was just
      // JIT-generated above — drill page falls back to
      // `QuestionInsightStrip` when this is null (backfill timed out
      // or LLM failed).
      idealAnswer: idealAnswer
        ? {
            strongAnswer: idealAnswer.strongAnswer,
            keyElements: idealAnswer.keyElements,
          }
        : null,
    })
  } catch (err) {
    logger.error({ err }, 'Failed to load drill question context')
    return NextResponse.json({ error: 'Failed to load' }, { status: 500 })
  }
}
