import { NextRequest, NextResponse } from 'next/server'
import mongoose from 'mongoose'
import { getServerSession } from 'next-auth'
import { authOptions } from '@shared/auth/authOptions'
import { connectDB } from '@shared/db/connection'
import { InterviewSession } from '@shared/db/models'
import { logger } from '@shared/logger'
import type { AnswerEvaluation, FeedbackData } from '@shared/types'
import { getDomainLabel } from '@interview/config/interviewConfig'
import { inngest } from '@shared/services/inngest'

/**
 * Below this average score we treat the question as "weak enough" to
 * warrant a strong-answer outline. Matches the threshold in
 * `weakestQuestionContext` (app/api/generate-feedback/route.ts:161) so
 * the batch enrichment and the JIT backfill never disagree about which
 * questions deserve coaching.
 */
const WEAK_QUESTION_SCORE_THRESHOLD = 60

function avgEvaluationScore(evaluation: AnswerEvaluation): number {
  return Math.round(
    ((Number(evaluation.relevance) || 0) +
      (Number(evaluation.structure) || 0) +
      (Number(evaluation.specificity) || 0) +
      (Number(evaluation.ownership) || 0)) /
      4,
  )
}

export const dynamic = 'force-dynamic'

/**
 * GET /api/learn/drill/context/question?sessionId=<id>&questionIndex=<n>
 *
 * Returns the per-question coach context the drill page needs to render
 * `IdealAnswerComparisonCard` (when `ideal_answers` is present for the
 * question) or the `QuestionInsightStrip` fallback (when it isn't).
 *
 * Pathway P2 Wave 5 (feature 5B) — surfaces existing data; zero new LLM
 * calls. `AnswerEvaluation.primaryGap` is precomputed during scoring;
 * `feedback.ideal_answers` is generated by the post-interview enrichment
 * step. The drill page previously had no path to either, so users
 * retried weak answers with no idea WHY the answer scored low or what
 * a strong version would have looked like.
 *
 * Auth: standard session-based + per-document ownership check.
 * Cross-user access returns 404 (not 403) to avoid confirming the
 * session id exists for a different user.
 */
export async function GET(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { searchParams } = new URL(req.url)
    const sessionId = searchParams.get('sessionId')?.trim()
    const questionIndexRaw = searchParams.get('questionIndex')

    if (!sessionId || !mongoose.Types.ObjectId.isValid(sessionId)) {
      return NextResponse.json({ error: 'sessionId is required and must be a valid ObjectId' }, { status: 400 })
    }
    // Guard against the `Number(null) === 0` / `Number('') === 0`
    // foot-gun: a missing/empty param would otherwise silently parse
    // to questionIndex=0 (a valid request for the first question).
    // Caller must explicitly send a digit string.
    if (questionIndexRaw === null || !/^\d+$/.test(questionIndexRaw.trim())) {
      return NextResponse.json({ error: 'questionIndex is required and must be a non-negative integer' }, { status: 400 })
    }
    const questionIndex = Number(questionIndexRaw)

    await connectDB()

    const doc = await InterviewSession.findOne({
      _id: new mongoose.Types.ObjectId(sessionId),
      userId: new mongoose.Types.ObjectId(session.user.id),
    })
      .select({
        'config.role': 1,
        'config.interviewType': 1,
        evaluations: 1,
        'feedback.ideal_answers': 1,
        enrichmentStatus: 1,
      })
      .lean<{
        config?: { role?: string; interviewType?: string }
        evaluations?: AnswerEvaluation[]
        feedback?: Pick<FeedbackData, 'ideal_answers'>
        enrichmentStatus?: string
      }>()

    if (!doc) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 })
    }

    const evaluation = (doc.evaluations ?? []).find((e) => e.questionIndex === questionIndex)
    let idealAnswer = (doc.feedback?.ideal_answers ?? []).find(
      (ia) => ia.questionIndex === questionIndex,
    )

    // Missing outline → enqueue the FULL-quality async enrichment job for
    // this session instead of the old 6s user-blocking JIT LLM call
    // (removed 2026-07-17; it inherited reasoningEffort 'high' at the
    // GPT-5.6 cutover and timed out on 100% of runs — third call site of
    // the feedback slot). The job regenerates the complete ideal_answers
    // set at 'high' and persists it; THIS request returns the existing
    // QuestionInsightStrip fallback immediately, and the outline is there
    // for the next visit (or the page's own refresh). Dedupe: skip the
    // send when a job is already pending/running for this session.
    if (!idealAnswer && evaluation) {
      const avg = avgEvaluationScore(evaluation)
      const jobActive = doc.enrichmentStatus === 'pending' || doc.enrichmentStatus === 'running'
      if (avg < WEAK_QUESTION_SCORE_THRESHOLD && !jobActive) {
        inngest
          .send({
            name: 'feedback/enrich.requested',
            data: { sessionId, userId: session.user.id, reason: 'drill-backfill', questionIndex },
          })
          .then(() =>
            InterviewSession.updateOne(
              { _id: new mongoose.Types.ObjectId(sessionId) },
              { $set: { enrichmentStatus: 'pending' } },
            ),
          )
          .catch((err) =>
            logger.warn(
              { err, sessionId, questionIndex },
              'drill-backfill enrichment enqueue failed; falling back to insight strip',
            ),
          )
      }
    }

    return NextResponse.json({
      primaryGap: evaluation?.primaryGap ?? null,
      // Ship the 4-dim scores too so the fallback `QuestionInsightStrip`
      // can call `deriveCoachingTip` (which needs the whole evaluation
      // shape, not just the gap name). Cheap — we already loaded the
      // evaluations array via .lean(); we just project the slice the
      // client needs and discard the rest.
      scores: evaluation
        ? {
            relevance: evaluation.relevance,
            structure: evaluation.structure,
            specificity: evaluation.specificity,
            ownership: evaluation.ownership,
          }
        : null,
      domain: doc.config?.role ?? null,
      interviewType: doc.config?.interviewType ?? null,
      // Returned only if it actually exists on the session OR was just
      // JIT-generated above — drill page falls back to
      // `QuestionInsightStrip` when this is null (backfill timed out
      // or LLM failed).
      idealAnswer: idealAnswer
        ? {
            strongAnswer: idealAnswer.strongAnswer,
            keyElements: idealAnswer.keyElements,
          }
        : null,
    })
  } catch (err) {
    logger.error({ err }, 'Failed to load drill question context')
    return NextResponse.json({ error: 'Failed to load' }, { status: 500 })
  }
}
