import { createElement } from 'react'
import type { ResumeData } from '../validators/resume'
import {
  getFontStack,
  getFontSizes,
  getCustomFontSizes,
  getGoogleFontUrl,
  DEFAULT_HEADING_SIZE,
  DEFAULT_BODY_SIZE,
} from '../config/fontConfig'
import { getTemplate } from '../components/templates'
// Pre-compiled, minified Tailwind bundle scoped to the resume templates.
// Generated by `node scripts/build-resume-css.js` (runs automatically via
// package.json prebuild/predev/pretest hooks). Imported as a JSON module so
// Next.js's bundler ships it with the serverless function on every target
// (Vercel, Docker, self-hosted) — no fs.readFile or origin fetching needed.
import resumePdfCss from '../styles/resume-pdf-css.json'

// ─── SSR: render the real React template used by the preview ─────────────────
// The preview in ResumePreview.tsx applies a wrapperStyle with CSS vars
// (--r-title/--r-body/--r-section/--r-meta) and a font-family. We replicate
// that wrapper here so the SSR output matches the preview pixel-for-pixel.

// Next.js App Router refuses static ESM imports of `react-dom/server` inside
// any module that might be bundled outside a server-only context. Loading it
// via `require` at call time keeps this module portable (API routes,
// background jobs, tests) without triggering the webpack guard.
function renderTemplateToMarkup(
  data: ResumeData,
  templateId: string,
): string {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const reactDomServer = require('react-dom/server') as typeof import('react-dom/server')
  const Template = getTemplate(templateId)
  return reactDomServer.renderToStaticMarkup(createElement(Template, { data }))
}

export function renderResumeHTML(data: ResumeData, templateId: string): string {
  const templateMarkup = renderTemplateToMarkup(data, templateId)

  const fontFamily = data.styling?.fontFamily
  const hasCustomSizes =
    data.styling?.headingSize != null || data.styling?.bodySize != null
  const sizes = hasCustomSizes
    ? getCustomFontSizes(
        data.styling?.headingSize ?? DEFAULT_HEADING_SIZE,
        data.styling?.bodySize ?? DEFAULT_BODY_SIZE,
      )
    : getFontSizes(data.styling?.fontSize)
  const googleFontUrl = getGoogleFontUrl(fontFamily)
  const googleFontLink = googleFontUrl
    ? `<link rel="stylesheet" href="${googleFontUrl}">`
    : ''
  const fontStack = getFontStack(fontFamily)

  // A4 @ 72dpi = 595 × 842 px. Matches PAGE_WIDTH/PAGE_HEIGHT in ResumePreview.
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  ${googleFontLink}
  <style>${resumePdfCss.css}</style>
  <style>
    @page { size: A4; margin: 0; }
    html, body {
      margin: 0;
      padding: 0;
      background: #ffffff;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    #resume-page {
      width: 595px;
      min-height: 842px;
      padding: 24px;
      box-sizing: border-box;
      background: #ffffff;
      font-family: ${fontStack};
      --r-title: ${sizes.title};
      --r-body: ${sizes.body};
      --r-section: ${sizes.section};
      --r-meta: ${sizes.meta};
    }
  </style>
</head>
<body>
  <div id="resume-page">${templateMarkup}</div>
</body>
</html>`
}

// ─── Puppeteer renderer ──────────────────────────────────────────────────────

interface RenderPdfOptions {
  margin?: { top: string; right: string; bottom: string; left: string }
}

async function renderPdfFromHtml(
  html: string,
  options?: RenderPdfOptions,
): Promise<Buffer> {
  // Dynamic require to handle environments without Puppeteer.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const puppeteer = require('puppeteer-core')

  // @sparticuz/chromium v110+ extracts a brotli-compressed Chromium at runtime.
  // For this to work on Vercel/Lambda, the package must be in
  // next.config.js → experimental.serverComponentsExternalPackages so webpack
  // leaves the archive intact. We also MUST pass chromium.args (the ~22 flags
  // tuned for serverless single-process execution); passing only --no-sandbox
  // causes the browser to crash or fail to spawn.
  let launchArgs: string[] = ['--no-sandbox', '--disable-setuid-sandbox']
  let executablePath: string

  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const chromiumMod = require('@sparticuz/chromium')
    const chromium = chromiumMod.default ?? chromiumMod
    if (Array.isArray(chromium.args) && chromium.args.length > 0) {
      launchArgs = [
        ...chromium.args,
        '--hide-scrollbars',
        '--disable-web-security',
      ]
    }
    executablePath = await chromium.executablePath()
  } catch {
    executablePath =
      process.env.CHROMIUM_PATH || '/usr/bin/chromium-browser'
  }

  const browser = await puppeteer.launch({
    args: launchArgs,
    executablePath,
    headless: true,
  })

  try {
    const page = await browser.newPage()
    await page.setViewport({ width: 1280, height: 1696 })
    await page.setContent(html, { waitUntil: 'networkidle0' })
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      // Zero puppeteer margins — the #resume-page element encodes its own
      // 24px padding that matches the preview's PAGE_PADDING.
      margin: options?.margin ?? {
        top: '0',
        right: '0',
        bottom: '0',
        left: '0',
      },
    })
    return Buffer.from(pdfBuffer)
  } finally {
    await browser.close()
  }
}

// ─── Public API ──────────────────────────────────────────────────────────────

export async function generatePDF(
  data: ResumeData,
  templateId: string,
): Promise<Buffer> {
  const html = renderResumeHTML(data, templateId)
  return renderPdfFromHtml(html)
}

/** @deprecated — kept for backward compatibility. Prefer `renderResumeHTML`. */
export function generateResumeHTML(data: ResumeData, templateId: string): string {
  return renderResumeHTML(data, templateId)
}
