import { createElement } from 'react'
import type { ResumeData } from '../validators/resume'
import {
  getFontStack,
  getFontSizes,
  getCustomFontSizes,
  getGoogleFontUrl,
  DEFAULT_HEADING_SIZE,
  DEFAULT_BODY_SIZE,
} from '../config/fontConfig'
import { getTemplate } from '../components/templates'
import { ResumePreviewPageProvider } from '../components/ResumePreviewPageContext'
import type { ResumePreviewPageContextValue } from '../components/ResumePreviewPageContext'
import {
  applySkillsTruncationToData,
  computeOmittedSkillCounts,
  computeSkillCategoryRatios,
  refineSkillRatiosIfStillOversized,
} from '../lib/skillCategoryTruncation'
import type { SplittableSectionMeasurement } from '../lib/resumePageBreaks'
// Pre-compiled, minified Tailwind bundle scoped to the resume templates.
// Generated by `node scripts/build-resume-css.js` (runs automatically via
// package.json prebuild/predev/pretest hooks). Imported as a JSON module so
// Next.js's bundler ships it with the serverless function on every target
// (Vercel, Docker, self-hosted) — no fs.readFile or origin fetching needed.
import resumePdfCss from '../styles/resume-pdf-css.json'

// ─── SSR: render the real React template used by the preview ─────────────────
// The preview in ResumePreview.tsx applies a wrapperStyle with CSS vars
// (--r-title/--r-body/--r-section/--r-meta) and a font-family. We replicate
// that wrapper here so the SSR output matches the preview pixel-for-pixel.

// Next.js App Router refuses static ESM imports of `react-dom/server` inside
// any module that might be bundled outside a server-only context. Loading it
// via `require` at call time keeps this module portable (API routes,
// background jobs, tests) without triggering the webpack guard.
function renderTemplateToMarkup(
  data: ResumeData,
  templateId: string,
  pageContext?: ResumePreviewPageContextValue,
): string {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const reactDomServer = require('react-dom/server') as typeof import('react-dom/server')
  const Template = getTemplate(templateId)
  // When a page context is supplied (PDF truncation pass), wrap the template in
  // the SAME provider the preview uses so ResumeSkillsSection slices oversized
  // categories and renders the "+N more" cue identically — no more clipping or
  // page-count divergence between preview and export (Codex r3319377027).
  const tree = pageContext
    ? createElement(
        ResumePreviewPageProvider,
        { value: pageContext },
        createElement(Template, { data }),
      )
    : createElement(Template, { data })
  return reactDomServer.renderToStaticMarkup(tree)
}

export function renderResumeHTML(
  data: ResumeData,
  templateId: string,
  pageContext?: ResumePreviewPageContextValue,
): string {
  const templateMarkup = renderTemplateToMarkup(data, templateId, pageContext)

  const fontFamily = data.styling?.fontFamily
  const hasCustomSizes =
    data.styling?.headingSize != null || data.styling?.bodySize != null
  const sizes = hasCustomSizes
    ? getCustomFontSizes(
        data.styling?.headingSize ?? DEFAULT_HEADING_SIZE,
        data.styling?.bodySize ?? DEFAULT_BODY_SIZE,
      )
    : getFontSizes(data.styling?.fontSize)
  const googleFontUrl = getGoogleFontUrl(fontFamily)
  const googleFontLink = googleFontUrl
    ? `<link rel="stylesheet" href="${googleFontUrl}">`
    : ''
  const fontStack = getFontStack(fontFamily)

  // A4 @ 72dpi = 595 × 842 px. Matches PAGE_WIDTH/PAGE_HEIGHT in ResumePreview.
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  ${googleFontLink}
  <style>${resumePdfCss.css}</style>
  <style>
    @page { size: A4; margin: 0; }
    html, body {
      margin: 0;
      padding: 0;
      background: #ffffff;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    #resume-pages-root {
      width: 595px;
      background: #ffffff;
    }
    .resume-wrapper {
      font-family: ${fontStack};
      --r-title: ${sizes.title};
      --r-body: ${sizes.body};
      --r-section: ${sizes.section};
      --r-meta: ${sizes.meta};
    }
    #resume-measure-root {
      position: absolute;
      visibility: hidden;
      pointer-events: none;
      width: 547px;
    }
    .resume-page {
      width: 595px;
      height: 842px;
      background: #fff;
      box-sizing: border-box;
      overflow: hidden;
      page-break-after: always;
    }
    .resume-page-inner {
      padding: 24px;
      box-sizing: border-box;
    }
    .resume-page-viewport {
      width: 547px;
      height: 794px;
      overflow: hidden;
      position: relative;
    }
    .resume-continuation-header {
      position: absolute;
      top: 0;
      z-index: 10;
    }
    .resume-page-content {
      width: 547px;
    }
  </style>
</head>
<body>
  <div id="resume-measure-root" class="resume-wrapper">
    <div id="resume-template-root">${templateMarkup}</div>
  </div>
  <div id="resume-pages-root"></div>
  <script>
    (function paginateForPdf() {
      const PAGE_HEIGHT = 842;
      const PAGE_PADDING = 24;
      const CONTENT_HEIGHT = PAGE_HEIGHT - PAGE_PADDING * 2;

      function relativeTop(el, root) {
        const rootRect = root.getBoundingClientRect();
        return Math.round(el.getBoundingClientRect().top - rootRect.top);
      }

      function bottom(unit) {
        return unit.offsetTop + unit.offsetHeight;
      }

      function pageEnd(pageStart, pageHeight, reservedTop) {
        return pageStart + pageHeight - (reservedTop || 0);
      }

      function fits(bottomPx, pageStart, pageHeight, reservedTop) {
        return bottomPx <= pageEnd(pageStart, pageHeight, reservedTop);
      }

      function pushBreak(breaks, continuation, at, needsHeader) {
        if (breaks[breaks.length - 1] === at) return;
        breaks.push(at);
        continuation.push(needsHeader);
      }

      function collectLeafMarked(templateRoot) {
        const marked = Array.from(templateRoot.querySelectorAll('[data-resume-section]'));
        return marked.filter(el => {
          let parent = el.parentElement;
          while (parent && parent !== templateRoot) {
            if (parent.hasAttribute('data-resume-section')) return false;
            parent = parent.parentElement;
          }
          return true;
        });
      }

      const UNIT_SELECTOR = '[data-resume-section-unit], [data-resume-skills-category]';

      function collectSectionUnits(sectionEl) {
        return Array.from(sectionEl.querySelectorAll(UNIT_SELECTOR)).filter(el => {
          const categoryRow = el.closest('[data-resume-skills-category]');
          return !categoryRow || categoryRow === el;
        });
      }

      function measureSplittable(sectionEl, templateRoot, sectionId) {
        const sectionTop = relativeTop(sectionEl, templateRoot);
        const headerEl = sectionEl.querySelector('[data-resume-section-header], [data-resume-skills-header]');
        const unitEls = collectSectionUnits(sectionEl);
        const header = headerEl ? {
          offsetTop: relativeTop(headerEl, templateRoot) - sectionTop,
          offsetHeight: headerEl.offsetHeight,
        } : { offsetTop: 0, offsetHeight: 0 };
        const units = unitEls.map((el, unitIndex) => ({
          unitIndex,
          offsetTop: relativeTop(el, templateRoot) - sectionTop,
          offsetHeight: el.offsetHeight,
        }));
        return {
          kind: 'splittable',
          sectionId,
          offsetTop: sectionTop,
          offsetHeight: sectionEl.offsetHeight,
          header,
          units,
        };
      }

      function measureBlock(el, templateRoot, sectionId) {
        const headerEl = el.querySelector('[data-resume-section-header]');
        return {
          kind: 'block',
          sectionId,
          offsetTop: relativeTop(el, templateRoot),
          offsetHeight: el.offsetHeight,
          headerHeight: headerEl ? headerEl.offsetHeight : 0,
        };
      }

      function isSplittable(el) {
        return collectSectionUnits(el).length > 0;
      }

      function measureSections(templateRoot) {
        const marked = collectLeafMarked(templateRoot);
        if (marked.length > 0) {
          return marked
            .sort((a, b) => relativeTop(a, templateRoot) - relativeTop(b, templateRoot))
            .map(el => {
              const sectionId = el.getAttribute('data-resume-section') || 'section';
              // Multi-column regions paginate as one atomic height-sliced block
              // (mirror of measureResumeSections.ts — Creative columns fix).
              if (el.hasAttribute('data-resume-columns')) {
                return {
                  kind: 'block',
                  sectionId,
                  offsetTop: relativeTop(el, templateRoot),
                  offsetHeight: el.offsetHeight,
                  headerHeight: 0,
                };
              }
              return isSplittable(el)
                ? measureSplittable(el, templateRoot, sectionId)
                : measureBlock(el, templateRoot, sectionId);
            });
        }

        return Array.from(templateRoot.children).map(child => {
          const skillsEl = child.querySelector('[data-resume-section="skills"]');
          if (skillsEl) return measureSplittable(skillsEl, templateRoot, 'skills');
          return measureBlock(child, templateRoot, 'block');
        });
      }

      function unitBottomAbs(sectionTop, unit) {
        return sectionTop + bottom(unit);
      }

      function layoutSplittable(section, pageStart, pageHeight, breaks, continuation) {
        const sectionTop = section.offsetTop;
        const sectionBottom = bottom(section);
        const header = section.header;
        const units = section.units;
        let pageStartLocal = pageStart;
        let reservedTop = 0;

        if (units.length === 0) {
          if (!fits(sectionBottom, pageStartLocal, pageHeight, reservedTop)) {
            pushBreak(breaks, continuation, sectionTop, false);
            return sectionTop;
          }
          return pageStartLocal;
        }

        const wholeFits = () => fits(sectionBottom, pageStartLocal, pageHeight, reservedTop);
        if (wholeFits()) return pageStartLocal;

        const firstUnitBottom = unitBottomAbs(sectionTop, units[0]);
        const firstChunkBottom = Math.max(
          firstUnitBottom,
          sectionTop + bottom(header) + units[0].offsetHeight,
        );

        if (!fits(firstChunkBottom, pageStartLocal, pageHeight, reservedTop)) {
          if (sectionTop > pageStartLocal) {
            pushBreak(breaks, continuation, sectionTop, false);
            pageStartLocal = sectionTop;
            reservedTop = 0;
          }
          if (wholeFits()) return pageStartLocal;
        }

        for (let index = 0; index < units.length; index++) {
          const unit = units[index];
          const unitBreakTop = sectionTop + unit.offsetTop;
          const unitBottomPx = unitBottomAbs(sectionTop, unit);

          if (!fits(unitBottomPx, pageStartLocal, pageHeight, reservedTop) && unitBreakTop > pageStartLocal) {
            if (index === 0) {
              if (sectionTop > pageStartLocal) {
                pushBreak(breaks, continuation, sectionTop, false);
                pageStartLocal = sectionTop;
                reservedTop = 0;
              }
            } else {
              pushBreak(breaks, continuation, unitBreakTop, true);
              pageStartLocal = unitBreakTop;
              reservedTop = header.offsetHeight;
            }
          }
        }

        return pageStartLocal;
      }

      function layoutBlock(section, pageStart, pageHeight, breaks, continuation) {
        const blockBottom = bottom(section);
        let reservedTop = 0;
        if (fits(blockBottom, pageStart, pageHeight, reservedTop)) return pageStart;

        const pageEndPx = pageEnd(pageStart, pageHeight, reservedTop);
        const startsOnCurrentPage =
          section.offsetTop >= pageStart && section.offsetTop < pageEndPx;
        if (startsOnCurrentPage && section.offsetTop > pageStart) {
          pushBreak(breaks, continuation, section.offsetTop, false);
          pageStart = section.offsetTop;
          reservedTop = 0;
          if (fits(blockBottom, pageStart, pageHeight, reservedTop)) return pageStart;
        }

        if (section.offsetHeight > pageHeight - reservedTop) {
          if (section.offsetTop > pageStart) {
            pushBreak(breaks, continuation, section.offsetTop, false);
            pageStart = section.offsetTop;
            reservedTop = 0;
          }
          let next = pageEnd(pageStart, pageHeight, reservedTop);
          while (next < blockBottom) {
            const repeatHeader = section.headerHeight > 0;
            pushBreak(breaks, continuation, next, repeatHeader);
            pageStart = next;
            reservedTop = repeatHeader ? section.headerHeight : 0;
            next = pageEnd(pageStart, pageHeight, reservedTop);
          }
          return pageStart;
        }

        pushBreak(breaks, continuation, section.offsetTop, false);
        return section.offsetTop;
      }

      function computePlan(sections, pageHeight) {
        const breaks = [0];
        const continuation = [false];
        let pageStart = 0;

        for (const section of sections) {
          if (section.kind === 'splittable') {
            pageStart = layoutSplittable(section, pageStart, pageHeight, breaks, continuation);
          } else {
            pageStart = layoutBlock(section, pageStart, pageHeight, breaks, continuation);
          }
        }

        return { breaks, continuation };
      }

      function readContinuationHeaderAtBreak(templateRoot, breakTop) {
        // Mirror modules/resume/lib/measureResumeSections.ts: resolve the
        // continuation header by the section whose vertical range straddles
        // breakTop, not by the nearest unit. Handles block sections (no units)
        // and never attaches a neighbouring section's header.
        const sections = collectLeafMarked(templateRoot);
        let matched = null;
        let matchedTop = -Infinity;

        for (const section of sections) {
          const top = relativeTop(section, templateRoot);
          const sectionBottom = top + section.offsetHeight;
          if (breakTop >= top && breakTop < sectionBottom && top > matchedTop) {
            matched = section;
            matchedTop = top;
          }
        }

        const section = matched;
        if (!section) return null;

        const header = section.querySelector('[data-resume-section-header], [data-resume-skills-header]');
        if (!header) return null;

        const rootRect = templateRoot.getBoundingClientRect();
        const headerRect = header.getBoundingClientRect();
        const title =
          header.getAttribute('data-resume-section-header')
          || header.getAttribute('data-resume-skills-header')
          || (header.textContent || '').trim()
          || 'Section';

        return {
          title,
          height: header.offsetHeight,
          left: Math.max(0, Math.round(headerRect.left - rootRect.left)),
          width: Math.max(0, Math.round(headerRect.width)),
          html: header.innerHTML,
        };
      }

      const measureRoot = document.getElementById('resume-measure-root');
      const templateRoot = document.getElementById('resume-template-root');
      const pagesRoot = document.getElementById('resume-pages-root');
      if (!measureRoot || !templateRoot || !pagesRoot) {
        window.__resumePagesReady = true;
        return;
      }

      const sections = measureSections(templateRoot);
      // Expose the skills section measurement so the Node side can compute
      // truncation ratios with the exact same pure helpers the preview uses.
      const skillsForTruncation = sections.find(function (s) {
        return s.kind === 'splittable' && s.sectionId === 'skills';
      });
      window.__resumeSkillsMeasurement = skillsForTruncation
        ? { header: skillsForTruncation.header, units: skillsForTruncation.units, contentHeight: CONTENT_HEIGHT }
        : null;
      const plan = computePlan(sections, CONTENT_HEIGHT);
      const templateHTML = templateRoot.outerHTML;
      const continuationHeaderMetrics = plan.breaks.map((breakTop, pageIndex) => (
        plan.continuation[pageIndex]
          ? readContinuationHeaderAtBreak(templateRoot, breakTop)
          : null
      ));

      pagesRoot.innerHTML = '';
      function pageClipHeight(pageIndex, breaks, pageContentHeight) {
        const start = breaks[pageIndex];
        const nextStart = breaks[pageIndex + 1];
        if (nextStart === undefined) return pageContentHeight;
        return Math.max(0, nextStart - start);
      }

      plan.breaks.forEach((breakTop, pageIndex) => {
        const page = document.createElement('div');
        page.className = 'resume-page';
        const inner = document.createElement('div');
        inner.className = 'resume-page-inner';
        const viewport = document.createElement('div');
        viewport.className = 'resume-page-viewport';
        viewport.style.height = pageClipHeight(pageIndex, plan.breaks, CONTENT_HEIGHT) + 'px';

        const headerMetrics = continuationHeaderMetrics[pageIndex];
        if (plan.continuation[pageIndex] && headerMetrics) {
          const header = document.createElement('div');
          header.className = 'resume-continuation-header';
          header.style.left = headerMetrics.left + 'px';
          header.style.width = headerMetrics.width + 'px';
          header.style.height = headerMetrics.height + 'px';
          header.innerHTML = headerMetrics.html;
          viewport.appendChild(header);
        }

        const content = document.createElement('div');
        content.className = 'resume-wrapper resume-page-content';
        content.style.marginTop = (-breakTop + (headerMetrics ? headerMetrics.height : 0)) + 'px';
        content.innerHTML = templateHTML;

        viewport.appendChild(content);
        inner.appendChild(viewport);
        page.appendChild(inner);
        pagesRoot.appendChild(page);
      });

      measureRoot.remove();
      window.__resumePagesReady = true;
    })();
  </script>
</body>
</html>`
}

// ─── Puppeteer renderer ──────────────────────────────────────────────────────

interface RenderPdfOptions {
  margin?: { top: string; right: string; bottom: string; left: string }
}

interface SkillsMeasurementFromBrowser {
  header: { offsetTop: number; offsetHeight: number }
  units: Array<{ unitIndex: number; offsetTop: number; offsetHeight: number }>
  contentHeight: number
}

/**
 * After the first paginate pass, ask the browser for the skills section
 * measurement and reuse the preview's pure ratio helpers to truncate oversized
 * categories, re-rendering the template through ResumePreviewPageProvider so the
 * exported PDF matches the preview's `+N more` truncation and page count exactly
 * (Codex r3319377027). No-op (single render) when nothing is oversized.
 */
async function applySkillTruncationForPdf(
  page: {
    evaluate: (fn: () => unknown) => Promise<unknown>
    setContent: (html: string, opts: { waitUntil: string }) => Promise<unknown>
    waitForFunction: (fn: () => unknown) => Promise<unknown>
  },
  data: ResumeData,
  templateId: string,
): Promise<void> {
  let ratios: Record<number, number> = {}

  for (let pass = 0; pass < 5; pass++) {
    const raw = (await page.evaluate(
      () => (window as unknown as { __resumeSkillsMeasurement?: unknown }).__resumeSkillsMeasurement ?? null,
    )) as SkillsMeasurementFromBrowser | null

    if (!raw || !Array.isArray(raw.units) || raw.units.length === 0) return
    const measurement = raw as unknown as SplittableSectionMeasurement

    if (pass === 0) {
      ratios = computeSkillCategoryRatios(measurement, raw.contentHeight)
      if (Object.keys(ratios).length === 0) return
    } else {
      if (!data.skills?.length) return
      const current = applySkillsTruncationToData(data, ratios).skills
      if (!current) return
      const refined = refineSkillRatiosIfStillOversized(
        measurement,
        raw.contentHeight,
        ratios,
        data.skills,
        current,
      )
      if (!refined) return
      ratios = refined
    }

    const pageContext: ResumePreviewPageContextValue = {
      skillsContinuationHeader: false,
      truncatedSkillCategoryIndices: [],
      truncatedSkillCategoryRatios: ratios,
      truncatedSkillCategoryOmittedCounts: computeOmittedSkillCounts(data.skills || [], ratios),
    }
    const truncatedHtml = renderResumeHTML(data, templateId, pageContext)
    await page.setContent(truncatedHtml, { waitUntil: 'networkidle0' })
    await page.waitForFunction(
      () => (window as { __resumePagesReady?: boolean }).__resumePagesReady === true,
    )
  }
}

async function renderPdfFromHtml(
  html: string,
  options?: RenderPdfOptions,
  truncationSource?: { data: ResumeData; templateId: string },
): Promise<Buffer> {
  // Dynamic require to handle environments without Puppeteer.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const puppeteer = require('puppeteer-core')

  // @sparticuz/chromium v110+ extracts a brotli-compressed Chromium at runtime.
  // For this to work on Vercel/Lambda, the package must be in
  // next.config.js → experimental.serverComponentsExternalPackages so webpack
  // leaves the archive intact. We also MUST pass chromium.args (the ~22 flags
  // tuned for serverless single-process execution); passing only --no-sandbox
  // causes the browser to crash or fail to spawn.
  let launchArgs: string[] = ['--no-sandbox', '--disable-setuid-sandbox']
  let executablePath: string

  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const chromiumMod = require('@sparticuz/chromium')
    const chromium = chromiumMod.default ?? chromiumMod
    if (Array.isArray(chromium.args) && chromium.args.length > 0) {
      launchArgs = [
        ...chromium.args,
        '--hide-scrollbars',
        '--disable-web-security',
      ]
    }
    executablePath = await chromium.executablePath()
  } catch {
    executablePath =
      process.env.CHROMIUM_PATH || '/usr/bin/chromium-browser'
  }

  const browser = await puppeteer.launch({
    args: launchArgs,
    executablePath,
    headless: true,
  })

  try {
    const page = await browser.newPage()
    // Match puppeteer's A4 CSS-pixel dimensions (8.27in × 11.69in @ 96dpi).
    // This ensures the browser's layout engine sees the same viewport that
    // the subsequent page.pdf({ format: 'A4' }) call will use.
    await page.setViewport({ width: 794, height: 1123 })
    await page.setContent(html, { waitUntil: 'networkidle0' })
    await page.waitForFunction(() => (window as { __resumePagesReady?: boolean }).__resumePagesReady === true)

    // Truncate oversized skill categories to match the preview, re-rendering
    // the template through the shared page-context provider. Only does work
    // (extra setContent passes) when a category is actually oversized.
    if (truncationSource) {
      await applySkillTruncationForPdf(page, truncationSource.data, truncationSource.templateId)
    }

    // ── Compute the exact scale to match the preview's page count ───────────
    //
    // The editor preview designs every page at 595×842 CSS px (A4 at 72dpi)
    // and decides page breaks based on that. Puppeteer's PDF output uses
    // 96dpi, where A4 = 794×1123 CSS px. The "naive" width-filling scale is
    // 794/595 = 1.3345, but at that scale, a resume that exactly fills one
    // preview page (842 px source height) scales to 1123.65 px — 0.65 px
    // over A4, which forces one orphan line onto a second page.
    //
    // Fix: measure the actual rendered element height, figure out how many
    // A4 pages the preview would have shown for that height (1 page per
    // 842 px source), then pick the largest scale that (a) still fills the
    // A4 width as much as possible and (b) never exceeds `pages × 1123 px`
    // after scaling. This snaps the PDF page count to the preview's exactly.
    const SOURCE_WIDTH = 595
    const SOURCE_PAGE_HEIGHT = 842
    const A4_WIDTH = 794
    const A4_HEIGHT = 1123

    const naturalHeight: number = await page.evaluate(() => {
      const el = document.getElementById('resume-pages-root') as HTMLElement | null
      return el ? el.offsetHeight : 842
    })

    const pagesIntended = Math.max(
      1,
      Math.ceil(naturalHeight / SOURCE_PAGE_HEIGHT),
    )
    const widthScale = A4_WIDTH / SOURCE_WIDTH
    const heightScale = (pagesIntended * A4_HEIGHT) / naturalHeight
    // Clamp to puppeteer's valid scale range (0.1, 2).
    const scale = Math.max(0.1, Math.min(2, Math.min(widthScale, heightScale)))

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      scale,
      // Zero puppeteer margins — the #resume-page element encodes its own
      // 24px padding that matches the preview's PAGE_PADDING.
      margin: options?.margin ?? {
        top: '0',
        right: '0',
        bottom: '0',
        left: '0',
      },
    })
    return Buffer.from(pdfBuffer)
  } finally {
    await browser.close()
  }
}

// ─── Public API ──────────────────────────────────────────────────────────────

export async function generatePDF(
  data: ResumeData,
  templateId: string,
): Promise<Buffer> {
  const html = renderResumeHTML(data, templateId)
  return renderPdfFromHtml(html, undefined, { data, templateId })
}

/** @deprecated — kept for backward compatibility. Prefer `renderResumeHTML`. */
export function generateResumeHTML(data: ResumeData, templateId: string): string {
  return renderResumeHTML(data, templateId)
}
